### ISSUE TITLE
Second parameter to ScheduleDetailPopup() does nothing

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#1006]
The ScheduleDetailPopup function accepts one parameter : https://github.com/nhn/tui.calendar/blob/master/src/js/view/popup/scheduleDetailPopup.js.

It is called in [factory/monthView.js](https://github.com/nhn/tui.calendar/blob/master/src/js/factory/monthView.js#L130) and [factory/weekView.js](https://github.com/nhn/tui.calendar/blob/master/src/js/factory/weekView.js#L261) by passing two parameters to it.  The second parameter is NO-OP and adds dead code.

**Comment by adhrinae** [comment]
@dilyanpalauzov 

Thanks for the report. I'll remove it in the next release.
