### ISSUE TITLE
Strange inheritance of Layout from View

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#1007]
In true JavaScript classes, derived classes must explicitly call `super()` in their contructor before using `this`.  TUI.Calendar does use prototypes instead of classes.  Converting the prototypes to classes with Lebab reveals that view/layout.js:Layout() extends the View class, but does not call its super method View.call().  For me it is unclear, how this inheritance works and whether there is need for Layout to extend View.

* Verify whether there is a need for inheritance of Layout from View and if there is, add View.call() in `function Layout`, otherwise remove the inheritance of Layout from View.

**Comment by adhrinae** [comment]
@dilyanpalauzov 

That's a pair point. Thanks for the report. It's an old codebase managed by many people so I couldn't notice it.

I found that `Layout` needs to inherit from `View` because it's using some methods like `render`, `destroy`. I'll add a `super` call with the next release.
