### ISSUE TITLE
Remove unused class weekday-schedules-height-span from src/css/weekday.styl

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#1008]
Commit 267a5504d26434 removes the usage of CSS class `weekday-schedules-height-span` from src/js/view/template/week/weekdayInWeek.hbs .  The class is still generated by css/weekday.styl.

**Comment by dilyanpalauzov** [comment]
CSS class `grid-date-title` is also generated by stylus, but not used.

**Comment by dilyanpalauzov** [comment]
src/js/view/template/month/more.hbs adds class `month-more-allday ` to the generated HTML, but this class is not defined  or used anyhow.  Adding the class serves no purpose.

**Comment by dilyanpalauzov** [comment]
js/view/template/popup/scheduleDetailPopup.hbs adds class `popup-detail-item` to the generated HMTL.  This class is not defined by the stylus templates and not used anyhow by JavaScript. I recommend removing `popup-detail-item` from js/view/template/popup/scheduleDetailPopup.hbs .

**Comment by dilyanpalauzov** [comment]
src/js/view/template/month/weekdayInMonth.hb adds class `weekday-grid-header` to the generated HMTL, but this class is not used anyhow.

**Comment by adhrinae** [comment]
@dilyanpalauzov 
Thanks for the report. I'll check it with the next update.

**Comment by adhrinae** [comment]
@dilyanpalauzov 
I've checked it, and I think I should remove unused CSS styles in stylus files but not classes in the `hbs` files.

Those classes have semantic annotations that help to understand what the `div`(or else) tag means. And there might be a chance some users are using it for their custom styles.
