### ISSUE TITLE
openCreationPopup - how to define preset Schedule data?

### ISSUE THREAD

**Issue by jlunz** [nhn/tui.calendar#1014]
## Summary
_Is there an easy way to open a popup (either CreationPopup or DetailPopup) with predefined schedule data (Title / Start / End)?_

If I use [openCreationPopup(schedule)](https://nhn.github.io/tui.calendar/latest/Calendar#openCreationPopup) I can see that my start and end gets changed through calls to getNearestHour:
https://github.com/nhn/tui.calendar/blob/9b467a01a1e0209e72160d077fe0562df1d19e30/src/js/handler/time/core.js#L89
![image](https://user-images.githubusercontent.com/117189/152574379-6110562e-7a5c-450d-a34d-9373fcc4a972.png)
Can this behaviour avoided or do I need to add [customized popups](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups)?

## Screenshots
https://jsfiddle.net/75kcat16/4/
Expected:
```
start = new Date('2022-02-05T10:58:00');
end = new Date('2022-02-05T12:12:00');
```
Result:
```
start = new Date('2022-02-05T11:00:00');
end = new Date('2022-02-05T12:30:00');
```
![image](https://user-images.githubusercontent.com/117189/152578809-b9fe8264-b279-40e9-868f-50fd3ed19eef.png)

## Version
https://github.com/nhn/tui.calendar/releases/tag/v1.15.2

**Comment by adhrinae** [comment]
@jlunz 

As you found, I'm afraid to say that you should implement your own customized popup in order to define the preset schedule like `12:12`.

**Comment by jlunz** [comment]
Thank you for taking the time to answer!
