### ISSUE TITLE
`{{collapsed}}` in daygridschedule.hbs never set?

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#1023]
template/week/daygridschedule.hbs contains:
```
<div class="{{CSS_PREFIX}}weekday-schedules {{collapsed}}" style="top:{{@root.scheduleContainerTop}}px;">
```
This template is called from view/week/dayGridSchedule.js:render()
```
container.innerHTML = tmpl(baseViewModel);
```
Do I see correctly, that `collapsed` is never set in JS and thus never rendered in the Handelbars templates?

**Comment by adhrinae** [comment]
@dilyanpalauzov 
It seems so when I've checked it.
