### ISSUE TITLE
Run the command on click schedule

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [nhn/tui.calendar#1039]
Goodmorning everyone,
do you know if it is possibile via javascript to run the event on click on a schedule?
i have found that via cal.getSchedule(id,calendarid) i can obtain the schedule.
do you know if it is possibile to run the comand to open the popup where i can change the value of the location,title etc.. of the schedule obtained with the command before?
thanks
regards

**Comment by adhrinae** [comment]
@andreameneguzzoinfol 

Hello, there's a `clickSchedule` event so that you can get the data when users click a certain schedule.

https://nhn.github.io/tui.calendar/latest/Calendar#event-clickSchedule

Closing the issue since it is answered.

**Comment by andreameneguzzoinfol** [comment]
Hello,
 i know that i can obtain the data when a uer click on a schedule but this is not what i want.
i have edited tui calendar js file to have the event onhover the schedule.
when i go onhover the schedule i call a javascript function but i want to open your poup on this function.
i am searching a function like schedule.showpopup()
thanks

**Comment by adhrinae** [comment]
@andreameneguzzoinfol 

Sorry about that, I missed the point of "to run the command to open the popup" in the sentence.

There's no API to open the popup from the schedule at this moment.
We're going to add the way to achieve it on the next major update, however, It'll take a few more months.
