### ISSUE TITLE
popup on beforeupdateschedule

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [nhn/tui.calendar#1042]
Goodmorning all,
I am trying to use the call of beforeUpdateSchedule to show a new popup when i ask other information like body,
i use a div where there is a txt field and a save button or the easy prompt() of javascript.
the issue is that when i move the schedule in the calendar this popup is shown.
is there any variable that say to me that i don't click on update button but just moved the calendar?
thanks
regards

**Comment by adhrinae** [comment]
> is there any variable that say to me that i don't click on update button but just moved the calendar?

Sorry. It's hard to understand your question.
Basically, the `beforeUpdateSchedule` event should be invoked when you try to move or resize the schedule.

https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeUpdateSchedule

Clicking just the schedule does not fire the `beforeUpdateSchedule` event.

**Comment by andreameneguzzoinfol** [comment]
when you move,resize or click on update schedule the event beforeUpdateSchedule  is called.
i want my custom open the popup when i click on update button on the event and not on onclick event
in this case the popup appear everytime i resize the schedule
the custom popup ask only some information like body but not the date etc.
thanks

**Comment by adhrinae** [comment]
Ok. Let's orgniaze the information.

1. You made your own custom popup appear when you click the 'update' button on the event.
**Question**: Where's the 'update' button? In the default popup when you enabled `useDetailPopup`?
2. Somehow every time you resize the schedule the popup appears.
**Question**: What popup? your custom popup? or something else? and How did you resize the schedule? by dragging?

I asked you for the example code in a different issue. This time is similar. I still don't get the context by just reading your text.
