### ISSUE TITLE
[ how to ]  ...only close the popup by button ? 

### ISSUE THREAD

**Issue by minbokang** [nhn/tui.calendar#1060]
when user click outside area the popup, popup is closed.

how can I  disable hide  the popup, except the close/update button ?

**Comment by adhrinae** [comment]
@minbokang 
Unfortunately, there's no option to disable the behavior when clicking outside of the popup.

**Comment by adhrinae** [comment]
Closing sine the question is answered.

**Comment by minbokang** [comment]
ok.
I'v found another way. that is a modify the modal css. 
I did it perfect.

**Comment by adhrinae** [comment]
@minbokang

That's nice!
Would you share the snippet of the modified CSS for others having similar trouble?
That would be helpful for them when they found this issue.

**Comment by minbokang** [comment]
ajust surrounding `<div>`
======================


.tui-full-calendar-section-state{
        display:none;
}
.tui-full-calendar-month-creation-guide { /*//////////////*/
    z-index: 2!important;
}

.tui-view-14 > .tui-full-calendar-popup{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 5;
}


.tui-full-calendar-popup-container{ /*//////////////*/
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);

    /* width: 50%; */
}
