### ISSUE TITLE
How can I customize this bar  with custom html ? 

### ISSUE THREAD

**Issue by shakil-brl** [nhn/tui.calendar#1074]
## Summary
I want to use custom style like  
![image](https://user-images.githubusercontent.com/76032597/161908662-c243af4c-fb23-4624-af53-b7e102b6d860.png)

## Screenshots
![image](https://user-images.githubusercontent.com/76032597/161908451-559c460e-b0c1-4526-8dc7-1a0c15da068c.png)

**Comment by adhrinae** [comment]
@shakil-brl 

Change the value of `week.timegridSchedule.borderRadius` in [theme](https://nhn.github.io/tui.calendar/latest/themeConfig). and modify some CSS on your own.

And Please write a description in detail as you can to get help from others.

**Comment by Shakil1081** [comment]
sir @adhrinae I want to add 2 custom dives in timegridSchedule
the area where I want to use border-color as per timegridSchedule dynamic  border-color  please check the image,
![image](https://user-images.githubusercontent.com/13831857/162582479-03cadb7b-b5cc-4443-8b12-229bec3d66df.png)

timegridSchedule top and bottom will add extra dive where the div will get dynamic border-color Not background color.

**thank you for your quick response**

**Comment by adhrinae** [comment]
@Shakil1081 

There are `goingDuration` and `comingDuration` templates for schedules having `goingDuration` and `comingDuration` properties. So you can leverage them.

- https://nhn.github.io/tui.calendar/latest/Schedule
- https://nhn.github.io/tui.calendar/latest/Template

You'll need to override CSS properties and I'm not sure it's possible to implement what you want.
