### ISSUE TITLE
How do I create multi-line event details on the different calendar views?

### ISSUE THREAD

**Issue by sriramramaswami** [nhn/tui.calendar#1078]
## Summary
It is unclear in the documentation on how to create event descriptions that span across multiple lines in the Today/Daily/Week/2 Week/Monthly views for all day events.  I have the essential need to display 2 rows of data on the main calendar page without it getting cut out. There are also no timed events so it has to be all day.

## Screenshots
Screenshots are attached
![overlapping_events](https://user-images.githubusercontent.com/8266445/162788443-7fe214a3-4f56-40e4-87b5-83a942f43558.png)

## Version
1.15.3

## Additional context
I tried using custom css and set the .tui-full-calendar-weekday-schedule div to use an auto height. However it is causing other events on the schedule to overlap with it because of the absolute positioning of each of the schedule event blocks in the view.I have overridden the allday template functions to give it my own 2 div simple template.

**Comment by adhrinae** [comment]
@sriramramaswami 
Unfortunately, the calendar only concerns that there are one-liner all-day events because it needs a fixed height to calculate the (absolute) position of each event.

Somehow we can improve it. but it's not on the plan.

**Comment by sriramramaswami** [comment]
@adhrinae , thank you for the response. Do you suggest any way that this can be worked around?

**Comment by adhrinae** [comment]
@sriramramaswami 
I don't think I have any of them. 😢
