### ISSUE TITLE
[how to] question about calendar.next()

### ISSUE THREAD

**Issue by khalisabrahman** [nhn/tui.calendar#1095]
Hi,

Let's say my calendar view is 'month'. I want to include 2 arrow buttons for the year such that when I click on the next button for the 'year', the calendar will render a view showing January 2023. How do I go about doing that using the calendar.next() function. 
![Screenshot 2022-05-01 at 12 58 44 PM](https://user-images.githubusercontent.com/51067852/166132951-d1982665-482e-48c2-b9a7-de0a8fde543b.png)

**Comment by Timothy-Y-H-Lee** [comment]
Hello?

I've just solve that same issue.

1. You can see the 'example16-template-for-popup.html' file in example directory.
2. You can find both of 'ic-arrow-line-left', 'ic-arrow-line-right' classes in the 'icons.css' file.
- Please add below codes in the 'icons.css' file.

```
.ic-arrow-double-line-left {
  background: url('../images/ic-arrow-double-line-left.png') no-repeat;
}

.ic-arrow-double-line-right {
  background: url('../images/ic-arrow-double-line-right.png') no-repeat;
}
```

3. You can make 'ic-arrow-double-line-left.png', 'ic-arrow-double-line-left@2x.png', 'ic-arrow-double-line-left@3x.png', 'ic-arrow-double-line-right.png', 'ic-arrow-double-line-right@2x.png', 'ic-arrow-double-line-right@3x.png' files 
from 'ic-arrow-line-left.png', 'ic-arrow-line-left@2x.png', 'ic-arrow-line-left@3x.png', 'ic-arrow-line-right.png', 'ic-arrow-line-right@2x.png', 'ic-arrow-line-right@3x.png' in the images directory

4. You can see as below codes in default.js
```
switch (action) {
    case 'move-prev':
      cal.prev();
      break;
    case 'move-next':
      cal.next();
      break;
    case 'move-today':
      cal.today();
      break;
...
```

So, please add as below code in switch code in the default.js file.
```
switch (action) {
    case 'movePrevYear':
      cal.prevYear();
      break;
    case 'moveNextYear':
      cal.nextYear();
      break;
...
    
```

5. You can see some Calender.prototypes in tui-calender.js as below code.
```
Calendar.prototype.next = function() {
    this.move(1);
    this.render();
};

Calendar.prototype.prev = function() {
    this.move(-1);
    this.render();
};
```

So, You can add some Calender.prototypes in tui-calender.js as below code.
```
Calendar.prototype.nextYear = function() {
    this.move(12);
    this.render();
};


Calendar.prototype.prevYear = function() {
    this.move(-12);
    this.render();
};
```

6. Almost there! Please call the 'Calendar.prototype.nextYear' and 'Calendar.prototype.prevYear' functions in the 'example16-template-for-popup.html' file.
```
<div class="code-html" id="tui-calendar-wrapper">
	<div id="menu">
		<span id="menu-navi">
			<div class="left">
				<button type="button" class="btn btn-default btn-sm move-today" data-action="move-today">Today</button>
			</div>
			<button type="button" class="btn btn-default btn-sm move-day move-prev-year" data-action="movePrevYear">
				<i class="calendar-icon ic-arrow-double-line-left" data-action="movePrevYear"></i>
			</button>
			<button type="button" class="btn btn-default btn-sm move-day" data-action="move-prev">
				<i class="calendar-icon ic-arrow-line-left" data-action="move-prev"></i>
			</button>
			<span id="renderRange" class="render-range"></span>
			<button type="button" class="btn btn-default btn-sm move-day" data-action="move-next">
				<i class="calendar-icon ic-arrow-line-right" data-action="move-next"></i>
			</button>
			<button type="button" class="btn btn-default btn-sm move-day move-next-year" data-action="moveNextYear">
				<i class="calendar-icon ic-arrow-double-line-right" data-action="moveNextYear"></i>
			</button>
			<div class="right">&nbsp;</div>
		</span>
	</div>
	<div id='calendar' style="height: 800px"></div>
</div>
```

Good luck!

Timothy Lee.

**Comment by Timothy-Y-H-Lee** [comment]
@khalisabrahman 
Please check out : 
https://github.com/Timothy-Y-H-Lee/tui.calendar/commit/91767d66a561d77d9d26e73ee3ff6d7e8034a464

**Comment by adhrinae** [comment]
@khalisabrahman As you can see from the comment above, the `next` and `prev` methods take a number as an argument. So you can move the range as you want.

@Timothy-Y-H-Lee Thanks for the detailed answer.

I'd suggest not expanding the Calendar's prototype directly, but you can create a function doing the same thing.

```js
function moveToPrevYear() {
  cal.prev(-12);
  cal.render();
}
```

Monkey-patching the library itself is not reliable to the sudden change of the library.

**Comment by khalisabrahman** [comment]
@adhrinae 
I tried your advice. I created a new function.
`function moveToNextYear() {
  cal.next(12);
  cal.render();
}`

However, when I called the function, the calendar will only render the next month view instead of next year.
I'm not sure what went wrong.

**Comment by adhrinae** [comment]
@khalisabrahman 

Sorry, That was a `move` method, not the `next`.

https://github.com/nhn/tui.calendar/blob/master/src/js/factory/calendar.js#L1132-L1140

Somehow the documentation of this method was not created.

**Comment by khalisabrahman** [comment]
Works like a charm. Thanks
