### ISSUE TITLE
customize of popup for new schedule?

### ISSUE THREAD

**Issue by Timothy-Y-H-Lee** [nhn/tui.calendar#1099]
실례지만, 질문을 드려도 될까요?
Excuse me, Do you have any idea that options with customize of popup for new schedule?

- 스케줄을 추가하는 팝업 다이얼로그에서, 사용하지 않는 항목을 숨기거나 없애는 방법(예: 팝업이 생성될 때에 줄 수 있는 객체 옵션 설정({'displayBusy' : false, 'displayLock' : false}))이나 참고 자료가 있을까요?
 자물쇠(개인/공개 스케줄)과 'Busy'상태가 필요하지 않습니다.
- I don't need 'lock image(open or private schedule)' and 'Busy' status. So, Can I give the popup options({'displayBusy' : false, 'displayLock' : false}) for new schedule when created it?

> ![image](https://user-images.githubusercontent.com/89777346/166220041-e6a32c7e-2270-4970-bdb1-c199a40173b8.png)

- 스케줄의 종류가 공휴일 같이, 일부 장소가 필요하지 않는 일정에서 'Location'을 display:none처럼 숨기거나 사용을 못하게 하는 방법이나 참고 자료가 있을까요?
- Some of type of schedule(which one is 'day off'), that don't need the 'Location'. So, Can I give 'disable or display:none' option for 'Location' when the type of schedule changed?

> ![image](https://user-images.githubusercontent.com/89777346/166219862-bcfc63ae-2c95-4174-ad4d-0a90f75bd819.png)

감사합니다.
Thank you!

티모시 드림
Timothy Lee.

## Version
Write the version of the calendar you are currently using.

**Comment by adhrinae** [comment]
@Timothy-Y-H-Lee 

TL;DR: You need to leverage CSS and JS to hide some inputs. But there's no option to customize the popup directly.

Please refer to #941.

**Comment by Timothy-Y-H-Lee** [comment]
@adhrinae Oh, I see... There're no options to customize the popup directory...
Thank you for your information and your time!

Have a nice day~
