### ISSUE TITLE
Is there a way to show events in the calendar with the same time they are stored in the db

### ISSUE THREAD

**Issue by klimentpetkov** [nhn/tui.calendar#1105]
## Summary
When I enter an event in the calendar form a popup with datepicker input fields e.g. 7:30am - 8:00am in the calendar it appears as 7:30am - 8:00am. Ok but when i decide to use this data from the inputs there are other values returned and in the DB they are stored as -2h (winter time) and -3h (summer time) according to daylight saving clock. And later they are fetched as is but again shown +2/+3H in the calendar. Is there a setting or a way I can make the calendar show the time as is without getting timezones local time etc. I mean if a create an event with times 7:30am - 8:00am to appear like that 7:30am - 8:00am and also to be stored in the db like that. Or if there is no such setting how can i handle this with a bit of additional code? This is needed because I want to use the time the same way for web and mobile. But in web this behavior is not accepable.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
tui-date-picker@4.3.1
tui-calendar@1.15.0

**Comment by adhrinae** [comment]
@klimentpetkov 

The default popup doesn't support DST well. I would suggest you create your own popup so that you can manage the DST issue by yourself.

Or you can still manipulate the `start` and `end` values before submitting them to the server.

```js
cal.on('beforeCreateSchedule', (e) => {
  // This callback will be invoked when the user clicks the 'Save' button in the popup.
  // So calculate the difference between actual time and the value from the argument and fix them.
  const start = e.start.toDate();
  const end = e.end.toDate();
  // ...
});
```

Maybe you can leverage some libraries like the `date-fns-tz`.

https://github.com/marnusw/date-fns-tz#readme
