### ISSUE TITLE
Color Selection part doesn't work on schedule create popup

### ISSUE THREAD

**Issue by mijin7916** [nhn/tui.calendar#1115]
## Summary
Color Selection part doesn't work on schedule create popup

## Screenshots
![제목 없음](https://user-images.githubusercontent.com/100767422/168841763-932a2d46-97a3-4e96-abdc-ffcd8af788b6.png)

## Version
Chrome: 101.0.4951.67
TUI: 1.15.3

**Comment by adhrinae** [comment]
@mijin7916 

It will work after you've set the `calendars` option.

https://nhn.github.io/tui.calendar/latest/CalendarProps
