### ISSUE TITLE
why your documentation is so terrible ? I had to read source code, even so I can't understand

### ISSUE THREAD

**Issue by long-life233** [nhn/tui.calendar#1123]
## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the calendar you are currently using.

**Comment by adhrinae** [comment]
Please follow our [Code of Conduct](https://github.com/nhn/tui.calendar/issues/1123#issue-1242928065) when you're writing any comments and be kind to others.

We already recognize that our documentation does not provide clear, readable information. So we're working on better documentation for the next major release.
