### ISSUE TITLE
How to add more options button in Schedule task ?

### ISSUE THREAD

**Issue by AliAbbas1577** [nhn/tui.calendar#1131]
## Summary
My simple question is that how can I Add More options button in my schedule if my **schedules** are above 5 or 6 in a week for a month. I am currently using the function of **cal.on.clickMore(e)** but my function is not being triggered. Anyone have a knowledge 
about that how to solve this ?

## Version
[1.12.14]

## Screenshots

![calIssue](https://user-images.githubusercontent.com/106576091/171101436-272ac0bb-c349-4236-8798-9fee975e2713.PNG)

****

**Comment by adhrinae** [comment]
@AliAbbas1577

I don't follow your question. But I assume that you want to show the 'More' button if there are a certain amount of schedules in a day.

Perhaps you can try the `month.visibleScheduleCount` option.

https://nhn.github.io/tui.calendar/latest/MonthOptions

```js
const calendar = new Calendar('#calendar', {
  month: {
    visibleScheduleCount: 5
  }
});
```

But please note that your calendar needs enough height to show at least 5 schedules in a day. It cannot guarantee 5 schedules if it cannot have a enough height per row.
