### ISSUE TITLE
name of the day of the week cannot be change for the "month" view, but it work for the "day" and "week" view

### ISSUE THREAD

**Issue by DiegoNamkhai** [nhn/tui.calendar#1190]
## Test Environment
Firefox latest, Ubuntu 22.04 lts(VM), vscode TextEditor, PHP 8.1.2 Development Server

## Current Behavior

The name of the day of the week cannot be change for the "month" view, but it work for the "day" and "week" view.

```js
var Calendar = window.tui.Calendar;

const calendar = new Calendar('#calendar', {
  defaultView: 'month',
  week: {
    dayNames: ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
  },
});

```

## Expected Behavior
I expect the month view to work as "week" and "day" as well
![image](https://user-images.githubusercontent.com/22345495/177518455-0135f8d4-3310-43d0-8ca0-52da08bc0a22.png)
![image](https://user-images.githubusercontent.com/22345495/177518615-c013033d-6387-40ef-9f14-4fdcebce01e5.png)
![image](https://user-images.githubusercontent.com/22345495/177518672-45de11b3-0806-4378-899e-fa9c15c86c73.png)

**Comment by adhrinae** [comment]
@DiegoNamkhai 

There's a `month.dayNames` option. Please refer to [this](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#monthdaynames).
