### ISSUE TITLE
Popup boxes have wrong position

### ISSUE THREAD

**Issue by balping** [nhn/tui.calendar#1197]
## Version
2.0.2 (calendar@2.0.2)

## Test Environment
Firefox 101

## Current Behavior

Pop-up boxes are displayed with a wrong offset

![a](https://user-images.githubusercontent.com/5840038/178086204-91c155e3-db37-4309-a9de-8410952a54a6.png)

![b](https://user-images.githubusercontent.com/5840038/178086214-47813ba9-45e8-47e6-bad6-59c4573d2fa1.png)

## Expected Behavior
Pop-up boxes should be displayed next to the selected area when creating a new event, or next to the existing event when editing one.

**Comment by adhrinae** [comment]
@balping 
This will be fixed in the next version. I'll ship next week.

Please refer to #1192.

**Comment by adhrinae** [comment]
The fix for this issue should be resolved in another PR. I found that #1192 is not related to this.
