### ISSUE TITLE
BUG: Weekly calendar shows TUESDAY as first day on Sundays (with startDayOfWeek = 1)

### ISSUE THREAD

**Issue by victorvogelpoel** [nhn/tui.calendar#1198]
## Version
tui calendar 2.02 (JS)

## Test Environment
Brave browser

## Current Behavior
On a SUNDAY (today), the calendar shows TUESDAY as the first column of the weekly calendar, and MONDAY is the last.

Today is Sunday, July 10th. When I change the laptop's date to July 11 (MONDAY), the weekly calendar shows the expected weekly calendar with first column MONDAY and last column SUNDAY.
Settings use "startDayOfWeek" = 1:

```js
    var Calendar = window.tui.Calendar;
      var cal = new Calendar('#app', {
        defaultView: 'week',
        isReadOnly: true,
        useDetailPopup: true,
        timezone: { zones: [ { timezoneName: 'Europe/Amsterdam' } ] },
        week: {
          showNowIndicator: false,
          startDayOfWeek: 1,
          hourStart: 8,
          taskView: false,
          narrowWeekend: true,
        },
      });
```

![image](https://user-images.githubusercontent.com/1768490/178145815-71a619f2-1346-407b-a47b-d6ef2c80a39c.png)

## Expected Behavior
On SUNDAY (today, or any day of the week), I expect the first column of the weekly calendar to be MONDAY and SUNDAY the last.

**Comment by adhrinae** [comment]
@victorvogelpoel 
I assume that setting the default timezone brought the bug. I forgot to apply the timezone when creating the range of the week.

Just to get more context, How many time differences between your timezone and Amsterdam(because you set it)?

**Comment by victorvogelpoel** [comment]
Hello @adhrinae,

Amsterdam is the timezone I am in and the browser/Windows is working in, so no timedifference.

I was hoping setting the timezone would trigger proper locale for time display (eg 24h display); figuring out the templating...

**Comment by adhrinae** [comment]
@victorvogelpoel 

I couldn't reproduce the error in the sandbox below:

https://codesandbox.io/s/calendar-startdayofweek-bug-o491nd

Do you get the same result as you reported? I'm unsure what brings the problem if there is no time difference between your system and the timezone option.

---

You might need to check [this documentation](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/template.md#display-time) about the locale for time display. Unfortunately, we don't offer automatic formatting by the timezone.

**Comment by adhrinae** [comment]
@victorvogelpoel 
Yeah, I got it. It's definitely not related to the timezone.

So the `startDayOfWeek` option is broken When the current time is on Sunday.

I'll investigate the issue and try to fix it. Thanks for the report.
