### ISSUE TITLE
Bug with week view

### ISSUE THREAD

**Issue by Adriani6** [nhn/tui.calendar#1199]
## Version
2.0.2

## Test Environment
Chrome 103.0.5060.66, Windows 11.

## Current Behavior

```js
new Calendar('#app', {
    defaultView: 'week',
    useFormPopup: false,
    gridSelection: false,
    usageStatistics: false,
    week: {
        taskView: false,
        eventView: true
     }
});
```

## Expected Behavior
When setting week.eventView to "time", the default action I would expect is to get a list of time slots, as per documentation, however this removes both, the "all day" panel along with the time grid meaning there is no way to just disable "all day" panel.

Thanks,

**Comment by adhrinae** [comment]
@Adriani6 

If you want to display the time grid only, you need to change the `week.eventView` option like below:

```
week: {
  eventView: ['time']
}
```

[This is on the documentation](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#weekeventview) with the description:

> The default is true, and both the allday panel and the time panel are displayed.
> ...
> In case of ['time'], only the time panel is displayed.

If you found that something is unclear or wrong in the doc, please tell us.
