### ISSUE TITLE
Question: Is it possible to render the 2 week view/ 3 week view blocks side by side rather than top to bottom?

### ISSUE THREAD

**Issue by sriramramaswami** [nhn/tui.calendar#1210]
## Test Environment
Chrome 103,  Windows 10, Angular 12.2.16

## Current Behavior
The current 2 week/3 week view renders the date blocks week by week top to bottom.

## Expected Behavior

Is there a possibility to render all date blocks in one row with a horizontal scrollbar for the 2 week / 3 week view?

**Comment by adhrinae** [comment]
@sriramramaswami 
Unfortunately, you can't.
Because the calendar calculates and renders according to events' height in each cell.
