### ISSUE TITLE
How to drag event without trigger a onClickEvent

### ISSUE THREAD

**Issue by loiclegoff** [nhn/tui.calendar#1216]
## Version
I'm using `2.0.4`

## Test Environment
Chrome, Windows, React v18

## Current Behavior
Here's a reproduction: https://codesandbox.io/s/hopeful-mayer-7sbgj7?file=/src/App.js

I'm new to TUI Calendar. I don't want to use popup that why I set `useDetailPopup` and `useFormPopup` to false.
To trigger the opening of my modal, I use the event : `onClickEvent`. This event is triggered when a move an event (by dragging). Is it expected ? Do you have a solution to distinct a click or a drag ?

My current config:
```js
    <Calendar
      usageStatistics={false}
      view="week"
      week={{
        eventView: ["time"],
        taskView: false
      }}
      onClickEvent={(event) => {
        alert(JSON.stringify(event));
      }}
      events={events}
      useFormPopup={false}
      useDetailPopup={false}
    />
```

## Expected Behavior
Not trigger onClickEvent when the action is a drag.

**Comment by adhrinae** [comment]
@loiclegoff 
I found that it's a bug inside the calendar.
We'll ship the fixed version this week.
