### ISSUE TITLE
When using hourStart, hourEnd dragging across days does not work properly 

### ISSUE THREAD

**Issue by jstark518** [nhn/tui.calendar#1238]
## Version
2.1.1

## Test Environment
Chrome Windows

## Current Behavior
In week view when using hourStart and/or hourEnd, dragging across days results in a error and the calendar no longer functions.

```js
const container = document.getElementById('calendar');

const options = {
    defaultView: 'week',
    week: {
        //  startDayOfWeek: 1,
        hourStart: 8,
        hourEnd: 18,
        taskView: false
    }
};
const calendar = new Calendar(container, options);
```

Uncaught TypeError: Cannot destructure property 'top' of 'timeGridRows[endRowIndex]' as it is undefined.

## Expected Behavior
Expect it to work like it does when hourStart and hourEnd is not defined, hopefully respecting the times.

**Comment by adhrinae** [comment]
@jstark518 

Please check the 2.1.2 version whether the bug is fixed.

**Comment by jstark518** [comment]
Thank you
