### ISSUE TITLE
`timeGridRows[endRowIndex] is undefined` error in week view when mouse drag on other column

### ISSUE THREAD

**Issue by henryfool91** [nhn/tui.calendar#1239]
Hey guys! Thanks again for the great package! 
I suppose i found a bug :)
## Version

2.1.1
## Current Behavior

Start select time in week view, drag to other column. After that calendar crashes
![TEST](https://media.giphy.com/media/RbjWkIEyCtVhmFESWA/giphy.gif)

Also, is there a way to completely turn off selections? I know about "isReadOnly" option, but i need to modify events thought dragging, so isReadOnly is not the way

Thanks in advance!

**Comment by adhrinae** [comment]
Possibly related to #1238.

**Comment by adhrinae** [comment]
@henryfool91 You can disable selection via the `gridSelection` option.

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#gridselection

**Comment by henryfool91** [comment]
> @henryfool91 You can disable selection via the `gridSelection` option.
> 
> https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#gridselection

I did that,  I works on click and double click, but click and drug still select

**Comment by adhrinae** [comment]
@henryfool91 
Then please use the previous version(`2.1.0` or `2.0.5`) until the bug is fixed.
I'll try to fix it ASAP.

**Comment by henryfool91** [comment]
2.1.2 fixes the issue, thanks!
