### ISSUE TITLE
Show time events in monthly view such as weekly/daily

### ISSUE THREAD

**Issue by matheusbenedet** [nhn/tui.calendar#1246]
Hello, is there a way to change the view of events of less than 24 hours in monthly mode?

Today events of less than 24 hours in monthly mode appear with a period and the name. There would be a way to make the bar appear equal to events greater than 24 hours.

Today:
![image](https://user-images.githubusercontent.com/55722495/183751895-7dedaa4a-47ad-4eee-995d-d090259c3a1d.png)

I want:
![image](https://user-images.githubusercontent.com/55722495/183752148-ce8f3a84-bcc8-4816-a804-782ca7d7b8cb.png)

**Comment by adhrinae** [comment]
@matheusbenedet 
Unfortunately, That's not customizable through any options.

Perhaps you can manipulate DOM elements after all events are rendered.
Events less than 24 hours(timed events) has `toastui-calendar-weekday-event-dot` class name. For instance:

1. Get all `toastui-calendar-weekday-event-dot` elements by the `document.querySelectorAll` etc.
2. (while looping) Crawl up to the parent.
3. Set the `border-left` and the `background-color` properties to the parent.
4. Hide the `toastui-calendar-weekday-event-dot` element.
