### ISSUE TITLE
Can I change the language of the Datepicker ?

### ISSUE THREAD

**Issue by wulf11** [nhn/tui.calendar#1248]
Is there any possibility to change the language of the datepicker component in the tui.calender ? The tui.date-picker itself provides an option for localeTexts and a changeLanguage method (https://nhn.github.io/tui.date-picker/latest/DatePicker). No problem when I use the datepicker alone..but how to change it in the tui.calender?

**Comment by adhrinae** [comment]
@wulf11 

Unfortunately, the calendar doesn't provide the option to customize the date picker or the popup itself.

You can fork the repo and modify [this code](https://github.com/nhn/tui.calendar/blob/main/apps/calendar/src/components/popup/dateSelector.tsx#L72-L91) for your use case.
