### ISSUE TITLE
Form Popup is triggered on Update event even if useFormPopup is false

### ISSUE THREAD

**Issue by florinleu** [nhn/tui.calendar#1249]
## Version
2.1.2

## Test Environment
Safari, Chrome, macOS 12.5

## Current Behavior
Tapping on Edit event in the Detail Popup opens the Form Popup even when useFormPopup is false.

## Expected Behavior
Tapping on Edit event in the Detail Popup when useFormPopup is false shouldn't open the Form popup and trigger an event to allow custom action (like opening a custom view).

**Comment by adhrinae** [comment]
@florinleu 
You're right. I'll fix and release the patch until next week.

**Comment by adhrinae** [comment]
@florinleu 

The [new version](https://github.com/nhn/tui.calendar/releases/tag/calendar%402.1.3) is released. Please try it out.

**Comment by adhrinae** [comment]
@sabatale 
No. the selection feature works accumulatively in the monthly view. But not for the same day. So I recognize this is a bug.

Could you create an issue about this so that we can track the issue easily?
