### ISSUE TITLE
How to disable the `scrollToNow` functionality?

### ISSUE THREAD

**Issue by reify-paul-kleinschmidt** [nhn/tui.calendar#1250]
## Version
`"@toast-ui/react-calendar": "^1.0.5"`

## Test Environment
Chrome on MacOS

## Current Behavior
I want to auto scroll to a specific schedule event when the calendar renders, but the default auto scroll to the current time is conflicting with this. Is it possible to disable the default `scrollToNow` behavior?

**Comment by adhrinae** [comment]
@reify-paul-kleinschmidt 

If you're using v1, There's no option to disable the default `scrollToNow` behavior.

In the newer version(The latest version is 2.1.2), [there's an option to disable the current time indicator](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#weekshownowindicator). Then it won't trigger the auto-scroll. But This will need a major migration issue.

**Comment by reify-paul-kleinschmidt** [comment]
@adhrinae Thanks, is there any documentation for upgrading from v1 to v2?
