### ISSUE TITLE
add a custom popup trigger event in react wrapper

### ISSUE THREAD

**Issue by loralameh** [nhn/tui.calendar#1262]
## Version
@toast-ui/react-calendar": "^2.1.3"

## Test Environment
testing in vs. code 
windows environment
chrome browser 

## Current Behavior
I am using the calendar to add appointments thus I want on a date click to open a modal to enter a person's data.

I checked the suggested way in the tui calendar docs and tried to replicate in the react wrapper but it does not workout. no console logs is appearing. I could not find in the docs an event to be triggered onclick (once clicked on a day date/time) 

```js

  const clickSchedule = function (e) {
    console.log('clickSchedule', e)
  }

  const beforeCreateSchedule = function (e) {
    console.log('beforeCreateSchedule', e)
  }

  const beforeUpdateSchedule = function (e) {
    console.log('beforeUpdateSchedule', e)
  }

  const beforeDeleteSchedule = function (e) {
    console.log('beforeDeleteSchedule', e)
  }


      <Calendar
        ref={calendarRef}
        useCreationPopup={false}
        useDetailPopup={false}
        clickSchedule={clickSchedule}
        beforeCreateSchedule={beforeCreateSchedule}
        beforeUpdateSchedule={beforeUpdateSchedule}
        beforeDeleteSchedule={beforeDeleteSchedule}
      />
```

## Expected Behavior
an event to be triggered when clicked on a date in the calendar

**Comment by Melissacinta** [comment]
```js
        clickSchedule={clickSchedule}
        beforeCreateSchedule={beforeCreateSchedule}
        beforeUpdateSchedule={beforeUpdateSchedule}
        beforeDeleteSchedule={beforeDeleteSchedule}
```
should be 

```js
        onClickEvent={clickSchedule}
        onBeforeCreateEvent={beforeCreateSchedule}
        onBeforeUpdateEvent={beforeUpdateSchedule}
        onBeforeDeleteEvent={beforeDeleteSchedule}
```
although onBeforeCreateEvent does not trigger my custom popup which is why i decided to go the root of forking the repo and editing the popup files but then i ran into this issue #1261

**Comment by loralameh** [comment]
thanks @Melissacinta & @adhrinae for your replies. 

I have followed what you mentioned but unfortunately I could not  trigger my custom popup to show upon the selection of a date.

**Comment by Melissacinta** [comment]
@loralameh  i have this same issue too

**Comment by adhrinae** [comment]
@loralameh @Melissacinta 

Please describe **HOW** you followed what I mentioned. I cannot guess what you've missed or if there are any bugs.

---

> I have followed what you mentioned but unfortunately I could not trigger my custom popup to show upon the selection of a date.

As you mentioned the 'selection of a date', let's focus on this.

First, You need to pass the handler to the `onSelectDateTime` prop. This event is fired when the user selects dates or times.

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/calendar.md#selectdatetime

Then there is a `gridSelectionElements` in the object passed to the event handler. All you need to do is get the position from the element by using the `getBoundingClientRect` method(or else) and show your custom popup leveraging this position.

**Comment by loralameh** [comment]
@adhrinae  that is the exact handler (onSelectDateTime) that I was searching for .. I was lost in the docs and could not figure it out I suggest adding this code to the react wrapper docs because it was a missing piece  for me... thank you so much for your time and help
