### ISSUE TITLE
Typo on example

### ISSUE THREAD

**Issue by wlcharlie** [nhn/tui.calendar#1273]
## Version
@toast-ui/react-calendar: ^2.1.3

## Test Environment
Chorme, Windows

## Current Behavior
Might be typo?
Just tested and it work with `onClickDayName` but not `onClickDayname`

https://github.com/nhn/tui.calendar/blob/main/apps/react-calendar/example/app.tsx#L267-L314
```js
onClickDayname={...}

should be 

onClickDayName={...}
```

**Comment by adhrinae** [comment]
Yeah, You're right. It should be `onClickDayName`.

https://github.com/nhn/tui.calendar/blob/main/apps/calendar/src/types/eventBus.ts#L40

**Comment by wlcharlie** [comment]
Tks for reply and glad to know 😄
