### ISSUE TITLE
Could I get the $vm DOM event in vue-calendar?

### ISSUE THREAD

**Issue by st474ddr** [nhn/tui.calendar#1274]
## Version
@toast-ui/vue-calendar: ^1.15.3

## Test Environment
edge, mac OS Monterey 12.5

## Current Behavior
Becasue of  #413 
I want to write the custom code that could make me show detail popup when mouseover.
So I try first
```
// custom.js
export function eventPopup() {
  const calendarEvents = document.querySelectorAll('.tui-full-calendar-weekday-schedule-title')
  calendarEvents.forEach((calendarEvent) => {
    calendarEvent.addEventListener('mouseover', () => {
      console.log('mouseover')
    })
  })
}

// index.vue
//...
 mounted() {
    this.$nextTick(() => {
      eventPopup()
    })
  },
```
However, I get empty nodeList.
So I wonder I should get DOM from `$vm`.
I know I can get the calendar DOM by `this.$refs.calendar`, but is there some method that I can get the **event DOM** ?

## Expected Behavior
 show detail popup when mouseover

**Comment by adhrinae** [comment]
@st474ddr 

I don't think so. Even though I'm not an experienced Vue developer, I can guess that your `eventPopup` function is called before the calendar finishing its painting. 

I suggest you to add an event listener to the `body`, not each event. Then you don't have to worry about the timing when the calendar instance mounted to the container.

[This comment](https://github.com/nhn/tui.calendar/issues/267#issuecomment-1204623131) will be helpful for you.

**Comment by st474ddr** [comment]
@adhrinae 
Thanks for your answer.
It actually works, but if I use this method then how can I get the event information with mouseover?

**Comment by adhrinae** [comment]
@st474ddr 
Each schedule block has data attributes for it.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/14539203/188836524-ac46c518-0ca4-48eb-8893-9ce6e85c9c79.png">

You can grab them and call the `getSchedule` instance method to retrieve information.

https://nhn.github.io/tui.calendar/1.15.3/Calendar#getSchedule

Notice that there's no way to open the default details popup through the method. See #555.

**Comment by st474ddr** [comment]
@adhrinae 
Thanks for your help. I have already solved my problem.
