### ISSUE TITLE
Event for just clicking a day / time? Detecting Click without Dragging

### ISSUE THREAD

**Issue by Bxnnet** [nhn/tui.calendar#1286]
## Test Environment

Windows 10, newest Chrome Browser

## Current Behavior

I cant find an event which is fired, when a day / time is just clicked by the user and not "dragged" which in my opinion would be quite important since not everyone always wants to create an for example multi day event. 
Does such an event exist / is there any workaround?

## Expected Behavior

It would be best if there would be an event triggered just by clicking some time / day on the calendar view

**Comment by adhrinae** [comment]
@Bxnnet 

Do you mean this event?

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/calendar.md#clickevent

**Comment by Bxnnet** [comment]
hey @adhrinae
thanks but thats not what im looking for. This one is fired when an event is clicked, I want an event which is fired when I click on the date for example 22.09 in the calendar view in order to create a new event. You get me?

**Comment by adhrinae** [comment]
@Bxnnet 

I see. the `selectDateTime` event fires even if you click a date or time, not dragging.

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/calendar.md#selectdatetime

I wonder how you set the calendar to fire the event and which event you tried. Any sample code reproducing the problem would be helpful.

**Comment by Bxnnet** [comment]
There is currently just the code loading the calendar and adding some events. For me the selectDateTime just fires when I drag trough any day oder time and not just when clicking a day.
To understand better: I now print 'hi' on

```  
calendar.on('selectDateTime', ({event}) => {
                console.log('hi');
            })
``` 

which works fine when dragging.
![grafik](https://user-images.githubusercontent.com/34416919/191740839-b633625e-60f4-4c22-96a8-946aeb9cdcc1.png)
But without dragging, no hi appears :(

**Comment by adhrinae** [comment]
@Bxnnet 

I'm not sure what the cause is because I'm not aware of your app's structure and what options you gave to the calendar. That is why I asked you for *a sample code reproducing the problem.* Not just what you did.

Here's a simple example tried to reproduce the problem. But It works fine.

https://user-images.githubusercontent.com/14539203/191868363-bbf01abf-f5fb-48c8-b1ef-e2c9575647cc.mov

**Comment by Bxnnet** [comment]
@adhrinae nevermind your video gave me the hint I needed. It seems like I initialized the calendar in an invalid way and now every thing works finde! 
Thank you so much for your help and patience!

Have a nice weekend mate
