### ISSUE TITLE
How to customize popup

### ISSUE THREAD

**Issue by samuel-xiangpeng** [nhn/tui.calendar#1289]
I just want to show the details of the incident, so I want to consult how to customize Popup

## Version
^2.1.3

## Current Behavior

```js
// Write example code
```

**Comment by adhrinae** [comment]
https://github.com/nhn/tui.calendar/discussions/941#discussion-3704132

1. Create your own popup using instance events such as `selectDateTime`, `clickEvent`.
2. Fork the repo and customize it.

**Comment by adhrinae** [comment]
Well, there are tons of tutorials explaining how to create a popup.

Example: https://www.w3docs.com/snippets/javascript/how-to-create-a-popup-form-using-javascript.html

You can try one of them.

**Comment by adhrinae** [comment]
Closing since the question is answered.
