### ISSUE TITLE
Support for category: "halfday"

### ISSUE THREAD

**Issue by sabatale** [nhn/tui.calendar#1299]
## Version
Lastet (JS).

## Current Behavior
From what I could find, we only have the option to show a full day or a timeslot. This is a personal calendar where it is not allowed to have multiple events at the same time. One common requirement we have would be to display a half-day on the monthly view, as opposed to the current line that covers about 1/4 of the screen.

## Expected Behavior
Is there a workaround to the category "allday" to have it take up half a monthly day? (probably not a hidden option, but CSS I'd assume?)

`category: "halfday"` or `category: "halfday-am"` / `category: "halfday-pm"`

**Comment by adhrinae** [comment]
I think that's too much for the particular requirement.

**Comment by sabatale** [comment]
No worries, although I think this can have more use cases.

Would you have a CSS idea alternative to make it happen on the side?

Thanks!

**Comment by adhrinae** [comment]
@sabatale 

It's somewhat tricky but I'll give you an idea.

1. Indicate half-day events to the calendar using the custom property [`raw`.](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/event-object.md)

```js
const halfdayEvent = {
  // ...
  raw: {
    isHalfday: true
  }
};
```

2. Set a template to render DOM containing the half-day-related information.

```js
const calendar = new Calendar('#app', {
  // ...
  template: {
    allday(event) {
      const isHalfday = event.raw.isHalfday;
      return `<span data-halfday=${String(isHalfday}>${event.title}</span>`
    }
  }
});
```

3. In your CSS, use the `:has` selector to cut down the width of half-day events.

```css
.toastui-calendar-weekday-event:has([data-halfday='true']) {
  width: 50%;
}
```

Please note that [the `:has` selector has a minimal range of support.](https://caniuse.com/css-has) You can leverage [this PostCSS Plugin](https://www.npmjs.com/package/css-has-pseudo) though.
