### ISSUE TITLE
How to custom useFromPopup / useDetailpopup

### ISSUE THREAD

**Issue by pjh-30002** [nhn/tui.calendar#1306]
## Version
Version is 1.15.3

## Test Environment

browser type is Chrome and Use Window

## Current Behavior

![image](https://user-images.githubusercontent.com/67908713/197732107-81d1d509-8e7e-41cc-a173-c224e2a4fcab.png)

I want to create a new field in the popup window and use it.
useFormPopup = {true} / useDetailPopup= {true}
I don't know where I can control the popup that appears in the above two options and how to apply it. 

Thanks :)

**Comment by adhrinae** [comment]
Unfortunately, You can't.

Please refer to #941.
