### ISSUE TITLE
customized template monthGridHeader returns multi level elements which will be show blank

### ISSUE THREAD

**Issue by sabercc** [nhn/tui.calendar#1308]
## Version
@toast-ui/react-calendar@2.1.3

## Test Environment
Mac
Chrome

## Current Behavior

```js
<Calendar
        template={{
          monthGridHeader(model) {
                const date = parseInt(model.date.split('-')[2], 10);
                const classNames = classnames('weekday-grid-date', { 'weekday-grid-date-decorator': model.isToday });
                return (
                  <span className={classNames}>
                    <span>xxxx</span>
                    <span>{date}</span>
                  </span>
                );
              },
        }}
/>
```
<img width="936" alt="image" src="https://user-images.githubusercontent.com/20875589/198223078-31d39770-1b98-4371-b742-c5862d01878c.png">

## Expected Behavior

normal render xxxx and `date`

**Comment by adhrinae** [comment]
From the [documentation](https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/template.md#template-list).

> Each property of the template is a function that returns a **VNode of preact** or a string

Apparently, you're passing the `ReactNode` to the template function which the calendar cannot understand how to handle it.

I've confirmed that returning HTML string like below works well:

```jsx
const template = {
  monthGridHeader(model) {
    const date = parseInt(model.date.split('-')[2], 10);
    const classNames = `weekday-grid-date ${
      model.isToday ? 'weekday-grid-date-decorator' : ''
    }`;

    return `
      <span className="${classNames}">
        <span>xxxx</span>
        <span>${date}</span>
      </span>
    `;
  },
};

<Calendar
  // ...
  template={template}
/>
```
