### ISSUE TITLE
Missing "Events" chapter in the latest (2.1.3) documentation

### ISSUE THREAD

**Issue by MarGraz** [nhn/tui.calendar#1318]
## Version
Version 2.1.3

## Test Environment
Browser: Firefox, OS: Windows 11

## Current Behavior
In the documentation for version 1.11.0, in the "Calendar" section, is present a chapter dedicated to the events exposed by the library. [Here an example](https://nhn.github.io/tui.calendar/1.11.0/Calendar#event-afterRenderSchedule). Instead, for the version 2.1.3 (latest), in "[Calendar Core](https://nhn.github.io/tui.calendar/latest/CalendarCore)", the chapter "Events" is missing. 

I tried to use the same events from version "1.11.0", like "clickSchedule" or "beforeCreateSchedule" in the "calendar.on()" method, but the events are not triggered. Probably the events name has been changed.

## Expected Behavior
Have a list of available events in the documentation for the version 2.1.3.
  
  
**"Events" in V.1**  
![events_v1](https://user-images.githubusercontent.com/19241483/203519064-8ea8a708-fb10-458e-bd2e-af9fe9c5b33c.png)

**No "Events in" V.2**  
![events_v2](https://user-images.githubusercontent.com/19241483/203519090-a864c1a0-bffb-4cc3-ae29-7d3a275bfaf2.png)

**Comment by adhrinae** [comment]
Sorry for the inconvinience but Please refer to #1313.

**Comment by adhrinae** [comment]
Closing since it's not actually 'missing'.
