### ISSUE TITLE
Ability to disable Milestone, Task & All Day

### ISSUE THREAD

**Issue by esaiaswestberg** [nhn/tui.calendar#1412]
## Version
2.1.3

## Test Environment

Brave Browser 1.56.20 (Chromium 115.0.5790.171)
Windows 11
Svelte-Kit

## Current Behavior

Currently when you setup a calendar and view it in either Day or Week view you get shown three panels which I think can be very useful for some people. I think it would be great if you could disable some or all of these panels.

```js
new Calendar('#calendar', {
    theme: {
        week: {
            milestonePanel: {
                enabled: false
            },
            taskPanel: {
                enabled: false
            },
            allDayPanel: {
              enabled: false
            },
        }
    }
})
```

## Expected Behavior

This would then allow the developer to hide these panels from certain views. The left-over space would be taken up by the "regular" calendar.

**Comment by adhrinae** [comment]
@esaiaswestberg 

Do you mean this option?

https://github.com/nhn/tui.calendar/blob/main/docs/en/apis/options.md#weekeventview

**Comment by esaiaswestberg** [comment]
Oh yes. I can't believe I didn't find this when going through the docs.

```js
calendar.setOptions({
  week: {
    eventView: true,
    taskView, false
  },
});
```

This got what I needed.
