### ISSUE TITLE
 Release tui.calendar as NuGet-Package for .Net Blazor applications

### ISSUE THREAD

**Issue by KevinKrueger** [nhn/tui.calendar#1444]
## Feature
My wish would be that you could release your calendar for .Net Blazor applications.
There is someone on github who had already implemented this. But it doesn't work properly.
Which is a real shame.

## Question
Would that be within the realm of possibility? (WASM & Server-Side)

**Comment by KevinKrueger** [comment]
You would benefit from this really being the first proper calendar in the Blazor landscape.
Telerik, Syncfusion & DevExpress can pack their bags.

**Comment by paulogustavo3301** [comment]
Bom dia, desculpe eu havia abandonado o projeto devido ao meu trabalho
exaustivo e frustrante, tentei fazer um projeto com a base de outros
projetos que vi porém a falta de tempo é me desmotivou, e eu que desistir
de programar

Em seg., 26 de fev. de 2024, 03:47, Kevin Krüger ***@***.***>
escreveu:

**Comment by KevinKrueger** [comment]
Update: https://github.com/gismofx/toast_ui.blazor_calendar/tree/devV2
