### ISSUE TITLE
Resizing the event from one day at one hour to another day at another hour does not work

### ISSUE THREAD

**Issue by logikamente** [nhn/tui.calendar#194]
## Version
1.7.0

## Development Environment
Firefox, Chrome

## Current Behavior
Weekly view.
1) For example, I would like to resize an event from August 29th to 12:00 until August 30th at 6:00 pm. I can not do it.
2) If I create a new event and I enter from August 29th at 12:00 to August 30th at 6:00 pm, an event will be inserted in the section of a whole day, but why?

## Expected Behavior
1) I expect I can do it.
2) I expect an event that takes up the whole space from August 29th to 12:00 am to August 30th at 6:00 pm in the timetable space.

**Comment by dongsik-yoo** [comment]
@logikamente 
1. `tui-calendar` doesn't have a functionality what you want. But we think it's necessary and we will come up with a plan to implement it.
2. Can you provide me the schedule data of number 2?

**Comment by dongsik-yoo** [comment]
I see. You use default popups that `tui-calendar` provides. Checking...
