### ISSUE TITLE
Question: about possible format option (line by line basis for users)

### ISSUE THREAD

**Issue by nicholasgcoles** [nhn/tui.calendar#200]
## Version

Have not implemented yet

## Development Environment

Have not implemented yet

## Current Behavior

```js
// Just a small question
```

## Expected Behavior

Is it possible to format the calendar in a way that it has users on a line by line basis? (Used for applications such as shift scheduling). Something along the lines of this:
![image](https://user-images.githubusercontent.com/1975028/45093954-4b932280-b11a-11e8-800e-00dbc61fece1.png)

Completely understand if this is not possible and not in the pipeline but would be great to know if this kind of manipulation is possible?

Thanks for a great calendar!

**Comment by dongsik-yoo** [comment]
@nicholasgcoles Thank you for your attention. It's possible to implement. Some guys need same thing, but requirements are not exactly defined and requested yet.

**Comment by nicholasgcoles** [comment]
@dongsik-yoo thank you for your reply! Is there anything I can do to assist the process?
