### ISSUE TITLE
Make calendar SSR compatitable? 

### ISSUE THREAD

**Issue by IniZio** [nhn/tui.calendar#207]
## Version

1.7.0

## Development Environment

Chrome, Ubuntu

## Current Behavior

Currently the library uses `window` object, which is not available in SSR server-side.

Most of uses are for setting timeouts, which is also available under Nodejs global object.

```js
// Write example code
```

## Expected Behavior

To work under SSR environment.

**Comment by dongsik-yoo** [comment]
@IniZio It's not possible now. But your idea is worth.

**Comment by dongsik-yoo** [comment]
SSR is in progress. It will be on v2.

**Comment by AksBad007** [comment]
Hi, I'm currently using v2.1.3 in next.js. I'm currently having problems regarding SSR (namely, 'window is not defined' error). Is there a way to fix it?
