### ISSUE TITLE
Multiple Calendars for 1 event?

### ISSUE THREAD

**Issue by awgul** [nhn/tui.calendar#215]
Hey,

I have for example 3 calendars (it's like 3 layers).
And Layers are named:
- Mike (id: mike)
- Tom (id: tom)
- Spike (id: spike)

And I want to add only 1 event with 3 layers, so the that `data-calendar-id="mike|tom|spike"` and make the bar as 3 colors (I could achieve that with gradient).

So when choosing CALENDAR (now we have a dropdown) I would replace it with some MultiSelect field etc.

Is that somehow achieveable?

**Comment by awgul** [comment]
Hey,
I achieved it as attached.
You can click on left and hide the calendars you need.
When you have event with 3 calendars and so there are 3 striped colors, one of the colors will vanish and the rest stay. The event will be hidden when all 3 calendars will be hidden.

And I did it by providing the the `calendarId` with values like `12|43|23` where the numbers are the calendar ids.
And in creation popup I replaced the current dropdown replacing it with multi select field.

![multi-calendar](https://user-images.githubusercontent.com/1591777/46461927-49c38a00-c7c0-11e8-85ad-f4d6c00e2c32.png)

**Comment by chavy25** [comment]
Hello, I would like to accomplish the same, but I´m having difficulties with just passing to calendarId '1|2|3'. I´d really appreciate if you can point me in the right direction
