### ISSUE TITLE
Undefined calendarId after changing calendar selection in new Schedule

### ISSUE THREAD

**Issue by theFra985** [nhn/tui.calendar#216]
Hi,
I found a problem while changing the given example for my own application.
When i handle the `beforeCreateSchedule` event on the calendar instance i get an undefined `calendarId` after changing at least once the selected calendar for the new schedule

```js
let cal = new tui.Calendar(...);
cal.on('beforeCreateSchedule', () => console.log(e));
```
Versions used:
- tui.code-snippet 1.4.0
- tui.time-picker 1.3.0
- tui.date-picker 3.1.0
- tui.calendar 1.7.0
- moment.js 2.22.2
- jquery 3.2.1

I don't know if i'm doing it wrong or what do you need to identify the problem.
Thanks,
Francesco

**Comment by theFra985** [comment]
I've found that I was using ints as ids

Converting them to strings made it works

Thanks anyway

**Comment by awgul** [comment]
Yes, I noticed that too.
You need strings.

**Comment by theFra985** [comment]
Can you add the Calendar documentation?
Because in the docs the link point to the tui.Calendar constructor
