### ISSUE TITLE
How to disable MoreView?

### ISSUE THREAD

**Issue by awgul** [nhn/tui.calendar#219]
Hey,

I'd like to see all the events?
I have generally 10 per day.
So I want to see all of them on smaller screens 
I'd like to see all of them in a Day View, Month view etc.

So generally I see all events and I just scroll the whole calendar down.
I could make it by making the calendar height to for example 1400px.
And the Month View will look good but then when I switch to 2 Weeks it's too high.

**Comment by dongsik-yoo** [comment]
We don't have any option to disable moreview to expand week height.
