### ISSUE TITLE
How to custom the category of calender?

### ISSUE THREAD

**Issue by dksuper** [nhn/tui.calendar#237]
## Version

v1.7.0

## Development Environment
chrome

## Current Behavior

How can I custom the category of calender ?
![image](https://user-images.githubusercontent.com/35549846/48047067-bf60b280-e1d1-11e8-95c0-af549fd784b9.png)

Thank you!

**Comment by dongsik-yoo** [comment]
@dksuper See https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#templatecustomize-ui. The names of the related properties are `milestoneTitle`, `taskTitle `, `alldayTitle `

**Comment by dksuper** [comment]
@dongsik-yoo
Thank you for reply: ) , but I have the other question , how can I increase the amount of calender category ,like this:
<img width="608" alt="2018-11-06 10 49 38" src="https://user-images.githubusercontent.com/35549846/48071917-623b2000-e216-11e8-803b-6f333fc39955.png">

**Comment by dongsik-yoo** [comment]
That's a resource view that we don't have. And there is no way to increase panels.

**Comment by alberto-morais** [comment]
> @dongsik-yoo
> Thank you for reply: ) , but I have the other question , how can I increase the amount of calender category ,like this:
> <img alt="2018-11-06 10 49 38" width="608" src="https://user-images.githubusercontent.com/35549846/48071917-623b2000-e216-11e8-803b-6f333fc39955.png">
I like featuring
