### ISSUE TITLE
Last saturday of February isn't working on timezones with Daylight Saving Time

### ISSUE THREAD

**Issue by augustocb23** [nhn/tui.calendar#257]
## Version
1.7.0 | Wed Aug 08 2018

## Development Environment
Chrome and Firefox, Windows 10

## Current Behavior
![Day not showing](https://user-images.githubusercontent.com/14170426/51182473-76099f00-18b5-11e9-856c-f917baf009d7.png)

In February, a Saturday just is repeating and the next one is not working. It's happening in the last week of the month.
It's not rendering, but if a create the date programmatically (I use a script that load from a WebMethod and add it), it's rendered before the Sunday. Look that the day Feb-16 is repeated and the week is starting on Saturday, not on Monday.
Even if I switch to week or day view, it's still now working. I can't add or edit events.

![Detail on the start of date](https://user-images.githubusercontent.com/14170426/51182183-88370d80-18b4-11e9-8eb5-e7d788a534cb.png)

#### Days not showing in each year

Year|Day
-----|------
2018|Feb-24
2019|Feb-23
2020|Feb-22
2021|Feb-27
2022|Feb-26

## Expected Behavior
Load the calendar correctly, with all days.

**Comment by dongsik-yoo** [comment]
@augustocb23 Can you provide your timezone? I'm using GMT+0900(Korea).

**Comment by sganzerla** [comment]
Hi, GMT -0300 (Brazil).

**Comment by sganzerla** [comment]
Brazil TimeZones with DST (Daylight Saving Time) rendering this error last week of the month.
Test error:
"E. South America Standard Time" -0300DST (Brasília - Distrito Federal)
"Central Brazilian Standard Time" -0400DST (Cuiába - Mato Grosso)
Test ok:
"SA Western Standard Time" - 0300 not DST (Fortaleza - Ceará)
"SA Pacific Standard Time" - 0500 not DST (Rio Branco - Acre)

**Comment by gabrielcaixeta** [comment]
Hi,

In my case, it is repeating the 16th and omitting the 23rd in the calendar in 2019. See the print-screen.

The time zone is GMT-0200 (Horário de Verão de Brasília). It is daylight saving time in the Brazil.
In other years the same problem is happening in the month of February: one day is duplicated and another is not shown.

![captura_toast](https://user-images.githubusercontent.com/8334460/51360214-eda41d80-1ab1-11e9-9e61-a74d380265f7.PNG)

**Comment by dongsik-yoo** [comment]
Oh my god!

**Comment by sganzerla** [comment]
@dongsik-yoo , @jungeun-cho,
This problem only occurs on the last day of daylight saving time of each year. In the case of Brazil on February 16.

**Comment by JonathanMarmitt** [comment]
Hi!
Any hope to solve this issue? I'm suffering it as well =/

**Comment by edureis** [comment]
Hi!
Any hope to solve this issue?

**Comment by jungeun-cho** [comment]
We are aware of the problem.
But we are too busy preparing for another project release.
I'm sorry for the inconvenience. Even if it takes a long time, I would like to change it carefully. I will try to solve the problem as soon as possible. :)

**Comment by sganzerla** [comment]
Thanks @jungeun-cho  for feedback, here in Brazil ended summer time day 16/02, calendar returned to function normally. We hope the new version will be ready before the penultimate week of February 2020. Good luck with Dr. Mario.

**Comment by dongsik-yoo** [comment]
@augustocb23 @augustocb23 @gabrielcaixeta @JonathanMarmitt @edureis Guys, good news!
I fixed this issue and `pre-release` [v1.10.1-rc](https://github.com/nhnent/tui.calendar/releases/tag/v1.10.1-rc) and published npm the package.
I tested it but I want you to confirm this fix.

**Comment by gabrielcaixeta** [comment]
Hi @dongsik-yoo,
I has tested this fix and worked for me.

**Comment by augustocb23** [comment]
Here works fine... until I change the date to the DST interval.

The DST ended in fev-16, and if I render the calendar today (mar-07), it's correct. When I change the date to jan-10, between the DST interval - in 2018, it's nov-11 to fev-16 - the bug comes out again.

## Error in fev-16

![bug](https://user-images.githubusercontent.com/14170426/53956026-46a72f80-40b9-11e9-8450-d5dbdb88a751.png)

## Normal rendering in fev-10

![ok](https://user-images.githubusercontent.com/14170426/53956379-393e7500-40ba-11e9-9822-1c834281c770.png)

**Comment by jungeun-cho** [comment]
@augustocb23 
We are working on DST again.
We are testing and verifying in more detail.
Thank you for confirming.

**Comment by dongsik-yoo** [comment]
Almost there!

**Comment by dongsik-yoo** [comment]
https://github.com/nhn/tui.calendar/releases/tag/v1.11.1-rc

Guys! Please check this version to fix DST bugs.

**Comment by frovere** [comment]
Thanks guys that seems to work, last week we change from UTC-3 to UTC-4.
April 7th is showing now.

Timezone: America/Santiago

## v1.11.0

![april-v1.11.0-America-Santiago](https://user-images.githubusercontent.com/5685929/55963423-cbe5ad00-5c40-11e9-9982-2a95019bf8a8.png)

![april-v1 11 0-month](https://user-images.githubusercontent.com/5685929/55964132-27fd0100-5c42-11e9-98d1-ac24b2f33be9.png)

## v1.11.1-rc

![april-v1 11 1-rc-America-Santiago](https://user-images.githubusercontent.com/5685929/55963783-778efd00-5c41-11e9-938e-ef279c6907ce.png)

![april-v1 11 1-rc-month](https://user-images.githubusercontent.com/5685929/55964144-2e8b7880-5c42-11e9-82f9-c685871e2246.png)

**Comment by augustocb23** [comment]
Great, now it's working! 😀

Thanks!
