### ISSUE TITLE
Schedules longer than 24h doesn't show up

### ISSUE THREAD

**Issue by karolkowalczykmako** [nhn/tui.calendar#265]
## Version
1.10.0

## Development Environment
Chrome, MacOS

## Current Behavior
When I'm trying to add schedule longer than 24h nothing happens. (there are also not visible in all day schedules).

```js
calendar.createSchedules([{
      id: String(1549009800000),
      calendarId: String(1),
      title: 'Test',
      category: 'time',
      start: new Date('Jan 31 2019 9:30:00 GMT+0100'), // or 1548923400000
      end: new Date('Feb 01 2019 10:30:00 GMT+0100'), // or 1549013400000
      bgColor: 'red',
      color: 'white',
      isAllDay: false,
      isReadOnly: false
    }]);
```

## Expected Behavior
That would be nice if we could create schedules as long as we want.

**Comment by dongsik-yoo** [comment]
@karolkowalczykmako The cause might be asychronous rendering. Try this.
```js
calendar.createSchedules({.......}, true); // don't render
calendar.render(true); // render synchronously now
```

**Comment by thormug** [comment]
When you create a schedule longer than 24h, it should appears on the "all day" schedule even if "isAllDay" is set to false.

In my opinion, when creating a schedule longer than 24 hours and isAllDay is set to false, it should render on the "time" part of the calendar.
