### ISSUE TITLE
Dynamically loaded schedules

### ISSUE THREAD

**Issue by lessan98** [nhn/tui.calendar#273]
I have a really weird problem that i can't figure out.

If i create schedules outside a request, all is fine, so this:

```
   me.calendar = new tui.Calendar(document.getElementById(`${me.id}-calendar`), {
        defaultView: 'week',
        taskView: false,
        useCreationPopup: true,
        useDetailPopup: true,
        week: {
            daynames: ['Du', 'Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sa'],
            narrowWeekend: false,
            startDayOfWeek: 1
        }
    });

    me.calendar.createSchedules(events);
```

works just as expected. However, if those events are dynamically loaded from the server like this:

   ```
me.calendar = new tui.Calendar(document.getElementById(`${me.id}-calendar`), {
        defaultView: 'week',
        taskView: false,
        useCreationPopup: true,
        useDetailPopup: true,
        week: {
            daynames: ['Du', 'Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sa'],
            narrowWeekend: false,
            startDayOfWeek: 1
        }
    });

    let startDate = new Date(me.calendar.getDateRangeStart()._date);
    let endDate = new Date(me.calendar.getDateRangeEnd()._date);

    fetch('/get-events?startDate=' + startDate.toISOString().split('T')[0] + '&endDate=' + endDate.toISOString().split('T')[0], {
        headers: {"Content-Type": "application/json; charset=utf-8"}
    }).then(function (response) {
        response.json().then(function (response) {
            me.calendar.createSchedules(response.events);
        });
    });
```

the schedules are created, that i am sure of, but the problem is that for some reason, the height of the calendar is set to 0 and i can't figure out why

**Comment by lessan98** [comment]
for anyone still facing this issue i solved it by adding 
`me.calendar.toggleScheduleView(true);`

after the creation of the schedules

**Comment by jungeun-cho** [comment]
@lessan98 
1. Can I see the response on json data?
2. Is there an error message in the console log?

**Comment by dongsik-yoo** [comment]
@lessan98 Please use `Calendar.render(true)` which renders synchronously.

**Comment by lessan98** [comment]
@jungeun-cho  it is an array of objects like this one, where the id goes from 0 to the number of schedules -1 
`calendarEvents = [];
calendarEvents.push({bgColor: "#a8e5c3",
​​
borderColor: "#a8e5c3",
​​
calendarId: "1",
​​
category: "time",
​​
color: "black",
​​
end: "2019-02-05T08:30:00",
​​
id: "0",
​​
start: "2019-02-05T08:00:00",
​​
title: "Discutie Proiecte"})`

No, there is no error in the console.


To detail exactly what i am doing, when the user clicks a button, i insert a div with id `calendar-${calendar.number}` (he can open multiple calendars but when testing i only opened one), then i instantiate a calendar object on this div, then i make an ajax request with startDate, endDate and userId to retrieve all the schedules of that user in that interval.
startDate and endDate are taken from what the calendar has rendered using `me.calendar.getDateRangeStart()._date` and `me.calendar.getDateRangeEnd()._date`

when the ajax has finished, i iterate over the response to build an array of objects like the one above, then i simply do  `me.calendar.createSchedules(calendarEvents);` 

this renders the events (i can see them with inspect element in the dom), but the height of the calendar is set to 0. When i add this `me.calendar.toggleScheduleView(true);` it works like a charm

I tested this on firefox dev edition and chrome

**Comment by lessan98** [comment]
@dongsik-yoo one more question, is it possible to customize the purple box for creating new schedules?
