### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by quantumwebco** [nhn/tui.calendar#278]
Is this calendar responsive?

**Comment by jungeun-cho** [comment]
@quantumwebco 
The width of the calendar can be adjusted automatically according to the screen size.
Could you explain your requirements in more detail?

**Comment by dongsik-yoo** [comment]
If the container size has changed, call `Calendar.render()` to re-render it.

**Comment by quantumwebco** [comment]
I was considering migrating from fullcalendar, which has a lot of options for display and responsiveness. I was just seeing if it would be a good change as I like some of the other features but I didn't see any responsive demos or mention in the docs about it. I'll install it and try it out. Thanks

**Comment by matthiasg** [comment]
It is not flex resize compatible out of the box (https://github.com/nhnent/tui.calendar/issues/268) which it might handle internally one day to a certain degree, but since there is no way to safely monitor an elements size a call to `render` will be required by the hosting application anyway.  

Calendar also does need to recalculate items heights for overflow items (`more`) which is not yet possible with pure CSS approach.

**Comment by nivritgupta** [comment]
@jungeun-cho  @matthiasg , will this calendar library  support responsiveness  feature if we used this calendar  in iPad /iPhone /Android-phone  devices ?

**Comment by khan9920** [comment]
Hey guys, I do not know if I am in the right thread, but I have a small problem resizing the calendar and fitting it inside a wrapper. I figured that if I change the position of the #calendar to relative, it fits in to the wrapper. However; it works only when I change it through the inspector. When I change it on the actual code, the rest of the fields are disappearing. Could you help me with this please? Attached a screenshot of the screen I am working on.
![Screen Shot 2019-06-21 at 8 31 57 AM](https://user-images.githubusercontent.com/29376547/59894663-0ddc5d80-93ff-11e9-8826-9849d37b5aed.png)

**Comment by dongsik-yoo** [comment]
@khan9920 Please check container element's height is set. There is no minimum height of month view yet.

**Comment by khan9920** [comment]
Hey @dongsik-yoo I set the height of tui-view-7 to 600px and it worked. Thanks so much! :)

**Comment by dongsik-yoo** [comment]
@khan9920 Great! But I think you'd better to set height at container element. tui-view-7 element might be changed after re-rendered.

**Comment by khan9920** [comment]
@dongsik-yoo I am sorry, I am a bit confused as to what you are referring to as the container. Could you explain it to me please?

**Comment by dongsik-yoo** [comment]
@khan9920 `#calendar` element is a container element for Calendar.
```html
<body>
...
<div id="calendar" style="height: 800px;"></div>
...
</body>
```

```js
var calendar = new Calendar('#calendar', {
  defaultView: 'month
});
```

And see this document (https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#html).

**Comment by khan9920** [comment]
@dongsik-yoo yes. That fixed it. Thanks so much!
