### ISSUE TITLE
Duplicate day of the month (16)

### ISSUE THREAD

**Issue by acsar** [nhn/tui.calendar#283]
## Version
1.10.0

## Development Environment
Crome 72.0.3626.109 (Versão oficial) 64 bits

## Current Behavior
Duplicate day of the month (16)
https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html

```js
// Write example code
```

**Comment by gabrielcaixeta** [comment]
Hi @acsar this issue was mentioned in #257
