### ISSUE TITLE
tutorial : useCreationPopup 

### ISSUE THREAD

**Issue by limbo127** [nhn/tui.calendar#287]
Hello,
can you give us a simple tutorial to change the useCreationPopup for example ?
regards,

My question is not about api documentation 
( const cal = new Calendar ('# cal', {
   defaultView: 'week',
   taskView: true,
   useCreationPopup: true,
   useDetailPopup: true,
   ... )

But a example how to create the html form / div element to integrate, extend the default popup. I need to add some field , then save into the schedule raw object.
Regards
Nicolas

**Comment by jungeun-cho** [comment]
@limbo127 
Unfortunately,
We do not provide functionality to modify the pop-up template in its entirety.

Currently, strings can only be changed for 'all day', 'free', 'busy', and 'save' buttons.
```js
const cal = new tui.Calendar('#cal', {
        defaultView: 'week',
        taskView: true,
        useCreationPopup: true,
        useDetailPopup: true,
        week: {
            daynames: ['Du', 'Lu', 'Ma', 'Mi', 'Jo', 'Vi', 'Sa'],
            narrowWeekend: false,
            startDayOfWeek: 1
        },
        template: {
          popupIsAllDay: function() {
            return 'All Day';
          },
          popupStateFree: function() {
            return 'Free';
          },
          popupStateBusy: function() {
            return 'Busy';
          },
          popupSave: function() {
            return 'Save';
          },
    ...
```
![creationpopuptemplate](https://user-images.githubusercontent.com/43128697/53214333-8d476380-368f-11e9-8ed1-0d77e2da76f1.png)

If you want to extend the template to creationPopUp
After forking the **tui-calendar repository**
Edit the template file(`tui-calendar/src/js/view/template/popup/scheduleCreationPopup.hbs`) and use it for your project.

**Comment by deweysia** [comment]
@jungeun-cho Hello, what do I do after editing the `tui-calendar/src/js/view/template/popup/scheduleCreationPopup.hbs` ? I'm using simply `tui-calendar/dist/tiu-calendar.js`. I don't think editing the `hbs` does anything.

**Comment by jungeun-cho** [comment]
@deweysia 

I am very sorry for the delay.

The dist directory is bundled files.
If you have modified the source code in the src directory, you should build it.

`npm run serve`
