### ISSUE TITLE
Is it possible to use Dragging and Resizing in mobile devices?

### ISSUE THREAD

**Issue by NazirTemirov** [nhn/tui.calendar#293]
## Current Behavior
I cannot dragg and resize schedules on mobile devices.

## Expected Behavior
Opportunity to dragg and resize schedules on mobile devices.

**Comment by jungeun-cho** [comment]
It is not draggable on mobile devices.
Resize at the resize event.
Check it
https://github.com/nhnent/tui.calendar/blob/master/examples/js/app.js
```js
window.addEventListener('resize', resizeThrottled);
resizeThrottled = tui.util.throttle(function() {
  cal.render();
}, 50);
```
