### ISSUE TITLE
bug that changes 12:00pm to 00:00pm in view popup

### ISSUE THREAD

**Issue by ArekZGate3** [nhn/tui.calendar#296]
## Version

1.9.1 but also see on latest
## Development Environment

chrome
## Current Behavior

12:00pm shoes as 00:00 in view popup. I am experincing the same in issue in my code as live on the https://ui.toast.com/tui-calendar/ website. Just move one of the time slots to 12:00 pm and you can see bug from image below.
![image](https://user-images.githubusercontent.com/8572494/54223732-21099400-44c6-11e9-8f9a-cdac14405477.png)

```js
// Write example code
```

## Expected Behavior

Expected Behavior would be to see 12:00pm - 02:00pm

**Comment by jungeun-cho** [comment]
In the example, the `timegridDisplayPrimaryTime` template is wrong.

![스크린샷 2019-03-21 17 05 54](https://user-images.githubusercontent.com/43128697/54739740-88c58a80-4bfc-11e9-9b26-758c240fc9a0.png)

I fixed it and updated the example.
https://nhnent.github.io/tui.calendar/latest/tutorial-example00-basic

**Comment by afrazahmmad** [comment]
This issue is still appearing

**Comment by afrazahmmad** [comment]
12 am is still coverting to 00 am 
timegridDisplayPrimaryTime is taking effect on it. This method only effects on day and week view timeline on left side of chart.

**Comment by restlessera** [comment]
I am using the version 1.12.0 and having the same issue. Did anyone worked the fix?

**Comment by W3b3r** [comment]
Some one have a fix?

**Comment by dongsik-yoo** [comment]
something is wrong. But you can use a template function to fix it.
### example
https://github.com/nhn/tui.calendar/blob/de14e39434f1d328303cf68efd905877160f5a75/examples/example16-template-for-popup.html#L74-L83
