### ISSUE TITLE
Create calendar schedules using jquery

### ISSUE THREAD

**Issue by onsjkm** [nhn/tui.calendar#303]
## Version

v1.11.0

## Current Behavior

I have included the necessary js scripts jquery.min.js (version 3.4.0) tui-code-snippet.js tui-calendar.js
and 
tui-calendar.css
and in the javascript trying to create schedules with the code snippet:
```js
// Write example code
    <div id="calendar" style="height: 800px;"></div>
    <script type="text/javascript">
        var cal = $('#calendar').tuiCalendar({
            usageStatistics: false,
            defaultView: 'month',
            taskView: true,
            template: {
                monthGridHeader: function(model) {
                    var date = new Date(model.date);
                    var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
                    return template;
                }
            }
        });
        cal.createSchedules([
            {
                id: '1',
                calendarId: '1',
                title: 'my schedule',
                category: 'time',
                dueDateClass: '',
                start: '2019-04-15T22:30:00+09:00',
                end: '2019-04-16T22:30:00+09:00'
            },
            {
                id: '2',
                calendarId: '1',
                title: 'second schedule',
                category: 'time',
                dueDateClass: '',
                start: '2018-01-18T17:30:00+09:00',
                end: '2018-01-19T17:31:00+09:00',
                isReadOnly: true    // schedule is read-only
            }
        ], true);
    </script>
```

## Expected Behavior

I was expecting calendar with schedules on it. But get 'function createSchedules not found'. How should I get access to the calendar object after its created using jquery?

**Comment by Slethael** [comment]
Not sure if it is the issue here as I'm using React, but I created 2 calendars in order to get the lib working, as follows : 
`let calendar = new Calendar(this.calRef.current, {
                calendars: [
                    {
                        id: '0',
                        name: 'Confirmé'
                    }, {
                        id: '1',
                        name: 'En attente'
                    }],
                defaultView: 'month',
                viewName: 'month',
                taskView: false,
                scheduleView: ['time'],
                template: {
                    monthGridHeader: function (model) {
                        const date = new Date(model.date);
                        return '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
                    },
                },`
I have the "Confirmé" calendar (as "confirmed", roughly translated, I use this to check rendez-vous) and "En attente" ("On hold", also for rendez-vous, taken but not confirmed yet).

What COULD work for you is adding this to your calendar.

**Comment by fklement** [comment]
@jungeun-cho @Slethael This issue is not resolved.

I'm currently struggling with the same.
@Slethael proposed fix does not help.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-15T02:30:19
          
          
            * 메일 제목 : 
Re: [nhn/tui.calendar] Create calendar schedules using jquery (#303)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by jungeun-cho** [comment]
@fklement 
Sorry for the late reply.

```js
// The #calendarEl is jquery wrapper.
var $calendarEl = $('#calendar').tuiCalendar({
            usageStatistics: false,
            defaultView: 'month',
            taskView: true,
            template: {
                monthGridHeader: function(model) {
                    var date = new Date(model.date);
                    var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
                    return template;
                }
            }
        });
```

When used like this, it returns the object wrapped with JQuery.

You can get the calendar instance from jquery data and use it.
`$calendarEl.data('tuiCalendar')`...
```js
var cal = $calendarEl.data('tuiCalendar');

cal.createSchedules([
      {
                id: '1',
                calendarId: '1',
                title: 'my schedule',
                category: 'time',
                dueDateClass: '',
                start: '2020-07-15T22:30:00+09:00',
                end: '2020-07-15T22:30:00+09:00'
            },
            {
                id: '2',
                calendarId: '1',
                title: 'second schedule',
                category: 'time',
                dueDateClass: '',
                start: '2020-07-17T17:30:00+09:00',
                end: '2020-07-17T17:31:00+09:00',
                isReadOnly: true    // schedule is read-only
            }
      ])
```

Would you like to try it?

---
I'll update the README.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-15T11:05:20
          
          
            * 메일 제목 : 
Re: [nhn/tui.calendar] Create calendar schedules using jquery (#303)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

**Comment by fklement** [comment]
@jungeun-cho Thanks for the prompt response. I'll check on this today and let you know.

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-07-15T17:25:40
          
          
            * 메일 제목 : 
Re: [nhn/tui.calendar] Create calendar schedules using jquery (#303)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
