### ISSUE TITLE
Wrong type for IMonthOptions.visibleWeeksCount

### ISSUE THREAD

**Issue by mklenk** [nhn/tui.calendar#307]
## Version
1.11.2

## Development Environment
Angular 7.2.9, Typescript v3.2.4

## Current Behavior
IMonthOptions.visibleWeeksCount is supposed to be a number but it's defined as boolean in https://github.com/nhn/tui.calendar/blob/8ba786a69143c01c14daa614be6b396478117198/index.d.ts#L169

**Comment by jungeun-cho** [comment]
@mklenk 

Our team modified it and merged it into the master branch.
It will be included in the next patch release.

Thanks.
