### ISSUE TITLE
Vanilla es6 import fails

### ISSUE THREAD

**Issue by AlexShafir** [nhn/tui.calendar#310]
## Version
tui-calendar: 1.11.2
tui-code-snippet: 1.5.1

## Development Environment
Windows 7, Chrome

## Task
I try to make use of calendar in vanilla js ES6 (no bundlers, no package managers etc)

I try:

```js
import {Calendar} from '/libs/tui/tui-calendar.js'
```

and error is:
```
SyntaxError: The requested module '/libs/tui/tui-calendar.js' does not provide an export named 'Calendar'
```

despite that docs mention that es6 import is supported

**Comment by jungeun-cho** [comment]
not named export.

import Calendar from 'tui-calendar'; /* ES6 */

**Comment by AlexShafir** [comment]
Thanks for your reply. This time I did this:

index.html:
```html
<head>

  <link rel='stylesheet' href="libs/tui/tui-calendar.css">
  <script src='libs/tui/tui-code-snippet.js'></script>
  <script src='libs/tui/tui-calendar.js'></script>

  <script type='module' src="/src/index.js">

<head/>
```

index.js:
```js
import Calendar from 'tui-calendar'

alert(Calendar)
```

And I got:  `Failed to resolve module specifier "tui-calendar"`

**Comment by AlexShafir** [comment]
What worked for me is: `var Calendar = tui.Calendar` instead of `import`.

Do you plan to add version that relies on ES6 import/export only?

**Comment by Johann-S** [comment]
That's pretty normal `tui.Calendar` is built as an UMD module, so in a browser you'll have a global var `tui.Calendar` and in a bundler you'll be able to do:

```js
import Calendar from 'tui-calendar'
```

If `tui-calendar` teams want to provided a module version, they have to build their libs in `ESM` which will allow for their users to use `tui-calendar` as a module in a browser, and it'll allow bundlers a better tree-shaking.
