### ISSUE TITLE
Is there any option like "autoAdjustOverflow" to set "detailPopup" auto adjust?

### ISSUE THREAD

**Issue by sj279811799** [nhn/tui.calendar#313]
## Version
"@toast-ui/react-calendar": "^1.0.1"
"tui-calendar": "^1.10.0"

## Development Environment
Chrome &  mac

## Current Behavior
![image](https://user-images.githubusercontent.com/12233760/56736290-5c240600-679a-11e9-99e9-4b0fe99612c0.png)

```js
// Write example code
```

## Expected Behavior
hello, is there any option like "autoAdjustOverflow" to set "detailPopup" auto adjust?

**Comment by jungeun-cho** [comment]
@sj279811799 
![스크린샷 2019-05-07 11 46 06](https://user-images.githubusercontent.com/43128697/57268204-e5eaa200-70bd-11e9-8fec-c6b15ff889d0.png)

By default, the detail popup is set to automatically fit.
Could you tell me more about your situation?

**Comment by sj279811799** [comment]
![image](https://user-images.githubusercontent.com/12233760/58484240-438d7e00-8194-11e9-892c-48989968e4d4.png)
There is a menu on the left，`left: -261px;`
