### ISSUE TITLE
Link to event page

### ISSUE THREAD

**Issue by Fijvect** [nhn/tui.calendar#314]
Hello! 
I'm about to try rebuilding the detail popup because I can't find a built-in way to add this. 

I am using the calendar to display events & classes. These sometimes involve ticket sales. I would like to be able to put a button somewhere that will link to an event page on my site in order to facilitate the user getting to the ticket sales location more easily.

I would have thought links to an event page would be a common usage, but I guess not! haha.

Is this a feature that exists yet that I may have missed somehow? Or can this perhaps be added in the future?

Thank you.

**Comment by jungeun-cho** [comment]
@Fijvect 

How about using a custom template?

or

When creating a calendar instance, set the option `useDetailPopup` to `false` and do whatever you want in the `clickSchedule` event handler.

e.g.)
```javascript
# 1
const calendar = new tui.Calendar(document.getElementById('cal'), {
  ...
  useDetailPopup: false,
  template: {
  ...
    time: function(schedule) {
      const start = moment(schedule.start.getTime()).format('HH:mm');
      const end = moment(schedule.end.getTime()).format('HH:mm');

      return `<strong>${start} ~ ${end}</strong><a href="/eventPageLink">${schedule.title}</a>`;
    },
```

```javascript
# 2
const calendar = new tui.Calendar(document.getElementById('cal'), {
  ...
  useDetailPopup: false,
};

calendar.on('clickSchedule', (schedule, event) => {
  /*
   what to do when you click on a schedule ...
   */
});
```

Check it out.
https://nhn.github.io/tui.calendar/latest/Template
https://nhn.github.io/tui.calendar/latest/Calendar#event-clickSchedule

Thanks! :blush

**Comment by Fijvect** [comment]
Thanks for your reply! :blush:

I tried the custom template method first, but it seemed like more work than I wanted to do for such a small tweak, haha!

I ended up just messing around with the source code and adding a "URL" attribute to the calendar. When a URL is provided it renders a button at the bottom.


In case anyone else want to do something similar, here's where you need to modify 3 files:

INSIDE OF schedule.js (found in src>js>model) change these 3 things:
Within "function Schedule():" add this:
```javascript
    /**
     * If a URL is provided then render a button at the bottom of detail popup.
     * @type {object}
     */
    this.url = '';
```
Within "Schedule.prototype.init = function(options) {" add this:
```javascript
    this.url = options.url || '';`
````
Within "Schedule.prototype.equals = function(schedule) {" add this:
```javascript
if (this.url !== schedule.url) {
        return false;
    }
```

THEN INSIDE OF scheduleDetailPopup.hbs (found in src>js>view>template>popup):
Add your HTML:
```hbs
    {{#if schedule.url}}
    <div class="{{CSS_PREFIX}}popup-link">
      <a href="{{schedule.url}}">View Event</a>
    </div>
    {{/if}}
```

THEN INSIDE OF popup.styl (found in src>css):
Add styling for your popup link however you'd like:
```style
.{css-prefix}popup-link
  display: block
  padding: 10px
  width: 100%;
  outline: none
  background: none
  border: none
  cursor: pointer

.{css-prefix}popup-link-a
  display:block;
  width: 100%;
```

Then `npm run bundle` to compile it and you're good to go!

Just need to add this when defining your calendar now:
```javascript
isAllDay: false,
url: '{{YOUR URL HERE}}',
body: 'loprem ipsum',
....etc
```

With a couple website-specific classes thrown on my button, it came out like this:
![image](https://user-images.githubusercontent.com/12387268/57563961-7abcfc00-7359-11e9-80e1-32b2df94e233.png)

**Comment by SidraMahmood** [comment]
@Fijvect how do you link your custom event handler with the popup view event?

**Comment by SidraMahmood** [comment]
![Screenshot from 2022-05-24 11-55-48](https://user-images.githubusercontent.com/92089171/169967854-861fbd03-0ac7-4c12-bcc0-679f2b8aa803.png)
I want to pass my custom event handlers in these popup options but it didn't pick my custom event it only work through the built-in event handlers
