### ISSUE TITLE
Wrong day after creating a new Schedule

### ISSUE THREAD

**Issue by tgobira** [nhn/tui.calendar#316]
## Version
Version 1.12.0

## Development Environment
Testing on Chrome with a Windows 10 OS.

## Current Behavior
I'm trying to feed schedules on my calendar from a JSON, but all Schedules created comes with wrong day identification on calendar.
![image](https://user-images.githubusercontent.com/23407525/56928264-a6fc9100-6aac-11e9-99a8-bfe9add1c1ae.png)

```js
function setSchedules() {
    calendario.clear();
    calendario.createSchedules(ScheduleList);
    refreshScheduleVisibility();
}

function retornaEventosAgenda() {
    ScheduleList = [];

    var url = url_listarRegistros,
        param = {},
        corpoEvento = '', tipoEvento, cor, dtEvento,
        dtHoje = retornaData_hoje(), evento;

    $.post(url, add_anti_forgery_token(param), function (response) {
        if (response && response.length > 0) {
            for (var i = 0; i < response.length; i++) {
                corpoEvento = response[i].NomeResponsavel + ' - ' + response[i].Descricao;

                evento = retornaData_yyyymmdd(response[i].DataEvento);
                dtEvento = new Date(evento);
                dtHoje = new Date(dtHoje);

                if (!response[i].NomeCliente.includes('DEFINIDO'))
                    tipoEvento = 'Contato com Cliente';
                else
                    tipoEvento = 'Atividade Interna do Sublime';

                if (dtEvento > dtHoje)
                    cor = '#1E90FF';
                else
                    cor = '#DC143C';

                if (response[i].Realizado == 1)
                    cor = '#32CD32';

                ScheduleList.push({
                    id: i,
                    calendarId: '1',
                    title: tipoEvento,
                    body: corpoEvento,
                    color: 'white',
                    bgColor: cor,
                    category: 'time',
                    start: dtEvento.setDate(dtEvento.getDate() + 1),
                    end: dtEvento,
                    isReadOnly: true    // schedule is read-only
                });
            }
        }
    });
}

$(document).ready(function () {
    retornaEventosAgenda();

    calendario = new tui.Calendar('#calendario', {
        defaultView: 'month',
        month: {
            daynames: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            moreLayerSize: {
                height: 'auto'
            }
        },
        template: templates,
        useCreationPopup: true,
        useDetailPopup: true,
        isReadOnly: true
    });

    setRenderRangeText();
    setSchedules();
    setEventListener();
});
```
## Expected Behavior
When feed or create new Schedule, it comes in the right date position with using other artifacts to correct this information.

**Comment by dongsik-yoo** [comment]
Can you provide some information?
* Your timezone
* 1 schedule json data(`start` and `end`)

**Comment by tgobira** [comment]
Hello @dongsik-yoo !

Here it goes:

- Timezeon: Brazil (UTC Offset: UTC -3)
- Start and End data: both 2019-04-27. See on pics above.

Return from DataBase (2019-04-27)
![image](https://user-images.githubusercontent.com/23407525/56961612-91c64780-6b2a-11e9-9e57-8ce55d72ad37.png)

When apply new Date() command it reaches 26 Apr 2019
![image](https://user-images.githubusercontent.com/23407525/56961634-9ee33680-6b2a-11e9-8f61-76faacc33cbb.png)

It occurs to every schedule (every date) that I insert into calendar. Even fixed values.

Example:
`var ScheduleList = [
    {
        id: '1',
        calendarId: '1',
        title: 'Evento 01',
        category: 'time',
        dueDateClass: '',
        start: '2019-04-27',
        end: '2019-04-27',
        isReadOnly: true    // schedule is read-only
    }
];`

**Comment by tgobira** [comment]
@dongsik-yoo , 1 more info about this problem.

Even with fixed values on a created schedule, the same problem occurs.

`
$(document).ready(function () {
    //retornaEventosAgenda(calendario);
    preencheDropList();
    preencheDropListResponsavel();

    calendario = new tui.Calendar('#calendario', {
        defaultView: 'month',
        month: {
            daynames: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
            moreLayerSize: {
                height: 'auto'
            }
        },
        template: templates,
        useCreationPopup: true,
        useDetailPopup: true,
        isReadOnly: true
    });

    calendario.createSchedules([
        {
            id: '1',
            calendarId: '1',
            title: 'my schedule',
            category: 'time',
            dueDateClass: '',
            start: '2019-04-27T22:30:00',
            end: '2019-04-27T02:30:00',
            isReadOnly: true    // schedule is read-only
        },
        {
            id: '2',
            calendarId: '1',
            title: 'second schedule',
            category: 'time',
            dueDateClass: '',
            start: '2019-04-30T17:30:00',
            end: '2019-04-30T17:31:00',
            isReadOnly: true    // schedule is read-only
        }
    ]);

    //setRenderRangeText();
    //setSchedules();
    //setEventListener();
});
`
![image](https://user-images.githubusercontent.com/23407525/56990818-74b26880-6b6c-11e9-966b-83b4fcc8ea05.png)

**Comment by tgobira** [comment]
@dongsik-yoo , I've found the problem cause and solved it.

The funtion new Date() on JS, when I passes a string date (2019-04-29) always return a day before that I've informed.

So I've passed the hour into the date, as new Date('2019-04-29 00:00') and now it returns the correct information to my Calendar.

Thank's for the attention!
