### ISSUE TITLE
visibleWeeksCount removes week from top

### ISSUE THREAD

**Issue by afrazahmmad** [nhn/tui.calendar#318]
Hello support!
thanks for great plugin.
I am facing an issue
If I limit number of weeks to 5 or less then calendar removes weeks from top and starting dates of current month are gone. 
another issue is if I switch view from month > week  and then back to month then all weeks are shown means visibleWeeksCount does not take effect.

Below image is removing first week of current month 
month:{		
    visibleWeeksCount:5
},
![image](https://user-images.githubusercontent.com/22490945/57354267-7f7c8700-7184-11e9-8349-3f72374609ad.png)

**Comment by jungeun-cho** [comment]
@afrazahmmad 
The `visibleWeeksCount` based on today's date.
If you use the `isAlways6Week: false` option, it will automatically be rendered in a monthly view for 5 or 6 weeks.

```javascript
const cal = new Calendar('#calendar', {
  defaultView: 'month',
  ...
  month: {
    // visibleWeeksCount: 5,
    isAlways6Week: false
  }
});
```
The second issue you mentioned works fine if you do not change the `month.visibleWeeksCount` option before `changeView`.
Please make sure that you do not change the option value when you do `setOptions` in your code.

I hope my answers help you.
