### ISSUE TITLE
Not able to serve and build code

### ISSUE THREAD

**Issue by coolvijaymca** [nhn/tui.calendar#319]
Hi All, I am trying to extend extend the new schedule popup box where I need to add few more field on the form. 
For this I pull the latest code from git and try to run npm serve command. However project is compiled with warning but not launching in browser. Anyone know how to run this code in browser.
===================== 
![Capture](https://user-images.githubusercontent.com/27564614/57381122-581fbd00-7178-11e9-9115-fe56e45cda26.JPG)
COMPILER RESULT ============================

C:\Program Files\Git\bin\tui.calendar>npm run serve

> tui-calendar@1.12.0 serve C:\Program Files\Git\bin\tui.calendar
> webpack-dev-server --mode development --progress --inline --hot

 10% building 1/1 modules 0 activei ｢wds｣: Project is running at http://0.0.0.0:8080/
i ｢wds｣: webpack output is served from /dist                                                                                                                                                               ‼ ｢wdm｣: Hash: e46094d617738f205f93
Version: webpack 4.30.0
Time: 17107ms
Built at: 05/08/2019 9:59:48 AM
               Asset      Size  Chunks             Chunk Names
    tui-calendar.css  35.4 KiB    main  [emitted]  main
tui-calendar.css.map  62.8 KiB    main  [emitted]  main
     tui-calendar.js  1.27 MiB    main  [emitted]  main
 tui-calendar.js.map  1.45 MiB    main  [emitted]  main
Entrypoint main = tui-calendar.css tui-calendar.js tui-calendar.css.map tui-calendar.js.map
[0] multi (webpack)-dev-server/client?http://0.0.0.0 (webpack)/hot/dev-server.js ./src/index.js 52 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0] (webpack)-dev-server/client?http://0.0.0.0 8.26 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.11 KiB {main} [built]
[./src/index.js] 1020 bytes {main} [built]
    + 125 hidden modules

WARNING in ./src/js/common/array.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\common\array.js
  234:1  warning  Function 'scheduleASC' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/monthView.js 9:12-38
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/common/autoScroll.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\common\autoScroll.js
  163:37  warning  Function has a complexity of 8  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/view/week/timeGrid.js 17:17-51
 @ ./src/js/factory/weekView.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/common/dirty.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\common\dirty.js
  161:11  warning  Method 'wrap' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/model/schedule.js 11:12-38
 @ ./src/js/factory/weekView.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/common/vpanel.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\common\vpanel.js
  105:30  warning  Function has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/common/vlayout.js 13:13-32
 @ ./src/js/factory/weekView.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/controller/base.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\controller\base.js
  146:33  warning  Function has a complexity of 18  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/controller.js 8:11-40
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/controller/viewMixin/week.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\controller\viewMixin\week.js
  215:16  warning  Function has a complexity of 8  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/controller.js 10:11-50
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/factory/calendar.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\factory\calendar.js
   655:34  warning  Function has a complexity of 11  complexity
  1022:27  warning  Function has a complexity of 11  complexity
  1520:33  warning  Function has a complexity of 8   complexity

✖ 3 problems (0 errors, 3 warnings)

 @ ./src/index.js 9:15-47

WARNING in ./src/js/factory/monthView.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\factory\monthView.js
  52:1  warning  Function 'createMonthView' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/calendar.js 17:23-45
 @ ./src/index.js

WARNING in ./src/js/handler/daygrid/creation.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\handler\daygrid\creation.js
  102:52  warning  Function has a complexity of 9  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/weekView.js 27:22-60
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/handler/month/core.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\handler\month\core.js
  54:5  warning  Function 'getDate' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/handler/month/resize.js 12:22-39
 @ ./src/js/factory/monthView.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/model/viewModel/scheduleViewModel.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\model\viewModel\scheduleViewModel.js
  175:44  warning  Function has a complexity of 9  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/controller/viewMixin/core.js 14:24-74
 @ ./src/js/factory/controller.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/view/month/more.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\view\month\more.js
  135:25  warning  Function has a complexity of 12  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/monthView.js 18:11-40
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/view/popup/scheduleCreationPopup.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\view\popup\scheduleCreationPopup.js
  241:56  warning  Function has a complexity of 12  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/factory/weekView.js 21:28-74
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/view/week/dayname.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\view\week\dayname.js
  112:38  warning  Function has a complexity of 8  complexity
  138:32  warning  Function has a complexity of 7  complexity

✖ 2 problems (0 errors, 2 warnings)

 @ ./src/js/factory/weekView.js 18:14-45
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/view/week/timeGrid.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\view\week\timeGrid.js
   35:1   warning  Function 'getHoursLabels' has a complexity of 7  complexity
   70:33  warning  Function has a complexity of 8                   complexity
  305:29  warning  Function has a complexity of 7                   complexity
  603:33  warning  Function has a complexity of 9                   complexity

✖ 4 problems (0 errors, 4 warnings)

 @ ./src/js/factory/weekView.js 20:15-47
 @ ./src/js/factory/calendar.js
 @ ./src/index.js

WARNING in ./src/js/view/weekday.js
Module Warning (from ./node_modules/eslint-loader/index.js):

C:\Program Files\Git\bin\tui.calendar\src\js\view\weekday.js
  176:38  warning  Function has a complexity of 8  complexity

✖ 1 problem (0 errors, 1 warning)

 @ ./src/js/view/week/dayGridSchedule.js 8:14-35
 @ ./src/js/view/week/dayGrid.js
 @ ./src/js/factory/weekView.js
 @ ./src/js/factory/calendar.js
 @ ./src/index.js
Child mini-css-extract-plugin ../../../../Program Files\Git\bin\tui.calendar\node_modules\preprocess-loader\index.js?{"CSS_PREFIX":"tui-full-calendar-","BUNDLE_TYPE":"Debug"}!../../../../Program Files\Git\bin\tui.calendar\node_modules\css-loader\index.js??ref--5-2!../../../../Program Files\Git\bin\tui.calendar\node_modules\stylus-loader\index.js??ref--5-3!../../../../Program Files\Git\bin\tui.calendar\src\css\main.styl:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/lib/css-base.js] 2.21 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/lib/url/escape.js] 448 bytes {mini-css-extract-plugin} [built]
    [./node_modules/preprocess-loader/index.js?{"CSS_PREFIX":"tui-full-calendar-","BUNDLE_TYPE":"Debug"}!./node_modules/css-loader/index.js?!./node_modules/stylus-loader/index.js?!./src/css/main.styl] ./node_modules/preprocess-loader?{"CSS_PREFIX":"tui-full-calendar-","BUNDLE_TYPE":"Debug"}!./node_modules/css-loader??ref--5-2!./node_modules/stylus-loader??ref--5-3!./src/css/main.styl 96.5 KiB {mini-css-extract-plugin} [built]
    [./src/css/image/handle-x.png] 189 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/handle-x@2x.png] 201 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/handle-y.png] 189 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/handle-y@2x.png] 197 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-arrow-left.png] 249 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-arrow-right.png] 257 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-arrow-solid-bottom.png] 297 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-arrow-solid-top.png] 309 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-checkbox-checked.png] 393 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-checkbox-normal.png] 213 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-close.png] 333 bytes {mini-css-extract-plugin} [built]
    [./src/css/image/ic-date.png] 277 bytes {mini-css-extract-plugin} [built]
        + 12 hidden modules
i ｢wdm｣: Compiled with warnings.

**Comment by jungeun-cho** [comment]
@coolvijaymca 

Open your browser
Enter url
http://localhost:8080/
Can not access?

I usually check it in the example code.
![스크린샷 2019-05-09 10 39 02](https://user-images.githubusercontent.com/43128697/57421423-b31fe580-7246-11e9-8f0d-4329565d56bc.png)
