### ISSUE TITLE
How to integrate html tag in schedule title.

### ISSUE THREAD

**Issue by tryrex67** [nhn/tui.calendar#324]
I want to have some word in bold, color, ... in the title of my schedule, but when i use an html tag on the calendar it display it correctly but when i open the detailpopup, html tag is writen in the title and nothing change in the title (ex: i want 9:00 am **Handball** but it display  9:00 am < span style="font-weight:bold" >Handball< /span >)

**Comment by dongsik-yoo** [comment]
@tryrex67 You have to make your own detail popup in that case. The default detail popup isn't customizable. 
And you can use [template function](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#templatecustomize-ui) to bold some text in calendar. They are `time` and `allday`.
