### ISSUE TITLE
how to modify popup detail ? 

### ISSUE THREAD

**Issue by tryrex67** [nhn/tui.calendar#325]
I see in previous post that to modify the detail popup we need to modify scheduleDetailPopup.hbs. But i don't find this file, and when i want to modify scheduleDetailPopup.hbs section in tui-calendar.js the code is not the same. So how can i modify scheduleDetailPopup.hbs and how to integer it ?

**Comment by MichalGajda** [comment]
You have to make fork of the repo. Then in src/js/view/popup and src/js/view/template you will find both scheduleDetailPopup.js and scheduleDetailPopup.hbs. Those are files resposible for template and login behind template.
Then you have to run 'bundle' script located in package.json, this will create new dist directory, which will contain your changes.
This is the way i did this, but to be honest i'm not sure if it's the best way to do this. I hope someone will correct me if i'm wrong.

**Comment by dongsik-yoo** [comment]
You can't modify default popups by any option. Instead, you can make own your popups. https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups
