### ISSUE TITLE
Disabling schedule creation in month/etc. view

### ISSUE THREAD

**Issue by MichalGajda** [nhn/tui.calendar#326]
## Current Behavior

Is there any possibility to disable schedule creation? I am not talking about         useCreationPopup: false, but to disable schedule creation in only some days. 

## Expected Behavior

It might be usefull to disable schedule creation in some cases.
Example of resolution:
 schedule.disableSchedule set to true could prevent user from creating schedule in that day and maybe create some visual effect like grey background.

**Comment by jungeun-cho** [comment]
@MichalGajda 
How about taking specific actions when creating a schedule?
For custom pop-up settings, see the links below.

https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

I hope it helps you. :)

**Comment by MichalGajda** [comment]
Yes, making custom popup may prevent schedule creating. However it doesnt solve issue with calendar fields(for example in monthly view) being for example grayed when they are disabled.
This behavior would make it obvious for users, that they cant book time on this day.
Is there any way to do this right now?
