### ISSUE TITLE
Weekly and Daily views not rendering schedule in few months

### ISSUE THREAD

**Issue by snyaggarwal** [nhn/tui.calendar#330]
## Version
1.12

## Development Environment
Chrome

## Current behaviour
Schedules are not showing in months June, Sep and Nov in day and week views.
All the other months and views are working fine.

Link to video - https://drive.google.com/file/d/1CIRe7VNRIS_NospqTIfSQAhPj3jGjo7e/view

**Comment by snyaggarwal** [comment]
Update - the issue is with 31st of the month.
so today is 31st, and I click on 1st june, the calendar lib is trying to set the date to 1st june,
lib starts with copying today which is 31/05/2019, the first thing is setFullYear 2019 - 31/05/2109 (good), second thing is setMonth 6 - 31/06/2019 (wrong). And it moves to next month with 31 days. 31/07/2019.
The fix it to set date and then month.
Will raise a pull request in some time.

**Comment by dongsik-yoo** [comment]
I got this.

**Comment by jungeun-cho** [comment]
@snyaggarwal 
We have discovered this problem and are going to fix it now.
As soon as the patch version will be released today.

**Comment by dongsik-yoo** [comment]
@snyaggarwal Thank you for your cooperation! I fix this and release [v1.12.1](https://github.com/nhn/tui.calendar/releases/tag/v1.12.1) version.

**Comment by snyaggarwal** [comment]
Cool
