### ISSUE TITLE
[tui calendar css] tui calendar 팝업 css 위치값 질문입니다 How can i adjust z-index value of popup ?

### ISSUE THREAD

**Issue by dayemond11** [nhn/tui.calendar#332]
![캡처](https://user-images.githubusercontent.com/51309681/58784786-31da2980-861f-11e9-800f-1ae6acb8a252.PNG)

캘린더 위치가 선택한 셀에따라 위로 생길 경우와 아래로 생길 경우가 있는데,
위로 생길 경우 메뉴에 가려지게 됩니다.
팝업이 잘리지 않게 아래로 팝업이 뜨게 하고 싶은데 어떻게 해야할까요?

The location of Calendar popup is sometimes under clicked point and above clicked point.
When the popup is located above the clicked point like this photo, it is hidden because of the upper menu bar. 
I want it to be located under the clicked point. How should I do?

**Comment by dongsik-yoo** [comment]
@dayemond11 I think it's a bug. We'll check it out.

**Comment by jungeun-cho** [comment]
@dayemond11 
The z-index of the popup starts at 1000.
Do you have a calendar inside an iframe?
