### ISSUE TITLE
separate template for detail popup

### ISSUE THREAD

**Issue by kzachos** [nhn/tui.calendar#338]
## Version
1.12.1

## Development Environment
Safari, MacOS

## Current Behavior
At the moment the detail popup for editing existing appointments is done with one template. 
https://user-images.githubusercontent.com/26706716/39230820-e73fa11c-48a2-11e8-9348-8e3d81979a78.png

## Expected Behavior
How can I choose a different detail popup template for past appointments, while keeping the existing one for future appointments when a user clicks on them?

**Comment by dongsik-yoo** [comment]
@kzachos Thank you for your suggestion. But we don't have any customizing popup design. If you want to do it, you can add your own popup now. See also #231.

**Comment by kzachos** [comment]
ok. Is it possible to change the useDetailPopup parameter dynamically depending on whether it is a past appointment or not?

**Comment by dongsik-yoo** [comment]
@kzachos It is not dynamic property. If you don't use useDetailPopup, you have to make yours.

**Comment by kzachos** [comment]
found a workaround, for anyone who is trying to do something similar
```           
'clickSchedule': function(e) {
            var schedule = e.schedule;
            var endDate = schedule.end.toDate();
            var now = Date.now();
            var isOld = now > endDate;
            if (isOld) {
                var popup = document.querySelector("#calendar > div > div.tui-full-calendar-floating-layer.tui-view-23 > div");
                popup.style.display = 'none';
                // if needed, call custom modal here
            }
        }
