### ISSUE TITLE
Customise UI by changing/override css 

### ISSUE THREAD

**Issue by kzachos** [nhn/tui.calendar#340]
## Version
1.12.1

## Development Environment
safari, MacOS

## Current Behavior
css is "fixed" based on tui-calendar.css

## Expected Behavior
Change some css elements to customise particular aspects of UI, e.g. change border of schedule by override current statement

```
.tui-full-calendar-time-schedule-content {
    border-width: 2px;
    border-style: solid;
}
```

currently is it
```
.tui-full-calendar-time-schedule-content {
    border-left-width: 3px;
    border-left-style: solid;
}
```

**Comment by jungeun-cho** [comment]
@kzachos 
Do you want something other than style override?

Style overrides are currently available.
![스크린샷 2019-06-24 09 41 57](https://user-images.githubusercontent.com/43128697/59984439-2ea5ec80-9665-11e9-8ac1-9878a8bbf8f0.png)

It is possible to override style attributes other than those applied directly to the element in an inline style.

**Comment by kzachos** [comment]
ok thanks, got it now, I meant Style overrides.
