### ISSUE TITLE
The schedule popup looks broken.

### ISSUE THREAD

**Issue by charmjeh** [nhn/tui.calendar#346]
![image](https://user-images.githubusercontent.com/43127789/60863601-3a480480-a25c-11e9-9cfb-1a38f8e95af0.png)

Hello, I am currently using tui-calendar by adding cdn to index.html.
The added code is shown below.

head part: 
```
    <link
      rel="stylesheet"
      type="text/css"
      href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css"
    />

```
body part: 
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
    <script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
    <script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.js"></script>
    <script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.js"></script>
    <script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```

Which part can I check?
Thank you for your time

## Version
most recent version 

## Development Environment
Chrome, vue.js

**Comment by jungeun-cho** [comment]
@charmjeh 
Can I see how you use Tui Calendar in your source code?


If you develop using vue, we support [vue wrapper](https://github.com/nhn/toast-ui.vue-calendar).

**Comment by charmjeh** [comment]
i created a calendar with the vue-calendar you mentioned and it works

thank you!

and i have another question.
1. how can i modify or delete item in create schedule modal?
2. can i limit the number of schedule per day?
(스케줄을 하루에 각 항목당 n개만 추가 가능하도록 하고 싶습니다.)

thank you for your time
