### ISSUE TITLE
[vue-calendar] how can i modify popup items?

### ISSUE THREAD

**Issue by charmjeh** [nhn/tui.calendar#347]
i wanted to delete some items in create schedule popup, 
so change both useCreationPopup and useDetailPopup to false.

but i don't know how to use tui.calendar popup template.(popup open & item modify)
how can i use creation popup/detail popup?

[here is my recent code. (link)](https://jsfiddle.net/eunhee_ju/6Lsvr1fc/18/)
check it out please.

thank you for your time

***

for creation popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleCreationPopup.hbs#L28-L32

for detail popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleDetailPopup.hbs#L10-L17

_Originally posted by @dongsik-yoo in https://github.com/nhn/tui.calendar/issues/217#issuecomment-429177930_

**Comment by charmjeh** [comment]
This is a question about the vue calendar, so end this issue

**Comment by jungeun-cho** [comment]
@charmjeh 
This issue is closed.
I'll solve your issue [here](https://github.com/nhn/toast-ui.vue-calendar/issues/27).
