### ISSUE TITLE
createPopup date picker is not displaying correctly.

### ISSUE THREAD

**Issue by Refined-Studios** [nhn/tui.calendar#348]
## Version
Latest version of: toast-ui.react-calendar

## Development Environment
Win10
NodeJS 10.16
Chrome Version 75.0.3770.100

## Current Behavior
When I try to create an event on the schedule and the create popup apears it looks fine. but when I try to use the date picker it does not look right:
![image](https://user-images.githubusercontent.com/44880575/60958633-f5c57300-a306-11e9-8955-9bec90d2d447.png)

when clicking the arrow it looks like this:
![image](https://user-images.githubusercontent.com/44880575/60958862-640a3580-a307-11e9-92ac-b14e8402548a.png)

It feels like its a CSS problem since the datepicker seems to show, but it shows in that minimal box. If I try to click precisely inside it a date gets picked, so the datepicker is in there but it is waaway too small. this happens in day, week and month view.

```js

const calendarOptions = ({
    calendars: 
        [{
            id: '0',
            name: 'Jaime',
            bgColor: '#9e5fff',
            borderColor: '#9e5fff'
        }],
    schedules: 
        [{
          id: '1',
          calendarId: '0',
          title: 'Test',
          category: 'time',
          dueDateClass: '',
          start: '2019-07-10T12:30:00+02:00',
          end: '2019-07-10T14:30:00+02:00'
        }],
    isReadOnly: false,
    defaultView: "month",
    disableDblClick: true,
    height: "650px",
    week: {
        startDayOfWeek: 1,
        showTimezoneCollapseButton: false,
        hourStart: 6,
        hourEnd: 20
      },
    month: {
        startDayOfWeek: 1
      },
    taskView: false,
    scheduleView: true,
    template: {
        allday(schedule) {
          return `${schedule.title}<i class="fa fa-refresh"></i>`;
        },
        alldayTitle() {
          return 'All Day';
        }
      },
    useDetailPopup: true,
    useCreationPopup: true,
    timezones: 
        [{
          timezoneOffset: 120,
          displayLabel: 'GMT+02:00',
          tooltip: 'Stockholm'
        }]
    
});

//..............CALENDAR RENDER CLASS................
//:::::::::::::::::::::::::::::::::::::::::::::::::::

class RenderCal extends React.Component {
    calendarRef = React.createRef();

    changeViewToDay = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('day', true);
    }

    changeViewToWeek = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('week', true);
    }

    changeViewToMonth = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('month', true);
    }

    handleClickNextButton = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.next();
    };
    handleClickPrevButton = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.prev();
    };

    render() {
        return (
            <>
            <div className="btn-group">
                <Button className="btn-sm" onClick={this.handleClickPrevButton} text="Prev" />
                <Button className="btn-sm" onClick={this.handleClickNextButton} text="Next" />
            </div>
            <div className="btn-group">
                <Button className="btn-sm" onClick={this.changeViewToDay} text="Day" />
                <Button className="btn-sm" onClick={this.changeViewToWeek} text="Week" />
                <Button className="btn-sm" onClick={this.changeViewToMonth} text="Month" />
            </div>
                <Calendar
                    ref={this.calendarRef}
                    {...calendarOptions}
                />
            </>
        );
    }
}



class Scheduling extends React.Component {
    state = {}

    render() {
        return (
            <Content title="Scheduling" subTitle="" browserTitle="IntelliBook - Manage Users">
                <Row>
                    <Col xs={4}>
                        <Box title="Add Event" type="primary" closable collapsable footer={<Button type="danger" text="Button" />}>
                            Hello World
            </Box>
                    </Col>
                    <Col xs={8}>
                        <Box title="Calendar">
                            <RenderCal />
                        </Box>
                    </Col>
                </Row>
            </Content>
        );
    }
}

export default Scheduling;
```

## Expected Behavior
Functional date picker.

**Comment by dongsik-yoo** [comment]
How can I reproduce this issue? ex> sample page

**Comment by Refined-Studios** [comment]
I'm not sure how to give you that info. I only installed it as per the instructions on the react wrapper page. If there was any dependencies that was not met it should have given me an error, right?

this is my page:
`import React from 'react';
import 'tui-calendar/dist/tui-calendar.css';
import Calendar from '@toast-ui/react-calendar';
import { Content, Row, Col, Box, Button } from 'adminlte-2-react';


//.............CALENDAR OPTIONS..............
//:::::::::::::::::::::::::::::::::::::::::::

// default keys and styles
var calTheme = {
    'common.border': '1px solid #e5e5e5',
    'common.backgroundColor': 'white',
    'common.holiday.color': '#ff4040',
    'common.saturday.color': '#333',
    'common.dayname.color': '#333',
    'common.today.color': '#333',
    
    // creation guide style
    'common.creationGuide.backgroundColor': 'rgba(81, 92, 230, 0.05)',
    'common.creationGuide.border': '1px solid #515ce6',
    
    // month header 'dayname'
    'month.dayname.height': '31px',
    'month.dayname.borderLeft': '1px solid #e5e5e5',
    'month.dayname.paddingLeft': '10px',
    'month.dayname.paddingRight': '10px',
    'month.dayname.backgroundColor': 'inherit',
    'month.dayname.fontSize': '12px',
    'month.dayname.fontWeight': 'normal',
    'month.dayname.textAlign': 'left',
    
    // month day grid cell 'day'
    'month.holidayExceptThisMonth.color': 'rgba(255, 64, 64, 0.4)',
    'month.dayExceptThisMonth.color': 'rgba(51, 51, 51, 0.4)',
    'month.weekend.backgroundColor': 'inherit',
    'month.day.fontSize': '14px',
    
    // month schedule style
    'month.schedule.borderRadius': '2px',
    'month.schedule.height': '24px',
    'month.schedule.marginTop': '2px',
    'month.schedule.marginLeft': '8px',
    'month.schedule.marginRight': '8px',
    
    // month more view
    'month.moreView.border': '1px solid #d5d5d5',
    'month.moreView.boxShadow': '0 2px 6px 0 rgba(0, 0, 0, 0.1)',
    'month.moreView.backgroundColor': 'white',
    'month.moreView.paddingBottom': '17px',
    'month.moreViewTitle.height': '44px',
    'month.moreViewTitle.marginBottom': '12px',
    'month.moreViewTitle.backgroundColor': 'inherit',
    'month.moreViewTitle.borderBottom': 'none',
    'month.moreViewTitle.padding': '12px 17px 0 17px',
    'month.moreViewList.padding': '0 17px',
    
    // week header 'dayname'
    'week.dayname.height': '42px',
    'week.dayname.borderTop': '1px solid #e5e5e5',
    'week.dayname.borderBottom': '1px solid #e5e5e5',
    'week.dayname.borderLeft': 'inherit',
    'week.dayname.paddingLeft': '0',
    'week.dayname.backgroundColor': 'inherit',
    'week.dayname.textAlign': 'left',
    'week.today.color': '#333',
    'week.pastDay.color': '#bbb',
    
    // week vertical panel 'vpanel'
    'week.vpanelSplitter.border': '1px solid #e5e5e5',
    'week.vpanelSplitter.height': '3px',
    
    // week daygrid 'daygrid'
    'week.daygrid.borderRight': '1px solid #e5e5e5',
    'week.daygrid.backgroundColor': 'inherit',
    
    'week.daygridLeft.width': '72px',
    'week.daygridLeft.backgroundColor': 'inherit',
    'week.daygridLeft.paddingRight': '8px',
    'week.daygridLeft.borderRight': '1px solid #e5e5e5',
    
    'week.today.backgroundColor': 'rgba(81, 92, 230, 0.05)',
    'week.weekend.backgroundColor': 'inherit',
    
    // week timegrid 'timegrid'
    'week.timegridLeft.width': '72px',
    'week.timegridLeft.backgroundColor': 'inherit',
    'week.timegridLeft.borderRight': '1px solid #e5e5e5',
    'week.timegridLeft.fontSize': '11px',
    'week.timegridLeftTimezoneLabel.height': '40px',
    'week.timegridLeftAdditionalTimezone.backgroundColor': 'white',
    
    'week.timegridOneHour.height': '52px',
    'week.timegridHalfHour.height': '26px',
    'week.timegridHalfHour.borderBottom': 'none',
    'week.timegridHorizontalLine.borderBottom': '1px solid #e5e5e5',
    
    'week.timegrid.paddingRight': '8px',
    'week.timegrid.borderRight': '1px solid #e5e5e5',
    'week.timegridSchedule.borderRadius': '2px',
    'week.timegridSchedule.paddingLeft': '2px',
    
    'week.currentTime.color': '#515ce6',
    'week.currentTime.fontSize': '11px',
    'week.currentTime.fontWeight': 'normal',
    
    'week.pastTime.color': '#bbb',
    'week.pastTime.fontWeight': 'normal',
    
    'week.futureTime.color': '#333',
    'week.futureTime.fontWeight': 'normal',
    
    'week.currentTimeLinePast.border': '1px dashed #515ce6',
    'week.currentTimeLineBullet.backgroundColor': '#515ce6',
    'week.currentTimeLineToday.border': '1px solid #515ce6',
    'week.currentTimeLineFuture.border': 'none',
    
    // week creation guide style
    'week.creationGuide.color': '#515ce6',
    'week.creationGuide.fontSize': '12px',
    'week.creationGuide.fontWeight': 'bold',
    
    // week daygrid schedule style
    'week.dayGridSchedule.borderRadius': '2px',
    'week.dayGridSchedule.height': '24px',
    'week.dayGridSchedule.marginTop': '2px',
    'week.dayGridSchedule.marginLeft': '8px',
    'week.dayGridSchedule.marginRight': '8px'
    };


const calendarOptions = ({
    calendars: 
        [{
            id: '0',
            name: 'Jaime',
            bgColor: '#9e5fff',
            borderColor: '#9e5fff'
        }],
    schedules: 
        [{
          id: '1',
          calendarId: '0',
          title: 'Test',
          category: 'time',
          dueDateClass: '',
          start: '2019-07-10T12:30:00+02:00',
          end: '2019-07-10T14:30:00+02:00'
        }],
    isReadOnly: false,
    defaultView: "month",
    disableDblClick: true,
    height: "650px",
    week: {
        startDayOfWeek: 1,
        showTimezoneCollapseButton: false,
        hourStart: 6,
        hourEnd: 20
      },
    month: {
        startDayOfWeek: 1
      },
    taskView: false,
    scheduleView: true,
    theme: calTheme,
    template: {
        allday(schedule) {
          return `${schedule.title}<i class="fa fa-refresh"></i>`;
        },
        alldayTitle() {
          return 'All Day';
        }
      },
    useDetailPopup: true,
    useCreationPopup: true,
    timezones: 
        [{
          timezoneOffset: 120,
          displayLabel: 'GMT+02:00',
          tooltip: 'Stockholm'
        }]
    
});

//..............CALENDAR RENDER CLASS................
//:::::::::::::::::::::::::::::::::::::::::::::::::::

class RenderCal extends React.Component {
    calendarRef = React.createRef();

    changeViewToDay = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('day', true);
    }

    changeViewToWeek = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('week', true);
    }

    changeViewToMonth = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.changeView('month', true);
    }

    handleClickNextButton = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.next();
    };
    handleClickPrevButton = () => {
        const calendarInstance = this.calendarRef.current.getInstance();
        calendarInstance.prev();
    };

    render() {
        return (
            <>
            <div className="btn-group">
                <Button className="btn-sm" onClick={this.handleClickPrevButton} text="Prev" />
                <Button className="btn-sm" onClick={this.handleClickNextButton} text="Next" />
            </div>
            <div className="btn-group">
                <Button className="btn-sm" onClick={this.changeViewToDay} text="Day" />
                <Button className="btn-sm" onClick={this.changeViewToWeek} text="Week" />
                <Button className="btn-sm" onClick={this.changeViewToMonth} text="Month" />
            </div>
                <Calendar
                    ref={this.calendarRef}
                    {...calendarOptions}
                />
            </>
        );
    }
}



class Scheduling extends React.Component {
    state = {}

    render() {
        return (
            <Content title="Scheduling" subTitle="" browserTitle="IntelliBook - Manage Users">
                <Row>
                    <Col xs={4}>
                        <Box title="Add Event" type="primary" closable collapsable footer={<Button type="danger" text="Button" />}>
                            Hello World
            </Box>
                    </Col>
                    <Col xs={8}>
                        <Box title="Calendar">
                            <RenderCal />
                        </Box>
                    </Col>
                </Row>
            </Content>
        );
    }
}

export default Scheduling;`

I can try to do a new react app and install it there to see if the problem persists on a brand new app?

**Comment by Refined-Studios** [comment]
on a fresh react app it looks like this:
![image](https://user-images.githubusercontent.com/44880575/60967817-d8e76a80-a31b-11e9-80c1-d1e9ebf48beb.png)

on my main app that looks like its a miniature version of that time dropdown. but what I want is the full datepicker with time also. do I need to set a special prop to enable that? it feels like I have missed something...

**Comment by Refined-Studios** [comment]
I tried removing the CSS import and this is what I got. now I see the datepicker and the timepicker although unstyled ofcourse. so it looks like it is a CSS problem:

![image](https://user-images.githubusercontent.com/44880575/60968357-2912fc80-a31d-11e9-9253-406a18d8e051.png)

**Comment by dongsik-yoo** [comment]
OK, I think I get the problem. Can you please import two css?
```js
import 'tui-date-picker/dist/tui-date-picker.css';
import 'tui-time-picker/dist/tui-time-picker.css';
```

**Comment by Refined-Studios** [comment]
This solved it! THANK you! been pulling my hair manually trying to find differences between the codebase in the wrapper and the main calendar! Thank you so much for the fast responses!

**Comment by dongsik-yoo** [comment]
@Refined-Studios I updated a guide about importing two css. Thank you!
https://github.com/nhn/tui.calendar#using-module-format-in-node-environment
