### ISSUE TITLE
Disable day hours from to

### ISSUE THREAD

**Issue by W3b3r** [nhn/tui.calendar#352]
Hi guys,

the calendar is awesome! :D 
I asking there because in documentation i don't find nothing on what i need.
My need is to disable hour from 0 am to 9 am and from 6 pm to 0pm (like working hours).
There is a method for do this?

Thanks in advance.
Best.

## Version
LASTES

## Development Environment
browser application chrome/mozilla..other browser

**Comment by dongsik-yoo** [comment]
`hourStart` and `hourEnd` options do it and make those time area invisible.
https://nhn.github.io/tui.calendar/latest/WeekOptions

**Comment by W3b3r** [comment]
Hi,

thanks for answare to my question!

i write to my calendar option this 

`calendar.setOptions({hourStart: 9, hourEnd: 18});`

But seem don't work i'm currently using 24 hours format and weekly display

**Comment by jungeun-cho** [comment]
@W3b3r 
This is the `week options`.

```js
const calendar = new Calendar(document.getElementById('calendar'), {
  ...
  week: {
    hourStart: 9,
    hourEnd: 18
  }
});
// or
calendar.setOptions({
  week: {
    hourStart: 9,
    hourEnd: 18
  }
})
```

**Comment by W3b3r** [comment]
That works!!!! :D :D :D 
Thanks too much for your help! :D :D
Best support ever!! :D :D :D

**Comment by nuprakash** [comment]
I am done like this but I need to show before 8 also.
I gave like this 
hourStart: 7,
hourEnd: 24,
from 8 to 24 displays.
The calendar should start at 8 am by scrolling I want to see 7,6am time
