### ISSUE TITLE
isReadOnly option not work with weekly views

### ISSUE THREAD

**Issue by lessfish** [nhn/tui.calendar#359]
the newest version.

sometimes I need to use `isReadOnly` option, when set isReadOnly, I can not see the `edit` and `delete` button in monthly views, but when I change to weekly views, I can still drag the schedule to edit, which has been set to isReadOnly

Is it designed to be so? Or do I miss something?

In my option, when the schedule is set isReadOnly, we cannot drag to edit it in weekly views

**Comment by jungeun-cho** [comment]
@lessfish 
It's a bug.
When `isReadOnly = true`, it is impossible to move the schedule, and it is impossible to adjust the size. I'll fix it quickly.

**Comment by jungeun-cho** [comment]
@lessfish 
If you want to handle your code right now, see the `e.schedule.isReadOnly` value in the` beforeUpdate Schedule` event.

```js
cal.on({
       ...
        'beforeUpdateSchedule': function(e) {
            console.log('beforeUpdateSchedule', e);
            // use e.schedule.isReadOnly
        },
```

**Comment by lessfish** [comment]
@jungeun-cho wait for your update, and thanks for your great work for tui.calendar!
