### ISSUE TITLE
Hide edit button from details popup

### ISSUE THREAD

**Issue by afrazahmmad** [nhn/tui.calendar#364]
Hello dear!
I want to hide edit button from details popup. 
Is there any way to do that ?
I used **popupEdit** callback function to hide it but it didn't work.

**Comment by jungeun-cho** [comment]
@afrazahmmad 
Do not you want to edit your schedule?
If so, Set isReadOnly prop to true when creating the schedule.

https://nhn.github.io/tui.calendar/latest/Schedule

Please fill out the [issue template](https://github.com/nhn/tui.calendar/blob/master/docs/ISSUE_TEMPLATE.md) form.
