### ISSUE TITLE
Can you define the Y-axis header on the left?

### ISSUE THREAD

**Issue by wjm0913** [nhn/tui.calendar#365]
## Current Behavior

```js
// Write example code
```

**Comment by jungeun-cho** [comment]
@wjm0913 
Write exactly what you are saying.
For example, if you are referring to a time zone title in a weekly view ...

Please fill out the issue template form.

**Comment by wjm0913** [comment]
The weekly view references time zone titles similarly
You can define it yourself
One person has a different store, which is shown on the Y-axis. Each store has a different time of day.
English is not good  Please understand
Finally, thank you very much for answering my questions! thank you

**Comment by jungeun-cho** [comment]
@wjm0913 
Use `timezoneDisplayLabel` as template option
https://nhn.github.io/tui.calendar/latest/Template
https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid

```js
 var cal = new tui.Calendar('#calendar', {
    defaultView: 'week',
    template: {
      ...
      timezoneDisplayLabel: function(timezoneOffset, displayLabel) {
        var gmt, hour, minutes;

        if (!displayLabel) {
          gmt = timezoneOffset < 0 ? '-' : '+';
          hour = Math.abs(parseInt(timezoneOffset / 60, 10));
          minutes = Math.abs(timezoneOffset % 60);
          displayLabel = gmt + getPadStart(hour) + ':' + getPadStart(minutes);
        }

        return displayLabel;
      },
    },
    week: {
      showTimezoneCollapseButton: true,
      timezonesCollapsed: false,
    },
    timezones: [
      {
        timezoneOffset: 540,
        tooltip: 'Seoul'
      },
      {
        timezoneOffset: -420,
        tooltip: 'Los Angeles'
      }
    ]
  });
```

**Comment by jungeun-cho** [comment]
@wjm0913 
You can also upload a capture image.
e.g.)
![2019-08-02 15_42_36 196](https://user-images.githubusercontent.com/43128697/62349993-4dd54b00-b53c-11e9-80f9-84f2ec2d434b.png)

**Comment by wjm0913** [comment]
Thank you very much

**Comment by wjm0913** [comment]
![1564728984(1)](https://user-images.githubusercontent.com/45306520/62350585-ba991700-b535-11e9-9f90-c10c96bfe370.jpg)

**Comment by jungeun-cho** [comment]
@wjm0913 
We do not offer this feature.

**Comment by wjm0913** [comment]
Thank you very much。You are very beautiful。^_^
