### ISSUE TITLE
Detail popup close method

### ISSUE THREAD

**Issue by vytya** [nhn/tui.calendar#368]
Can't find any solution or example with closing of detail popup. 
For now if popup opened user could close it by clicking anywhere outside. But for example in my app calendar is take all possible space of viewport, so if click outside, it can be some empty slot (new event popup opening) or some existing event (detail popup opening and I get a problem with closing opened detail popup again).

**Comment by dongsik-yoo** [comment]
OK, any suggestion? or expected behavior?

**Comment by vytya** [comment]
Suggestion - create method for closing detail popup (if it didn't created already).
TUI Calendar already have similar in creating popup 
![изображение](https://user-images.githubusercontent.com/1582424/62453352-d6d9c580-b77a-11e9-82d5-7fc2432769fa.png)

**Comment by vytya** [comment]
If someone will need my solution.
I created my own function with closest('.tui-full-calendar-floating-layer') and add style.display = 'none' on it.

**Comment by pvllmr** [comment]
@vytya Where and on what element do you call your function? Thanks for helping.

**Comment by vytya** [comment]
@pvllmr my whole close function

`const openedPopupMainParent = [].slice.call(document.querySelectorAll('.tui-full-calendar-floating-layer'))

      if (openedPopupMainParent) {
        openedPopupMainParent.forEach(function(item) {
          if (item.style.display === 'block') {
            item.style.display = 'none'
          }
        })
      }`

but it's in vue, if you use just javascript, then create eventlistener and check event.target for closest floating layer and apply display: none on it.
