### ISSUE TITLE
How to create recurring event

### ISSUE THREAD

**Issue by gomzygba** [nhn/tui.calendar#371]
## Version

Not using yet
## Current Behavior

Hi, from the documentation, its a bit unclear if recurrence is supported. Does Toast Calendar provide ability to create/modify recurring events? If recurrence is supported, how will an end user be able to create recurring tasks?
```js
// Write example code
```

## Expected Behavior

I should be able to create/modify an event and provide end user with ability to set/unset recurrence.

**Comment by jungeun-cho** [comment]
@gomzygba 
TUI Calendar does not generate schedule data for repetition.

However, if you set any value in the recurrence rule when you `createSchedules ` (for example, an appointment that allows you to create a recurrence schedule in the Back End API), the schedule data will have this `recurrenceRule` prop.

With this `recurrenceRule`, you can handle it where we store the actual schedule data(backend).

**Comment by egill31** [comment]
Hello there,

I realise this is closed, but can anyone indicate where to find some info on `recurrenceRule`? The only definition I have managed to find in the documentation is: The recurrence rule.

Thanks a lot for the great project!

**Comment by dongsik-yoo** [comment]
@egill31 
[Dooray!](dooray.com) which uses TOAST UI Calendar uses [RFC5545 recurrence rule](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html).

**Comment by p4rz1val** [comment]
@dongsik-yoo Any plans on implementing recurring events in the future?

**Comment by JyotiSingh4** [comment]
> Hello there,
> 
> I realise this is closed, but can anyone indicate where to find some info on `recurrenceRule`? The only definition I have managed to find in the documentation is: The recurrence rule.
> 
> Thanks a lot for the great project!

Hi @egill31 

Were you able to integrate recurrence rule with toast UI calendar?
