### ISSUE TITLE
Not able to create schedule.

### ISSUE THREAD

**Issue by more-yogesh** [nhn/tui.calendar#376]
> tui-date-picker.min.js:8 Uncaught TypeError: Cannot read property 'on' of undefined
>     at Object.on (tui-date-picker.min.js:8)
>     at init._setEvents (tui-date-picker.min.js:7)
>     at new init (tui-date-picker.min.js:7)
>     at init._initHeader (tui-date-picker.min.js:7)
>     at new init (tui-date-picker.min.js:7)
>     at new init (tui-date-picker.min.js:7)
>     at init._initializePickers (tui-date-picker.min.js:8)
>     at new init (tui-date-picker.min.js:8)
>     at Function.a.createRangePicker (tui-date-picker.min.js:7)
>     at ScheduleCreationPopup../src/js/view/popup/scheduleCreationPopup.js.ScheduleCreationPopup._createDatepicker (scheduleCreationPopup.js:563)

![image](https://user-images.githubusercontent.com/24932160/62875112-0ae75480-bd40-11e9-8f68-5a630cf166bf.png)
[https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic](
https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic)

**Comment by dongsik-yoo** [comment]
Dependency packages have been changed. In progress.

**Comment by more-yogesh** [comment]
Will you please let me know when it'll start working or please let me know a similar working example with different version?

**Comment by dongsik-yoo** [comment]
@more-yogesh If you want it now, use "1.11.0" version until we solve this.

**Comment by more-yogesh** [comment]
> @more-yogesh If you want it now, use "1.11.0" version until we solve this.

Not solved same issue continues with 1.11.0

**Comment by dongsik-yoo** [comment]
@more-yogesh Oh, do you use directly this repo with npm? OK, then, it'll take some time. Please take a cup of coffee. @jungeun-cho will solve it shortly.

**Comment by jungeun-cho** [comment]
@more-yogesh 
https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic
Try again. It should work find now. 😊 
![스크린샷 2019-08-13 15 51 01](https://user-images.githubusercontent.com/43128697/62920958-3589e980-bde2-11e9-97e8-c39950516fc8.png)

**Comment by more-yogesh** [comment]
Its Done Thanks :)

**Comment by coolvijaymca** [comment]
@jungeun-cho Can you confirm which file you changed. I have download earlier repo and customize it for my purpose. So if you can let me know the changes you have made in your repository them I will add the same to my repo.

Thank You

**Comment by jungeun-cho** [comment]
@coolvijaymca 
Added `<script src =" https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js "></ script>` to the example **using the CDN**.

We will deploy a lighter version of the TOAST UI Calendar 2.0, removing the dependency between `tui-code-snippet` and `tui-dom`.
