### ISSUE TITLE
Customizing schedular object 

### ISSUE THREAD

**Issue by pranayteja2773** [nhn/tui.calendar#379]
Hello 

I want to add more data in schedule object and use it in 'afterRenderSchedule' event for customizing the front end view. where print e.schedule in console, it is not showing visitor data.

for example,
'afterRenderSchedule': function(e) {
            var schedule = e.schedule;
			console.log(schedule);
        },
 var schedules = [{
        id: '1',
        calendarId: '1',
        officeId:'2',
        userId:29,
        title: 'my schedule',
        category: 'time',
        location:'india',
        dueDateClass: '',
        start: '2019-08-16T17:30:00',
        end: '2019-08-16T18:30:00',
        attendees: ['mukul','chandresh'],
        isReadOnly: false,
		vistior:[{
			visitorId: '1',
			visitorName: 'pranay',
			orgId: '1',
			orgName: 'visitors'
		},
		{
			visitorId: '2',
			visitorName: 'chandresh',
			orgId: '2',
			orgName: 'visitors2'
		}
		],
    }];
![Uploading Tui_calender.png…]()

**Comment by jungeun-cho** [comment]
@pranayteja2773
https://nhn.github.io/tui.calendar/latest/Calendar#event-afterRenderSchedule

The `afterRenderSchedule` event fires after each schedule has been rendered on the calendar.
You can get the DOM element of the schedule data using `calendar.getElement (schedule.id, schedule.calendarId)`.

**Comment by dongsik-yoo** [comment]
@pranayteja2773 If this is solved, please close this.

**Comment by pranayteja2773** [comment]
Thank for your reply.

What I want is to set the custom option in schedule object. I go through the document and I found the solution. I am setting custom options in raw  object.

schedules.push({
                id: Schedule1[i].scheduleid,
                calendarId: Schedule1[i].conferenceid,
                title: Schedule1[i].title,
                officeId: Schedule1[i].officeid,
                start: moment(Schedule1[i].visitstart).format('YYYY-MM-DDTHH:mm:ss'),
                end: moment(Schedule1[i].visitend).format('YYYY-MM-DDTHH:mm:ss'),
                category: 'time',
                color: Schedule1[i].ColorName,
                bgColor: Schedule1[i].ColorName,
                dragBgColor: Schedule1[i].ColorName,
                borderColor: Schedule1[i].ColorName,
                raw: [{
                        userId: Schedule1[i].hostedby,
                        visitor: visitor,
                        attendees: Schedule1[i].attendeesNo,
                        notes: arrNoteData,
                        host_name: Schedule1[i].host_name,
                        office_name: Schedule1[i].OfficeName,
                        conference_name: Schedule1[i].ConferenceName,
                        reminder_type: Schedule1[i].remindertype,
                        reminder_duration: Schedule1[i].reminderduration,
                        email_invite: Schedule1[i].isemail,
                    }],
            });
