### ISSUE TITLE
Popup: detail body as HTML

### ISSUE THREAD

**Issue by pecuchet** [nhn/tui.calendar#380]
## Version
tui-calendar@1.12.4

## Development Environment
FF Developer Edition 69.0b11

## Current Behavior
Currently the ``Schedule.body`` property is not outputted as HTML in the popup, but as plain text. So ``<p>This is my body</p>`` is rendered as such with converted HTML entities .

## Expected Behavior
It would be nice if ``innerHTML`` was used to insert the content of ``Schedule.body`` and of the custom template function ``popupDetailBody``.

**Comment by jungeun-cho** [comment]
@pecuchet 
The template code should be able to input html code.
I will apply to the next patch version. :)
