### ISSUE TITLE
Calendar date is off by one day?

### ISSUE THREAD

**Issue by geoffyuen** [nhn/tui.calendar#382]
## Version
Latest:
https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js
https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js

## Development Environment
Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Mac OS 10.14.6

## Current Behavior
The date of the displayed month is off by 1 day (eg, August 22 is not Friday)
https://codepen.io/geoffyuen/pen/WNeRRyE

```js
https://codepen.io/geoffyuen/pen/WNeRRyE
Copied and pasted from the code from https://github.com/nhn/tui.calendar
```

## Expected Behavior
Should render month dates correctly

**Comment by jungeun-cho** [comment]
@geoffyuen 
I want to know your timezone.

**Comment by geoffyuen** [comment]
Central (GMT-5)

**Comment by jungeun-cho** [comment]
@geoffyuen 
I deleted your custom template(`monthGridHeader`) and it works fine.

![스크린샷 2019-08-22 21 20 06](https://user-images.githubusercontent.com/43128697/63562334-35cf7500-c598-11e9-8e0a-fea5705ee2e1.png)

**Comment by geoffyuen** [comment]
Strange. The custom template was copied directly from the example on https://github.com/nhn/tui.calendar

**Comment by jungeun-cho** [comment]
Thanks to you :)

```
model.date // 2019-08-22
new Date ("2019-08-22") // Wednesday August 21 2019 19:00:00 GMT-0500
```
I will fix the docs.
If you want to use the `monthGridHeader` template, you'll have to handle `model.date` directly.

e.g. using `split`...

**Comment by geoffyuen** [comment]
Thank you! So it had nothing to do with the timezone only the custom template?
