### ISSUE TITLE
export interfaces in typescript declarations

### ISSUE THREAD

**Issue by vincaslt** [nhn/tui.calendar#383]
## Version
v1.12.4

## Development Environment
Windows 11, Chrome

## Current Behavior

```
declare module 'tui-calendar' {
    export default tuiCalendar.Calendar;
}
```

Is increadibly restrictive. 

## Expected Behavior
It would be good to export interfaces too, so that we could write types that use them, like for instance for https://github.com/nhn/toast-ui.react-calendar

**Comment by jungeun-cho** [comment]
@vincaslt 
[v1.12.5] (https://github.com/nhn/tui.calendar/releases/tag/v1.12.5) released.

React Wrapper is [v1.0.3] (https://github.com/nhn/toast-ui.react-calendar/releases/tag/v1.0.3).

Happy coding. 😆
