### ISSUE TITLE
On selecting multiple days, create new task popup appears which is not required.

### ISSUE THREAD

**Issue by afrazahmmad** [nhn/tui.calendar#391]
Thanks for great plugin!
When we select multiple days or drag cursor after selection then create schedule popup appears which is not required. How can I disable it ?
Video can be seen in below link
https://ahsanali-renesistech.tinytake.com/tt/MzczODA3OV8xMTM3ODYzOQ

**Comment by dongsik-yoo** [comment]
@afrazahmmad [This](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups) will be helpful.

**Comment by afrazahmmad** [comment]
Thanks it worked :)
