### ISSUE TITLE
Clicks becomes no effect after upgrade to v1.12.5

### ISSUE THREAD

**Issue by masaoliou** [nhn/tui.calendar#393]
## Version
v1.12.5

## Development Environment
Opera

## Current Behavior
Clicks on schedules, event `clickSchedule` does not fire. Single clicks on date cells does not fire event `beforeCreateSchedule`, either.
However, double clicks on date cells, and and dragging-and-dropping across date cells, do fire event `beforeCreateSchedule`.

```js
let c=new Calendar(
	document.getElementById('cal')
	,{
		disableDblClick:false
		,disableClick:false
	}
);
c.on(
    {
	    'beforeCreateSchedule':e=>{
	    	    console.log('beforeCreateSchedule');
	    	    //not get fired by single clicks. get fired by double clicks.
	    }
	    ,'clickSchedule':e=>{
		console.log('clickSchedule');
		//not get fired by clicks.
	    }
    }
);
```

## Expected Behavior
Both single and double clicks on schedules used to fire event `beforeCreateSchedule`. Single clicks on schedules used to fire `clickSchedule`. Hopefully these behaviors can be reverted to previous version.

**Comment by jungeun-cho** [comment]
@masaoliou 
Can you give me a representation?
(For example, [jsfiddle](https://jsfiddle.net), [codepen](https://codepen.io/pen/))

You can check the [Options](https://nhn.github.io/tui.calendar/latest/Options).

**Comment by masaoliou** [comment]
@jungeun-cho 
The [Jsfiddle](https://jsfiddle.net/cnliou/0d84y7wk) comprises only two files: `index.html` and `bundle.js`. `Bundle.js` is created with `rollup` from [app-main.js.gz](https://github.com/nhn/tui.calendar/files/3582728/app-main.js.gz) .
[tui-calendar-style.js.gz](https://github.com/nhn/tui.calendar/files/3582760/tui-calendar-style.js.gz) is for statement `import {tuiCalendarStyle} from './tui-calendar-style.js';` in file `app-main.js`.

**Comment by masaoliou** [comment]
Please pardon me! This issue along with others are not caused by version upgrade.
They arise from the incompatibility with `Polymer Lit-Element`.

The following usage is problematic:

````javascript
import {LitElement,html,css} from 'lit-element';
import Calendar from 'tui-calendar/dist/tui-calendar.js';
import {tuiCalendarStyle} from './tui-calendar-style.js';

class AppMain extends LitElement{
	static get styles() {
		return [
			tuiCalendarStyle
			,css`
				:host {
					display:block;
				}
			`
		];
	}
	render(){
		return html`
			<div id="calendar"></div>
		`;
	}
	firstUpdated(){
		this._calendar=new Calendar(
			this.shadowRoot.getElementById('calendar')
			,{
				defaultView:'month'
			}
		);
		this._calendar.on(
			{
			    'beforeCreateSchedule':e=>{
					//This fires after dragging-and-dropping cells and double clicks on cells.
					//Single clicks do not fire.
					console.log(e);
			    }
				,'clickSchedule':e=>{
					//Does not fire.
					console.log(e);
			    }
			}
		);
		this._calendar.createSchedules(
			[
			    {
			        id: '1',
			        calendarId:'1',
			        title: 's1',
			        category: 'time',
			        dueDateClass: '',
			        start: '2019-09-18T02:30:00+09:00',
			        end: '2019-09-19T02:30:00+09:00'
			    }
			]
		);
	}
}

window.customElements.define('app-main',AppMain);
````
Besides, if the calendar element is created within `mdc-dialog` which utilizes `slot`, the calendar displays only header. One must switch between views, say from `week` to `month`, in order to bring out the calendar's lower part:

````javascript
	render(){
		return html`
		<mdc-dialog>
			<div slot="content">
				<div id="calendar"></div>
			</div>
		</mdc-dialog>
		`;
	}
````


The following usage yields all the expected behaviors but the calendar element is created at wrong place (as a child element of `body`):

````javascript
import {LitElement,html,css} from 'lit-element';
import Calendar from 'tui-calendar/dist/tui-calendar.js';
import 'tui-calendar/dist/tui-calendar.css';

class AppMain extends LitElement{
	static get styles() {
		return [
			css`
				:host {
					display:block;
				}
			`
		];
	}
	render(){
		return html`
			<div id="calendar"></div>
		`;
	}
	firstUpdated(){
		this._calendar=new Calendar(
			'#non-exist'
			,{
				defaultView:'month'
			}
		);
		this._calendar.on(
			{
			    'beforeCreateSchedule':e=>{
					console.log(e);
			    }
				,'clickSchedule':e=>{
					console.log(e);
			    }
				,'afterRenderSchedule':e=>{
					console.log('afterRenderSchedule');
				}
			}
		);
		this._calendar.createSchedules(
			[
			    {
			        id: '1',
			        calendarId:'1',
			        title: 's1',
			        category: 'time',
			        dueDateClass: '',
			        start: '2019-09-18T02:30:00+09:00',
			        end: '2019-09-19T02:30:00+09:00'
			    }
			]
		);
	}
}

window.customElements.define('app-main',AppMain);
````

**Comment by tvvignesh** [comment]
@jungeun-cho @masaoliou I have the exact same problem. Using tui calendar within Lit-Element. beforeUpdateSchedule, beforeCreateSchedule fires but clickSchedule schedule doesn't when used within Shadow Dom of Lit-Element.

As of now, I am hacking around this issue by using this:
```
let elements = this.shadowRoot.querySelectorAll('.tui-full-calendar-weekday-schedule');

        for (let i = 0; i < elements.length; i++) {
            elements[i].addEventListener('click', elem.scheduleClicked, false);
        }
```

Selecting by class and binding click events myself and then getting the data from it. But. I don't think this is right.

Overall, the issue is that tui calendar does not seem to be completely supported within a shadow dom

**Comment by dongsik-yoo** [comment]
I think because of Lit-Element lifecycle. The container element must be a real element and attached and not be changed.
