### ISSUE TITLE
is there any way to export and import for sync purpose?

### ISSUE THREAD

**Issue by yrong** [nhn/tui.calendar#394]
## Current Behavior

```js
// Write example code
```

**Comment by jungeun-cho** [comment]
@yrong 
Could you write a detailed description?
For example, you can download a screen calendar as an image as a screenshot, or export the calendar data to csv...

**Comment by yrong** [comment]
yes, export and import. e.g: export in android and import in iPhone .  Csv is a option, maybe [iCal(RFC 5545)](https://en.wikipedia.org/wiki/ICalendar) is better

**Comment by jungeun-cho** [comment]
@yrong 
There is no support plan.
You have to implement it yourself.
