### ISSUE TITLE
Not able to create schedule

### ISSUE THREAD

**Issue by W3b3r** [nhn/tui.calendar#395]
Hi guys,

like a title when i try to create a new schedule i get this error.
![Screenshot (3)](https://user-images.githubusercontent.com/18245190/64790788-f385cc00-d576-11e9-9b05-b2c0e797f0a7.png)
Few months ago it worked but now goes in error.

The file vendor.bundle.base.js is a js file with all base script like data table and others

Here is what script i load
`<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chance/1.0.13/chance.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>`

Thanks in advace
Best.

**Comment by jungeun-cho** [comment]
@W3b3r 
Check out.
https://github.com/nhn/tui.calendar#via-contents-delivery-network-cdn

```html
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script src="https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```

**Comment by W3b3r** [comment]
Hi jungeun-cho,

thanks for answer the issue is solved.

I take this opportunity to ask if there is a view for years?

Thanks in advace.
Best.

**Comment by jungeun-cho** [comment]
@W3b3r 
The yearly view is on plan. :)
Happy Coding!

**Comment by W3b3r** [comment]
Thank you very much
