### ISSUE TITLE
Popup should pop only in the calendar space

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#402]
## Version
"@toast-ui/vue-calendar": "^1.1.1",
But this probably comes from master "tui.calendar" version, not vue specific

## Development Environment

Latest Chrome, Linux

## Current Behavior

```js
import { Calendar } from '@toast-ui/vue-calendar';
Vue.component('calendar', Calendar)
import 'tui-calendar/dist/tui-calendar.css';
import 'tui-date-picker/dist/tui-date-picker.css';
import 'tui-time-picker/dist/tui-time-picker.css';

<calendar style="height: 800px;" />
```

Click on first/last day to get the built-in popup.

Issue: popup isn't fully visible, as it doesn't fit outside the calendar view

## Expected Behavior
Popup should always be positioned inside the <calendar> widget. An easy solution would be to make it centered for now, or always near the current cell, but oriented towards center of the wideget.

![Screenshot from 2019-09-17 13-00-21](https://user-images.githubusercontent.com/1283842/65032499-f3594800-d94b-11e9-9bfe-9993e0a72bb8.png)

**Comment by jungeun-cho** [comment]
@mariusa 
It would be better for the popup to be displayed within the calendar container. :)
I will schedule the work.

**Comment by mariusa** [comment]
Hello @jungeun-cho :)
Actually, I realized most people use custom popups/actions, so this work would not be relevant. We will also build custom popups. 

I believe the 2.0 version is much more important to focus on.
Thank you!
