### ISSUE TITLE
On weekly planning, artifact on next day when creating an event from 23:30 to 00:00 (instead of 23:59)

### ISSUE THREAD

**Issue by ebaynaud** [nhn/tui.calendar#409]
First, thank you very much for this amazing project. Now my first bug report:

## Version
1.12.5

## Development Environment
Chrome, macOs, reactjs wrapper

## Current Behavior
Currently, on weekly view, if I add an event from 23:30 to 00:00 on Monday, there is an event appearing from 00:00 to 00:30 on Tuesday.

## Expected Behavior
It is not consistent with all other events created. When creating and event from 23:00 to 23:30, it works well. So when creating an event from 23:30 to 00:00, we should not have something appearing the day after.

## Workaround
I can edit all events finishing at midnight to make them finish at 23:59 but that's a workaround that should not be required...

**Comment by jungeun-cho** [comment]
@ebaynaud 
The bug is right.
We will try to fix it and go out to the next patch version.
