### ISSUE TITLE
can i try make a auto connection with Database using calendar?

### ISSUE THREAD

**Issue by Djunnni** [nhn/tui.calendar#414]
hi, i want to make a calendar with database(front-level connection) 
how about??

**Comment by jungeun-cho** [comment]
Of course.:)
You can implement

**Comment by Djunnni** [comment]
기존에 원했던 것은 Database를 바로 연결시켜줄 수는 없을까? 생각했습니다. 
하지만 이럴 경우 tui-calendar의 로드맵에서 벗어나지 않을까 고민하였습니다.

"getSchedulesFromUrl" 함수를 만들어서 url로 부터 json을 받아와 캘린더에 띄워주는 함수를 만들어보려고 하는데 
의견이 궁금합니다.

"getSchedulesFromUrl"은 "createSchedules" 를 재사용할 생각입니다.
이 함수가 있다면 CDN으로 사용하시는 분들께서도 쉽게 사용할 수 있을 것이라고 생각합니다. 

해당함수를 만들어 pull request를 하려고 하는데 의견을 듣고 싶습니다.
