### ISSUE TITLE
Timezone issue on onclickSchedule, beforeCreateSchedule, afterRenderSchedule events.

### ISSUE THREAD

**Issue by pranayteja2773** [nhn/tui.calendar#420]
## Current Behavior

This Calendar libarary is amazing and easy to understand. You provided well documentaion.
My Calendar App project deployed in server which Located in US. So I set timezone offset -420 for US/pacific timezone at Calendar initialization. It is showing correct time in Calendar grid. I accessing my project in India location. When i try to create meeting and view existing meeting, start time and end time of schedule object in beforecreateSchedule event, afterRenderSchedule event, clickSchedule event are giving Indian time format, even though i set timezone as US/Pacific. I manually converted those time to US time format in above mentioned events. 
```js
// Calendar Initialization
cal = new Calendar('#calendar', {
        defaultView: 'week',
        taskView: false,
        scheduleView: ['time'],
        useCreationPopup: false,
        useDetailPopup: false,
        calendars: CalendarList,
        timezones: [
            {
                timezoneOffset: parseInt(offset), //-420
                tooltip: timzone // US/Pacific
            }],

// For creating meeting.
'beforeCreateSchedule': function (e) {
            //console.log('beforeCreateSchedule', e);
            var start = moment(e.start.getTime()).tz(timzone).format('YYYY-MM-DD HH:mm');
            var end = moment(e.end.getTime()).tz(timzone).format('YYYY-MM-DD HH:mm');
            var currentDateTime = moment().tz(timzone).format('YYYY-MM-DD HH:mm');
            var isAllDay = e.isAllDay;
            var guide = e.guide;
            $('.actionBtn').hide();
            var triggerEventName = e.triggerEventName;
            schedulePopup(currentDateTime, start, end, false);

            e.guide.clearGuideElement();
        },
## Expected Behavior
Timezone needs to handled schedule object.

**Comment by dongsik-yoo** [comment]
@pranayteja2773 At this time, we don't support zoned Date instance yet. You have to use formatting library like moment when making zoned date format string.
