### ISSUE TITLE
popupSave faile if I change other color calendar

### ISSUE THREAD

**Issue by yinghsin** [nhn/tui.calendar#421]
## Version
v1.12.5

## Development Environment
Google Chrome 
 77.0.3865.90

## Current Behavior
I used the [online demo]( https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic)
I can modify the event's subtitle, content, start and end time, but nothing will change after clicked the UPDATE button, only if I change the calendar dropdown list at the same time.
## Expected Behavior
The calender of event could be update.

**Comment by jungeun-cho** [comment]
@yinghsin 
I confirmed.
It's a bug.
I'm going to fix it quickly.
