### ISSUE TITLE
[v2] Please consider using a different term instead of "schedule"

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#429]
When getting started with tui.calendar, I found the "schedule" quite confusing, until I realized that's meant to mean one individual "event", "appointment", or "meeting". Google calendar calls those "events".

https://www.google.com/search?q=define+schedule says schedule is a list of intended events. That what would the purpose of an individual "calendar", or schedule (eg My calendar, Company, Family...)

In v2, would you please consider renaming the "schedule" terminology to "event" in API and docs, while maybe also keeping "schedule" API for backwards compatibility?

Thanks

**Comment by jungeun-cho** [comment]
@mariusa 
Yeah, That's good idea. 🙂 
I need to define a term clearly.

**Comment by tobiasschuerg** [comment]
I second that!

At the first glimpse I was also looking for some event classes until I realized that they are called schedules...

**Comment by adhrinae** [comment]
@tobiasschuerg Yup. We're going to change the term `Schedule` to `Event` in the next major version. [(Example)](https://github.com/nhn/tui.calendar/blob/next/apps/calendar/src/model/eventModel.ts)

**Comment by adhrinae** [comment]
Closing since the new alpha version implements it.
