### ISSUE TITLE
bug: calendar colors are ignored

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#432]
When one creates a 'schedule' event, it is possible to set colors and that works.

Also, when one sets the 'calendars' property, calendars have colors set too.

It sounds reasonable to render schedules using the calendar colors, unless those have been customized in schedule color properties. However, this doesn't work now.

These lines should NOT be needed, since calendars already have colors specified, and schedules are linked to those calendar ids:
https://github.com/nhn/tui.calendar/blob/192aee0bf872c1bea56acb18ae63ea5a1075a225/examples/js/app.js#L272

Thanks

**Comment by jungeun-cho** [comment]
If a calendar list(`calendars`) is set, the calendar color has priority.
That line of example code is not necessary.

**Comment by mariusa** [comment]
> That line of example code is not necessary.

It would be best to be removed then, to avoid confusion? Because the example app is the best reference for how calendar works.
