### ISSUE TITLE
changing schedule.category from 'time' to 'allday' doesn't move to all day row, even after updateSchedule()

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#434]
Hi,

When changing schedule.category from 'time' to 'allday' and invoking updateSchedule, the schedule is NOT moved to all day row (other updates work). If reloading the page, then schedule shows properly.

**Comment by mariusa** [comment]
Probably related: when changing schedule.category from 'time' to 'allday' and invoking ```updateSchedule```, the schedule is NOT moved to all day row (other updates work). If reloading the page, then schedule shows properly.

**Comment by jungeun-cho** [comment]
When updating the schedule, if the category value is 'allday', you should also set the `isAllDay` property to `true` internally.

If you can't wait for a patch, use `isAllDay`.

**Comment by mariusa** [comment]
@jungeun-cho After merging the pull request, would you please also make a new release to include this and latest fixes?

**Comment by jungeun-cho** [comment]
@mariusa 
I think a patch version will be released next week.

**Comment by mariusa** [comment]
@jungeun-cho I just wanted to say Thank you. The new release works great!
