### ISSUE TITLE
Where the callendar gather the data??

### ISSUE THREAD

**Issue by systemyokienne** [nhn/tui.calendar#435]
Hallo, Im trying to use your callendar, but i have few problems:
1. I dont know whats the database of the callendar. Where can i find the saved events? In some file or database?
2. Im trying to edit the example basic file, so i could use it to my project, but there is still showing random events, and my new events are not saving. When i refresh the page they disappear. What have i to do to be able to use this callendar?

It would be great if there was some tutorial for newbies who want to use this great callendar on their websites. Step by step because the installation guide doesnt work for me so i decided to use the example file.

Sorry for my english.

**Comment by mariusa** [comment]
Here's an example from Vue version:
https://github.com/nhn/toast-ui.vue-calendar/issues/19

You need to handle saving events on the server and loading them to calendar widget.

**Comment by systemyokienne** [comment]
Is there some example with saving the data to database and read events from there?

**Comment by jungeun-cho** [comment]
@systemyokienne 
The actual schedule data is not stored.
In order to store data, you have to connect directly to the database.

**Comment by lorenzoPrimi** [comment]
@jungeun-cho it would be nice to add some examples in the README or in the example folder
