### ISSUE TITLE
bug + fix: calendar colors always overwrite schedule colors

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#437]
Need: we need some schedules to be in custom colors, different than the calendar they belong to.
This should work according to docs, since each schedule can have it's own colors.

Bug: calendar colors always overwrite schedule colors, instead of letting those alone if they were set in schedule data.

Fix: change the code block at
https://github.com/nhn/tui.calendar/blob/188b1846eb1023660e0776ef0fcfc1a4846e9b64/src/js/factory/calendar.js#L757

to
```
        //overwrite only if not customized
        if (color) {
            if (typeof obj.color == 'undefined') { obj.color = color.color; }
            if (typeof obj.bgColor == 'undefined') { obj.bgColor = color.bgColor; }
            if (typeof obj.borderColor == 'undefined') { obj.borderColor = color.borderColor; }
        }
```

I tested that this fix works for me.

Please make to commit this in v2 too.

Thanks

**Comment by jungeun-cho** [comment]
@mariusa 
In the TOAST UI calendar, if there is `calendars`, the priority is to set the schedule color to the specified color of the calendar.

If you want to color each event, don't set `calendars` property when you create an instance of the calendar.

if not,

When creating create schedules, why don't you choose the color of this schedule as an option to use calendar color or custom schedule color?

I look forward to your help. You can be a contributor.😇

**Comment by mariusa** [comment]
Hi @jungeun-cho ,

> In the TOAST UI calendar, if there is calendars, the priority is to set the schedule color to the specified color of the calendar.
> If you want to color each event, don't set calendars property when you create an instance of the calendar.

Both calendars and schedules accept custom colors. A calendar has schedules, so schedule should inherit the color from calendar, but it should be possible to overwrite at the schedule level.

Let's make an analogy with HTML & CSS. A ```div``` can have ```p``` elements. One can set the background color of ```div``` HTML element, but also for ```p```.  

What you say, transposed to HTML:
> if there is ```div``` element, the priority is to set the ```p``` color to the specified color of the ```div```.  (```p```/schedule inside that ```div```/calendar) 
> If you want to color each ```p```, don't set ```div``` property 

But that's not useful. One needs all content inside a ```div``` to be the color of the ```div```, except some content which can be customized.
All ```p```'s inherit the color of their parent ```div```, unless a color is specified for a specific ```p```.



> You can be a contributor. 

Yes, I'd like to make a pull request with this fix. But first, we need to agree on behavior.
Would you agree with this: A calendar has schedules, so schedule should inherit the color from calendar, but it should be possible to overwrite at the schedule level.
?

**Comment by jungeun-cho** [comment]
@mariusa 

It would be better to provide an option rather than unconditionally overwriting the color of the schedule.

Each calendar has its own color for displaying events, but
  What do you think about **offering the option to choose the color's priority** if you need to display some events in different colors?

For example...
```js
calendar.createSchedules([
    {
        id: '1',
        calendarId: '1',
        title: 'Happy Halloween Party ,
        category: 'time',
        start: '2019-10-30T20:00:00+09:00',
        end: '2019-10-30T23:00:00+09:00',
        bgColor: '#f77c1f',
        dragColor: '#f77c1f',
        color: '#fff',
        useOnlyScheduleColor: true    // like this? (default value: false)
    }
]);
...
```

What do you think?

**Comment by mariusa** [comment]
> It would be better to provide an option rather than unconditionally overwriting the color of the schedule.

It's not unconditional. The custom app logic can set custom schedule colors as needed. If no custom colors are set, then use the calendar colors.

> What do you think about offering the option to choose the color's priority if you need to display some events in different colors?

If we need to display some events in different colors (which is actually our need!), we set schedule colors for desired schedules. When not set, we expect the calendar colors to be used by default.

So, there's no need for such an option, as programmer can choose what schedules in what colors to show. But, that doesn't work now, because the calendar colors always overwrite schedule color (hence this bug report & fix included in initial comment).

**Comment by jungeun-cho** [comment]
Hmm..
It was our rule to follow the calendar if the calendar list already existed even though it had a schedule color.

There are other issues with calendar colors and schedule colors.
I'll think about these two things together.

Thank you for your detailed feedback.😆

**Comment by jungeun-cho** [comment]
@mariusa 
We decided to agree with what you said.
May I ask you for a PR?

**Comment by dongsik-yoo** [comment]
@mariusa master is right branch. I'll migrate all changes to v2.
