### ISSUE TITLE
release for Issue 405 fix?

### ISSUE THREAD

**Issue by silverskysoft** [nhn/tui.calendar#439]
## Development Environment
NPM

## Current Behavior
Issue 405  seems fixed. But can we please have a release that includes that?
```js
// Write example code
```

## Expected Behavior
Update release with Issue 405 fixed

**Comment by mariusa** [comment]
Please include the fix from #437 as well, if making a new release.

**Comment by jungeun-cho** [comment]
@silverskysoft 
* [v1.12.6](https://github.com/nhn/tui.calendar/releases/tag/v1.12.6) was released.
