### ISSUE TITLE
I hope to use HTML tag in schedules title.  But not Success

### ISSUE THREAD

**Issue by blacklisten** [nhn/tui.calendar#441]
## Version
1.12.5

## Development Environment
window 10
google browser 76.0

## Current Behavior
I hope to use HTML tag in schedules title.   But is not Success
![image](https://user-images.githubusercontent.com/26319882/67140828-151e5580-f291-11e9-9bef-1046a95d1bc8.png)

```js
schedule: [{
  bgColor: "#67c23a",
  borderColor: "#67c23a",
  category: "time",
  color: "#fff",
  dragBgColor: "#67c23a",
  end: 1568359800000,
  id: "001",
  location: "ShangHai",
  start: 1568352600000,
  title: "Title Name<br/> Class Name"
}]
view: 'week',
scheduleView: ['time'],
// Write example code
```

**Comment by blacklisten** [comment]
I through edit time.hbs.  solve the problem.  because i find time-tmpl Function 


**time-tmpl Function**
```js
'time-tmpl': function(model) {
    return common.stripTags(model.title);
 }
stripTags: function(str) {
    return str.replace(/<([^>]+)>/ig, '');
}

```

**solve method**

```js
{{{time-tmpl model}}} -> {{{model.title}}}
```

Will this bring other hidden dangers???

**Comment by mariusa** [comment]
It would be useful to support HTML in title

**Comment by jungeun-cho** [comment]
@blacklisten 
How about using a template?
https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month

**Comment by blacklisten** [comment]
I tried the template but didn't get what I wanted

I want this, it supports some HTML tag
![image](https://user-images.githubusercontent.com/26319882/67651055-4fb37c80-f97a-11e9-82eb-d983ded00c59.png)

I using https://github.com/nhn/tui.calendar/issues/441#issuecomment-544129413 achieve it

@jungeun-cho

**Comment by jungeun-cho** [comment]
@blacklisten 
```js
const cal = new Calendar('#calendar', {
    ...
    template: {
      time: function(schedule) {
        return schedule.title;
      }
    }
  });
```
