### ISSUE TITLE
Calendar full month view configuration

### ISSUE THREAD

**Issue by ignasga** [nhn/tui.calendar#442]
## Development Environment:
Archlinux
webpack
vuejs
npm
code
firefox

## Current Behavior
When month configuration is set to `visibleWeeksCount: 6,`, the month starts with current week and shows 6 weeks in total. If you remove this setting - calendar still shows 6 weeks, but it starts with first week of current month, and current day is somewhere further (e.g. if this is day 20, then it will be in 3rd or 4th week).

## Expected Behavior
I think there should be separate variables to configure how many weeks calendar is showing and whether it starts with first week of month or with current week.

**Comment by jungeun-cho** [comment]
@ignasga 

When you create an instance of a calendar,
What about using `isAlways6Week: false` in the month option?
Automatically mark 5 or 6 weeks as needed.

https://nhn.github.io/tui.calendar/latest/MonthOptions

```js
cal = new Calendar('#calendar', {
        defaultView: 'month',
        ...
        month: {
            isAlways6Week: false
        }
    });
```

**Comment by ignasga** [comment]
Yes, this did work,
thanks for the help!
