### ISSUE TITLE
Calendar color not reflected in Schedules until reloading the page.

### ISSUE THREAD

**Issue by pranayteja2773** [nhn/tui.calendar#444]
## Current Behavior

I am using the Calendar list as resources. We have multiple offices which contain multiple resources. I have Office dropdown based on that I am showing Calendar list. This is done using ajax call. When change Calendar list color, but doesn't reflect on schedules. Reloading page solving my issue since all javascript files are reloading again. But with Ajax call, I am unable to set Calendar color to Schedules.
Kindly help me on this issue. How can i set color to schedule while loading schedules to Calendar?
![image](https://user-images.githubusercontent.com/33422173/67506191-442a3200-f6aa-11e9-939c-48ba2f9b202d.png)

```js
// Write example code
//Even though i have right color name, schedules color is not changing.
var Schedule1 = getSchedules(hostId, officeId);
for (var i in Schedule1) {
schedules.push({
                id: Schedule1[i].scheduleid,
                calendarId: Schedule1[i].conferenceid,
                title: Schedule1[i].title,
                officeId: Schedule1[i].officeid,
                start: moment.tz(Schedule1[i].visitstart, timzone).format(),
                end: moment.tz(Schedule1[i].visitend, timzone).format(),
                category: 'time',
                color: '#ffffff',
                bgColor: Schedule1[i].ColorName,  //getting correct color name here, but it is applied to schedular.
                dragBgColor: Schedule1[i].ColorName,
                borderColor: Schedule1[i].ColorName,
                raw: [{
                        userId: Schedule1[i].hostedby,
                        visitor: visitor,
                        attendees: Schedule1[i].attendeesNo,
                        notes: arrNoteData,
                        host_name: Schedule1[i].host_name,
                        office_name: Schedule1[i].OfficeName,
                        conference_name: Schedule1[i].ConferenceName,
                        reminder_type: Schedule1[i].remindertype,
                        reminder_duration: Schedule1[i].reminderduration,
                        email_invite: Schedule1[i].isemail,
                    }],
            });
}
ScheduleList.push(schedules);
 cal.createSchedules(ScheduleList[0]);
 refreshScheduleVisibility();
```

**Comment by jungeun-cho** [comment]
@pranayteja2773
Does the value of `Schedule1[i].conferenceid` match the value of` id` put in `calendars`? (string, number..)

**Comment by brandonellis** [comment]
I am experiencing a similar issue.  The update of time works for the schedule on the calendar.  However, if you are changing the calendarId on an update the schedule color is not reflected until a page reload happens.
