### ISSUE TITLE
Now showing schedule on safari

### ISSUE THREAD

**Issue by dupled** [nhn/tui.calendar#446]
## Version

1.12.6
## Development Environment

Safari 13.0.2, macOS 10.15.0
## Current Behavior

It just shows the blank schedule grid with the error in the console, not showing the schedule blocks, although it does appear on Chrome and Firefox. I use tui.calendar's CDN.
![image](https://user-images.githubusercontent.com/25809350/67621880-59d06080-f83e-11e9-9949-09a95a047f14.png)

## Expected Behavior

I need help with this issue to make it works on Safari, thank you!

**Comment by jungeun-cho** [comment]
@dupled 
https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic

An example runs on Safari.

And this file (like `main.css`) does not exist on cdn.
```js
// css
http://uicdn.toast.com/tui-calendar/latest/tui-calendar.css

// js
http://uicdn.toast.com/tui-calendar/latest/tui-calendar.min.js
```

**Comment by mariusa** [comment]
Hi, we also tested with Safari on an iPhone and no schedule blocks appear. On Android Chrome/FF it works ok.
We're trying to replicate.

**Comment by lgveronese** [comment]
Hi,

After spend some time on it, I found the "problem".

My schedule was like this: (Not working)

```
{
...
 "start": "2019-11-01 08:30:00",
 "end": "2019-11-01 09:30:00",
... 
}
```

Then, I changed it to: (Working)
```
{
...
 "start": "2019-11-01T08:30:00-03:00",
 "end": "2019-11-01T09:30:00-03:00",
... 
}
```
And it works! Hope it helps you!

I think that is a problem with Moment.js lib..

**Comment by mariusa** [comment]
Hi, thanks so much for sharing this. It works now with your change!

It also works with "2019-11-01T08:30:00". I was using a space instead of "T".

Thanks again :)

**Comment by mariusa** [comment]
Actually, "2019-11-01T08:30:00" give wrong hour on Safari only (looks like it's defaulting to GMT, even though the give hour is in local time). If I add "-00:00", then it breaks all other browsers, shifting the hour.
