### ISSUE TITLE
Unable to create schedule

### ISSUE THREAD

**Issue by LoYungSum** [nhn/tui.calendar#447]
## Version
latest (cdn)

## Development Environment
Chrome 78.0.3904.70
macOS Catalina 10.15

## Current Behavior
I've wanted to create schedules. But it doesn't work
(I've changed how the `data/schedules.js` worked. Others remain unchanged)

```js
function generateScheduleDetails(data) {
    data.activities.forEach((value, index, array) => {
      console.log('Adding ', value);
      var schedule = new ScheduleInfo();

      schedule.id = value.id;
      schedule.calendarId = value.calendarId;

      schedule.title = value.title;
      schedule.body = value.body;

      schedule.start = new Date(value.start);
      schedule.end = new Date(value.end);

      var calendar = findCalendar(value.calendarId);

      schedule.color = calendar.color;
      schedule.bgColor = calendar.bgColor;
      schedule.dragBgColor = calendar.dragBgColor;
      schedule.borderColor = calendar.borderColor;

      if (value.isAllday) {
        schedule.category = 'allday';
      } else {
        schedule.category = 'time';
      }

      if (schedule.category === 'milestone') {
        schedule.color = schedule.bgColor;
        schedule.bgColor = 'transparent';
        schedule.dragBgColor = 'transparent';
        schedule.borderColor = 'transparent';
      }
      console.log(schedule);

      ScheduleList.push(schedule);
    });
  }
```

An example of the log adding
![image](https://user-images.githubusercontent.com/25066078/67629833-83799e00-f8b7-11e9-86b8-651a65f9fb99.png)

## Expected Behavior
The calendar should have some schedule pop up.

I've also tried to use the chrome console to fetch the schedule by `cal.getSchedule(id, calendarId)`. But it said undefined

**Comment by jungeun-cho** [comment]
@LoYungSum 
Check the `createSchedules` method

https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#usage
```js
 var cal = new tui.Calendar('#calendar', {
    ...
    useCreationPopup: true, // Did you turn this option on?
    useDetailPopup: true
  });
```
https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules

**Comment by LoYungSum** [comment]
I've turned the settings on

```var cal = new tui.Calendar('#calendar', {
  defaultView: 'month',
  taskView: true,
  template: templates,
  useCreationPopup: true,
  useDetailPopup: true,
  calendars: calCalendars,
});
```

I think I've coded the `createSchedules` correctly. Is there something wrong that I've missed?

I've tried to check the array before the above method is executed.
```
function setSchedules() {
    cal.clear();
    generateSchedule(cal.getViewName(), cal.getDateRangeStart(), cal.getDateRangeEnd());
    cal.createSchedules(ScheduleList);
    console.log('The ScheduleList',ScheduleList);
    refreshScheduleVisibility();
  }
```
And the output is as follows
![image](https://user-images.githubusercontent.com/25066078/67662265-007f4300-f99e-11e9-8796-d71152bc68b2.png)

**Comment by LoYungSum** [comment]
Does the ID of a schedule must be a UUID?

**Comment by LoYungSum** [comment]
@jungeun-cho Do you know how to solve the problem?

**Comment by jungeun-cho** [comment]
@LoYungSum 
Can you give me information with [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) so that I can understand the scenario?

The [codesandbox](https://codesandbox.io/) is fine too.

**Comment by LoYungSum** [comment]
I'm hosting with Google Cloud, but there seems to be a shortage which caused the app to crash. I'll upload the code as soon as it's fixed.

https://status.cloud.google.com/

**Comment by LoYungSum** [comment]
http://stlouis-cloud.web.app/calendar
There you go

**Comment by LoYungSum** [comment]
@jungeun-cho

**Comment by dongsik-yoo** [comment]
@LoYungSum Your method call order is wrong. Your post API returns `ScheduleList` data after `setSchedules()` called. It's asynchronous method problem.

**Comment by LoYungSum** [comment]
Oh. Thanks for the help @dongsik-yoo . But now I get another problem.

```
Uncaught (in promise) TypeError: end.getTime is not a function
    at Object.range (tui-calendar.js:3085)
    at tui-calendar.js:24942
    at forEachArray (tui-code-snippet.js:947)
    at Object.forEach (tui-code-snippet.js:1024)
    at tui-calendar.js:24933
    at forEachArray (tui-code-snippet.js:947)
    at Object.forEach (tui-code-snippet.js:1024)
    at tui-calendar.js:24932
    at forEachArray (tui-code-snippet.js:947)
    at Object.forEach (tui-code-snippet.js:1024)
```

The error occurs when I switch a month (From Nov -> Dec)
