### ISSUE TITLE
Custom popup modal without prompt

### ISSUE THREAD

**Issue by elenacyl** [nhn/tui.calendar#449]
## Version
1.12.6

## Development Environment
Chrome

## Current Behavior
I am using the react wrapper. When I create my own popup, the `const title = prompt()` method works, but I want to use my own modal form (without using the prompt).

```js
function onBeforeClickSchedule(e) {
    onOpen(true); // open my custom modal
    const schedule = {
      id: +new Date(),
      calendarId: 1,
      title: 'mytitle',
      start: e.start,
      end: e.end,
      isAllDay: true,
      category: 'time',
      // my own custom props
      recurringStart: createRecStartDate,
      recurringEnd: createRecEndDate,
      venueId: 1,
      creatorId: 1,
      attendance: createAttendees,
    };
    calendarInst.createSchedules([schedule]); // this does not work
    e.guide.clearGuideElement();
  }
```

## Expected Behavior
I have been unable to create a schedule in the calendar instance when I use my own popup modal. Is there an example of using custom popup **without using a prompt**? I want to create my own modal and on clicking the submit button in the modal, create the schedule.

**Comment by jowpurcinelli** [comment]
Hey, were you able to solve this? @elenacyl
