### ISSUE TITLE
24 hour time format required for WEEK and DAY views.

### ISSUE THREAD

**Issue by ignasga** [nhn/tui.calendar#452]
## Version
latest

## Development Environment
Archlinux
webpack
vuejs
npm
code
firefox

## Current Behavior
Calendar week view is showing time in 12 hour format (1-12 AM/PM).

## Expected Behavior
I would expect to change some setting to select whether I want to show hours in week view in 24 or 12 hour format. It's the same in day view too.
In my case the calendar is not meant for US users, but rather some European country, so time format required is 24 hour.
(I noticed that current time (marked with purple line) is showing 24hour time.)

**Comment by jungeun-cho** [comment]
@ignasga 
https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid

Use
`timegridDisplayTime`
`timegridDisplayPrimayTime `
