### ISSUE TITLE
Moment js not working with tui.calendar

### ISSUE THREAD

**Issue by Robertutzu** [nhn/tui.calendar#454]
So i try to modify the popup template with this code:
```
	popupDetailDate: function(isAllDay, start, end) {
			console.log(start);
			console.log(end);
			return (moment(start).format('DD.MM.YYYY hh:mm') + ' - ' + moment(end).format('DD.MM.YYYY hh:mm'));
		}
```
and it returns wrong date or same date as start
from what i saw the start and end returns as TZdate and is not interpreted ok by momentjs

schedules demo used:
 ```
 {
            "id": "219",
            "calendarId": "53",
            "title": "test",
            "body": "demo",
            "bgColor": "#ff5500",
            "category": "time",
            "dueDateClass": "",
            "isAllDay": "true",
            "start": "2019-10-29 09:57:49",
            "end": "2019-11-01 10:14:12"
        }
```
i use the latest version of tui.calendar and latest version of moment.js

**Comment by Robertutzu** [comment]
ok, for who needs, i just resolved with this:
popupDetailDate: function(isAllDay, start, end) {
			startr=new Date(start);
			endr=new Date(end);
			return (moment(startr).format('DD.MM.YYYY hh:mm') + ' - ' + moment(endr).format('DD.MM.YYYY hh:mm'));
		}

**Comment by jungeun-cho** [comment]
@Robertutzu 
https://nhn.github.io/tui.calendar/latest/tutorial-example16-template-for-popup
```js
    popupDetailDate: function(isAllDay, start, end) {
      var isSameDate = moment(start).isSame(end);
      var endFormat = (isSameDate ? '' : 'YYYY.MM.DD ') + 'hh:mm a';

      if (isAllDay) {
        return moment(start).format('YYYY.MM.DD') + (isSameDate ? '' : ' - ' + moment(end).format('YYYY.MM.DD'));
      }

      return (moment(start).format('YYYY.MM.DD hh:mm a') + ' - ' + moment(end).format(endFormat));
    },
   ...
```

**Comment by Robertutzu** [comment]
> @Robertutzu
> https://nhn.github.io/tui.calendar/latest/tutorial-example16-template-for-popup
> 
> ```js
>     popupDetailDate: function(isAllDay, start, end) {
>       var isSameDate = moment(start).isSame(end);
>       var endFormat = (isSameDate ? '' : 'YYYY.MM.DD ') + 'hh:mm a';
> 
>       if (isAllDay) {
>         return moment(start).format('YYYY.MM.DD') + (isSameDate ? '' : ' - ' + moment(end).format('YYYY.MM.DD'));
>       }
> 
>       return (moment(start).format('YYYY.MM.DD hh:mm a') + ' - ' + moment(end).format(endFormat));
>     },
>    ...
> ```

As i said in the first comment, there is a problem with moment interpreting the TZdate so it wont work ok with moment js. Just try it and you will see that.

**Comment by dongsik-yoo** [comment]
@Robertutzu Please refer to this [TZDate document](https://nhn.github.io/tui.calendar/latest/TZDate#toDate).
