### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by haojia321** [nhn/tui.calendar#459]
Hi, 
Does Tui Calendar support localization? I dont see it in documentation.

Thanks

**Comment by mariusa** [comment]
Would you please detail a list of what should be localizable?

For example:
1. in week view, the day names at top (18 Mon, 19 Tue)

IMHO, The popups shouldn't be localizable, since one can easily replace them with custom popups.

**Comment by mariusa** [comment]
Following up, we need just this to be localizable:
in week view, the day names at top (18 Mon, 19 Tue)

We'd like to pass this data via a `locale` property to be used by calendar widget where needed:
https://github.com/iamkun/dayjs/blob/dev/src/locale/ko.js
