### ISSUE TITLE
Unchecking `isAllDay` has no effect

### ISSUE THREAD

**Issue by WilliamWsyHK** [nhn/tui.calendar#463]
## Version
1.12.7

## Development Environment
Windows IE 11 and Chrome 78

## Current Behavior
Unchecking `isAllDay` has no effect. The `beforeUpdateSchedule` does not populate any changes when `isAllDay` is unchecked.

```js
beforeUpdateSchedule: function (e) {
    let schedule = e.schedule;
    // here when nothing else changes except isAllDay, then changes === null.
    let changes = e.changes || {};
    console.log(changes.isAllDay);
    // should print "undefined".
}
```

## Expected Behavior
`isAllDay === false` if the user has click to uncheck the all day checkbox.

**Comment by mariusa** [comment]
Set `category = 'allday'`
isAllDay is a read-only property

**Comment by WilliamWsyHK** [comment]
Maybe you mis-understood, but what I mean is not changing the `isAllDay` in my code, but when `beforeUpdateSchedule` is being called, value of `isAllDay` is not set. You can also experience the same in _**example app**_, especially unchecking the "All Day" checkbox.

**Comment by mariusa** [comment]
I recommend to use `category == 'allday'` to check. Simpler than having N properties isThis, isThat, isScheduleStartingAt8AM...

**Comment by WilliamWsyHK** [comment]
Thanks @mariusa, but that will definitely defeat the purpose of having `isAllDay` from the start, i.e. why the team create such property if you are not intentionally change its value when there is updates on the field? This is just confusing.

But for now it make sense to use `category === 'allday'` to check, provided that the update will populate the changed value.

**Comment by mariusa** [comment]
Right. There is a proposal to remove 'isAllDay'

**Comment by jungeun-cho** [comment]
@WilliamWsyHK 
I reproduced it.
If you changed the **All Day** checkbox
It is correct to send `isAllDay` or` category` information in `changes`.

I'll fix it in the next patch version.
