### ISSUE TITLE
Milestone and task render schedule (range of date) not working correctly

### ISSUE THREAD

**Issue by elenacyl** [nhn/tui.calendar#467]
## Development Environment
Chrome

## Current Behavior
Date of milestone is from 25/11 to 28/11 but it only renders on the end date (28/11). How can I make it show as a range across the 4 days?
![Screen Shot 2019-11-25 at 1 09 33 PM](https://user-images.githubusercontent.com/28526129/69514123-34418e80-0f85-11ea-8771-a58f99c7d726.png)

```js
const schedules = [
      {
        id: '1',
        calendarId: '0',
        title: 'Sprint Meeting',
        body: 'Sprint meeting',
        category: 'milestone',
        dueDateClass: '',
        start: '2019-11-25T17:31:00+09:00',
        end: '2019-11-28T17:31:00+09:00',
      },
    ];
```

## Expected Behavior
I want milestone to show as this:
![Screen Shot 2019-11-25 at 1 11 54 PM](https://user-images.githubusercontent.com/28526129/69514119-2f7cda80-0f85-11ea-99f6-a32993e9ed1d.png)

This only occurs when the category is 'time/allday' but not 'milestone/task'

**Comment by dongsik-yoo** [comment]
@elenacyl I publish [v1.12.8](https://github.com/nhn/tui.calendar/releases/tag/v1.12.8). Please check it out.
