### ISSUE TITLE
New to javascript, need help getting data from ajax

### ISSUE THREAD

**Issue by gary492** [nhn/tui.calendar#472]
Hi, I am new to javascript but using this calendar for my college project and need to get it to work.
I am trying to use the api of "/api/ConferenceRooms/" to get the start time and end time posted on the calendar, but I havent had any success.
 Here is a picture of the data from the api
![image](https://user-images.githubusercontent.com/58373847/69905996-451d4600-1371-11ea-8f60-d0eca50bfcc2.png)

I want the "startTime" to set as the start date and the "endTime" as the end date. With their name some where on the event.The goal is everytime a new array is added to the api, a new event is made in the calendar.
 Here is my code so far:

![image](https://user-images.githubusercontent.com/58373847/69906010-a9400a00-1371-11ea-8531-1d7b9737a02d.png)

**Any help would really be appreciated, thank you in advance**

**Comment by dongsik-yoo** [comment]
@gary492 You need to read [the getting-started usage](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#usage).
