### ISSUE TITLE
Click events for task and milestone?

### ISSUE THREAD

**Issue by xeon826** [nhn/tui.calendar#478]
## Version
^1.12.8

## Development Environment
Google-chrome Version 78.0.3904.97 (Official Build) (64-bit), Ubuntu 18.04

## Current Behavior
When I click on a date or "allday" in in the week view I get an event, but I don't get one for "task" or "milestone" I don't see any events in the API for this.

```js
  var calendar = new Calendar('#calendar', {
    defaultView: 'month', // set 'week' or 'day'
    taskView: true, // e.g. true, false, or ['task', 'milestone'])
    scheduleView: ['time', 'task', 'milestone', 'allday'], // e.g. true, false, or ['allday', 'time'])    useCreationPopup: true,
    calendars: CalendarList,
    useDetailPopup: false,
    useCreationPopup: false,
    month: {
      scheduleFilter(schedule) {
        return Boolean(schedule.isVisible);
      }
    },
    theme: theme,
    template: template
  });

  let modalEl = container.querySelector('#shift-view'),
    beginInput = modalEl.querySelector('.begin input'),
    endInput = modalEl.querySelector('.end input'),
    userInput = modalEl.querySelector('#employee'),
    titleHeader = modalEl.querySelector('#my-dialog-title');
  calendar.on({
    'clickSchedule': e => openClickedScheduleModal(e, modalEl, beginInput, endInput, userInput, titleHeader),
    'beforeCreateSchedule': function(e) {
      console.log('beforeCreateSchedule', e);
      // open a creation popup
    },

    'beforeUpdateSchedule': function(e) {
      console.log('beforeUpdateSchedule', e);
      e.schedule.start = e.start;
      e.schedule.end = e.end;
      calendar.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
    },
    'beforeDeleteSchedule': function(e) {
      console.log('beforeDeleteSchedule', e);
      calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);
    },
// no event here
    'beforeCreateTask': function(e) {
      console.log('beforeCreateTask', e);
    },
  });

```

## Expected Behavior
I want it to return an event when I click on the task/milestone pane, right now it only does it for the schedule or "allday" rows.

**Comment by dongsik-yoo** [comment]
`clickSchedule` event is for them, too. Check `schedule.category`.
```js
calendar.on('clickSchedule', ({schedule, event}) => {
  if (schedule.category === 'milestone') {
    //
  } else if (schedule.category === 'task') {
    //
  } else {
    //
  }
});
```

**Comment by xeon826** [comment]
> ```js
> calendar.on('clickSchedule', ({schedule, event}) => {
>   if (schedule.category === 'milestone') {
>     //
>   } else if (schedule.category === 'task') {
>     //
>   } else {
>     //
>   }
> });
> ```

I'm referring to when a blank space is clicked in the milestone/task pane in the week view. Only allday will return an event for 'beforeCreateSchedule' but not milestone or task.

**Comment by xeon826** [comment]
Please let me know if this is a feature that can be implemented, if not, I'll have to find a workaround.

**Comment by dongsik-yoo** [comment]
I understood the situation you said. Not implemented yet. It'll take some time to implement it.
The reason we didn't implement it is the creation popups of task or milestone are different with normal events's. So, I think we can implement it, but  you have to also implement the creation popups of task and milestone.

**Comment by xeon826** [comment]
It would be nice if at least there was an event for it, no need for a popup.

**Comment by xeon826** [comment]
Is it possible we could have this feature? just an event is fine.
