### ISSUE TITLE
Cannot read property 'mixin' of undefined

### ISSUE THREAD

**Issue by skoblenick** [nhn/tui.calendar#483]
## Version
-  `1.12.9`
-  `1.12.6`

## Development Environment
MacOs 10.15.2, Chrome, WebPack 4.39.1 with babel 7.5.5

## Current Behavior
An error is thrown when code is transpiled in webpack on both versions `1.12.9` or `1.12.6`. Version 1.12.3 works without issue.

```js
Uncaught TypeError: Cannot read property 'mixin' of undefined
    at Object../src/js/view/view.js (tui-calendar.js:23098)
    at __webpack_require__ (tui-calendar.js:36)
    at Object../src/js/view/layout.js (tui-calendar.js:18537)
    at __webpack_require__ (tui-calendar.js:36)
    at Object../src/js/factory/calendar.js (tui-calendar.js:8197)
    at __webpack_require__ (tui-calendar.js:36)
    at Object.<anonymous> (tui-calendar.js:1569)
    at Object../src/index.js (tui-calendar.js:1603)
    at __webpack_require__ (tui-calendar.js:36)
    at tui-calendar.js:100
```

The error is occurring on:

```
/**
 * set state
 * @param {object} state - state
 */
View.prototype.setState = function(state) {
    util.extend(this.state, state);
};

util.CustomEvents.mixin(View); // << error here

module.exports = View;
```

## Expected Behavior
Component doesn't throw.

**Comment by jungeun-cho** [comment]
I think that the version of tui-code-snippet is wrong.

```
$ npm ls tui-code-snippet
```
Can you confirm that the version of tui-code-snippet is 1.5.x?

**Comment by skoblenick** [comment]
I am using yarn with workspaces enabled:
```
$ yarn list tui-code-snippet
yarn list v1.19.1
└─ tui-code-snippet@1.5.2
✨  Done in 0.90s.
```

The npm result:
```
$ npm ls tui-code-snippet
@example/my-app
└── (empty)
```

**Comment by indietools** [comment]
I'm seeing the same issue using yarn:

```$ yarn list tui-code-snippet
yarn list v1.22.0
warning package.json: No license field
warning No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ tui-calendar@1.12.11
│  └─ tui-code-snippet@1.5.2
└─ tui-code-snippet@2.3.1
Done in 0.09s.
```

**Comment by indietools** [comment]
I tested each version against `tui-code-snippet@1.5.2` and the breaking change happened between `1.12.5` and `1.12.6`.

**Comment by indietools** [comment]
I isolated this to the SHA (7f7e89f)[https://github.com/indietools/tui.calendar/commit/7f7e89fbd488441943f7e5d0ef6093c7827563b8] where several dependencies are updated.

The issue appears to be with `tui-time-picker` versions >2.0. 

@skoblenick - This works with the newest version (1.12.11) of `tui-calendar` if one rebuilds with the `tui-time-picker` reverted to `^1.5.0`.   You can see my forked example (here)[https://github.com/indietools/tui.calendar/commit/a33310a0c69639e03dbdac996f68e079898091a8].
