### ISSUE TITLE
Timezone issue while showing calendar events.

### ISSUE THREAD

**Issue by pranayteja2773** [nhn/tui.calendar#484]
## Current Behavior

Even though time zones provided in Calendar options. It is only working properly for current date time indicator with blue and rest of all functionalities are taking browser time but not the option mentioned in timezone.

![image](https://user-images.githubusercontent.com/33422173/71875920-7dbbf680-314b-11ea-8988-574803a96afa.png)

**This issue in Day, Week and Month view.**
For other things like start time and end time in schedule popup, I am handling with moment time zone. The main issue is calendar view and Today button. These are working on browser time.

**Week view**
![image](https://user-images.githubusercontent.com/33422173/71876243-5285d700-314c-11ea-8d1a-bfc225074fe1.png)

**Month View**
![image](https://user-images.githubusercontent.com/33422173/71876752-857c9a80-314d-11ea-858b-495004a11cdd.png)

**Day view**
![image](https://user-images.githubusercontent.com/33422173/71876936-f58b2080-314d-11ea-956f-ecaa34e05a68.png)

```js
// Write example code
```

## Expected Behavior

Is there any way to handle above issue?

**Comment by jungeun-cho** [comment]
The main time zone should be the first element of the `timezones` array.
Did you do that?

**Comment by pranayteja2773** [comment]
would mind provide an example to rectify my issue?

**Comment by jungeun-cho** [comment]
```js
timezones: [
  { // you want to see
    timezoneOffset: -420,
    tooltip: 'Us/Pacfic'
  },
  { // add system timezone info (Browser, OS time..)
    timezoneOffset: 540,
    tooltip: 'Seoul'
  }
]
```
