### ISSUE TITLE
Timezone: wrong offset calculation when offsets are 30 minutes apart (first tz is 30 minutes ahead than second)

### ISSUE THREAD

**Issue by snyaggarwal** [nhn/tui.calendar#488]
Timezones comparison rendering works well except this one case when the first timezone is 30 minutes ahead of the second. Rather than subtracting 30 minutes from the second timezone its adding 30 minutes to it.
Please take a look at [this codepen](https://codepen.io/snyaggarwal/pen/OJPoNEb).
The timezones are rendered wrong (relatively).

Expected behavior - first timezone(+570) should be 30 minutes ahead of the second timezone(+540).

**Comment by jungeun-cho** [comment]
As you said, the time slot in the second time zone is incorrectly displayed.

If you see the screenshot below, this is correct.

![스크린샷 2020-01-21 23 46 11](https://user-images.githubusercontent.com/43128697/72814628-4fd4c700-3ca0-11ea-8558-45e249a98f96.png)

I'll test it and patch it.

**Comment by snyaggarwal** [comment]
Thanks
