### ISSUE TITLE
calendar list overflow

### ISSUE THREAD

**Issue by LoYungSum** [nhn/tui.calendar#490]
## Version
latest (from cdn)

## Development Environment
Chrome 79.0.3945.130, MacOS 15.1.2 (All latest)

## Current Behavior
The calendar list in the sidebar overflows

## Expected Behavior
Can there be a scroll bar when the sidebar overflows?

![Screenshot 2020-01-21 at 5 33 59 PM](https://user-images.githubusercontent.com/25066078/72792620-4b92b480-3c74-11ea-9c01-02cafa9eda43.png)

**Comment by jungeun-cho** [comment]
@LoYungSum 
This is not a tui-calendar's issue.
Fix the your calendar list containers style code.(at your service code level)
For example)


```css
.calendar-list {
  overflow: auto;
  height: ...
}
```

**Comment by LoYungSum** [comment]
I have tried to set overflow to auto and height to 100%, but it doesn’t work

**Comment by jungeun-cho** [comment]
The `%` value is relative. Thus, it becomes 100% based on the **height of the parent container**.

**Comment by LoYungSum** [comment]
So what should the height value be? As I've tried to specify the height of the parent box to 100%. But still fails

**Comment by jungeun-cho** [comment]
Again, it's not a calendar issue.
I hope to fix it at your service code level.

On a lighter note, to use overflow, the container must have a height that can be calculated.

For example.
```css
height: calc(100vh - 200px);
```
