### ISSUE TITLE
Modify layout of rendered schedules on Calendar

### ISSUE THREAD

**Issue by supertrip86** [nhn/tui.calendar#492]
I'd like to customize a little the content of the schedules rendered on the Calendar. Is there any API for that, or should I just change the template in /src/js/view/template/month/more.hbs ? Is that the only template responsible for the rendering? Should I edit anything else?
Thanks for your kind help

**Comment by jungeun-cho** [comment]
We support a variety of templates.
Check the following:

https://nhn.github.io/tui.calendar/latest/Template
https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month
https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid
https://nhn.github.io/tui.calendar/latest/tutorial-example16-template-for-popup

Please keep the issue template.
