### ISSUE TITLE
[ Documentation fix needed] CustomEvents  

### ISSUE THREAD

**Issue by AvgustPol** [nhn/tui.calendar#496]
## Version 
1.12.10
https://github.com/nhn/tui.calendar/releases/tag/v1.12.10

## Development Environment
Google chrome Version 79.0.3945.130 (Official Build) (64-bit)
OS is Windows 10* 64-bit

## Current Behavior
Broken link at documentation for the **CustomEvents** 
https://nhn.github.io/tui.calendar/latest/CustomEvents 

![ 404 ](https://sun9-7.userapi.com/c857624/v857624458/164672/n4QHTXxk9XQ.jpg)

## Expected Behavior
Nice guide 'how to create CustomEvents'

**Comment by jungeun-cho** [comment]
The correct link is:
https://nhn.github.io/tui.code-snippet/latest/CustomEvents

I'll fix the API documentation.

**Comment by jungeun-cho** [comment]
Patched in [v1.12.11](https://github.com/nhn/tui.calendar/releases/tag/v1.12.11)
