### ISSUE TITLE
[질문] 한글 지원이 가능한가요?

### ISSUE THREAD

**Issue by devbbin** [nhn/tui.calendar#497]
안녕하세요. 토스트 캘린더를 잘 사용하고있는 유저입니다. 문의사항이 있는데요,

![image](https://user-images.githubusercontent.com/59042602/73321214-21994d80-4285-11ea-85d3-2ebac8ced2bd.png)

혹시 해당 부분 한글화를 지원하고 계신가요?

**Comment by dongsik-yoo** [comment]
Check this [WeekOptions.daynames](https://nhn.github.io/tui.calendar/latest/WeekOptions) option.
