### ISSUE TITLE
Handle visible when using read only mode in week view.

### ISSUE THREAD

**Issue by Nopraz** [nhn/tui.calendar#499]
## Version
1.11.0

## Development Environment
Safari 13.0.4 in MacOS Catalina 10.15.2

## Current Behavior
Hello !

When using the week view in read only mode, the handles of schedules are visible but you cannot use them (normal behavior), i think it will be better if they were not visible when in ReadOnly mode.

For now i'm hiding each handle by using jquery in the afterRenderSchedule event 
```js
let calendarElement = $('#calendar');
calendar.on('afterRenderSchedule', function(event) {
    if(readOnly){
	calendarElement.find('.handle-x').hide();
    }
});
```

## Expected Behavior
I think it is supposed to hide the handle at the bottom of each schedules when you are in ReadOnly Mode but it is actually visible but not actually enabled so it's just a style thing i think.

Thank you in advance

edit : typo

**Comment by jungeun-cho** [comment]
Hi. This issue has been patched in the last version.([v1.12.10](https://github.com/nhn/tui.calendar/releases/tag/v1.12.10))
