### ISSUE TITLE
Custom Logic before create/update schedule popup is open (using tui-calender)  

### ISSUE THREAD

**Issue by saijao** [nhn/tui.calendar#501]
Is there is any event that is trigger before create/update schedule popup is open.
I also want to know how to open create/update schedule from custom button.

If possible kindly provide sample code here.

I find createBeforeSchedule/beforeUpdateSchedule in official documentations but unable to find event like that.

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/Calendar#openCreationPopup

https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js#L258

**Comment by saijao** [comment]
> https://nhn.github.io/tui.calendar/latest/Calendar#openCreationPopup
> 
> https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
> https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js#L258

thanks

**Comment by saijao** [comment]
is there is any option to view resource schedule?

can i add/remove input elements from create popup?

**Comment by harikesh409** [comment]
> is there is any option to view resource schedule?
> 
> can i add/remove input elements from create popup?

You can check guide document in [getting-started.md#customize-popups](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups).
