### ISSUE TITLE
Click event on date or time cell

### ISSUE THREAD

**Issue by XpertKhan** [nhn/tui.calendar#502]
I am working on tui-calender in my application
Scenario:

In day view mode:
when spacific time  portion is click on timegrid then i want some custom logic

I week or month view mode:
When specific date is click then i want some custom logic on that as will

Also is there is way to set some custom data-attribute on schedule item

using following events.

`
       
       
        'clickDayname': function (date) {
            debugger
            console.log('clickDayname', date);
        },
       
        'clickSchedule': function (e) {
            
            console.log('clickSchedule', e);
        }, 
        'beforeCreateSchedule': function (event) {
            
            event.isAllDay == true;
            var guide = event.guide;
            var triggerEventName = event.triggerEventName;
            var _eventId = Math.floor((Math.random() * 1000) + 1);
            var schedule = {
                id: 0,
                calendarId: event.calendarId,
                title: event.title,
                location: event.location,
                category: 'time',
                dueDateClass: '',
                start: event.start,
                end: event.end,
                isAllDay: event.isAllDay,
                isReadOnly: true

            }

            //SaveEvent(schedule);

            if (triggerEventName === 'click') {
                // open writing simple schedule popup
                //schedule = {...};
            } else if (triggerEventName === 'dblclick') {
                // open writing detail schedule popup
                //schedule = {...};
            }

           
        },
        'beforeUpdateSchedule': function (e) {
             
            console.log('beforeUpdateSchedule', e);
            e.schedule.start = e.changes.end != undefined ? e.changes.start : e.schedule.start;
            e.schedule.end = e.changes.start != undefined ? e.changes.end : e.schedule.end;
            e.schedule.location = e.changes.location != undefined ? e.changes.location : e.schedule.location;
            e.schedule.title = e.changes.title != undefined ? e.changes.title : e.schedule.title;
            e.schedule.isAllDay == true;
            //cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
        },
        'beforeDeleteSchedule': function (e) {
            console.log('beforeDeleteSchedule', e);
            //cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
        }`

**Comment by jungeun-cho** [comment]
Do you want to know where the source code is in to insert your custom logic?

Would it help to look at event hooks in [Docs](https://nhn.github.io/tui.calendar/latest/Calendar#event-afterRenderSchedule)?
