### ISSUE TITLE
Is possible to disabled drag highlight box?

### ISSUE THREAD

**Issue by ayophanz** [nhn/tui.calendar#505]
## Current Behavior

```js
// Write example code
```

**Comment by jungeun-cho** [comment]
Can you write more specifically?
Do you want to prevent drag events?

**Comment by ayophanz** [comment]
> Do you want to prevent drag events?

 yes

**Comment by jungeun-cho** [comment]
Do you want to prevent modification of the date of the schedule?
Then try the `isReadOnly` option.

https://nhn.github.io/tui.calendar/latest/Options
https://nhn.github.io/tui.calendar/latest/Schedule

We can apply to the whole calendar
It can also be applied to individual schedules.
