### ISSUE TITLE
Month wrog grouping

### ISSUE THREAD

**Issue by Edsol** [nhn/tui.calendar#508]
## Version
latest

## Development Environment
Firefox dev-edition on debian 10

## Current Behavior

I generate simple calendar with month view:

```js
  var calendar = new tui.Calendar('#calendar', {
    isReadOnly: true,
    defaultView: 'month',
    taskView: true,
    week: {
      daynames: ['Domenica','Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato'],
    },
  });
```

and create event from json data, loaded with createSchedules() func:
```json
{"id":14,"category":"allday","calendarId":"1","isReadOnly":true,"start":"2019-07-06T00:00:00+00:00","color":"#fff","title":"FE143HV","body":"Scadenza"},{"id":16,"category":"allday","calendarId":"1","isReadOnly":true,"start":"2020-01-09T00:00:00+00:00","color":"#fff","title":"FE182XC","body":"Scadenza"}
```

![immagine](https://user-images.githubusercontent.com/19670024/74319065-a18fdf00-4d7e-11ea-9d0d-cf98a987c69f.png)

why do you group events? how can I view events individually as examples:

![immagine](https://user-images.githubusercontent.com/19670024/74319207-d56b0480-4d7e-11ea-8765-2630f1ee5294.png)

**Comment by jungeun-cho** [comment]
The schedule data you created is the same as `calendarId: "1"`.

https://nhn.github.io/tui.calendar/latest/Schedule

Can you assign values ​​to the `color`, `bgColor`, `BgColor` and `border Color` properties when creating a schedule?
