### ISSUE TITLE
add element to popup

### ISSUE THREAD

**Issue by davide86** [nhn/tui.calendar#509]
hi, i want to know if there is a way to add element to standard popup like number and email.

and how i can save to scheduled event

thank you

**Comment by jungeun-cho** [comment]
You can check a guide document in [getting-started.md#customize-popups](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups).

Check out the link below
api
https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules
https://nhn.github.io/tui.calendar/latest/Calendar#updateSchedule
https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule
https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeUpdateSchedule

example
https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic

source code
https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js
