### ISSUE TITLE
How to customise create/edit Schedule popup style and position

### ISSUE THREAD

**Issue by Anzil-Aufait** [nhn/tui.calendar#510]
## Version
Latest Version 

## Expected Behavior

I want to add new elements schedule popup also want to change position from right to left popup and styling .

**Comment by jungeun-cho** [comment]
You can check a guide document in [getting-started.md#customize-popups](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups).

**Comment by Anzil-Aufait** [comment]
Thank you for your replay.

I'm using **`custom schedule popup`** , how can i save and update the calendar with new data ??

**Comment by jungeun-cho** [comment]
Check out the API
https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules
https://nhn.github.io/tui.calendar/latest/Calendar#updateSchedule

Source code used in the [example](https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic).

https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js

**Comment by Anzil-Aufait** [comment]
@jungeun-cho , on **`clickSchedule`** I'm showing my custom popUp for schedule details. 

Is there any option to set that popup position for correspond schedule(date) position. 

This is the [**demo**](https://codepen.io/AnzilkhaN/pen/GRJqPVK?editors=0110).

**Comment by jungeun-cho** [comment]
@Anzil-Aufait 
Sorry!
In the schedule click event handler, [you can get the schedule element](https://nhn.github.io/tui.calendar/latest/Calendar#getElement) and then position it with `getBoundingClientRect()`.

```js
calendar.on('clickSchedule', function(e) {
  const { calendarId, id } = e.schedule;
  const el = cal.getElement(id, calendarId);

  console.log(e, el.getBoundingClientRect());
});
```
