### ISSUE TITLE
How to show calendarInfo data on calendar schedules

### ISSUE THREAD

**Issue by Anzil-Aufait** [nhn/tui.calendar#512]
## Version

Latest Version

## Expected Behavior

How can i show **`CalendarInfo`** in this **Schedule data** :

```
var schedules = [
            {id: 489273, title: 'Workout for 2020-04-05', isAllDay: false, start: '2020-02-01T11:30:00+09:00', end: '2020-02-01T12:00:00+09:00', goingDuration: 30, comingDuration: 30, color: '#ffffff', isVisible: true, bgColor: '#69BB2D', dragBgColor: '#69BB2D', borderColor: '#69BB2D', calendarId: 'Post', category: 'time', dueDateClass: '', customStyle: 'cursor: default;', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''},
            {id: 18073, title: 'completed with blocks', isAllDay: false, start: '2020-02-17T09:00:00+09:00', end: '2020-02-17T10:00:00+09:00', color: '#ffffff', isVisible: true, bgColor: '#54B8CC', dragBgColor: '#54B8CC', borderColor: '#54B8CC', calendarId: 'Event', category: 'time', dueDateClass: '', customStyle: '', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''}
        ];
```

On your example 
[(https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic)](https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic)

You used chance.js to create dummy data , but i'm using above data for **`schedules`** . 

I want to some schedule data on calendar with calendar info

**Comment by jungeun-cho** [comment]
Do you want to display calendar data on a calendar?

https://nhn.github.io/tui.calendar/latest/Template

Using an optional `template` property, you will need to match the `calendarId` with the list of calendars used at the service code level.

**Comment by Anzil-Aufait** [comment]
thank you for the response.
Can you please show me any example ??

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month

Can you write in detail what you want?
Do you want to display calendar information in your schedules?

Can I get a [codesandebox](https://codesandbox.io/), [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io/) link to reproduce?

**Comment by Anzil-Aufait** [comment]
I  want to display calendar information on my schedules , with above data.

![image](https://user-images.githubusercontent.com/49673771/74634628-44cf6280-518a-11ea-91f5-52caf6090a4e.png)

Above image , schedules is on load image. That Schedules don't have calendar info, like ::

> calendar: CalendarInfo {id: "2", name: "Company", checked: true, color: "#ffffff", bgColor: "#00a9ff", …}


![image](https://user-images.githubusercontent.com/49673771/74635019-261d9b80-518b-11ea-89f5-dcf9d048b86a.png)

Above image is after create schedule with calendarIfo data. 

I'm showing **`clickSchedule`** modal based on schedule event name. 

So, i can't show my **`clickSchedule`** popup on load, because there is no calendar event.

**Comment by Anzil-Aufait** [comment]
@jungeun-cho , here is a [demo](https://codepen.io/AnzilkhaN/pen/MWweZGp?editors=0010) .

Please open 2nd tab.

**Comment by jungeun-cho** [comment]
@Anzil-Aufait 
First of all, when creating a schedule, the calendarId value should be '2' instead of 'Post'.

You put calendar's name in the `calendarId` value.

You have to enter calendar's id.

And when you create a schedule, you specify the properties `bgColor`, `dragBgColor`, `borderColor`, and `color` so that they will be rendered in the color you specify.

If you want to calendar's color, exclude the properties(`bgColor`, `dragBgColor`, `borderColor`, and `color`) when creating schedules.

**Comment by Anzil-Aufait** [comment]
@jungeun-cho,  When creating a schedule it's working fine. That's not my issue.

Showing CaendarInfo on load is my issue. I want add this data :: 

`

> calendar: CalendarInfo {id: "7", name: "Birthdays", checked: true, color: "#ffffff", bgColor: "#ffbb3b", …}

`

on my **`schedules`** data for **`setSchedules()`** function.

**Comment by jungeun-cho** [comment]
Did you change the `calendarId` of schedule in `setSchedules()`?
change 'Post' to '1' and change 'Events' to '2'.


```js
 var schedules = [
            {id: 489273, title: 'Workout for 2020-04-05', isAllDay: false, start: '2020-02-01T11:30:00+09:00', end: '2020-02-01T12:00:00+09:00', goingDuration: 30, comingDuration: 30, color: '#ffffff', isVisible: true, bgColor: '#69BB2D', dragBgColor: '#69BB2D', borderColor: '#69BB2D', calendarId: '1', category: 'time', dueDateClass: '', customStyle: 'cursor: default;', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''},
            {id: 18073, title: 'completed with blocks', isAllDay: false, start: '2020-02-17T09:00:00+09:00', end: '2020-02-17T10:00:00+09:00', color: '#ffffff', isVisible: true, bgColor: '#54B8CC', dragBgColor: '#54B8CC', borderColor: '#54B8CC', calendarId: '2', category: 'time', dueDateClass: '', customStyle: '', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''}
        ];
...
```
Don't see calendarInfo in clickSchedule event hook?
![스크린샷 2020-02-19 16 12 23](https://user-images.githubusercontent.com/43128697/74810445-bc3ff600-5332-11ea-8a8c-0f89a687e1d8.png)

Do you want to add new calendar?
```js
    calendar = new CalendarInfo();
    id += 1;
    calendar.id = String(id);
    calendar.name = 'Birthdays';
    calendar.color = '#ffffff';
    calendar.bgColor = '#ffbb3b';
    calendar.dragBgColor = '#ffbb3b';
    calendar.borderColor = '#ffbb3b';
    addCalendar(calendar);
```

**Comment by jungeun-cho** [comment]
Do you want to display Calendar List?
![스크린샷 2020-02-19 15 57 26](https://user-images.githubusercontent.com/43128697/74811142-3f158080-5334-11ea-92ea-5ba7cc1e32d8.png)

or
Do you want to display shchedule title with calendar info?
![스크린샷 2020-02-19 16 00 14](https://user-images.githubusercontent.com/43128697/74811147-4046ad80-5334-11ea-9201-2b7a1c30b2bb.png)

**Comment by Anzil-Aufait** [comment]
> Did you change the `calendarId` of schedule in `setSchedules()`?
> change 'Post' to '1' and change 'Events' to '2'.
> 
> ```js
>  var schedules = [
>             {id: 489273, title: 'Workout for 2020-04-05', isAllDay: false, start: '2020-02-01T11:30:00+09:00', end: '2020-02-01T12:00:00+09:00', goingDuration: 30, comingDuration: 30, color: '#ffffff', isVisible: true, bgColor: '#69BB2D', dragBgColor: '#69BB2D', borderColor: '#69BB2D', calendarId: '1', category: 'time', dueDateClass: '', customStyle: 'cursor: default;', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''},
>             {id: 18073, title: 'completed with blocks', isAllDay: false, start: '2020-02-17T09:00:00+09:00', end: '2020-02-17T10:00:00+09:00', color: '#ffffff', isVisible: true, bgColor: '#54B8CC', dragBgColor: '#54B8CC', borderColor: '#54B8CC', calendarId: '2', category: 'time', dueDateClass: '', customStyle: '', isPending: false, isFocused: false, isReadOnly: false, isPrivate: false, location: '', attendees: '', recurrenceRule: '', state: ''}
>         ];
> ...
> ```
> 
> Don't see calendarInfo in clickSchedule event hook?
> ![스크린샷 2020-02-19 16 12 23](https://user-images.githubusercontent.com/43128697/74810445-bc3ff600-5332-11ea-8a8c-0f89a687e1d8.png)
> 
> Do you want to add new calendar?
> 
> ```js
>     calendar = new CalendarInfo();
>     id += 1;
>     calendar.id = String(id);
>     calendar.name = 'Birthdays';
>     calendar.color = '#ffffff';
>     calendar.bgColor = '#ffbb3b';
>     calendar.dragBgColor = '#ffbb3b';
>     calendar.borderColor = '#ffbb3b';
>     addCalendar(calendar);
> ```

@jungeun-cho , Thank yo for the quick replay. I made the changes. 

 But when use custom **`useDetailPopup`** the **`calenderInfo`** not showing , It's only showing when using default **`useDetailPopup`**. 

Here is the **[demo](https://codepen.io/AnzilkhaN/pen/GRJqPVK?editors=0110)** with changes & custom **`useDetailPopup`** .

I'm showing different **`clickSchedule`** popUp based on the **`calendarInfo event name`** .

**Comment by Anzil-Aufait** [comment]
> want to display shchedule title with calendar info

Yes i want to display shchedule title with calendar info.

**Comment by Anzil-Aufait** [comment]
> Do you want to display Calendar List?
> ![스크린샷 2020-02-19 15 57 26](https://user-images.githubusercontent.com/43128697/74811142-3f158080-5334-11ea-92ea-5ba7cc1e32d8.png)
> 
> or
> Do you want to display shchedule title with calendar info?
> ![스크린샷 2020-02-19 16 00 14](https://user-images.githubusercontent.com/43128697/74811147-4046ad80-5334-11ea-9201-2b7a1c30b2bb.png)

Yes , I want to display shchedule title with calendar info.

**Comment by jungeun-cho** [comment]
@Anzil-Aufait 
I understand.
This is the bug. 😭 
They have to pass calendar Info for clickSchedule event hook.

**Comment by jungeun-cho** [comment]
To  display schedule title with calendar info, use template.
```js
const cal = new Calendar('#cal', {
  ...
  template: {
    time: function(schedule) {
      return `${schedule.title}`; // just example,  check schedule data, match the calendarId
    },
  }
...
```
https://nhn.github.io/tui.calendar/latest/Template
https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month

**Comment by Anzil-Aufait** [comment]
> @Anzil-Aufait
> I understand.
> This is the bug. 😭
> They have to pass calendar Info for clickSchedule event hook.

@jungeun-cho Finally. 

I'm showing popUp based on the **`event.name`**. When will this fix ??

**Comment by jungeun-cho** [comment]
@Anzil-Aufait 
Oh, I'm sorry. I was mistaken.

The calendar information will be removed from the `clickSchedule` event hook when using the default popup provided by default.

The TOAST UI Calendar focuses on schedules, and calendar data only uses color information.

In your service code level, use `schedule.calendarId` to match your `CalendarList`.

![스크린샷 2020-02-19 17 47 07](https://user-images.githubusercontent.com/43128697/74817574-75f19380-5340-11ea-82cd-45410c481e0b.png)

**Comment by Anzil-Aufait** [comment]
> @Anzil-Aufait
> Oh, I'm sorry. I was mistaken.
> 
> The passed `calendar` data will be removed from the `clickSchedule` event hook when using the default popup provided by default.
> 
> The TOAST UI Calendar focuses on schedules, and calendar data only uses color information.
> 
> In your service code level, use `schedule.calendarId` to match your `CalendarList`.
> 
> ![스크린샷 2020-02-19 17 47 07](https://user-images.githubusercontent.com/43128697/74817574-75f19380-5340-11ea-82cd-45410c481e0b.png)

@jungeun-cho , Thank you for the replay. 

Now I'm showing **`clickschedule`** based on `**schedule.calendarId**`. And it;s working fine. 

But there is one more problem , how can i show **`shchedule`** with **`calendarIfo`** color's like color, bgColor, borderColor . Like your in this example  [https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month](https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month)

Here is the changed [**demo**](https://codepen.io/AnzilkhaN/pen/GRJqPVK?editors=0110) . 

Thank you.

**Comment by jungeun-cho** [comment]
@Anzil-Aufait 
What's the problem?
```js
calendar = new CalendarInfo();
calendar.id = '3';
calendar.name = 'Offer';
calendar.color = '#578E1C';
calendar.bgColor = '#EEF8F0';
calendar.dragBgColor = '#EEF8F0';
calendar.borderColor = '#EEF8F0';
```
![스크린샷 2020-02-20 11 18 47](https://user-images.githubusercontent.com/43128697/74894649-f4971100-53d2-11ea-9c4d-89264bce1966.png)

**Comment by Anzil-Aufait** [comment]
@jungeun-cho 

Problem is there is no **`bgColor or color`** for when showing schedules onLoad. 

**`This is the style onLoad ::`**

![image](https://user-images.githubusercontent.com/49673771/74899665-9ca4de00-53c3-11ea-9b09-2bf591b4c8c4.png)

And this is the schedule when i add 3 different schedules with different Schedule type :: 

![image](https://user-images.githubusercontent.com/49673771/74899812-e8f01e00-53c3-11ea-820b-1d75aa85d213.png)


**When i add Schedules clicking on calendar the schedule bgColor, color and borderColor are adding.**

**Comment by jungeun-cho** [comment]
Is this what you want?

![스크린샷 2020-02-20 14 56 28](https://user-images.githubusercontent.com/43128697/74905394-6b430700-53f1-11ea-90a4-d31544d40bfb.png)


In the monthly view, it is displayed like that for an all-day schedule.
When creating schedule data, set `category = 'allday'` (in `beforeCreateSchedule` event hook on your code)

**Comment by Anzil-Aufait** [comment]
> Is this what you want?
> 
> ![스크린샷 2020-02-20 14 56 28](https://user-images.githubusercontent.com/43128697/74905394-6b430700-53f1-11ea-90a4-d31544d40bfb.png)
> 
> In the monthly view, it is displayed like that for an all-day schedule.
> When creating schedule data, set `category = 'allday'` (in `beforeCreateSchedule` event hook on your code)

@jungeun-cho , Thank you very much it's work fine.
