### ISSUE TITLE
Uncaught TypeError: options.month.scheduleFilter is not a function

### ISSUE THREAD

**Issue by xhemajlbytyqi** [nhn/tui.calendar#517]
## Current Behavior

I have an error that is 'scheduleFilter is not function' when I click more, this error was not before.
So the line  **return options.month.scheduleFilter(item.model);**

```
    // binding +n click schedule
    clickHandler.on('clickMore', function(clickMoreSchedule) {
        var date = clickMoreSchedule.date,
            target = clickMoreSchedule.target,
            schedules = util.pick(baseController.findByDateRange(
                datetime.start(date),
                datetime.end(date)
            ), clickMoreSchedule.ymd);

        schedules.items = util.filter(schedules.items, function(item) {
            return options.month.scheduleFilter(item.model);
        });

        if (schedules && schedules.length) {
            moreView.render(getViewModelForMoreLayer(date, target, schedules, monthView.options.daynames));

            schedules.each(function(scheduleViewModel) {
                if (scheduleViewModel) {
                    /**
                     * @event More#afterRenderSchedule
                     */
                    monthView.fire('afterRenderSchedule', {schedule: scheduleViewModel.model});
                }
            });

            monthView.fire('clickMore', {
                date: clickMoreSchedule.date,
                target: moreView.getMoreViewElement()
            });
        }
    });
```

**Comment by jungeun-cho** [comment]
This issue was caused by the `month` option when creating a calendar instance.
This had only occurred on v1.12.10.
Can you check  installed version again?

**Comment by xhemajlbytyqi** [comment]
@jungeun-cho yes I checked again, This is my currently version  tui-calendar@1.12.7

**Comment by jungeun-cho** [comment]
Can I get a [codesandebox](https://codesandbox.io/), [jsfiddle](https://jsfiddle.net/), [codepen](https://codepen.io/) link to reproduce?

example)
https://codesandbox.io/s/tuicalendar-31hm5

**Comment by bel-mont** [comment]
> This issue was caused by the `month` option when creating a calendar instance.
> This had only occurred on v1.12.10.
> Can you check installed version again?

Can you be more specific? I'm having the same issue with v1.12.10, exact same line
`return options.month.scheduleFilter(item.model);`
I'm using the vue wrapper
`<calendar style="height: 800px;" :view="'month'" :schedules="scheduleList" :usage-statistics="false" ref="calendarEl" :is-read-only="true" :template="template" />`
My schedule list is an array of objects with nothing of note, just plain data.
My template is
```
template: {
          // The template is specified because otherwise, nothing is being shown.
          schedule: function(schedule) {
            return schedule.title;
          }
        }
```

**Comment by bel-mont** [comment]
I don't really know why this was not working in the first place, but for now I managed to add an override for the month object.
I added this option to my vue component
`:month="monthOverride"`
And I defined the function  in that object.
```
monthOverride: {
          scheduleFilter: function(schedule) {
            return Boolean(schedule.isVisible);
          }
        }
```
Which I got from the code in the calendar script, in line 18964 of https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js.
There were other places where the function is defined (like in line 9074), but that one seemed to work the best for me, since nothing would show up if I used the other functions.

**Comment by jungeun-cho** [comment]
@bel-mont 
Use v1.12.11.

Do you use cdn in your project environment?
This is the [vue wrapper sample code](https://codesandbox.io/s/toast-ui-calendar-for-view-wrapper-pvgks).

**Comment by bel-mont** [comment]
Yes, I've been using a CDN. I'd prefer to use NPM only. but my current environment does not support it in a fully integrated manner.

Also, thanks. I switched to v1.12.11 and everything works fine. I got rid of my workarounds, and after rearranging some code everything works as expected.
