### ISSUE TITLE
Unable to update Raw content in schedule

### ISSUE THREAD

**Issue by harikesh409** [nhn/tui.calendar#518]
## Version
1.2.11

## Development Environment
**Browser**: Google Chrome
**OS**: Windows 10

## Current Behavior
Only the default options are updated but the elements in the `raw` are not getting updated. I am using the below code to update the schedule that is present.

```js
var schedule = {
    title: title,
    raw: {
        project,
        client,
        task,
        activity,
        duration,
        comments
    }
};
cal.updateSchedule(id, '1', schedule);
```

**Comment by Raketten1963** [comment]
This issue seem to be back in 1.15

**Comment by adhrinae** [comment]
@Raketten1963 
Could you provide me with an example to reproduce the problem?
I've tested and it seems working for me.

**Comment by Raketten1963** [comment]
Sorry for above, I found my mistake....

**Comment by adhrinae** [comment]
@Raketten1963 
That's fine :)
Glad to hear that it's working.

**Comment by Raketten1963** [comment]
Thanks @adhrinae - you are doing an amazing project, I am blown away with it....
