### ISSUE TITLE
How to activate 'body' use ? (display 'body' to popupdetail for example)

### ISSUE THREAD

**Issue by ph25** [nhn/tui.calendar#532]
Hello,
i just begin in using tui Calendar and i want to use 'body' information (input 'body' in popupdetail for example)
But i don't found how to activate this.
I found nothing in documentation or examples...

Thanks.

**Comment by alanmrochadeveloper** [comment]
On your calendar instantiation, inside template declaration insert this function:  
popupDetailBody: function (schedule) {
                    return 'body here : ' + schedule.body;
                }
when you open up the popupDetail it will be there. I hope i helped you!
I don't know if i can help others. If not, please delete my post.

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/Template
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

```js
const el = document.getElementById('app');
const cal = new Calendar(el, {
    useCreationPopup: false,
    useDetailPopup: true,
...
});

// event handlers
cal.on({
    'clickSchedule': function(e) {
        console.log('clickSchedule', e);
    },
    'beforeCreateSchedule': function(e) {
        console.log('beforeCreateSchedule', e);
        /*
           Show the input form controls you have customized.

           const {start, end} = e; // You can use start and end dates.
        */

        /*
          If you dont' want to show any popup, just use `e.guide.clearGuideElement()`
          then close guide element(blue box from dragging or clicking days)
        */
        e.guide.clearGuideElement();
    },
    'beforeUpdateSchedule': function(e) {
        console.log('beforeUpdateSchedule', e);
        
       /* Also, Show the your form controls */
        e.schedule.start = e.start;
        e.schedule.end = e.end;

        /* then call updateSchedule method */
        cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
    },
    'beforeDeleteSchedule': function(e) {
        console.log('beforeDeleteSchedule', e);
        cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
    }
});
```

**Comment by ph25** [comment]
It's ok for DetailPopup, thanks.
But how activate 'body' in CreationPopup ?

**Comment by jungeun-cho** [comment]
not planned yet.

If you need it urgently,
Fork the repository You can modify the handlebar file.
https://github.com/nhn/tui.calendar/tree/master/src/js/view/template/popup

**Comment by ph25** [comment]
Ok. 
Thanks.

**Comment by Avinodh** [comment]
@jungeun-cho - I  am using TUI Calendar in my app, and had the same question - is there an easy way to enable the "Body" input field for the Event Creation pop-up? If forking is the only option, I can do that, but would appreciate an easier solution of one exists.

Thank you! 

P.S: This is an incredible product, and it's been really easy to integrate into my application.

**Comment by adhrinae** [comment]
@Avinodh 

Still, you need to fork the project for customizing popups.

For more info, check [the discussion](https://github.com/nhn/tui.calendar/discussions/941).

**Comment by Avinodh** [comment]
@adhrinae Thanks for pointing me to the discussion, the two options described there seem feasible with some effort. 

+1 to the suggestion regarding adding a way to dynamically customize the content of pops using flags of sorts in the next major version! Thanks again for your continued efforts in building this great calendar!
