### ISSUE TITLE
category: 'time' style same as category: 'allday'

### ISSUE THREAD

**Issue by Anzil-Aufait** [nhn/tui.calendar#534]
## Version
New verson

## Expected Behavior
Is there any option for setting **`category: 'time'`**  style  same as **`category: 'allday'`** .

Now there is no bgColor, borderColor and color for , when setting **`category: 'time'`** for schedule.

I want set schedule **`category`** as **`time`** with same as **`category: 'allday'`**.

**Comment by jungeun-cho** [comment]
Can you write your requirements in detail?

On **monthly view** and **weekly view**,
How to display all day schedule(`category='allday'`) and time schedule(`category='time'`) is different.

### monthly view
<img width="911" alt="스크린샷 2020-03-06 13 00 12" src="https://user-images.githubusercontent.com/43128697/76050341-7037b700-5faa-11ea-895e-fbe574e1ec6f.png">

### weekly view
<img width="927" alt="스크린샷 2020-03-06 12 31 30" src="https://user-images.githubusercontent.com/43128697/76047722-04a01a80-5fa7-11ea-9cbe-eb766bc444e4.png">

**Comment by Anzil-Aufait** [comment]
@jungeun-cho , Thank you for the replay.

Currently i'm using all day **`schedule (category='allday')`** . But I want to show schedule according to time so I changes to time **`schedule(category='time')`** , then it's work fine. 

But the style changes on **`schedule(category='time')`**, there is no `bgColor, borderColor and color`  for schedule item. 

This is the [**demo**](https://codepen.io/AnzilkhaN/full/GRJqPVK) . There is two **`schedule(category='time')`** items.

**Comment by jungeun-cho** [comment]
Not planned yet.

You can modify it as follows,
This is not a normal use.

---
You can use `customStyle` of schedule data.
 
Use style overrides
```css
.tui-full-calendar-weekday-schedule-bullet {
  display: none;
}

.tui-full-calendar-weekday-schedule-title {
  color: inherit !important;
}
```

```js
function saveNewSchedule(scheduleData) {
  ...
  const schedule = {
    ...
   // use customStyle
    customStyle: `background-color: ${calendar.bgColor}; color: ${calendar.color};`
  };
  cal.createSchedules([schedule]);
...
}
```
https://codesandbox.io/s/tuicalendar-using-custom-style-chx4c

**Comment by Anzil-Aufait** [comment]
@jungeun-cho , Thank you for the replay. 

It's work fine.
