### ISSUE TITLE
monthly 모드에서 입력한 Title이 길어서 줄바뀜이 생길때 백그라운드 컬러적용 범위

### ISSUE THREAD

**Issue by kanggeol** [nhn/tui.calendar#535]
타이틀 내용이 길어서 여러줄이 될 때, 백그라운드 컬러 적용 범위를 여러줄에 적용가능한지 문의드려요. 

아래 이미지는 CSS에서 height 항목을 껐을때 입니다.
![monthly](https://user-images.githubusercontent.com/27131537/75965270-e76a3e00-5f0b-11ea-8e97-30f0dce3c06b.jpg)

어떻게 해야할까요??

**Comment by dongsik-yoo** [comment]
I have a question. What is your To-Be? What do you mean that `background-color` can be applied to multiple lines?

**Comment by kanggeol** [comment]
> I have a question. What is your To-Be? What do you mean that `background-color` can be applied to multiple lines?

타이틀이 1줄이면 배경색 1줄, 타이틀이 2줄이 되면(입력내용이 길어져서) 배경색도 2줄..
현재는 위 이미지처럼 나오지 않고, 아래와 같습니다.
![attach1](https://user-images.githubusercontent.com/27131537/76051473-41bbdb00-5fae-11ea-8099-283f6e13299b.jpg)

**Comment by jungeun-cho** [comment]
There is no support plan.
