### ISSUE TITLE
[UI error][Monthly View] Overlapped when schedule 2 starts 1 day before schedule 1 ends

### ISSUE THREAD

**Issue by brosbunbo** [nhn/tui.calendar#539]
## Describe the bug
As the title, please check below screenshots:

## To Reproduce
"tui-calendar": "^1.12.9"

1. UI ok:
  - Schedule 1: 2020-02-21 00:00:00 ~ 2020-02-28 00:00:00
  - Schedule 2: 2020-02-26 00:00:00 ~ 2020-02-29 00:00:00

2. UI error:
  - Schedule 1: 2020-02-21 00:00:00 ~ 2020-02-28 00:00:00
  - Schedule 2: 2020-02-27 00:00:00 ~ 2020-02-29 00:00:00

## Expected behavior
UI in screenshot 2 should not be overlapped

## Screenshots
1. UI ok:
![UI_ok](https://user-images.githubusercontent.com/4328195/76588148-98369580-6529-11ea-8177-3d948384939c.png)

2. UI error:
![UI_error](https://user-images.githubusercontent.com/4328195/76588150-9cfb4980-6529-11ea-9fbd-1e1799255258.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 18.0
 - Browser: Chrome
 - Version: 80

Thanks and Best Regards,

**Comment by jungeun-cho** [comment]
@brosbunbo 
We reproduced.
That's a bug.
We will make a plan and fix it.

**Comment by jungeun-cho** [comment]
@brosbunbo 

Is it being reproduced?
I tried to fix it today but it doesn't reproduce

https://codesandbox.io/s/tuicalendar-issue-539-0mwdt?file=/src/index.js

---
Can you tell me the link to the source code to be reproduced?

**Comment by brosbunbo** [comment]
@jungeun-cho 
Please try this data with your above sandbox:
```
const schedules = [
  {
    bgColor:"#4b89dc",
    borderColor:"#a1b56c",
    calendarId:6,
    category:"time",
    color:"white",
    dragBgColor:"#a1b56c",
    dueDateClass:"",
    id:2,
    isAllDay:0,
    title:"22222",
    start: '2020-02-21 00:00:00',
    end: '2020-02-28 00:00:00',
  },
  {
    bgColor:"#4b89dc",
    borderColor:"#a1b56c",
    calendarId:6,
    category:"time",
    color:"white",
    dragBgColor:"#a1b56c",
    dueDateClass:"",
    id:1,
    isAllDay:0,
    title:"1111",
    start: '2020-02-27 00:00:00',
    end: '2020-02-29 00:00:00'
  }
]
```
