### ISSUE TITLE
Has dynamic height option?

### ISSUE THREAD

**Issue by quantrpeter** [nhn/tui.calendar#541]
Hi 
   Has dynamic height option? auto adjust the height by detecting number of event in a day?
Thanks
Peter

**Comment by jungeun-cho** [comment]
Keep the issue template.
And would you describe your requirements in detail?
Monthly or weekly view ...

The monthly view is adjusted according to **the height of the calendar container**, and if the schedule increases, you can check it with more view.

The weekly view can be specified by setting the `theme` option.
```js
const cal = new tuiCalendar(el, {
  defaultView: "week",
  theme: {
    'week.timegridOneHour.height': '100px',
    'week.timegridHalfHour.height': '50px',
```

**Comment by quantrpeter** [comment]
@jungeun-cho  thanks a lot
