### ISSUE TITLE
How can I fire event when I click any day in "month" view ?

### ISSUE THREAD

**Issue by Exorcismus** [nhn/tui.calendar#542]
My request is simple, I need to fire an event when I click on any day, for example print the day clicked, but am not sure how to do that
![image](https://user-images.githubusercontent.com/5602496/76711203-73534580-6716-11ea-8c54-f0d153af6c9a.png)

**Comment by jungeun-cho** [comment]
@Exorcismus 
You can the `clickSchedule` event.
https://nhn.github.io/tui.calendar/latest/Calendar#event-clickSchedule

**Comment by Exorcismus** [comment]
I opted to use `beforeCreateSchedule` but now I can't dis-select the chosen day, is there away to keep toggling the selected day ?

**Comment by enessayaci** [comment]
There is not a clear explanation in docs about this, I cant still a way to get notified by an event when I click a day in month view
