### ISSUE TITLE
default Popup adding new elements patternized. 

### ISSUE THREAD

**Issue by alanmrochadeveloper** [nhn/tui.calendar#543]
Hello, I have a question, since I couldn't find anything matching this, I want to use default popup, but add new elements following its pattern, something like, inside popup create HTML we got ".tui-full-calendar-popup .tui-full-calendar-popup-container .tui-full-calendar-popup-section", popup is composed(divided) per sections('tui-full-calendar-popup-section'), how to add it by using built-in tui-calendar methods? if there isn't any built-in function for that, what about to create such method, which we could, add as many sections as we need, like, function addNewSection: return ´<span>inner html here<span>´ inside the sections?!. I brought this question cuz i like ur popup style and want to keep it, instead of creating a new one in something like  "swetalert2" which is good too.

**Comment by jungeun-cho** [comment]
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

You can open your modal(like sweetalert) in `beforeCreateSchedule` event hook.

**Comment by alanmrochadeveloper** [comment]
> event hook



> https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups
> 
> You can open your modal(like sweetalert) in `beforeCreateSchedule` event hook.

it's not crystal clear for me since beforeCreateSchedule is fired when you already have your Default Popup open, could you please give some example.
