### ISSUE TITLE
 Hide edit and delete button

### ISSUE THREAD

**Issue by iris0301** [nhn/tui.calendar#546]
Is there anyway to hide edit and delete button in popdetail?
I tried to set the schedule be readonly, but then I was not allowed the drag the schedule. I want to drag that and show the popdetail without edit and delete button.

**Comment by jungeun-cho** [comment]
It occurs in the weekly view.
(It works correctly in monthly view)
The `end` is changed by dragging.

The resize icon should not be displayed when the schedule is `isReadOnly = true`.
It will be fixed in the next patch version.

**Comment by iris0301** [comment]
I mean is there any way to remove edit and delete button in popdetail? Cuz in readonly mode, it doesn’t allowed me to drag the schedule. I want drag and resize function without delete and edit button in popdetail.

**Comment by jungeun-cho** [comment]
I understand. When it is readonly, it is disable draggable.

**Comment by jungeun-cho** [comment]
Do you want a custom template?
Fundamentally
In read-only mode, the schedule cannot be dragged or modified

**Comment by kukko** [comment]
Is there any mode to hide the edit or delete buttons? Because there are cases when I have to hide the delete button but have to show the edit button. With the template parameter I can change the text on those buttons, but I can't hide them.

The`isReadOnly` attribute is not enough because I would like to use the time modification with drag.

**Comment by pvllmr** [comment]
@kukko 
I made it work this way.
```
document.getElementById("calendar").addEventListener("click", hideButtons);
function hideButtons(){
    var buttons = document.getElementsByClassName("tui-full-calendar-section-button")[0];
    if(buttons){
        buttons.style.display = "none";
    }
}
```

The class name of the deleteButton is "tui-full-calendar-popup-delete" and the edit button analogously. The vertical line can be accessed via the class name "tui-full-calendar-popup-vertical-line".

**Comment by JonathanStevanka143** [comment]
Bump, can you guys PLEASE incorporate something to fix this.... setting "readonly" does not work. Please allow us to set a bool so we can show/hide the detail buttons easily.....

**Comment by JonathanStevanka143** [comment]
If anyone has this same issue, just hardcode the CSS in the style on whatever page you are showing the calendar on etc.
This is the section that holds the 'Edit | Delete' Button.

`.toastui-calendar-section-button {
        display: none!important;
    }`
