### ISSUE TITLE
How to make text in calendar detail popup selectable

### ISSUE THREAD

**Issue by supertrip86** [nhn/tui.calendar#549]
Hi everyone,
I was wondering how to make the text inside the Detail Popup of the calendar selectable. I have been digging around a little, but couldn't find any rule preventing user from selecting the text, such as user-select: none in CSS.
So, what it's making the trick? How can I enable text select in Detail Popup?

**Comment by jungeun-cho** [comment]
I think users will be uncomfortable.

So, I'm trying to improve this.

It's related to mouse event action. Internally, we do not use drag and drop apis(e.g. dragstart, drop...) when creating and deleting schedules, we deal with them as mouse events(e.g. mousemove, mousedown...).

In addition to the mouse events for clicking the schedule (to see the schedule details) and creating schedule,
we are going to debug more about the basic mouse behavior.

**Comment by supertrip86** [comment]
I think it can be handy for users to be able to select the text of at least one or two areas of the detail popup. Sometimes they might want to share externally some of those data, such as titles or locations, for example via email
