### ISSUE TITLE
Is there an API for filtering calendars in the side pane

### ISSUE THREAD

**Issue by sergeymelkumyan** [nhn/tui.calendar#550]
In this [example](https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic
) there is seperate section (pane) for turning on/off the calendars to be shown in the right pane. Please advice how can be this accomplished, is there an API?

**Comment by jungeun-cho** [comment]
This is the script file used in the example file.
https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js#L336

You can use `toggleSchedules`.
https://nhn.github.io/tui.calendar/latest/Calendar#toggleSchedules
