### ISSUE TITLE
Clarify if tui-calendar 1.12 can work with tui-code-snippet 2.2

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#551]
Calling
```
yarn init
yarn add tui-calendar
yarn list
```
prints
```
yarn list v1.22.4
├─ tui-calendar@1.12.12
│  ├─ tui-code-snippet@^1.5.0
│  ├─ tui-code-snippet@1.5.2
│  ├─ tui-date-picker@^4.0.2
│  └─ tui-time-picker@^2.0.1
├─ tui-code-snippet@2.3.1
├─ tui-date-picker@4.0.3
│  ├─ tui-code-snippet@^2.2.0
│  └─ tui-time-picker@^2.0.3
└─ tui-time-picker@2.0.3
   └─ tui-code-snippet@^2.2.0
```

As you see, tui-code-snippet in istalled once under proj-dir/node_modules/tui-calendar/node_modules/tui-code-snippet (1.5.2) and once under proj-dir/node_modules/tui-code-snippet (2.2.0).

I think tui-calendar/package.json should be told, that it can work also with tui-code-snippet 2.2.0, so that the javascript package manager does not have to install two versions of tui-code-snippet.   

Whether tui-calendar can work with tui-code-snippet 2.2.0 I do not know.

As can be seen at https://github.com/twbs/bootstrap/blob/v4-dev/package.json, peerDependencies contains "jquery": "1.9.1 - 3", and devDependencies contains "jquery": "^3.4.1".

My understanding is that this means:
- if jquery 2 is available before bootstrap 4 is installed, then use jquery 2
- otherwise install jquery 3
But my understanding is also, that peerDependency amends dependencies and has nothing to do with devDependencies.

In anycase, please verify if tui-calendar can work with tui-code-snippet 2.2. and if it can and if tui-code-snippet can be used by date-picker, time-picker, and tui-calendar, then do not install two versions of tui-code-snippet (1.5 and 2.2.)

**Comment by jungeun-cho** [comment]
Migration is required to use tui-code-snippet 2.x in tui-calendar version 1.x.
We're going to fix this in Calendar 2.0.

**Comment by dilyanpalauzov** [comment]
My reading is that tui-calendar 1.x does not work with tui-code-snippet 2.x.

**Comment by jungeun-cho** [comment]
@dilyanpalauzov 

The dependency of tui-code-snippet on tui-date-picker and tui-time-picker will be removed.

Because it is distributed as a bundle, it is no longer a dependency

**Comment by dilyanpalauzov** [comment]
I do not understand what wil be distributed as bundle.

Note that feat/2.0 currently it is not distributed as ES6-file-module-bundle, but as several files.  @toast-ui/date is also not distributed as bundle.  Of the latter the  `package.json` contains "module": "src/" and there are four files.

**Comment by jungeun-cho** [comment]
tui-code-snippet is a utility code defragmentation.
As mentioned before, migration is required to use tui-code-snippet 2.x version in current calendar version 1.x. (No work yet)

---

You said two versions of tui-code-snippet were installed.
That's right, but tui-date-picker and tui-time-picker will be improved.

The tui-code-snippet will be moved from dependency to **devDependency** in tui-time-picker and tui-date-picker that use tui-code-snippet as a dependency.

Then the calendar will be installed only one version of tui-code-snippet.
