### ISSUE TITLE
Example does not aling to TypeScript definitions: class Calendar.constructor

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#558]
When I go to https://nhn.github.io/tui.calendar/latest/Calendar under Examples I see `var calendar = new tui.Calendar(document.getElementById('calendar'), {`.  In TypeScript document.getElementById returns `HTMLElement | null`, but in tui-calendar/index.d.ts is written
```typescript
export default class Calendar {
   constructor(container: Element | string, options?: IOptions);
}
```
tsc says `Element|null` is not compatible to `HTMLElement|string`: null is not assignable.

Either correct the example, or the interface.

**Comment by jungeun-cho** [comment]
It is not a bug, so there is no need to fix it.

In the TypeScript compiler, the return value of `document.getElementById` and` document.querySelector` may be `null`.

so

```ts
const el = document.getElementById ("app")!; // use Non-null assertion operator
```
or

```ts
const el = document.getElementById ("app");

if (el) { // check element
  ...
}
```
