### ISSUE TITLE
Clarify dependency on tui.dom/v3.0.0

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#561]
README.md contains:
```
## 🔩 Dependency

* [tui-code-snippet](https://github.com/nhn/tui.code-snippet) >= 1.5.0  
* [tui-date-picker](https://github.com/nhn/tui.date-picker) >= 4.0.2 is optional.
* [tui-time-picker](https://github.com/nhn/tui.time-picker) >= 2.0.1 is optional.
```
• Why do the examples contain ` <script src="https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js"></script>`, if it is not a dependency?
• Write < 2 for tui-code-snippet, to clarify that the newer code-snippet are not compatible

**Comment by jungeun-cho** [comment]
The code snippet version is fixed to v1.5.2 in the cdn, and tui-dom 3.0 is not required.
It will be removed from the example HTML file.
