### ISSUE TITLE
is there anyway to remove the busy button and all day check box. on pop up ?

### ISSUE THREAD

**Issue by Krucht** [nhn/tui.calendar#562]
![image](https://user-images.githubusercontent.com/63386501/78858183-d1ddbc00-7a55-11ea-9822-bbc3a3099595.png)
 i want to remove the busy and check box

**Comment by jungeun-cho** [comment]
1) Fork this repository so you can use the handlebar template.
https://github.com/nhn/tui.calendar/blob/master/src/js/view/template/popup/scheduleCreationPopup.hbs
or
2) You can use your custom popup.
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#templatecustomize-ui

**Comment by Krucht** [comment]
thank you for the fast response. is there anyway to add another input box  text like Location and Subject ? i tried the second option to use a costume pop up. but still kinda having a problem on where should I put the code.

**Comment by sam551875** [comment]
Hi, Krucht

You can put the code in here.
https://github.com/nhn/tui.calendar/blob/master/dist/tui-calendar.js

![Github_Placeholder](https://user-images.githubusercontent.com/51784878/78863520-5dfade00-7a6c-11ea-85ce-f809f1140804.PNG)

After you change the _string_, you will see the effects in pop up.

It works for me, hope it helps you as well.

**Comment by jungeun-cho** [comment]
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

You can use `beforeCreateSchedule` event hook.

After opening your custom popup, you can add a schedule using `cal.createSchedule`.
(https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules)


```js
var cal = new Calendar('#calendar', {
    useCreationPopup: false,
    useDetailPopup: false,
...
});

// event handlers
cal.on({
    'clickSchedule': function(e) {
        console.log('clickSchedule', e);
    },
    'beforeCreateSchedule': function(e) {
        console.log('beforeCreateSchedule', e);
        // You can write your code here :)
        // open a creation popup

        // If you dont' want to show any popup, just use `e.guide.clearGuideElement()`

        // then close guide element(blue box from dragging or clicking days)
        e.guide.clearGuideElement();
    },
    'beforeUpdateSchedule': function(e) {
        console.log('beforeUpdateSchedule', e);
        e.schedule.start = e.start;
        e.schedule.end = e.end;
        cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
    },
    'beforeDeleteSchedule': function(e) {
        console.log('beforeDeleteSchedule', e);
        cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
    }
});
```

**Comment by Krucht** [comment]
Thank you @jungeun-cho finally managed to do it

**Comment by dongsik-yoo** [comment]
There is some request about creation popup and detail popup of an event, but it's still a default functionality which is everyone can add their own. The default popup can only be customizable as we are intended.

**Comment by Volmarg** [comment]
```js
    /**
     * @description will modify the creation popup by watch for parent dom element and on the moment that children are
     *              added it will attempt to find the popup elements and modify them
     */
    private modifyScheduleCreationPopup(): void
    {
        let parentWrapperObserver = new MutationObserver( (mutations) => {
            $('.tui-full-calendar-section-allday').addClass('d-none');
            $('.tui-full-calendar-section-state').addClass('d-none');
        })

        let htmlDomElement = document.querySelector('.tui-full-calendar-floating-layer');
        parentWrapperObserver.observe(htmlDomElement, {
            childList: true,
        })
    }
```

The elements cannot be removed as the errors are thrown.
