### ISSUE TITLE
스케쥴이 영역을 벗어날경우 'more' 또는 '+'로 표시 되지 않고 그냥 전체를 표출하는 옵션은 없나요?

### ISSUE THREAD

**Issue by junekume** [nhn/tui.calendar#572]
If your schedule is out of range, isn't there an option to just express the entire schedule without 'more' or '+'?

Please reply to me

Please refer to the image of the link below.
https://drive.google.com/file/d/1IJbUgIW1YeoCuQLFnEZDx1KloZIK5GaI/view?usp=sharing

스케쥴이 ROW(갯수)가 영역을 벗어날경우 'more' 또는 '+'로 표시 되지 않고 그냥 전체 스케쥴을 표출하는 옵션은 없을까요?

답변부탁드립니다 (__)

**Comment by jungeun-cho** [comment]
This feature is not yet supported.

**Comment by KimGenius** [comment]
This feature fix not yet?
