### ISSUE TITLE
Toast-UI Calendar with CDN lacking functionalities

### ISSUE THREAD

**Issue by alishaz-polymath** [nhn/tui.calendar#573]
Hello, I was trying to work with Toast UI calendar. I tried to use it via CDN which requires us to insert the following:
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css" />
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.css" />
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.css" />

<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script src="https://uicdn.toast.com/tui.dom/v3.0.0/tui-dom.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>  

When I tried to create a calendar in my .html file, I noticed that it lacked a few functions such as date-picker, render-range, or even the event scheduler pop-up. Not only the functions, but they didn't even show up properly on the window(prev,next buttons were empty spaces). 
I also noticed that you mentioned 'tui-code-snippet' as a dependency for this calendar: https://github.com/nhn/tui.calendar#-dependency
However, I'm not sure what to include from the tui-code-snippet exactly, as there are a bunch of functions in there and you state that we should only import the functions we need from it: https://github.com/nhn/tui.code-snippet#-usage

I simply need to use the calendar with its scheduling functionality and a few views(monthly, weekly and daily). Please advise how I can get it done.

Kind regards,
Syed Ali Shahbaz

**Comment by alishaz-polymath** [comment]
Hi, I just wanted to provide an update on this.
I have tried to include the tui-code-snippet as well:
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
Which only helped in rendering the calender in the .html page, however, the functionalities were all still missing.

**Comment by jungeun-cho** [comment]
check.
https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html

Can you give me a reproducible link?

**Comment by alishaz-polymath** [comment]
Hi,
here's the link. I simply followed the instructions provided for a simple .html page using CDN links (unless I misunderstood the steps).
https://alishaz.com/test/tui-calendar

> check.
> https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html

Sure thing, I'll check it out.  Thanks. In the mean time, if you can confirm whether I was on the wrong path or if something is missing in the link I provided, please let me know.
I simply want to create a monthly view calendar with default pop-ups of event-scheduling capabilities.

**Comment by alishaz-polymath** [comment]
> 
> 
> check.
> https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
> 
> Can you give me a reproducible link?

Hi,
I updated the page in accordance with the example provided. There are still a couple of things missing. I am not worried about the CSS not showing button icons, etc. but  the "renderRange" is not showing up, and the buttons(prev-next) are not changing the calendar month in this case. In the example file, it does that, however, in my case, it doesn't. What am I missing here?


Thanks for your help!

**Comment by alishaz-polymath** [comment]
Hi, 
I noticed many functions described in the app.js file which complement what I plan to use with the calendar, like scheduling as well as the basic functions of prev-next and the render-date function.
I can import the necessary functions from app.js to get the job done now. Thank you for looking into this, and thanks for this fantastic open-source plugin. Really appreciate it!
