### ISSUE TITLE
examples: no class="render-range"

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#574]
examples/*.html contains: ` <span id="renderRange" class="render-range"></span>` but `render-range` is nowhere defined.

**Comment by jungeun-cho** [comment]
So what's the problem?

**Comment by dilyanpalauzov** [comment]
This is useless code that makes understanding the examples harder.

**Comment by jungeun-cho** [comment]
No support for example files is provided.

You can modify and use it as needed.

I hope you raise an issue with the calendar library itself.
