### ISSUE TITLE
Ignore days number and focus on week days (Monday, Tuesday, etc...)

### ISSUE THREAD

**Issue by hadi4172** [nhn/tui.calendar#575]
## Summary
is it possible to configure the calendar to be only from Monday to Sunday in recurrence (so ignore the days)?

## Screenshots
Something like this
![image](https://user-images.githubusercontent.com/59520451/79707270-ec036f80-8289-11ea-9138-c5fdd2077d78.png)

Thanks.

**Comment by jungeun-cho** [comment]
When instantiating a calendar, you can use the `template` and` theme` values ​​as options.
e.g. https://codesandbox.io/s/tuicalendar-issue-575-o9xh3
```js
const cal = new tuiCalendar(el, {
  defaultView: "week",
  taskView: false,
  scheduleView: ["time"],
  template: {
    weekDayname: function(model) {
      return `<span class="tui-full-calendar-dayname-date">
        </span>&nbsp;&nbsp;<span class="tui-full-calendar-dayname-name">
        ${model.dayName}</span>`;
    }
  },
  theme: {
    "week.dayname.textAlign": "center"
  },
  ...
});
```
