### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by titoff002** [nhn/tui.calendar#580]
Good evening,

I have a display problem.

![image](https://user-images.githubusercontent.com/24948237/80036153-7ef21300-84f1-11ea-8d3a-7ba53a5133d8.png)

How to make sure that the calendar does not overflow on the right area (circled in yellow)? because in my case, it supersoses my menu.

thank you

**Comment by jungeun-cho** [comment]
Check the style code of the container in which the calendar is rendered.

Adjusting the layout is what you do in your code.
