### ISSUE TITLE
Hello, please reply.

### ISSUE THREAD

**Issue by junekume** [nhn/tui.calendar#586]
https://drive.google.com/file/d/11sVFGwdUWs59jNBDcQ1GzkWhpzqoJ6TU/view?usp=sharing

If there are many long schedules like the picture of the attached link, the calendar screen is not good to see.
I'd like to show you a short schedule first, is there any way?

첨부한 링크의 그림처럼 긴일정이 많을경우 달력화면이 보기 좋지않아
짧은 스케쥴부터 우선으로 보여주고 싶은데 방법이 없을까요?

**Comment by jungeun-cho** [comment]
@junekume 
The TUI calendar has rules for rendering schedules.
The longest schedule is rendered first.
