### ISSUE TITLE
Is there any example on how to use the schedule from my own database? instead of Random?

### ISSUE THREAD

**Issue by Krucht** [nhn/tui.calendar#597]
![image](https://user-images.githubusercontent.com/63386501/80672123-01706900-8ad6-11ea-8f3b-78e6e78df3ea.png)

is there anyway to use my own database? so i don't need generate random schedule ? any help would be appreciated

**Comment by jungeun-cho** [comment]
@Krucht 
Load your schedule data stored in your database and call `createSchedules()` to add your schedule to the TUI calendar.

https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#create-schedules

**Comment by bennyatc** [comment]
Hi. 
I’m sorry but I don’t understand how connect my Laravel database to the calendar.

**Comment by bennyatc** [comment]
Any help for me?
Tks

**Comment by j-a-h-i-r** [comment]
Create an API on your laravel code. Then from you JS code, get the scheduler data from the laravel API endpoint. Use the `createSchedules()` method to create schedules from the API response.

**Comment by bennyatc** [comment]
Thank you for your reply.
Reading some replies I understood there is an automatic way to do it.
Best regards.
