### ISSUE TITLE
Display a time frame smaller than 24 hours

### ISSUE THREAD

**Issue by jadelukk** [nhn/tui.calendar#600]
Is it possible to display a time frame in the time grid which is smaller than 24 hours?
For: e.q.: I want to display a time frame: from 08:00- 18:00 instead of 01:00 - 23:00 how it is by default

**Comment by jungeun-cho** [comment]
@Vukajlovic 
You can specify the time range for the weekly view.
When creating a calendar instance, you can specify a range time as `week.hourStart` and `week.hourEnd` in the options.

```js
const cal = new Calendar(el, {
    defaultView: 'week',
    scheduleView: true,
   ...
    week: {
        hourStart: 7,
        hourEnd: 19
    }
});
```

**Comment by jadelukk** [comment]
Thank you, it worked!
