### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by bennyatc** [nhn/tui.calendar#606]
Hello.
I don't find how to set an Italian time format (00:00-24:00).

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the calendar you are currently using.

**Comment by jungeun-cho** [comment]
TUI Calendar provides callback function to change various types of templates.
I don't know exactly where you want to change the time format.

However, I hope the following will help you.

https://nhn.github.io/tui.calendar/latest/Template

Template Name | Description
-- | -- 
timegridDisplayPrimaryTime | The display label template function of primary timezone in time grid
timegridDisplayTime | The display time template function in time grid
timegridCurrentTime | The current time template function in time grid

https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid

**Comment by bennyatc** [comment]
Thank you for very fast and usefull answer.
