### ISSUE TITLE
Building out shifts on a week view without relying on the date portion

### ISSUE THREAD

**Issue by JadedEric** [nhn/tui.calendar#612]
## Summary
We are investigating tui-calendar as an option for a project that will highlight client working shifts, within the week view. Thus far, we have had to modify our dates to include the "date" portion of the shift times because there seem to be no way to render these on the grid without it.

Our client's shifts (a mine) run weekly, on exactly the same time frame, each day. If we are being forced to worry about the date portion, then this component will not work for us.

## Screenshots
![example](https://user-images.githubusercontent.com/1898304/82817540-73ea2400-9e9d-11ea-83d8-dbd75015d3dc.png)

An example of what we're trying to achieve.

## Version
v1.12.13

## Additional context
All we're trying to do is show shifts based on the hours, we don't care about the dates.

**Comment by jungeun-cho** [comment]
In the calendar, the entered event is displayed. Therefore, it will not automatically generate a schedule internally.

If you want to display the recurring schedule, you must enter the schedule manually.
