### ISSUE TITLE
Main example does not show source code?

### ISSUE THREAD

**Issue by harrellbm** [nhn/tui.calendar#613]
## Summary
I am having trouble finding a basic working example of a tui calendar.  I am working in node (more specifically electron).  And have not been able to figure out basic things like capturing input from popups, etc.  The biggest thing that would help is just being able to see the source code for the main example on your demo page.

## Screenshots
If applicable, add screenshots to help explain your quest

## Version
12.x

**Comment by dilyanpalauzov** [comment]
Check https://github.com/nhn/tui.calendar/tree/master/examples.

**Comment by harrellbm** [comment]
Awesome thank you!
