### ISSUE TITLE
Location value of default popup is always undefined

### ISSUE THREAD

**Issue by gayeon1025** [nhn/tui.calendar#615]
## Describe the bug
Location value of default popup is always undefined.
All of information was valid except **location** though I filled out all the inputs of default popup
## To Reproduce
1. Enable useCreationPopup option.
2. Fill out all the inputs of default popup
3. Check the log in the event listener function for beforeCreateSchedule
## Expected behavior
The value of location should not be undefined if you input location value.

## Screenshots
![](https://user-images.githubusercontent.com/33685994/83034948-c8df9300-a073-11ea-835e-1dc6a9aae25e.png)

## Desktop (please complete the following information):
 - OS: Mac OS X
 - Browser: chrome
 - Version 81.0.4044.138

**Comment by j-a-h-i-r** [comment]
Is this fix pushed to npm? I'm using tui-calendar `1.12.13` and still facing this bug
