### ISSUE TITLE
Question: how to enable "menu-navi" navigation?

### ISSUE THREAD

**Issue by atsepkov** [nhn/tui.calendar#620]
In every example of your calendar I see, you have a navigation bar at the top that can take the user between weeks/months, yet I wasn't able to find any way to enable it playing with options and looking at your docs. The only reference to it I see is some examples creating a div with id of "menu-navi", but I don't understand how it's hooked in back into the calendar? Thanks

**Comment by jungeun-cho** [comment]
I hope it helped you.

https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js
