### ISSUE TITLE
Undefined css class tui-full-calendar-weekday-schedule-focused

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#621]
[month/more.hbs:L47](https://github.com/nhn/tui.calendar/blob/master/src/js/view/template/month/more.hbs#L47) contains class `{{#if model.isFocused}}{{CSS_PREFIX}}weekday-schedule-focused {{/if}}`, but in [dist/tui-calendar.css](https://github.com/nhn/tui.calendar/blob/master/dist/tui-calendar.css) there is no `weekday-schedule-focused` for the class.

* Remove `{{#if model.isFocused}}{{CSS_PREFIX}}weekday-schedule-focused {{/if}}` from `month/more.hbs`.

**Comment by dilyanpalauzov** [comment]
* `{{CSS_PREFIX}}weekday-schedule-focused` is contained also twice in month/weekdayInMonthSchedule.hbs and once in week/dayGridSchedule.hbs. 

* week/time.hbs references class `{{CSS_PREFIX}}time-schedule`, but this class does not exist in dist/tui-calendar.css

**Comment by jungeun-cho** [comment]
It doesn't use that selector directly inside the source code, but there was a need to access and override css when using it on the client.

**Comment by dilyanpalauzov** [comment]
So, is this meant to permit the user do define a css-class or it was used in the past but is not used today?

**Comment by jungeun-cho** [comment]
Users can override the style with this selector.
