### ISSUE TITLE
Uncaught ReferenceError: Calendar is not defined

### ISSUE THREAD

**Issue by VamshiSeshasayan** [nhn/tui.calendar#631]
## Summary
Calendar UI is not rendered. There was an error "Uncaught ReferenceError: Calendar is not defined". I am using Laravel, NPM, Mix for compiling assets. 

The following is the code.
**HTML**
<div id="calendar" style="height: 800px;"></div>
**app.js**
var Calendar = require( 'tui-calendar' );
require( 'tui-code-snippet' );
**app.scss**

@import "~tui-calendar/dist/tui-calendar.css";
@import '~tui-date-picker/dist/tui-date-picker.css';
@import '~tui-time-picker/dist/tui-time-picker.css';

**Javascript**
<script type="text/javascript">
        var calendar = new Calendar('#calendar', {
            defaultView: 'month',
            taskView: true,
            template: {
                monthDayname: function(dayname) {
                    return '<span class="calendar-week-dayname-name">' + dayname.label + '</span>';
                }
            },
            month: {
                workweek: true // show only 5 days except for weekend
            }
        });
    </script>

## Version
I have installed the package using npm.
npm install --save tui-calendar

**Comment by jungeun-cho** [comment]
Can you give me a link that can be reproduced? (e.g. jsfiddle, codesandbox...)
https://codesandbox.io/s/toast-ui-calendar-basic-ppo2t

I want to know your front end development environment.
Do you use commonjs?

**Comment by shikhapathak6** [comment]
**Use tui.Calendar in place of Calendar**
<script type="text/javascript">
 var calendar = new tui.Calendar('#calendar', { 
defaultView: 'month', 
taskView: true, 
template: { 
monthDayname: function(dayname) 
{ return '' + dayname.label + ''; } 
},
 month:
 { workweek: true // show only 5 days except for weekend } }); 
</script>
