### ISSUE TITLE
how to get date  without template. 

### ISSUE THREAD

**Issue by oyaai** [nhn/tui.calendar#633]
Can i get date select without template popup. Please suggestion.  
Thank you. 

`      var getDate = cal.getDate();
      var toDate = cal.getDateRangeStart();
      var obj = cal.getElement("","");
      $(document).ready(function(){
        $('#calendar').click(function(event) {
          //var toDate = getDate.toDate();
          $.each(event, function(index, val) {
              //console.log(val.category);
              //alert(index + " =>"+val);
          });
          alert('date'+getDate+" || "+toDate);
        });
      });`

**Comment by jungeun-cho** [comment]
You can use [tui-time-picker](https://github.com/nhn/tui.time-picker) and [tui-data-picker](https://github.com/nhn/tui.date-picker).
