### ISSUE TITLE
ScheduleDetailPopup.prototype._getYAndArrowTop shall not return negative y

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#636]
When showing the detailSchedulePopup, the value for `top` CSS property is calculated in ScheduleDetailPopup.prototype._getYAndArrowTop.  When the function is called with parameters 389.5, 413.5, 680, 38, 638 it calculates `y = scheduleVerticalCenter - (layerHeight / 2) = 61.5`. Then `if (y + layerHeight > containerBottom)` matches and y=top is set to -80, instead of 0.

• Ensure that `ScheduleDetailPopup.prototype._getYAndArrowTop` does not set negative y, as this makes no sense - the hidden data cannot be displayed.

**Comment by jungeun-cho** [comment]
If `container Top` is 38 and `containerBottom` is 63, the height of the calendar container is 600.
If the height of the pop-up layer is 680, the layer overflows the calendar container.

It would overflow to the top or overflow to the bottom.

Currently it overflows to the top.

If y is 0, it will overflow to the bottom.

**Comment by dilyanpalauzov** [comment]
If it overflows to the bottom, users can scroll to see the content at the end.  When it overflows to the top (above the start of the browser window) users cannot scroll.

**Comment by jungeun-cho** [comment]
I understand. :)
