### ISSUE TITLE
What is a “Guide”?

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#637]
The source code of tui.calendar contains on several places “guide”-code.

Please explain what does this “guide” mean.

**Comment by jungeun-cho** [comment]
![schdule-guide](https://user-images.githubusercontent.com/43128697/85239072-e2a2a900-b46c-11ea-93e9-12773d84a2d4.png)

The guide will be used for tasks related to the blue squares and selection ring range times that appear when creating a schedule.

**Comment by dilyanpalauzov** [comment]
Thanks for your answer.  What do the moveguide and resizeguide do?
