### ISSUE TITLE
How to left and right side drag and drop enable for month view ?

### ISSUE THREAD

**Issue by vishal551** [nhn/tui.calendar#648]
I have some requirements but not fulfill by the toast UI calendar. 
Can you please help me out here?

1) how to enable drag and drop for calendar month view event?
2) How to event set for the full day color currently it displayed in thin line?

Please help me ASAP

**Comment by jungeun-cho** [comment]
1. `isReadOnly` attribute of schedule can be designated as `false`. (e.g.`schedule.isReadOnly = true`)
2. Set the category setting of the schedule to "allday". (e.g.`schedule.category: 'allday'`)
