### ISSUE TITLE
Repeating events

### ISSUE THREAD

**Issue by vsoch** [nhn/tui.calendar#649]
## Summary
Hey @nhn! This is another beautiful tool you've made that I just stumbled upon. I have a quick question - I'm looking for a calendar that supports repeating events, but not weekly/monthly, moreso something like:

> Repeat on the third Thursday of the month
> Repeat on the first Friday of the month

etc. Is there an example around here somewhere showing how that might work? I'm comparing against fullcalendar.js, which seems to have some limited support only with an additional plugin and lots of custom code, and I'm hoping there is a way to avoid that. Thank you!

**Comment by jungeun-cho** [comment]
@vsoch 
We are only responsible for rendering for the schedule entered by the user.
You will have to generate and include your repetitive schedules.

**Comment by vsoch** [comment]
Ok, many thanks!

**Comment by dongsik-yoo** [comment]
@vsoch There is no functionality that supports repeating events. In Dooray! using this calendar generates repeating events at their own codes based on recurrence rule. And Dooray! calls `createSchedules()`

**Comment by michael-mathieu** [comment]
> @vsoch There is no functionality that supports repeating events. In Dooray! using this calendar generates repeating events at their own codes based on recurrence rule. And Dooray! calls `createSchedules()`

do you confirm that in 2024, it is still not supported? I try to use the 'recurrenceRule' from EventObject, but my -basic- rule is ignored.
recurrenceRule: 'FREQ=DAILY;UNTIL=20241231'
