### ISSUE TITLE
tui.code-snippets@2.3.2 generates l.CustomEvents is undefined when inititalize calendar

### ISSUE THREAD

**Issue by si458** [nhn/tui.calendar#650]
## Describe the bug
```
Uncaught TypeError: l.CustomEvents is undefined
    <anonymous> view.js:212
    Webpack 12
```

## To Reproduce
Steps to reproduce the behaviour:
1. include version 2.3.2 of tui.code-snippet
2. initialize calendar

## Expected behaviour
expected calendar to initialize

## Desktop (please complete the following information):
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] ANY
 - Version [e.g. 22] ANY

## Additional context
i have tried git cloning and then `npm run bundle` (NOT CHANGING ANY FILES) and use the min.js file
i have also tried cloudflare cdnjs build too (https://cdnjs.cloudflare.com/ajax/libs/tui-code-snippet/2.3.2/tui-code-snippet.js)

**Comment by jungeun-cho** [comment]
You should use the tui code snippet version 1.5.2.

**Comment by si458** [comment]
Is the any reason why I can’t use any of the version 2 with the calendar? 
Can you maybe update the help guides/readme to show it only works with version 1.5.2?

**Comment by jungeun-cho** [comment]
README updated.

We officially offer **TOAST cloud CDN**.
https://github.com/nhn/tui.calendar#via-contents-delivery-network-cdn

```js
<script src="https://uicdn.toast.com/tui.code-snippet/v1.5.2/tui-code-snippet.min.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```
Migration is required to use tui.code-snippet 2.x.


No plans yet. (Calendar 1.x )

However, TOAST UI Calendar 2.0 is developing with code-snippet 2.x.
