### ISSUE TITLE
change an all-day schedule to a new single day failed.

### ISSUE THREAD

**Issue by lhysdl** [nhn/tui.calendar#657]
## Describe the bug

When change an all-day schedule to one day by setting the start-day and end-day to the same day,  the result is weird.
The "end day" value disappear.

## To Reproduce
1. Go to 'https://ui.toast.com/tui-calendar/'
2. Choose an all-day schedule, click edit.
3. Set the start date and the end date to be the same day, click save.
4. See the result

## Expected behavior
Should work like you create a new single day all-day schedule.

## Screenshots
![video](https://user-images.githubusercontent.com/4022718/87642448-2347c680-c77c-11ea-849c-ba7d636044f1.gif)

## Desktop (please complete the following information):
 - OS: mac cataLina 10.15.5
 - Browser chrome
 - Version 83.0.4103.116

**Comment by lhysdl** [comment]
I tracked code, It seems that the endDate will be converted to Lastday(23:59:59).
```js
ScheduleCreationPopup.prototype._getRangeDate = function(startDate, endDate, isAllDay) {
    if (isAllDay) {
        startDate.setHours(0, 0, 0);
        endDate = datetime.isStartOfDay(endDate) ?
            datetime.convertStartDayToLastDay(endDate) :
            endDate.setHours(23, 59, 59);
    }
}


convertStartDayToLastDay: function(d) {
        var date = new TZDate(d);
        if (datetime.isStartOfDay(d)) {
            date.setDate(date.getDate() - 1);
            date.setHours(23, 59, 59);
        }

        return date;
    },
```
If I set an one-day schedule with {startDate:7-15;endDate:7-15}, then it will be updated as {startDate:7-15;endDate:7-14} .

**Comment by jungeun-cho** [comment]
duplicated #646 
@lhysdl 
It will be fixed and released next week.

**Comment by lhysdl** [comment]
When will these fixes be released ?

**Comment by jungeun-cho** [comment]
I'm going to get another review and merge.
We have a schedule inside our team.

Deploy as early as this week,
Or maybe it will be early next week.
