### ISSUE TITLE
Can i get a guide element with method onClickSchedule ?

### ISSUE THREAD

**Issue by hieulhminh** [nhn/tui.calendar#658]
Hi, I use custom popup instead of default popup. How can i guess some property like top, left, width, etc.. when i clicked an existing schedule. Thank you

**Comment by jungeun-cho** [comment]
```js
    cal.on({
        'clickSchedule': function(e) {
            const {event, schedule} = e;
            const {id, calendarId} = e.schedule;

            const elSchedule = cal.getElement(id, calendarId);
            const scheduleRect = elSchedule.getBoundingClientRect();
            
            // TODO : Using the rect, you can position your popup.

        },
```

**Comment by hieulhminh** [comment]
> ```js
>     cal.on({
>         'clickSchedule': function(e) {
>             const {event, schedule} = e;
>             const {id, calendarId} = e.schedule;
> 
>             const elSchedule = cal.getElement(id, calendarId);
>             const scheduleRect = elSchedule.getBoundingClientRect();
>             
>             // TODO : Using the rect, you can position your popup.
> 
>         },
> ```

It's worked. Thank you
