### ISSUE TITLE
Schedule.prototype.setAllDayPeriod  logic

### ISSUE THREAD

**Issue by lhysdl** [nhn/tui.calendar#662]
## Summary
```js
Schedule.prototype.setAllDayPeriod = function(start, end) {
    // If it is an all-day schedule, only the date information of the string is used.
    if (util.isString(start)) {
        start = datetime.parse(start.substring(0, 10));
    } else {
        start = new TZDate(start || Date.now());
    }
    if (util.isString(end)) {
        end = datetime.parse(end.substring(0, 10));
    } else {
        end = new TZDate(end || this.start);
    }

    this.start = start;
    this.start.setHours(0, 0, 0);
    this.end = end || new TZDate(this.start);
    this.end.setHours(23, 59, 59);
};
```
I don't understand why to use ```if (util.isString(start)) {
        start = datetime.parse(start.substring(0, 10));
    } ``` to deal with string arg as a special case, because```new TZDate()```accept string arg.

in my case, I store start-date value as json date, for example ''2020-07-06T16:00:00.000Z'' (my timezone is +8)
 ```datetime.parse(start.substring(0, 10))```
will give me 2020-07-06 as the start-date, which is not what I want.
```new TZDate(start)```give me the right date which is 2020-07-07.

As summary,  ```datetime.parse(start.substring(0, 10))``` will not consider **timezone** like ```new TZDate(start)``` do, which lead to logical inconsistency.

## Version
1.12.13

**Comment by jungeun-cho** [comment]
I understand. It needs to be improved.

**Comment by lhysdl** [comment]
can I make a PR to fix it?

**Comment by jungeun-cho** [comment]
Of course.
