### ISSUE TITLE
Write in README.md the precise versions of the supported browsers

### ISSUE THREAD

**Issue by dilyanpalauzov** [nhn/tui.calendar#666]
Following https://github.com/nhn/tui.calendar/pull/618, write in README.md minimal versions of the supported browsers.  This shall make possible to determine, which JavaScript (and CSS) functions can be used directly without polyfills: Function.bind, Array.indexOf()…

**Comment by jungeun-cho** [comment]
This is our team's policy.
Except for ie, it will change all browsers to "latest".
