### ISSUE TITLE
How can I custom the timeGridSchedule component

### ISSUE THREAD

**Issue by qngnud** [nhn/tui.calendar#678]
## Summary
I want to custome the timeGridSchedule component, it's tui-full-calendar-time-schedule class

## Screenshots
The timeGridSchedule is shapes in the below screenshot
![image](https://user-images.githubusercontent.com/48669780/88532527-f5416c80-d02e-11ea-87e2-152d8981434c.png)

My expected:
![image](https://user-images.githubusercontent.com/48669780/88535097-90d4dc00-d033-11ea-979a-5fd1253630b3.png)

## Version
@toast-ui/react-calendar: "^1.0.5"

## Additional context
I tried all the template options of the docs but it doesn't help. Hope you reply soon, thanks!

**Comment by jungeun-cho** [comment]
What exactly do you want to do?

In the template, the things that can be changed in relation to the schedule are `time`, `milestone`,'allday','task','goingDuration', and'comingDuration'.

@toast-ui/react-calendar is just a tui-calendar wrapper, the timeGridSchedule React component  that you said doesn't exist.

**Comment by qngnud** [comment]
> What exactly do you want to do?
> 
> In the template, the things that can be changed in relation to the schedule are `time`, `milestone`, `allday`, `task`, `goingDuration`, and `comingDuration`.
> 
> @toast-ui/react-calendar is just a tui-calendar wrapper, the timeGridSchedule React component that you said doesn't exist.

Hi jungeun-cho, I just update my expected, I think that shapes is timegridSchedule because when I try to add themeConfig "week.timegridSchedule.borderRadius" so that shapes change border radius.

**Comment by jungeun-cho** [comment]
Not yet supported.
Since the style attribute of the schedule is inline, new features are needed.
Alternatively, there is a way to override the class and use it, but this is not recommended.

```css
      .tui-full-calendar-time-schedule {
        border: 5px solid #000 !important;
      }
```
