### ISSUE TITLE
How can I change content of template in .hbs file?

### ISSUE THREAD

**Issue by qngnud** [nhn/tui.calendar#684]
## Summary
Hi, I need to change some content of template to show on schedule. It's time.hbs file. It have a line of code is ```{{{time-tmpl model}}}```. I tried to find usages and found that helper.js can change content of those template. But when I tried to change function ```'time-tmpl``` in helper.js, nothing change. Can you show me where is it?

## Screenshots
I want to modify this
```{{{time-tmpl model}}}```
![image](https://user-images.githubusercontent.com/48669780/88693754-dffd3880-d129-11ea-841f-e38ab720310d.png)
```'time-tmpl'```
![image](https://user-images.githubusercontent.com/48669780/88693850-fd320700-d129-11ea-80f8-cb1a7430bfb5.png)

## Version
v1.12.13

**Comment by dilyanpalauzov** [comment]
Check the templates.time option:

https://nhn.github.io/tui.calendar/latest/Template
