### ISSUE TITLE
How can I display schedule property in time.hbs file?

### ISSUE THREAD

**Issue by qngnud** [nhn/tui.calendar#685]
## Summary
I need to add more information about schedule right in the schedule shape, don't need to click to view detail of that schedule. How can I do it? I tried using model but it's only have the model.title property!

## Screenshots
![image](https://user-images.githubusercontent.com/48669780/88817202-6d529280-d1e7-11ea-8a00-a60437736a2a.png)

## Version
v1.12.13

## Additional context
Thanks for your help!

**Comment by jungeun-cho** [comment]
not planned yet
