### ISSUE TITLE
Trigger custom popup when selecting multiple days

### ISSUE THREAD

**Issue by zedy** [nhn/tui.calendar#689]
Hi,

I'm making a month view calendar and am using custom popups for making/deleting/editing schedules. This works fine when I click on any day, but it's not working when i click-drag to select multiple days (on month view). 

It was working with default popup, but not with custom.

Here's my code:

```
const Cal = new Calendar('#calendar', {
    usageStatistics: false,
    defaultView: 'month',
    useCreationPopup: false,
    month: {
        startDayOfWeek: 1,
        isAlways6Week: false,
        workweek: false,
    }
});

Cal.on({
    'beforeCreateSchedule': function(e) {
        $modal.triggerPopup('open'); // just calls the popup
    }
});
```

**Comment by jungeun-cho** [comment]
Please give me a [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/) link to reproduce your problem.
