### ISSUE TITLE
Disable dragging without isReadOnly=true

### ISSUE THREAD

**Issue by pvllmr** [nhn/tui.calendar#691]
Is it possible to disable dragging and resizing of Schedules without having to set isReadOnly to true?
I use "beforeCreateSchedule" to be able to change from month to day view by clicking on a day. Therefore I need the calendar to be writable.

**Comment by jungeun-cho** [comment]
The `isReadOnly` option was related updating(e.g. dragging, resizing...) of Schedule.
Did you set `useCreationPopup` to `false`?
And you are using `beforeCreateSchedule` for other purposes. so you have to attach the form to fill out the schedule.
