### ISSUE TITLE
Increase number of schedules in a day

### ISSUE THREAD

**Issue by dariusz-hub** [nhn/tui.calendar#692]
Is it possible to achieve such an effect that all meetings are displayed and the line height is calculated automatically?

actual
![Screenshot_2020-07-29](https://user-images.githubusercontent.com/53866006/88811544-fac9be80-d1b6-11ea-9896-986fdf8b37fd.png)

expected
![unknown](https://user-images.githubusercontent.com/53866006/88810643-ecc76e00-d1b5-11ea-8036-c8d5f2f70b32.png)

**Comment by jungeun-cho** [comment]
Not planned yet.
