### ISSUE TITLE
Can you set a schedule programmatically?

### ISSUE THREAD

**Issue by mspanish** [nhn/tui.calendar#694]
This looks very interesting, but I can't find any info about setting a schedule from database programmatically rather than via the UI (in this case the user will be choosing classes so they should be filled in via the database and not by the user. I need the events to be recurring too, not on specific dates, just days of week.

**Comment by jungeun-cho** [comment]
1) setting a schedule from database programmatically
A. TOAST UI Calendar doesn't deal with data directly. It just renders the entered schedule to the UI.
     You can fetch data(e.g. from database) on your project and call [`cal.createSchedule()`](https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules).
<br>
2) I need the events to be recurring.
A. You can create repetitive data and then put them into your calendar.
