### ISSUE TITLE
Undefined location

### ISSUE THREAD

**Issue by gabor2mbeauty** [nhn/tui.calendar#698]
## Describe the bug
Schedule doesnt save the location.

## To Reproduce
Intuitive:
Try to add location in the Schedule Popup

## Solve
tui-calendar.js:20565 _onClickCreateSchedule:

> this.fire('beforeCreateSchedule', {  
>         calendarId: form.calendarId,  
>         title: form.title.value,  
>         location: location.value,  
>         raw: {  
>             class: form.isPrivate ? 'private' : 'public'  
>         },  
>         start: form.start,  
>         end: form.end,  
>         isAllDay: form.isAllDay,  
>         state: form.state    
>     });

The _onClickCreateSchedule function 'form' parameter seems fine, change line 20568 to 
`location: form.location.value,`

**Comment by jungeun-cho** [comment]
https://github.com/nhn/tui.calendar/pull/616
It has already been worked on.
It will be released in v1.12.14
