### ISSUE TITLE
How to access the class TZDate in a browser environment?

### ISSUE THREAD

**Issue by tiliev** [nhn/tui.calendar#703]
To access the `Calendar` class (as described [here](https://nhn.github.io/tui.calendar/latest/Calendar)) in a browser environment, your docs suggest we should use
```
var Calendar = tui.Calendar;
```
This works as expected.

But how to access the class `TZDate` (as described [here](https://nhn.github.io/tui.calendar/latest/TZDate)) in a browser environment?

I am struggling to convert JS Dates to your format.

**Comment by jungeun-cho** [comment]
The `TZData` class is not exported externally. Refer to the [file](https://github.com/nhn/tui.calendar/blob/v1.12.14/src/js/common/timezone.js) if necessary.

In Calendar 2.0, we plan to use [toast-ui.date](https://github.com/nhn/toast-ui.date) instead of using TZDate.
