### ISSUE TITLE
Week schedule does not get smaller than 20 minutes

### ISSUE THREAD

**Issue by ifrancesalcantara** [nhn/tui.calendar#706]
I am introducing time schedules to a week view calendar depending on an interval, but when the interval gets smaller than 20 minutes it seems like it reaches a little more than the end date. For example:

1 hour interval
![image](https://user-images.githubusercontent.com/56117446/96861531-83799300-1464-11eb-9a4b-2ee48ce20097.png)

20 minute interval
![image](https://user-images.githubusercontent.com/56117446/96860064-99865400-1462-11eb-8168-cc2e0b60515f.png)

15 minute interval
![image](https://user-images.githubusercontent.com/56117446/96860150-b28f0500-1462-11eb-9657-880f63a47184.png)

5 minute interval
![image](https://user-images.githubusercontent.com/56117446/96859422-c71ecd80-1461-11eb-92f4-4e1a55609d2d.png)

**Comment by jungeun-cho** [comment]
The minimum of a schedule time is set to 20 minutes.
It would be nice if it should be calculated based on the height value per hour of the time grid.
We plan to include this feature in Calendar 2.0.
