### ISSUE TITLE
Date Selector on Calendar Not Formatting Correctly

### ISSUE THREAD

**Issue by UnitedBagels** [nhn/tui.calendar#707]
## Describe the bug

When creating a new schedule box, the formatting for the date selector does not render properly.

## To Reproduce

1. Installed Toast-UI React calendar v. 1.0.5 with npm
2. Added calendar component to webpage
3. Click on an empty section of the calendar

## Expected behavior

The date selector should function and have the proper formatting.

## Screenshots

![image](https://user-images.githubusercontent.com/23223619/97091200-27e80a80-1608-11eb-8e7c-58c33e641f80.png)

## Desktop (please complete the following information):

- OS: Windows 10 (npm on WSL)
- Browser: Chrome 86.0.4240.111
- Version: (from package.json) toast-ui/react-calendar 1.0.5

## Additional context

I'm not sure if this is a global issue or specific to my project. Any guidance would be greatly appreciated.

**Comment by jungeun-cho** [comment]
https://codesandbox.io/s/toast-uireact-calendar-82fi9
Have you imported the date picker and time picker stylesheets?
```js
import "tui-date-picker/dist/tui-date-picker.css";
import "tui-time-picker/dist/tui-time-picker.css";
```

Did you check the message in your console log?
