### ISSUE TITLE
dayGrid click event problem When don't use popup.

### ISSUE THREAD

**Issue by sjpark0513** [nhn/tui.calendar#712]
## Summary
The clickschedule not working correctly. after I click daygrid with no popupwindow option in Monthly view. 
and the highlight doesn't disappear when click other day on daygrid.  
The monthly example on this site work equally with my Project.
How can I clear highlight and clickevent work correctly.

## Screenshots
If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/73677490/97651414-497d4200-1a9f-11eb-89b3-78f99ed1f903.png)

## Version
@version 1.12.13

**Comment by jungeun-cho** [comment]
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups

```js
```
