### ISSUE TITLE
Posting data that ends up in calendar. 

### ISSUE THREAD

**Issue by dadweiss** [nhn/tui.calendar#713]
I’ve read the docs. I use MySQL. Terascript as middleware. I can select  data, And render it for viewing, update and delete. I have an events table. I want to select, format assign to the proper variable and the load the calendar. 

Using tui charts I see in their example how to select data format it and assign it to a var and render a chart

I’m look for something similar in calendar.so I can select data from MySQL and format it, assign it to a proper variable and get a calendar 

Then hopefully figure out how events are trapped when an event is drawn on the calendar and is sent to the dB

Thank you for your kind help

Mark Weiss. 
435-373-6363
Dmark.weiss@icloud.com

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the calendar you are currently using.

**Comment by dilyanpalauzov** [comment]
Talking about MySQL and databases here is out of scope.  In the examples directory there are examples you can use to start.  These examples describe what and how tui.calendar is supposed to do.

**Comment by dadweiss** [comment]
1) If the examples were clear about data format as they are in Tui charts I wouldn’t have reached out for help.

2)  I contacted the developer and he said to reach out here. 

3) this is not a question about accessing MySQL, I can do that without outside assistance.

4) It is about where to find in the docs how data is to be formatted  

5) tui charts and other charting offerings are clear about the formatting  of data that the software needs to consume to display properly. 

If someone would be so kind as to point out what I am missing In the docs I can mostly take it from there. 

Thank you.

**Comment by dilyanpalauzov** [comment]
As I do not use TUI Charts, so I cannot compare with it to answer your question.  Data can be: start of schedule, start of month, start of day in a particular TZ, location, calendar name, date cell, month days.  I even do not know whether the answer of your question is in css or in JavaScript.

**Comment by dilyanpalauzov** [comment]
> tui charts and other charting offerings are clear about the formatting of data that the software needs to consume to display properly. The calendar offering is not quite as clear to me.

Can you provide an example, where the display in TUI calendar is done improperly?

**Comment by jungeun-cho** [comment]
If you fetch the schedule data from your database, you can render the schedule to the calendar using the [`createSchedules`](https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules) api.
You can also use api like [`deleteSchedule`](https://nhn.github.io/tui.calendar/latest/Calendar#deleteSchedule), [`updateSchedule`](https://nhn.github.io/tui.calendar/latest/Calendar#updateSchedule).

If you want to check the type of a schedule object, click [here](https://nhn.github.io/tui.calendar/latest/Schedule).

The description of the event callback function is [here](https://nhn.github.io/tui.calendar/latest/Calendar#event-afterRenderSchedule).

The following is a calendar example and code attached.

https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic
https://github.com/nhn/tui.calendar/tree/master/examples
