### ISSUE TITLE
Calendar rendering issues.

### ISSUE THREAD

**Issue by VoHoTv** [nhn/tui.calendar#714]
## Describe the bug
When I create the following shipments there is a gap in the bar from the 20th to 24th october and it shows "1 more" while there is only one shipment for that date (see screenshot).

```
calendar.createSchedules([
    {
        id: 11035,
        calendarId: "1",
        category: "time",
        title: "Vendor 1",
        start: "2020-10-04",
        end: "2020-10-19",
    },
    {
        id: 11036,
        calendarId: "1",
        category: "time",
        title: "Vendor 3",
        start: "2020-10-04",
        end: "2020-10-19",
    },
    {
        id: 11039,
        calendarId: "1",
        category: "time",
        title: "Vendor 4",
        start: "2020-10-04",
        end: "2020-10-19",
    },
    {
        id: 11030,
        calendarId: "1",
        category: "time",
        title: "Vendor 4",
        start: "2020-10-13",
        end: "2020-10-27",
    },
]);

```

![0924e42d6492eddc594dbf122e26f761](https://user-images.githubusercontent.com/58689798/97805270-5e033b00-1c55-11eb-9b43-182400d70e7c.png)

## To Reproduce
1. Create the shipments shown above.

## Expected behavior
The expected behavior is that there is no gap and no "1 more" since there is only 1 shipment on that date.

**Comment by jungeun-cho** [comment]
```js
```
