### ISSUE TITLE
Doesn't keyboard addEventListener support? The beforeCreateSchedule function only works for mouse events.

### ISSUE THREAD

**Issue by iblesoy** [nhn/tui.calendar#715]
## Summary
Doesn't keyboard addEventListener support?
The beforeCreateSchedule function only works for mouse events.

## Version
@version 1.12.14

## Additional context
To improve web accessibility, we want to be able to navigate the date with the keyboard.
I added a button tag using templete, but I couldn't find a way to call the'beforeCreateSchedule' function for the button as a keyboard event.
Is there a way?

**Comment by jungeun-cho** [comment]
Not planned yet
