### ISSUE TITLE
How do i disable or remove 'Milestone', 'Task' & 'All day'?

### ISSUE THREAD

**Issue by TheEvilTomat0** [nhn/tui.calendar#716]
Hi,

How can i disable or remove the milestone task & all day bar?

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/Options
```js
const cal = new tui.Calendar('#calendar', {
  defaultView: 'week', // set 'week' or 'day'
  taskView: false,  // e.g. true, false, or ['task', 'milestone']
  scheduleView: ['time'] // e.g. true, false, or ['allday', 'time']
});
```

**Comment by TheEvilTomat0** [comment]
Ah thank you, this works!

**Comment by sameerauf1** [comment]
Hi, I was looking at the solution provided by @jungeun-cho  I attempted to remove the task view by setting `taskView: false` in the options, but the task list is still being displayed. I would like to completely remove the milestone, task, and all-day categories. Here is the relevant portion of my code:

```javascript
const options = {
    defaultView: 'day', // Change to 'week' view
    taskView: false,      // Disable task view
    milestoneView: false,  // Disable milestone view
    scheduleView: ['time'], // Enable only the time-based schedule view, you can adjust this array based on your needs

    // ... other options
};

**Comment by eddelymy** [comment]
how can i hide Monday on the calendar toast

**Comment by horprogs** [comment]
If someone else is looking for an actual way how to hide Milestones, Tasks and All day, here what you need to include in the settings:

```
week: {
        taskView: false,
        eventView: ['time'],
}
```

https://github.com/nhn/tui.calendar/blob/calendar%402.1.3/docs/en/apis/options.md#weekeventview
