### ISSUE TITLE
Event Handlers

### ISSUE THREAD

**Issue by FroggyJuul** [nhn/tui.calendar#717]
## Version
1.12.14
## Development Environment
Chrome, MacOS

## Current Behavior

When clicking on an empty time slot the edit schedule dialog closes and the create schedule dialog is opened.

I have created my own custom popups but do not see which events are called to trigger the above actions.

I have placed console.log commands in the events in app.js from the distribution but none of these are called.

Are there more event handlers that I am missing or do I need to call a function in tui-calendar.js?

// Write example code

 // event handlers
    cal.on({
        'clickMore': function(e) {
            console.log('clickMore', e);
        },
        'clickSchedule': function(e) {
            console.log('clickSchedule', e);
            
            var attendees = "";
            //console.log(e.schedule.attendees);
            
            $.each(e.schedule.attendees, function (key, value) {	 
            	attendees += value + ',';	
   			});
            
            $('#editSchedule-attendees').html(attendees);
            
            
            $('#editSchedule').show();
        },
        'clickDayname': function(date) {
            console.log('clickDayname', date);
        },
        'beforeCreateSchedule': function(e) {
            console.log('beforeCreateSchedule', e);
            saveNewSchedule(e);
        },
        'beforeUpdateSchedule': function(e) {
            var schedule = e.schedule;
            var changes = e.changes;

            console.log('beforeUpdateSchedule', e);

            if (changes && !changes.isAllDay && schedule.category === 'allday') {
                changes.category = 'time';
            }

            cal.updateSchedule(schedule.id, schedule.calendarId, changes);
            refreshScheduleVisibility();
        },
        'beforeDeleteSchedule': function(e) {
            console.log('beforeDeleteSchedule', e);
            cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
        },
        'afterRenderSchedule': function(e) {
        	
        	console.log('afterRenderSchedule');
        	
            var schedule = e.schedule;
            // var element = cal.getElement(schedule.id, schedule.calendarId);
            // console.log('afterRenderSchedule', element);
        },
        'clickTimezonesCollapseBtn': function(timezonesCollapsed) {
            console.log('timezonesCollapsed', timezonesCollapsed);

            if (timezonesCollapsed) {
                cal.setTheme({
                    'week.daygridLeft.width': '77px',
                    'week.timegridLeft.width': '77px'
                });
            } else {
                cal.setTheme({
                    'week.daygridLeft.width': '60px',
                    'week.timegridLeft.width': '60px'
                });
            }

            return true;
        }
    });

## Expected Behavior

Close edit schedule popup on clicking other time slot and open create popup on clicking empty timeslot.

**Comment by jungeun-cho** [comment]
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups
```js
cal = new Calendar('#calendar', {
  defaultView: 'week',
  useCreationPopup: false,
  useDetailPopup: false,
  ...
});
```
You can use `beforeCreateSchedule`.
