### ISSUE TITLE
Schedule Events Deleted after a Page Refresh 

### ISSUE THREAD

**Issue by Tichnut** [nhn/tui.calendar#727]
Hi, 
I might be missing something here, but it seems like the calendar events are gone after I refresh the web page. 
Should I take care of the data storage or is there something that I'm missing? 

Thanks

**Comment by jungeun-cho** [comment]
The TOAST UI calendar only renders the entered event.
No data is stored separately.
You need to manage schedule data in your project.

We provide a default popup for convenience and fire the `beforeCreateSchedule`, `beforeDeleteSchedule`, and `beforeUpdateSchedule` events.
