### ISSUE TITLE
Schedules not showing up in calendar

### ISSUE THREAD

**Issue by angarc** [nhn/tui.calendar#732]
## Summary
I can't quite figure out the correct way to add schedules to calendars.

## Version
I'm using version 1.12.14

## Additional context
```javascript
    var calendar = new Calendar(document.getElementById('calendar-container'), {
      defaultView: 'week',
      calendars: [
        {
          id: '1',
          name: 'My Calendar',
          color: '#ffffff',
          bgColor: '#9e5fff',
          dragBgColor: '#9e5fff',
          borderColor: '#9e5fff'
        }
      ]
    })

    calendar.createSchedules([
      {
          id: '1',
          calendarId: '1',
          title: 'my schedule',
          dueDateClass: '',
          start: '2020-12-10T04:30:00+00:00',
          end: '2020-12-10T08:30:00+00:00'
      },
    ])

    calendar.render()
```

this is my code. When I check the calendar, I don't see any schedules, it's just a blank calendar. This code is copied from the documentation. The only thing i changed were the start and end date times for the schedule.

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules
https://nhn.github.io/tui.calendar/latest/Schedule

You have to set the `category` attribute of schedule.
The category has values of `'time'`, `'allday'`, `'milestone'` and `'task'`.
