### ISSUE TITLE
Sample calendars

### ISSUE THREAD

**Issue by dadweiss** [nhn/tui.calendar#733]
Thank you for the samples.  An you point me to which code item in the sample source is accessing the data that makes up the calendar ? 

## Summary
A clear and concise description of what the question is.

## Screenshots
If applicable, add screenshots to help explain your question.

## Version
Write the version of the calendar you are currently using.

**Comment by jungeun-cho** [comment]
* tutorial: https ://github.com/nhn/tui.calendar/tree/master/docs
* API/Example : https://nhn.github.io/tui.calendar/latest/Calendar
* example directory : https://github.com/nhn/tui.calendar/tree/master/examples
