### ISSUE TITLE
How to clear guide element on click outside of popup (container) or explicit cancel button from custom popup?

### ISSUE THREAD

**Issue by villerdex** [nhn/tui.calendar#736]
## Summary
I'm adding a custom popup for creating a schedule. I'm aware of `event.event.guide.clearGuideElement()` from `beforeCreateSchedule` but I only want to clear the guide from external event such as custom cancel or click from the outside of my popup. 

Is there a way to clear the guide element by calling a function explicitly? or if I miss something from the documentation please let me know. Thanks

## What did I tried so far:
1) I did my research and read the documentation
2) Storing `event` as my instance variable so I can call it later, But it only clear the latest guide

## Version
1.12.14

**Comment by jungeun-cho** [comment]
It fire in `beforeCreateSchedule`.
I have no plans yet.

---

In the weekly view, if you click anywhere else, the guide automatically disappears.
However, the guide does not disappear in the monthly view. (This should be fixed...)
The way I can tell you now...
Store the guide element directly to your application and use it.

```js
cal.on({
  ....
  'beforeCreateSchedule': function(e) {
    var viewName = cal.getViewName();

    if (viewName === 'month') {
      guideElements.push(e.guide.guideElements); // It doesn't matter whether it is an Array or a Set.
    } else {
      guideElements.push(e.guide.guideElement);
    }
    ...
  },
});

...
// your event listener
function cancel(e) {
  // remove the stored guide element directly. (e.g. guideElements.forEach....)
  el.remove();
  // or
  el.parentNode.removeChild(el);
}
```

The reason that the properties of the guide element of the monthly view and the weekly view are different is that the guide of the monthly view is multiple.

**Comment by villerdex** [comment]
Thanks @jungeun-cho 

In monthly view I was able to make work around by showing popup and storing the `event`

this will make the `guide element` show one at a time, closing the most recent before the user able to click another date
