### ISSUE TITLE
how to prevent `More` window popup from displaying?

### ISSUE THREAD

**Issue by villerdex** [nhn/tui.calendar#738]
## Summary
Is there any API to hide or not show the more window popup when clicked? There is an event `clickMore` but it do not have an option to prevent the window from showing.

Thank you.

**Comment by jungeun-cho** [comment]
The More layer is a layer to show schedules that are not visible in the monthly view.
It is opened through the More button.

What are you trying to do?
For example, do you want to display your custom popup?

**Comment by villerdex** [comment]
I want to disable/hide the `More layer`.

My requirement is to create a `list of schedules` instead of showing the `More Layer`

**Comment by jungeun-cho** [comment]
Your requirements are not clear.
API design requires specific specifications.

It's not just adding an interface that hides more layers.
The more layer is related to the more button.

```
to create a list of schedules
```
I don't know what this means. How do you create a schedule list in which UI?

**Comment by villerdex** [comment]
The `list of schedules` is my custom UI, which should display all the schedule of the day. That's why I want to NOT display the more popup whenever I click the more button.

**Comment by jungeun-cho** [comment]
I understand. I have no plans yet for this API.
well.. if you need it right now for your project, you can the `.tui-full-calendar-month-more` selector to `display: none`.

```html
<div id="calendar"></div>
```

```css
#calendar .tui-full-calendar-month-more {
  display: none;
}
```

**Comment by villerdex** [comment]
Thanks @jungeun-cho 

I was little skeptical to use pure css solution but yeah, I think this is the only option for now.

closing this now
