### ISSUE TITLE
It is possible ti disable form validation check?

### ISSUE THREAD

**Issue by egonom** [nhn/tui.calendar#739]
Sorry, I can't create a jsfiddle for this thing, but I'm trying to explain.
If the calendar div embedded into a html form and the form contains some required fields, than on the new event popup window's "busy" dropdown's click is fired the form validation process: the page scrolling to the first unfilled required field. That's OK, but unwanted event. Can I disable it? How?
Best regards
egonom

**Comment by jungeun-cho** [comment]
I don't think this is a TOAST UI calendar issue.

Could you give me a reproducible code like a [codesandbox](https://codesandbox.io/)?

But why did you create a calendar inside the html form tag?

**Comment by tuical** [comment]
OK, here is an example page with one required field: https://86qgl.sse.codesandbox.io/
When you try to create a new event in the calendar and the popup box were shown, try to click on the State dropdown.

"But why did you create a calendar inside the html form tag?"
Why not? I used the calendar for adding intervals to some records which edited with a form.

I think I understand now. The event popup form is not added to the body of the page, as usual, but to the calendar element, which is thus embedded in the outer form. OK, I have to avoid this problem :(

**Comment by jungeun-cho** [comment]
Please do not misunderstand. I just asked. Happy Coding :)
