### ISSUE TITLE
calendar.next(), .prev(), .today() not working

### ISSUE THREAD

**Issue by mectorfector** [nhn/tui.calendar#742]
Hello! Awesome project!

I hope you can be of assistance with a minor problem.
Thanks in advance! :-)

I have included both tui-code-snippet.js, tui-calendar.js and tui-calendar.css.
I also have jQuery included.

I create the calendar with:
`
$(function () {
    var calendar = new tui.Calendar('#calendar', {
      defaultView: 'month'
    })
})
`
The calendar appears in the div, so it seems to be working.

However, when calendar.next() is called onclick from a button, the browser console prints:

> TypeError: calendar.next is not a function. (In 'calendar.next()', 'calendar.next' is undefined)

I hope you can help! This is really bugging me :-(
Have a great weekend

**Comment by jungeun-cho** [comment]
Does your button event listener exist within the scope that created the calendar instance?
```js
$(function () {
  var calendar = new tui.Calendar('#calendar', { defaultView: 'month' })
  
  btn.addEventListener('click', e => {
    // console.log(calendar);
  });
})
```
