### ISSUE TITLE
Update CDN to 1.13.0

### ISSUE THREAD

**Issue by amclelland** [nhn/tui.calendar#743]
## Version
1.12.13

## Development Environment
Chrome on Macbook

## Current Behavior
https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js points to 1.12.13

## Expected Behavior
Would like it to be updated to point to 1.13.0

**Comment by jungeun-cho** [comment]
I updated `latest`.
https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js
https://uicdn.toast.com/tui-calendar/v1.13.0/tui-calendar.js

**Comment by amclelland** [comment]
Thanks @jungeun-cho !
