### ISSUE TITLE
How to integrate tui.context-menu into tui.calendar

### ISSUE THREAD

**Issue by qngnud** [nhn/tui.calendar#745]
## Summary
I want to add a context menu to every single schedule. I can use tui.context-menu, but I don't know how to add it to every schedule. Please give me a hand, thanks!

## Version
1.13.0

## Addition Content
If I can use a custom context menu like a custom pop-up, it will be better

**Comment by jungeun-cho** [comment]
Not in the plan yet.

The event that fires on the right click is not being emitted.

But I think there is a demand for this function.

For example...
```js
cal.on({
  clickSchedule: function (e) {
    /* ... */
  },
  rightClickSchedule: function (e) {
    const { schedule, calendar, element, event } = e;

   /* Write an action when a right-click event fires */
  },
});
```

Nothing has been planned for this feature yet, but we will consider it in the next version.

**Comment by qngnud** [comment]
I resolved my problem, use afterRenderSchedule to do it.
`export const afterRenderSchedule = (props: IProps) => {
  const {calendarRef, event, setContextmenu} = props;
  const schedule = event.schedule;
  const element = calendarRef.current.calendarInst.getElement(schedule.id, schedule.calendarId);
  const id = element.getAttribute("data-schedule-id");
  element.addEventListener("contextmenu", (e) => rightClickSchedule({e, id, setContextmenu}));

  return () => {
    element.removeEventListener("contextmenu", (e) => rightClickSchedule({e, id, setContextmenu}));
  };
};`
But I still hope this will become a feature. Thanks!
