### ISSUE TITLE
Additional Schedule Popup Fields

### ISSUE THREAD

**Issue by rosendyakov** [nhn/tui.calendar#746]
Hello, I need to display additional data apart from the default one onto my schedule popup, however I still haven't found the way. Here's what I've done so far:

I've created my schedules as you can see below, and I'm trying to add and display new schedule properties, such as attendee and more. Whenever I try to add new elements to the default popup via modifying the handlebars template file, nothing happens.

Could you help me out? I've submitted my schedule creation code below, customPropIneedToDisplay is an example name for my custom properties I need to add and display.

`<script type="text/javascript">

    cal.createSchedules([
            {
                id: '30',
                calendarId: '2',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 06:00:00',
                end: '2021-02-08 06:39:59',
                customPropIneedToDisplay: ' '
            },
            {
                id: '29',
                calendarId: '1',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 07:00:00',
                end: '2021-02-08 07:39:59',

            },
            {
                id: '31',
                calendarId: '1',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 07:40:00',
                end: '2021-02-08 08:19:59',

            },
            {
                id: '32',
                calendarId: '2',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 08:20:00',
                end: '2021-02-08 08:59:59',

            },
            {
                id: '28',
                calendarId: '3',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 09:00:00',
                end: '2021-02-08 09:44:59',

            },
            {
                id: '24',
                calendarId: '1',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 10:15:00',
                end: '2021-02-08 10:59:59',

            },
            {
                id: '33',
                calendarId: '1',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 11:00:00',
                end: '2021-02-08 11:39:59',

            },
            {
                id: '25',
                calendarId: '2',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 11:30:00',
                end: '2021-02-08 12:14:59',

            },
            {
                id: '26',
                calendarId: '4',
                title: 'name12',
                category: 'time',
                start: '2021-02-08 12:15:00',
                end: '2021-02-08 12:59:59',

            },
            {
                id: '35',
                calendarId: '2',
                title: 'name12',
                category: 'time',
                start: '2021-02-10 11:30:00',
                end: '2021-02-10 12:09:59',

            },
    ]);
    
</script>

`

**Comment by jungeun-cho** [comment]
@rosendyakov 
https://nhn.github.io/tui.calendar/latest/Schedule
You can use `raw`  field.

```js
cal.createSchedules([
        {
            id: '30',
            calendarId: '2',
            title: 'name12',
            category: 'time',
            start: '2021-02-08 06:00:00',
            end: '2021-02-08 06:39:59',
            raw: {
              customPropIneedToDisplay: ' '
            }
        },
```
