### ISSUE TITLE
Default display not as expected

### ISSUE THREAD

**Issue by maximus1127** [nhn/tui.calendar#748]
I have copy/pasted the code from your demo page and I'm not getting the expected results. I've played with multiple configurations but I still can't seem to get this to work. No matter what I do, my calendar does not have a header bar where I can select which different view I want (month, week, day, etc). 

Here is my code:

```
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>My App</title>
        <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css" />
        <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.css" />
        <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.css" />
    </head>
    <body>
      <div id='calendar'></div>
      <script src="https://uicdn.toast.com/tui.code-snippet/v1.5.2/tui-code-snippet.min.js"></script>
      <script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
      <script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
      <script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
        <script>
          var Calendar = tui.Calendar;

          var calendar = new Calendar('#calendar', {
            defaultView: 'month',
            taskView: true,
            template: {
              monthDayname: function(dayname) {
                return '<span class="calendar-week-dayname-name">' + dayname.label + '</span>';
              }
            }
          });
        </script>
    </body>
</html>
```
And here is what that renders:

![image](https://user-images.githubusercontent.com/31026284/107311553-270ea380-6a54-11eb-9b04-8e656702f10e.png)

Also, when I copy/paste the "weekly" example html code from the docs website, my header looks like this:
![image](https://user-images.githubusercontent.com/31026284/107369234-218e7900-6aa7-11eb-9983-a45eacef12d1.png)

instead of like this:
![image](https://user-images.githubusercontent.com/31026284/107369264-2ce1a480-6aa7-11eb-8770-76f45efcc0bc.png)

How can I get my calendar to look like the demo version?

**Comment by jungeun-cho** [comment]
check it out!
https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html
