### ISSUE TITLE
how to catch doubleclick event to the existing schedule

### ISSUE THREAD

**Issue by guswhd7894** [nhn/tui.calendar#749]
## Summary
i wondering if i could double click on the existing schedule in the calendar

## Screenshots
![image](https://user-images.githubusercontent.com/78841382/107473560-3d337580-6bb4-11eb-98b3-27cbc8ed5d34.png)

double clicking on the existing schedule

## Version

newest

**Comment by jungeun-cho** [comment]
It is not supported in v1.
However, it would be nice to allow users to choose how to catch events.
I would consider developing Calendar v2. :)

**Comment by gismofx** [comment]
@jungeun-cho seems like nobody replied, but It would be nice to be able to run a custom action. Check Event for single or double click and then handle how ever the user wants.
