### ISSUE TITLE
Can I split days to 2 or 3 pieces?

### ISSUE THREAD

**Issue by sundowatch** [nhn/tui.calendar#750]
Hi,

I want to make a calendar and I wonder if I can split day to 2 or 3 pieces and give label to each piece.

Thank you.

**Comment by jungeun-cho** [comment]
The view you want is the screenshot below?

<img width="830" alt="스크린샷 2021-02-17 13 43 23" src="https://user-images.githubusercontent.com/43128697/108157510-44173680-7126-11eb-99e5-8e6f9c342384.png">

This view is not supported in v1. We plan to support in v2.

**Comment by sundowatch** [comment]
@jungeun-cho  Actually, I want week view and split days into shifts.

**Comment by jungeun-cho** [comment]
@sundowatch 
[Mon, Wed, Fri]
[Tue, Thu, Sat]

Do you want something to look like this?
Sorry, this feature is not supported in v1.

It is planned to be provided in v2.
