### ISSUE TITLE
Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by ready-research** [nhn/tui.calendar#752]
**Describe the bug**
`tui-calendar` is vulnerable to `Cross-Site Scripting (XSS)`.

**To Reproduce**
1. Open any example https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic
2. Edit any of the event in calendar with script ex: `AA"<img src=x onerror=alert('XSS')>'`
3. XSS payload will get executed.

**Expected behavior**
Display calendar events with out execution of any scripts.

**Screenshots**
![tui-calendar](https://user-images.githubusercontent.com/72916209/107954378-63954e80-6fc2-11eb-85b3-1bae97d472fd.PNG)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser [Any browser ex: chrome, safari]
 - Version [All(including latest 1.13.0)]

**Comment by jungeun-cho** [comment]
It is not necessary to directly resolve to Cross-Site Scripting from the internal source of the TOAST UI Calendar, but to escapeHTML when creating a event.
I will update examples.

**Comment by arjunshibu** [comment]
Hi @jungeun-cho I've fixed a similar vulnerability in `tui.chart` package as you can see https://github.com/nhn/tui.chart/pull/604
So can I try to fix this also?

**Comment by jungeun-cho** [comment]
Sure. You can fix it. :)

**Comment by arjunshibu** [comment]
Hi @jungeun-cho thanks for the reply. I've added a fix for this vulnerablity and made a PR here https://github.com/418sec/tui.calendar/pull/1.

Do you mind reviewing it there? If you are okay with this fix, please comment `@huntr-helper - LGTM` in that PR so the bot will open the same PR to this repo for you. Commenting this will give me a small reward for fixing this issue🚀.

Once again thank you so much for your time😄

**Comment by JamieSlome** [comment]
@jungeun-cho - would you be able to validate here:

https://www.huntr.dev/bounties/1-npm-tui-calendar/

**Comment by adhrinae** [comment]
Thanks for your efforts. At this moment I'm maintaining this project.
DOMPurify is a great solution, but we don't want to enlarge the bundle size for the small fixes.

But the XSS vulnerability should be fixed. So I'll implement a simpler solution and fix the issue.

**Comment by arjunshibu** [comment]
Hi @adhrinae is it okay if I fix this without libraries?

**Comment by adhrinae** [comment]
@arjunshibu That would be great.

**Comment by arjunshibu** [comment]
Not that efficient as `dompurify`😅. It's also small sized.

**Comment by adhrinae** [comment]
This issue is resolved by the v1.14.1 release.
