### ISSUE TITLE
Refreshing schedules layout

### ISSUE THREAD

**Issue by micmanar** [nhn/tui.calendar#753]
## Summary
I'm having some problem inserting the calendar in a flex container: apparently the initial height of the parent element is still not correct when the internal layout ot the calendar is calculated.

But when I add a schedule, everything is recalculated and the layout is fine.

My question is: how does the insertion of a new schedule trigger the layout recalculation? Is it possible to invoke the recalculation by code?

I'm using the week view.

Thanks

**Comment by jungeun-cho** [comment]
You can use [`cal.render()`](https://nhn.github.io/tui.calendar/latest/Calendar#render).
Do you have a link to reproduce it? (jsfiddle, codepen, codesandbox)
