### ISSUE TITLE
How to localize word 'more' in monthly view

### ISSUE THREAD

**Issue by claudiosfr** [nhn/tui.calendar#761]
# Version
TOAST UI Calendar
 @version 1.12.14 | Tue Sep 22 2020

## Development Environment
Any browser

## Current Behavior
Is there a way to localize the word 'more' in monthly view?
Thank You in advance!

![InkedScreenshot 2021-03-10 100634_LI](https://user-images.githubusercontent.com/5812804/110604890-ddb39000-8188-11eb-9845-9d14f0a59631.jpg)

**Comment by jungeun-cho** [comment]
We supports various templates. 

https://nhn.github.io/tui.calendar/latest/Template

```js
cal = new Calendar('#calendar', {
  defaultView: 'month',
  ...
  template: {
    ...
    monthGridHeaderExceed: function(hiddenSchedules) {
      return `<span class="weekday-grid-more-schedules">${hiddenSchedules} more</span>`;
    },
 },

```

**Comment by claudiosfr** [comment]
It was my fault: I didn't read too carefully your API documentation.
jungeun-cho, thank You so much for Your kind and prompt reply.
I really appreciate this.
Regards.
