### ISSUE TITLE
Min width for cards on daily view

### ISSUE THREAD

**Issue by KaranChe97** [nhn/tui.calendar#763]
When multiple cards are assigned on same time all the cards  shrinked to fit the width of the calendar which makes hard to read the contents on the card. Is there a way to fix a minimum width for scheduled cards. 

## Screenshots
![Screenshot 2021-03-12 111248](https://user-images.githubusercontent.com/34377367/110897747-0459fe00-8324-11eb-876d-ba2bffb6b52e.png)

**Comment by jungeun-cho** [comment]
This width is being calculated equally. We've been thinking a lot about this.
What if the width of the schedule card is specified and it exceeds the width of the grid column?

**Comment by KaranChe97** [comment]
May look weird but overflow-x with scroll is also fine in such cases.

**Comment by anhao** [comment]
> May look weird but overflow-x with scroll is also fine in such cases.

That's a good idea.

**Comment by anhao** [comment]
### Screenshots
![urVZYLXMGC](https://user-images.githubusercontent.com/9844218/112714044-5a799480-8f13-11eb-972c-75d403c3d597.gif)
