### ISSUE TITLE
In the example, the schedule's drag event doesn't work consistently

### ISSUE THREAD

**Issue by gowthamgajula** [nhn/tui.calendar#766]
## Version
1.13.0

## Development Environment
browser- chrome, OS- windows-10

## Current Behavior
 I am unable to drop the element of particular selected/dragged schedule element from one date to another date in monthly, weekly, daily views. But in the demo examples, under calender-app only that drag & drop is working. In the remaining section like monthly, weekly, daily, sections drop is not happening only dragging is working.

## Expected Behavior
Need Drop feature for whatever the scheduled element is dragged.

**Comment by jungeun-cho** [comment]
Please keep our issue templates!
In the calendar app, this is an integrated example with event handlers attached.
In the rest of the example, only necessary options are defined.
If you need source code, please refer to [here](https://github.com/nhn/tui.calendar/blob/master/examples).

**Comment by gowthamgajula** [comment]
Instead of source code can u provide what exactly can i do to make drop feature workable
