### ISSUE TITLE
How to add new custom template (e.g. milestone, allday, time or etc)

### ISSUE THREAD

**Issue by Nrvjvn** [nhn/tui.calendar#769]
## Summary
I am using this tool in Angular 8+ and I want to add custom template in top view where we show (milestone, allday and time). I want to add more template here...
can I add? if yes please let me know example if you have...

Thanks

**Comment by jungeun-cho** [comment]
[DOCS](https://nhn.github.io/tui.calendar/latest/)

### Template Options
* https://nhn.github.io/tui.calendar/latest/Template

### Examples
* https://nhn.github.io/tui.calendar/latest/tutorial-example14-template-for-month
* https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid
* https://nhn.github.io/tui.calendar/latest/tutorial-example16-template-for-popup

**Comment by Nrvjvn** [comment]
Thanks for reply...

I read docs but not getting any answer form it....

I want to add timeView option like (Late Fees, Leave and more...) instead of (MILESTONE, TASK, and ALL DAY)..  I cannot find this thing...

**Comment by jungeun-cho** [comment]
![test](https://user-images.githubusercontent.com/43128697/113383139-3a881c00-93be-11eb-8141-8644df513911.png)
Are you talking about the title here?

**Comment by Nrvjvn** [comment]
No, I am not taking change title... I am taking How to add new here....?

**Comment by gismofx** [comment]
> ![test](https://user-images.githubusercontent.com/43128697/113383139-3a881c00-93be-11eb-8141-8644df513911.png)
> Are you talking about the title here?

How do you change the title?

**Comment by jungeun-cho** [comment]
@Nrvjvn 
> No, I am not taking change title... I am taking How to add new here....?

Currently, only grids for milestones, tasks, and all day are supported.

Only the title is changed for this item.

**Comment by jungeun-cho** [comment]
@gismofx 
> > ![test](https://user-images.githubusercontent.com/43128697/113383139-3a881c00-93be-11eb-8141-8644df513911.png)
> > Are you talking about the title here?
> 
> How do you change the title?

Check out the comments above.

```js
const cal = new Calendar(el,  {
  ...
  template: {
    alldayTitle: () => `<span class="tui-full-calendar-left-content">Leave</span>`,
  }
});
```

**Comment by Nrvjvn** [comment]
@jungeun-cho thanks for replay...

I know how to change text... but I want to add more.... and it is not possible as you said in...

> @Nrvjvn
> 
> > No, I am not taking change title... I am taking How to add new here....?
> 
> Currently, only grids for milestones, tasks, and all day are supported.
> 
> Only the title is changed for this item.
