### ISSUE TITLE
How to add a custom popup?

### ISSUE THREAD

**Issue by Leschonander** [nhn/tui.calendar#779]
Looking through the documentation, I already know this is how you disable the default popup
```
var cal = new Calendar('#calendar', {
    useCreationPopup: false,
    useDetailPopup: false,
...
});
```
However, not mentioned in the documentation is how to add the replaced one afterwards. I have a modal made in bootstrap
that has bespoke form entries, that I got to work already with `createSchedules`. But how would I make that modal be the one that would pop up when I clicked on a given date to create an event?

Not sharing full modal because it's made from bootstrap and therefore massive, but what it involve using the `id` of the modal to link it to the calendar object? 
```
<div class="modal fade" id="create_event" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
```

**Comment by jungeun-cho** [comment]
check [it](https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups) out
```js
// event handlers
cal.on({
    'beforeCreateSchedule': function(e) {
        console.log('beforeCreateSchedule', e);
        // open a your creation popup
        /*...*/
  
        // then close guide element(blue box from dragging or clicking days)
        e.guide.clearGuideElement();
    },
});
```

**Comment by Leschonander** [comment]
Thanks 👍. Realized I was using the wrong event handler. `beforeCreateSchedule` works like a charm
