### ISSUE TITLE
calender should show server time not client time

### ISSUE THREAD

**Issue by ankita1612** [nhn/tui.calendar#780]
I am using tui-calendar in PHP. my application is working based on timezone. each user who loggedin can set their timezone in our setting . now tui calender is taking client side time zone so same application I open in chicago it shows chicago date time wise calnder and in india it shows india timewise.I don't want it. I want to fixed it as per my server's timezone. can you please help me .

**Comment by jungeun-cho** [comment]
You have to calculate the difference between the time zone set by the user and the server time zone.
Could it be helpful to use the time zone option?
https://nhn.github.io/tui.calendar/latest/Timezone
