### ISSUE TITLE
How to access or use < new TZdate() > via browser environment

### ISSUE THREAD

**Issue by holyfrog666** [nhn/tui.calendar#786]
First of all, TY for this good calendar function.

I just used tui-calendar as CDN, like below. ( Not Node environment )
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>

I just used tui-calendar for my calendar And There was something problem to add schedules which is need as repeat.

So I realized that I need the way to use "new TZdate()" & "tzdate().toDate()"

I already tried to find how to use But It seems like TZdate() is in the "timezone.js" which I couldn't find in Toast Cloud list.

I have to import "intlUtil.js" and "timezone.js" but that codes's environment seems like only avail on Node environment.

**Is there any possible way I can use "new TZdate()"?**

Then, please lmk.
Thanks, TUI dev

**Comment by jungeun-cho** [comment]
TZDate is an internally used date class. It is not supported by external API.
