### ISSUE TITLE
Use with FacetWP... ajax data

### ISSUE THREAD

**Issue by rossberenson** [nhn/tui.calendar#801]
Hi!

Great calendar! I'm using it for an event site that I'm building. I have everything working except for the filtering. I'm trying to use FacetWP for filtering. 

In the end, I have a json being generated via wp query and the calendar reads that json and displays all the events. This works just fine. 

The problem I'm running into is when a filter is changed. The json data gets updated and then the calendar breaks. The calendar itself gets destroyed for some reason. I don't have any code telling it to do so. FacetWP has a few events where I can do xyz on a filter change. I have been trying to re-init the calendar to no avail. I have tried `calendar.createSchedules(calendarEvents); calendar.render()` and some others as well. I'm starting to hit a wall. 

I was able to get a custom filter working, which toggles calendars but I'd really prefer to get FacetWP filtering to work for more advanced filtering.

Any ideas?

Thanks!

**Comment by jungeun-cho** [comment]
I can't reproduce, so I can't figure out the details of the situation.
Would you like to clear the view for re-rendering?

https://nhn.github.io/tui.calendar/latest/Calendar#clear
```js
cal.clear();

cal.createSchedules(...);

// If you need a calendar toggle...
cal.toggleSchedules(...);

cal.render(true);

```

**Comment by rossberenson** [comment]
Hi @jungeun-cho!

I didn't think this would be something you could easily replicate. I'll try to provide more information. [FacetWP](www.facetwp.com) is a WordPress plugin that handles filtering. They provide a [Loaded](https://facetwp.com/documentation/developers/javascript/facetwp-loaded/) event.

The resulting output is a json that the calendar then reads. When a user uses a filter, the json is then updated. I'm trying to tell the calendar to re-read the json data. 

I've tried what you suggested before reaching out. What happens is, after a user filters the data, the whole calendar gets destroyed for some reason. All the HTML markup, everything relating to the calendar vanishes. FacetWP uses for data updating, so I wasn't sure if this conflicts with TUI Calendar or not.

```
document.addEventListener('facetwp-loaded', function () {
    calendar.clear();
    calendar.createSchedules(calendarEvents, true);
    calendar.render();
});
```

Before filtering
![Screen Shot 2021-05-17 at 11 30 31 PM](https://user-images.githubusercontent.com/2307364/118585960-e1a2f600-b767-11eb-9448-1909510aa6dd.png)

After filtering the `.tui-full-calendar-layout` element gets removed from the DOM. Can't figure out why such a thing would happen.

You can see it in action on the dev site. https://ija2021.justdev.co/schedule/  Use the black filter, not the blue. The blue is hiding and showing calendars for testing purposes. The black 'Categories" filter is FacetWP modifying the json that the calendar reads.

Thanks!

**Comment by adhrinae** [comment]
@rossberenson Hi, I'm checking your dev site but it seems working. Is your problem resolved?
FYI, I've checked the code and found out `clear`, `render` methods don't destroy the main DOM element.

**Comment by rossberenson** [comment]
I'm so sorry! I forgot to update this. It was a conflict with some other code. I have solved it since. Meant to update this ticket. I greatly appreciate you following up on the issue. The data source kept getting messed up when being filtered, which caused an error within the calendar. It would cause the calendar to break. Once I solved my data issue, calendar worked as expected.
