### ISSUE TITLE
Schedule with category time not displayed correctly

### ISSUE THREAD

**Issue by quevon24** [nhn/tui.calendar#809]
Hi, I hope you can help me, I'm trying to use week view, with this:

$(document).ready(function () {

            var calendar = new tui.Calendar('#calendarInstructor', {
                defaultView: 'week',
                taskView: false,
                useCreationPopup: false,
                useDetailPopup: false,
                week: {
                    daynames: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'],
                    narrowWeekend: false,
                    startDayOfWeek: 1
                },
            });

            calendar.createSchedules([
                {
                    id: '1',
                    calendarId: '1',
                    title: 'my schedule',
                    body: 'body',
                    category: 'time',
                    dueDateClass: '',
                    start: new Date('2021-05-19T09:00:00'),
                    end: new Date('2021-05-19T11:00:00'),
                    isReadOnly: true    // schedule is read-only
                },
                {
                    id: '2',
                    calendarId: '1',
                    title: 'second schedule',
                    body: 'body',
                    category: 'time',
                    dueDateClass: '',
                    start: new Date('2021-05-20T13:00:00'),
                    end: new Date('2021-05-20T14:00:00'),
                    isReadOnly: true    // schedule is read-only
                }
            ]);

});

The problem is that schedules are not placed in correct time, are always placed at top, and also title is not displayed.

![image](https://user-images.githubusercontent.com/6474994/118561315-6e31c200-b730-11eb-9aaa-b375903a8f71.png)

What I'm doing wrong? Also can I use different time format, like a string: '2021-05-20 15:30'?

**Comment by jungeun-cho** [comment]
https://codesandbox.io/s/tuicalendar-issue-809-fuibl

<img width="645" alt="스크린샷 2021-05-18 03 11 15" src="https://user-images.githubusercontent.com/43128697/118575543-ad5c2380-b7c1-11eb-917e-434edc2947e9.png">
It cannot be reproduced.
What's the problem?

**Comment by quevon24** [comment]
> https://codesandbox.io/s/tuicalendar-issue-809-fuibl
> 
> <img alt="스크린샷 2021-05-18 03 11 15" width="645" src="https://user-images.githubusercontent.com/43128697/118575543-ad5c2380-b7c1-11eb-917e-434edc2947e9.png">
> 
> It cannot be reproduced. What's the problem?

Thanks for you answer, i'm loading it with:

```
<link rel="stylesheet" href="{% static 'plugins/tui-calendar/tui-calendar.min.css' %}">
<script src="https://uicdn.toast.com/tui.code-snippet/v1.5.2/tui-code-snippet.min.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```

I have the <div> inside a bootstrap 4 tab panel, the problem is that the schedules are not placed correctly on it's start and end time, only placed correctly on it's date, always displays at top and also doesn't show the title, they looks like the image:

![image](https://user-images.githubusercontent.com/6474994/118580014-b8c53580-b754-11eb-8f2e-e5fc1baf2bb8.png)

**Comment by jungeun-cho** [comment]
Could you give me a link to reproduce it? (like jsfiddle, codesandbox, codepen)
I need your development environment including Bootstrap 4.

I think it's because the style sheet is overwritten.

**Comment by quevon24** [comment]
Let me se what I can do because it's an internal project, occasionally loads correctly, correct position and correct height:

![image](https://user-images.githubusercontent.com/6474994/118666809-12f7e200-b7b9-11eb-8cc3-b92dd7878af7.png)

But almost everytime doesn't calculate the position and height is 0:

![image](https://user-images.githubusercontent.com/6474994/118667118-55b9ba00-b7b9-11eb-9f74-37efd836fab2.png)

**Comment by quevon24** [comment]
**Update**

After a lot of tests the problem is because the tui-calendar is placed inside the tab-pane, I guess that because the tab-pane is hidden initially the tui-calendar has problems to calculate schedule position of the hidden tab.

I solved doing this:

```
$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                    if (e.target) {
                        if (e.target.id == 'my-tab-id') {
                            calendar.render();
                        }
                    }
                })
```

With this when the tab is selected, renders the calendar with the createSchedules list previously added.
