### ISSUE TITLE
Calendar Not Shown When Being Called From IFrame In Different Domain

### ISSUE THREAD

**Issue by sambadabudiarga** [nhn/tui.calendar#811]
## Describe the bug
I have a website with a domain, say, www.aaa.com.
In that website, I called the calendar I have created using tui.calendar which I hosted at www.abc.com using iframe.
The calendar does not show up, it shows an error in the console instead.
**Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.** 

I found that this error happened in Chromium/Chrome.
Tested in Firefox, the same error does not happen

## To Reproduce
1. Host the calendar in the a domain
2. Call that calendar hosted in a domain in another domain
3. Try to access that another domain from Chromium/Chrome
4. The calendar won't shows up.

## Expected behavior
I found that there's a solution in StackOverflow to change how to call the browser API.
Can be seen from here, https://stackoverflow.com/a/66133745/5391801

## Desktop (please complete the following information):
 - Chrome, Chromium

**Comment by jungeun-cho** [comment]
I think I should check this issue myself.
Could you get reproducible domain information?

**Comment by sambadabudiarga** [comment]
The calendar is being hosted at iseka.services.

And it called in an iframe from crm.zoho.com.

Sent from mobile device.

Sambada Budiarga
Software Developer
e: ***@***.***

**Comment by jungeun-cho** [comment]
Isn't the hosting provider blocking the iframe?
Do you bring pages other than the calendar well?

<img width="1427" alt="스크린샷 2021-05-27 22 50 41" src="https://user-images.githubusercontent.com/43128697/119837974-ff2d4800-bf3d-11eb-8238-90b06a9055cb.png">

In general, schedules rendered as iframes come well.

**Comment by sambadabudiarga** [comment]
Hi,

I am sorry for not being clear enough.
The host https://iseka.services is hosting the calendar.
While the calendar itself accessed from crm.zoho.com using iframe the host above.

I think this is an intermittent issue.
I've tried to reproduce this issue few times again to no avail.

Thank you for your quick response.
Have a good day.
