### ISSUE TITLE
How to dis-select the chosen day in 'month' view?

### ISSUE THREAD

**Issue by wangyibinwangyi** [nhn/tui.calendar#815]
## Summary
I opted to use beforeCreateSchedule but now I can't dis-select the chosen day, is there away to keep toggling the selected day ?

## Screenshots
![QQ截图20210526155545](https://user-images.githubusercontent.com/24824599/119623842-24855d80-be3b-11eb-85c3-918b20cf89b8.png)

## Version
v1.13.0

**Comment by jungeun-cho** [comment]
You can use `e.guide.clear()`
```js
'beforeCreateSchedule': (e) => {
  /*...*/
  e.guide.clear();
 },
```

**Comment by wangyibinwangyi** [comment]
> You can use `e.guide.clear()`
> 
> ```js
> 'beforeCreateSchedule': (e) => {
>   /*...*/
>   e.guide.clear();
>  },
> ```

Thank you ! But it will clear all choosed area, and I can't get the guideElement DOM ;
![image](https://user-images.githubusercontent.com/24824599/119932049-2410d200-bfb5-11eb-94be-b2589bf69e85.png)
![image](https://user-images.githubusercontent.com/24824599/119933153-1d368f00-bfb6-11eb-9231-b8990a4fd268.png)

**Comment by adhrinae** [comment]
@wangyibinwangyi
You can access `guideElement` before you clear it. so if you want to get a position etc, clone those values before clearing guides.

```js
calendar.on('beforeCreateSchedule', e => {
  const guideEl = Object.values(e.guide.guideElements)[0];
  const rect = guideEl.getBoundingClientRect();
  e.guide.clear();
  console.log(rect); // you can still use the rect 🎉
});
```

**Comment by wangyibinwangyi** [comment]
Thank you! But the blue rect I choosed is still miss .... 
![image](https://user-images.githubusercontent.com/24824599/122400534-632bb500-cfae-11eb-83e4-f1fa703cd132.png)
![image](https://user-images.githubusercontent.com/24824599/122400702-8a828200-cfae-11eb-9fd2-8925636342c2.png)


> @wangyibinwangyi
> You can access `guideElement` before you clear it. so if you want to get a position etc, clone those values before clearing guides.
> 
> ```js
> calendar.on('beforeCreateSchedule', e => {
>   const guideEl = Object.values(e.guide.guideElements)[0];
>   const rect = guideEl.getBoundingClientRect();
>   e.guide.clear();
>   console.log(rect); // you can still use the rect 🎉
> });
> ```

**Comment by adhrinae** [comment]
@wangyibinwangyi I think you can clear the guide as late as you can after processing all the business logics to create a schedule.

If you need to create the schedule on the different function or method, you may need to store the guide as variable and then use it later.

```js
let currentGuide;
calendar.on('beforeCreateSchedule', e => {
  currentGuide = e.guide;
  // ...
});

// ... Somewhere on your code
function createSchedule() {
  // ... after you've created a schedule
  guideEl.clearGuideElements();
}
```
