### ISSUE TITLE
I tried to prevent the creation of two events at the same time

### ISSUE THREAD

**Issue by Askhabov-HM** [nhn/tui.calendar#817]
I tried to prevent the creation of two events at the same time. Made such an implementation. What do you think about this? Was there a simpler solution in the API?

`'beforeUpdateSchedule': function(event) {
                // GET EVENT START DATE
                let newScheduleDate = new Date(
                    event.start.getFullYear(),
                    event.start.getMonth(),
                    event.start.getDate(),
                    event.start.getHours(),
                    event.start.getMinutes(),
                    );

                // TODAY DATE
                let todayDate = new Date();

                let collide = false;

                if( newScheduleDate <= todayDate){
                    alert('It is impossible to reschedule the lesson to an unavailable time');
                }
                else{
                    for( let key in calendar._controller.schedules.items){
                        
                        if(
                            calendar._controller.schedules.items[key].id
                                !==
                            event.schedule.id
                        ){
                            let start = calendar._controller.schedules.items[key].start.toDate() + '';
                            let end = calendar._controller.schedules.items[key].end.toDate() + '';
                            let changesStart = event.changes.start ? event.changes.start.toDate() + '' : event.schedule.start.toDate() + '';
                            let changesEnd = event.changes.end ? event.changes.end.toDate() + '' : event.changes.end.toDate() + '';
    
                            if(
                                start <=  changesStart && changesStart <= end
                                ||
                                end >= changesEnd && changesEnd >= start
                                ){
                                collide = true;
                                break;
                            }
                        }
                    }

                    if(collide){
                        alert('It is impossible to reschedule the lesson to an unavailable time')
                    }
                    else{
                        event.schedule.start = event.start;
                        event.schedule.end = event.end;
                        calendar.updateSchedule(event.schedule.id, event.schedule.calendarId, event.schedule);
                    }
                }
            },`

**Comment by jungeun-cho** [comment]
There are no plans for API support yet.
I checked your code.

The event contains travel time data. It has time to go and time to come.(goingDuration, comingDuration)
https://nhn.github.io/tui.calendar/latest/Schedule

When calculating collisions, you have to consider travel time.
