### ISSUE TITLE
Automatic scroll to first schedule

### ISSUE THREAD

**Issue by quevon24** [nhn/tui.calendar#824]
Hi, I was wondering if there is a way to scroll automatically to first schedule in day view? Or a way to set start time and end time for the view, I mean, instead of showing from 12 am to 12 pm maybe set from 7am to 7pm.

**Comment by jungeun-cho** [comment]
Sorry, we don't currently support automatic scrolling to the first event.
You can set the start time and end time in the time grid.

```js
const cal = new Calendar(el,  {
    week: {
        hourStart: 7,
        hourEnd: 19
    }
});
```
https://nhn.github.io/tui.calendar/latest/WeekOptions
