### ISSUE TITLE
Unable to display calendar style and pop up

### ISSUE THREAD

**Issue by charlottecol123** [nhn/tui.calendar#830]
## Describe the bug
Hello, 
I can't display the style of the calendar and pop up. I tried to implement the style-css module without success.

I'm not using JQuery.
I am using de lastest version (v1.13.0).

## Screenshots
Here is the display I get after implementing the library and adding imports:

![image](https://user-images.githubusercontent.com/83231026/121654941-86320280-ca9e-11eb-97f3-7504931a9174.png)

**Comment by adhrinae** [comment]
@charlottecol123
Hello, I'm afraid that you don't give us enough information to check this issue.

* I don't understand what "displaying the style of the calendar and popup". Does that mean you cannot customize styles of calendar and popup?
  * If so, you can read more about theme [here](https://nhn.github.io/tui.calendar/latest/themeConfig)
* If you're saying about the other bug, Please describe details about the bug and steps to reproduce it. Such as,
  * What you really intended
  * What happened at real
  * The code example when you facing the bug
  * (Optional) How far did you even tried to resolve this problem

**Comment by charlottecol123** [comment]
Hello, thank you for your answer.

Here is the display I would like to have :
![image](https://user-images.githubusercontent.com/83231026/121902235-6d884d80-cd27-11eb-9bfa-9c5c594f3f7d.png)

And also with the different Popup 
![image](https://user-images.githubusercontent.com/83231026/121902400-927cc080-cd27-11eb-85b0-5db433f9a411.png)
![image](https://user-images.githubusercontent.com/83231026/121902441-9dcfec00-cd27-11eb-87b0-80cf4d0ead0c.png)

But for the moment I can only display this :
![image](https://user-images.githubusercontent.com/83231026/121902714-dcfe3d00-cd27-11eb-9636-a012fb0aecdb.png)

And when I click on an event or a place to create an event, the popups do not appear.

I installed the packages by using "npm install tui-calendar"  but when I'm trying to import these lines :

```
import "tui-calendar/dist/tui-calendar.css";

// If you use the default popups, use this.
import 'tui-date-picker/dist/tui-date-picker.css';
import 'tui-time-picker/dist/tui-time-picker.css'
```

I have this error that appears three times :
```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| /* @charset 'utf-8'; */
```

I think the problem must come from the webpack.config.js.
Here is the code for the module part :

```
module: {
    rules: [
      {
        test: /\.(ts|js)$/,
        //test: /\.js$|jsx/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
      {
        test: /\.styles.scss$/,
        // test: /\.css$/,
        use: [
          "sass-to-string",
          {
            loader: "sass-loader",
            options: {
              sassOptions: {
                outputStyle: "compressed",
              },
            },
          },
        ],
      },
      {
        test: /\.(scss|css)$/,
        exclude: [/\.styles.scss$/, /node_modules/],
        use: [MiniCssExtractPlugin.loader, "css-loader", "sass-loader"],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf|png|svg|jpg|jpeg|gif)$/i,
        type: "asset/resource",
      },
    ],
  },
```
The farst I've gone is trying to modify the css of the webpack.config.js.

Thank you again for taking the time to help me !!

**Comment by adhrinae** [comment]
@charlottecol123 Yeah, you picked the right point about this problem.
At the block of handling external css files like `.scss` & `.css`, you're excluding `node_modules` folder. Even though `tui-calendar` and their friends' css files located somewhere in `node_modules` folder.

So try to remove `/node_modules/` regex in the `exclude` array.

Besides that, you also have to enable options in order to use popups.

```js
const calendar = new Calendar('#app', {
  defaultView: 'week',
  useCreationPopup: true,
  useDetailPopup: true
});
```

Those options are disabled by default. Please check out the [docs](https://nhn.github.io/tui.calendar/latest/Options).

**Comment by charlottecol123** [comment]
Hello,
Thank you again for your answer. 

Indeed, removing `/node_modules/` did remove the error. But that didn't bring out the style.
To be able to display it, I add the default.css file that I imported as follows:
`@use "./default.css" as *;`
I have the right style that is displayed.

Thank you for your time !

**Comment by adhrinae** [comment]
@charlottecol123 I see. That looks like you need to import related CSS files into your scss(sass) file so that your project environment can recognize third-party styles. Good to know :)
