### ISSUE TITLE
Will this work with asp.net web forms?

### ISSUE THREAD

**Issue by ahmadknet** [nhn/tui.calendar#832]
will this work asp.net web forms?

**Comment by adhrinae** [comment]
@ahmadknet
Sadly, I'm not aware of ASP.NET web forms, however, I assume that you're going to use ASP.NET as your backend.
you can integrate the calendar with your back-end server through [XHR](https://en.wikipedia.org/wiki/XMLHttpRequest). 
You may need to find out some javascript fundamentals [like this](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

`tui.calendar` provides various events when the user handles the event, so you can easily send a request to a server catching those events.

Please check out [our documentation](https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule).

**Comment by ahmadknet** [comment]
![ui toast issue](https://user-images.githubusercontent.com/6794037/122050485-1fe01380-ce01-11eb-9aff-f1a0f93698ad.png)

Please see the image for the issue I am getting.

**Comment by ahmadknet** [comment]
![ui toast issue](https://user-images.githubusercontent.com/6794037/122050698-59188380-ce01-11eb-8925-ba4a00900284.png)

Please see the image for the issue I am getting.
Thanks
Ahmad Ali Khan

**Comment by ahmadknet** [comment]
> @ahmadknet
> Sadly, I'm not aware of ASP.NET web forms, however, I assume that you're going to use ASP.NET as your backend.
> you can integrate the calendar with your back-end server through [XHR](https://en.wikipedia.org/wiki/XMLHttpRequest).
> You may need to find out some javascript fundamentals [like this](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
> 
> `tui.calendar` provides various events when the user handles the event, so you can easily send a request to a server catching those events.
> 
> Please check out [our documentation](https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule).

I'll use ajax jquery and asp.net API to save to the for the backend.

**Comment by ahmadknet** [comment]
Could you please share an example of code reading and writing from an MS-SQL server or any other database. ?
Thanks

**Comment by adhrinae** [comment]
@ahmadknet
I don't understand what the image means.

> Could you please share an example of code reading and writing from an MS-SQL server or any other database. ?

I'm sorry, but your question is way beyond the context of this project.
You need to learn how to write Javascript code to interact with any of your backend servers. and You have to figure out how to write that backend server by yourself.
Since this library is made with browser-side Javascript codes, it doesn't care what your backend is.
