### ISSUE TITLE
When I added calendar list ,schedule can't get calendar ID.

### ISSUE THREAD

**Issue by LinX9581** [nhn/tui.calendar#833]
I want to manual add calendar list , but schedule list can't get calendar ID.
one btn
two input (name,color)
<pre>
$('#addListBtn').click(async function () {
    let calendarName = $('#addListInput').val()
    let calendarColor = $('#listColor').val()
    calendar = new CalendarInfo();
    calendar.id = Date.now();
    calendar.name = calendarName;
    calendar.color = '#ffffff';
    calendar.bgColor = calendarColor;
    calendar.dragBgColor = calendarColor;
    calendar.borderColor = calendarColor;
    addCalendar(calendar);
    console.log(calendar.id + 'add calendar id');
    $('#calendarList').append( 
       https://github.com/nhn/tui.calendar/blob/master/examples/js/app.js#L446 // html can't not chow
    )
    $('.dropdown-menu-title[data-action="toggle-monthly"]').click() // rerender calendar
}
</pre>

Cal event handlers also can't get calendar list ID
<pre>
  'beforeCreateSchedule': function (e) {       //建立新的scedule
      console.log('beforeCreateSchedule', e);   // e.calendarId = null
      saveNewSchedule(e);
  },
</pre>

But when I put new calendar list to database and create new page，
rerender calendar list from database , schedule can get calendar list id

How can I let schedule get calendar list Id after I create new calendar list?

**Comment by adhrinae** [comment]
@LinX9581 
I can nearly get the idea you cannot get the `calendarId` from the schedule after creating a calendar instance dynamically.

Basically, [the `beforeCreateSchedule` event doesn't have `Schedule` instance](https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule) so you cannot get the `calendarId` from it.
However, the behavior gets changed when you enable the `useCreationPopup` option. After clicking the 'Save' button on the schedule creation popup, you can get `calendarId` from the event object.

```js
  const cal = new Calendar('#app', {
    scheduleView: true,
    useCreationPopup: true
  });

  cal.on('beforeCreateSchedule', e => {
    console.log(e.calendarId); // will be null if you didn't choose a specific calendar
  });
```

**Comment by LinX9581** [comment]
Schedule list can't get calendar ID because of "calendar.id = Date.now();"
It should be "calendar.id = String(Date.now());"

**Comment by adhrinae** [comment]
@LinX9581 Good news! I've just published the new version resolving the issue. You can use the latest version(v1.13.1) to use number-based calendar ids.
