### ISSUE TITLE
달력의 날짜를 한줄로 표시하는 방법

### ISSUE THREAD

**Issue by taehyunlee** [nhn/tui.calendar#837]
## Summary
한줄로 표시된 Type 'task' 달력을 만들고 있는데 도움이 필요합니다.
1. 한번에 표시될 날짜의 수를 늘리는 방법이 있습니까?
2. 표시될 날짜의 수를 늘릴 수 있다면 보여질 너비를 설정하여
 드래그나 스크롤을 사용 하고 싶습니다. 가능한 것인지

## Screenshots
![TUI_Calendar_q1](https://user-images.githubusercontent.com/5907714/122320386-18ce1800-cf5d-11eb-9a3b-77f87f9bddfd.PNG)
스크롤의 위치는 하단- 가로 스크롤

## Version
tui.calendar-1.13.0  Use.

## Additional context
달력 옵션
defaultView = 'week'
taskView: ['task']
sheduleView: false

**Comment by adhrinae** [comment]
Please make sure you have filled out the issue **respecting our form in English** and given us as much context as possible. If not, the issue will be closed or not replied to.

We don't support customizing the week view columns at this moment.
