### ISSUE TITLE
Support for a calendar height lower than 600px

### ISSUE THREAD

**Issue by RasmusVedsted** [nhn/tui.calendar#842]
## Version
v1.13.0

## Development Environment
Browser: Chrome 91.0.4472.114 (64 bit)
OS: Windows 10

## Current Behavior
When styling the calendar div with a height less than 600px, the height of the calendar does not appear any smaller than when it's styled with a height of 600px.

```js
var Calendar = tui.Calendar;

var calendar = new Calendar('#calendar', {
    defaultView: 'week',
    taskView: true
});
```

```html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.css" />

    <!-- If you use the default popups, use this. -->
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.css" />
    <link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.css" />

    <script src="https://uicdn.toast.com/tui.code-snippet/v1.5.2/tui-code-snippet.min.js"></script>
    <script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.min.js"></script>
    <script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.min.js"></script>
    <script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
</head>
<body>

    <div id="calendar" style="height: 400px;"></div>

    <script>
        var Calendar = tui.Calendar;

        var calendar = new Calendar('#calendar', {
            defaultView: 'week',
            taskView: true
        });
    </script>
</body>
</html>
```

## Expected Behavior
I expected heights of 600px and 400px to yield different visual results. Can we get support for heights smaller than 600px?

Maybe I'm going about this the wrong way? I'm trying to achieve a smaller calendar. The widths I can achieve are satisfying, but not the heights.

**Comment by adhrinae** [comment]
@RasmusVedsted
I think It's a style issue.
We made a decision that to keep `min-height` for the layout containers in order to prevent event items get shrunk.

* Related source codes
  - https://github.com/nhn/tui.calendar/blob/master/src/css/week/layout.styl
  - https://github.com/nhn/tui.calendar/blob/master/src/css/month.styl

So your approach should work after overriding some styles.
For example,

```html
<!-- on the same HTML file you wrote -->
<head>
  <style>
    /* for monthly view */
    .tui-full-calendar-month {
      min-height: auto;
    }

    /* for weekly view, please double check it has 'container' as postfix */
    .tui-full-calendar-week-container {
      min-height: auto;
    }
  </style>
</head>
```

**Comment by RasmusVedsted** [comment]
@adhrinae
Thank you! This is perfect. I had attempted some other style overrides previously, but I think I had the wrong class names, and I didn't think to use auto instead of some pixels.

My issue is indeed solved after applying the overriding style rules you provided. Thanks!
