### ISSUE TITLE
Scroll to  a certain time  

### ISSUE THREAD

**Issue by BruceLi8** [nhn/tui.calendar#845]
Hi, thanks for the pretty calendar firstly.
I wonder whether is there any way for scroll to a certain time such as 9: 00 AM , which may similar to [scrollToNow](https://nhn.github.io/tui.calendar/latest/Calendar#scrollToNow) method.

**Comment by BruceLi8** [comment]
I currently do it as below:

>`javascript
var dom = document.querySelector('.tui-full-calendar-timegrid-container');
dom.scroolTo({ top: 300 });
`

**Comment by adhrinae** [comment]
@BruceLi8 
Thanks for your support :)
Sadly, we [only support scrolling to the current time.](https://nhn.github.io/tui.calendar/latest/Calendar#scrollToNow) at this moment.

**Comment by Aerophite** [comment]
Looks like the class names have changed since a solution was posted. Current way of doing this would be with

```
var dom = document.querySelector('.toastui-calendar-time');
dom.scrollTo({ top: 300 });
```
