### ISSUE TITLE
Removing dates from the weekly calendar

### ISSUE THREAD

**Issue by RoshanPShetty** [nhn/tui.calendar#849]
Hi. Thank you for the wonderful calendar firstly. I have the created a weekly calendar below. How can I remove the dates i.e. 21, 22, 23, 24, 25 and just have Monday-Friday as the labels? I am trying to create a static schedule with recurring tasks every week so I don't require the dates. I have been going through the documentation but I couldn't find a solution. Any suggestion is appreciated. 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/CfzSD.jpg

**Comment by adhrinae** [comment]
@RoshanPShetty
Hi :wav

**Comment by RoshanPShetty** [comment]
Thank you so much!

**Comment by RoshanPShetty** [comment]
Do you happen to know how I could implement this in R? There is a ToastUI htmlwidget that I am trying to use and it has the [```cal_template()```](https://dreamrs.github.io/toastui/reference/cal_template.html) option similar to the ```template``` option you mentioned. Since the documentation is in js, I am not sure how it works with R. If you have any idea on how it can be approached, I would greatly appreciate that!
