### ISSUE TITLE
CalendarId is null after selecting another calendar in default creation popup

### ISSUE THREAD

**Issue by thisunknownuser** [nhn/tui.calendar#851]
When creating a new schedule and changing the calendar in the top dropdown, the id of the new selected calendar seems to be always null

**Steps to reproduce**

1. Open the default popup to create a new schedule
2. Select another calendar on the list
3. Click on save
4. "calendarId" is null

**What I've tried so far :**

Issue seems to be the same as #216 but the suggested solution (added line calendarId: schedule.calendarId) doesn"t solve the issue as this line is already in tui-calendar.js v 1.13.0

**Comment by adhrinae** [comment]
@thisunknownuser I found that the default popup cannot get `calendarId` when calendars have ids with the number type. This should be fixed. Please create your calendars with string ids until then.

Reference: https://github.com/nhn/tui.calendar/issues/216#issuecomment-426938599
