### ISSUE TITLE
 Can't I customize design the schedule div?

### ISSUE THREAD

**Issue by mingiki** [nhn/tui.calendar#858]
hi

1. Can't custom design the schedule div?
![image](https://user-images.githubusercontent.com/6078850/124874558-d602db80-e002-11eb-82b7-a7c5e38ea74c.png)

2. If possible, can you design a template according to month/week/day view

**Comment by adhrinae** [comment]
@mingiki You have a couple of options to customize the calendar.

- You can set [Theme Config](https://nhn.github.io/tui.calendar/latest/themeConfig)
- You can modify the CSS styles of schedule elements by yourself.
