### ISSUE TITLE
Change date format within schedule creation/edit dialog

### ISSUE THREAD

**Issue by Maximilian-L** [nhn/tui.calendar#860]
Hello everyone, 

is it currently possible to change the format of the schedule start and end dates that are displayed within the schedule creation/edit dialog without making use of a fully customized dialog?
I want to keep using the default dialogs, just with the dates formatted differently.

Thank you!

**Comment by adhrinae** [comment]
@Maximilian-L Unfortunately, [It's fixed to `yyyy-MM-dd` style at this moment.](http://github.com/nhn/tui.calendar/blob/62158bc4d711fbfd82a27e8ac213df7c562ea49b/src/js/view/popup/scheduleCreationPopup.js#L609-L610)
It would be better if the default dialog supports any different time format someday, but we're not planning it yet.
