### ISSUE TITLE
Make Toast UI Calendar Horizontally Scrollable

### ISSUE THREAD

**Issue by deadlessdead** [nhn/tui.calendar#865]
Hello I'm a newbie developer, I am trying to create page which is divided into 2 sections (using columns). TUI Calendar is in the right section. I want to make TUI Calendar not be reponsive when in tablet or phone screen size, but instead horizontally scrollable.

I tried give nowrap and overflow-x to my column but TUI Calendar still decreasing its width (responsive) but the other element is horizontally scrollable.

Can I make it horizontally scrollable? If I have to edit in CSS, can you provide me information which class do I have to edit? Thankyou.

**Comment by adhrinae** [comment]
@deadlessdead
The calendar width is relying on its container's width.
So It will be horizontally scrollable when you give enough width to the container element.

```html
<div id="calendar">
  <!-- The calendar will be mounted here -->
</div>

<style>
  #calendar {
    width: /* your choice. maybe 1280px at this time. */ 1280px;
  }
</style>

<script>
  const cal = new Calendar('#calendar', /* your option */)
</script>
```
