### ISSUE TITLE
Can I prevent only dragging schedule event without setting isReadOnly as false

### ISSUE THREAD

**Issue by mnoko33** [nhn/tui.calendar#869]
## Summary
In my case, I want to prevent only dragging schedule (drag schedule block or end of it) event which fire `beforeUpdateSchedule` handler and still use clicking empty block event which fire `beforeCreateSchedule` handler

There is `isReadOnly` props to prevent for user to do something into schedules but it also prevent fire  `beforeCreateSchedule` handler.

as a result, I want to prevent only dragging schedule event without setting isReadOnly as true
is there any function (ex. something like disableDrag??) or solution for me ?

**Comment by adhrinae** [comment]
@mnoko33
We don't provide an option preventing only dragging.
However, you can prevent dragging schedules by setting the `isReadOnly` flag to every schedule you want to make sticky.

[See `isReadOnly` flag.](https://nhn.github.io/tui.calendar/latest/Schedule)

**Comment by mnoko33** [comment]
Oh, there is isReadIOnly flag for each schedule!  
I was just looking for calendar object.. This is what I want and thanks for the quick reply
