### ISSUE TITLE
Type definitions for beforeCreateSchedule

### ISSUE THREAD

**Issue by mnoko33** [nhn/tui.calendar#870]
## Describe the bug

As interface IEvents, event handler `beforeCreateSchedule` has schedule parameter which is typeof ISchedule.
But actual object is 
```
{
  start: TzDate,
  end: TZDate,
  guide: MonthGuide,
  isAllDay: Boolean,
  triggerEventName: string
}
```

Also In document (https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule), parameter type of beforeCreateSchedule is not ISchedule.

But in Type definitions for TOAST UI Calendar v1.13.1 (index.d.ts file in project)
```
export interface IEvents {
    'afterRenderSchedule'?: (eventObj: {schedule: ISchedule}) => void;
    'beforeCreateSchedule'?: (schedule: ISchedule) => void;
    'beforeDeleteSchedule'?: (eventObj: IEventScheduleObject) => void;
    'beforeUpdateSchedule'?: (eventObj: IEventObject) => void;
    'clickDayname'?: (eventObj: IEventDateObject) => void;
    'clickMore'?: (eventObj: IEventMoreObject) => void;
    'clickSchedule'?: (eventObj: IEventScheduleObject) => void;
    'clickTimezonesCollapseBtn'?: (timezonesCollapsed: boolean) => void;
}
```

as a result, I think it should be fixed for use typescript with tui-calendar

**Comment by adhrinae** [comment]
@mnoko33 Thanks for the report. It clearly needs to be fixed.
