### ISSUE TITLE
schedules sum count

### ISSUE THREAD

**Issue by mingiki** [nhn/tui.calendar#872]
hi

every day
weekly
monthly

Can't count the number of schedules in units?

Is there an API to get the number of displayed schedules?

ex)
![image](https://user-images.githubusercontent.com/6078850/128669505-00861c2a-9cbb-48bc-a674-da502dad61a9.png)

![image](https://user-images.githubusercontent.com/6078850/128669413-ed8b0d41-8458-425d-9a32-e0312f81904e.png)

![image](https://user-images.githubusercontent.com/6078850/128669480-e14c7f23-4e40-40ec-a69b-9f5b2862444f.png)

**Comment by adhrinae** [comment]
@mingiki
We don't have an interface to provide data of `Schedule` yet. You might need to manage another set of schedules and sync it to the calendar. and use the other set of schedules to extract information like the total count of schedules.

I understand this is a very uncomfortable approach. So Would it be ok if there's an API to get all schedules as an array? That wouldn't be hard to implement.

```js
const cal = new Calendar(container, { /* ... */ });

cal.getAllSchedules(); // [/* a list of schedules you added by order */];
```

Except that, It's hard to provide an interface getting all schedules prettier at this moment.

**Comment by adhrinae** [comment]
@mingiki We decided not to implement a new API since the whole schedule data come from the outside of the calendar.

You need to implement your own calculation methods and inject those numbers into the calendar with templates.
