### ISSUE TITLE
Customize creation popup

### ISSUE THREAD

**Issue by saraxp98** [nhn/tui.calendar#884]
## Version
@version 1.13.1 | Tue Jul 06 2021

## Development Environment
- language: Javascript
- browser: Chrome

```js
/* calendar opts */
var calendar = new tui.Calendar('#calendar', {
        defaultView: 'month',
        taskView: false,     
        scheduleView: true, 
        useCreationPopup: true, 
        useDetailPopup: true,   
        template: { //template calendario e popups
            task: function (schedule) {
                return '#' + schedule.title;
            },
            taskTitle: function () {
                return '<span class="tui-full-calendar-left-content">TASK</span>';
            },
            allday: function (schedule) {
                return getTimeTemplate(schedule, true);
            },
            alldayTitle: function () {
                return '<span class="tui-full-calendar-left-content">ALL DAY</span>';
            }, 
            time: function (schedule) {
                return '<strong>' + moment(schedule.start.getTime()).format('HH:mm') + '</strong> ' + schedule.title;
            },
            titlePlaceholder: function () {
                return 'Attività';
            },
            locationPlaceholder: function () {
                return 'Luogo';
            },
            startDatePlaceholder: function () {
                return 'Inizio';
            },
            endDatePlaceholder: function () {
                return 'Fine';
            },
            popupSave: function () {
                return 'Salva';
            },
            popupUpdate: function () {
                return 'Aggiorna';
            },
            popupEdit: function () {
                return 'Modifica';
            },
            popupDelete: function () {
                return 'Elimina';
            },
            popupDetailDate: function (isAllDay, start, end) {
                let startDate = new Date(start);
                let endDate = new Date(end);

                console.log('startDate: ' + startDate);
                console.log('endDate: ' + endDate);

                let isSameDate = moment(startDate).isSame(endDate);
                let endFormat = (isSameDate ? '' : 'DD.MM.YYYY ') + 'HH:mm';

                if (isAllDay) {
                    return moment(startDate).format('DD.MM.YYYY') + (isSameDate ? '' : ' - ' + moment(endDate).format('DD.MM.YYYY'));
                }
                return (moment(startDate).format('DD.MM.YYYY') + ' ' + moment(startDate.getTime()).format('HH:mm') + ' - ' + moment(endDate.getTime()).format(endFormat));
            },
            popupDetailLocation: function (schedule) {
                return 'Luogo : ' + schedule.location;
            },
            popupDetailUser: function (schedule) {
                return 'Partecipanti: ' + (schedule.attendees || []).join(', ');
            },
            popupDetailState: function (schedule) {
                return 'Stato: ' + schedule.state || 'Busy';
            },
            popupDetailRepeat: function (schedule) {
                return 'Ricorsivit&agrave;: ' + schedule.recurrenceRule;
            },
            popupDetailBody: function (schedule) {
                return 'Altri dettagli: ' + schedule.body;
            }
        },
        month: {
            daynames: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
            startDayOfWeek: 1
        },
        week: {
            daynames: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
            startDayOfWeek: 1
        },
        calendars: calendars   
    });

/* saveNewSchedule method */
function saveNewSchedule(scheduleData) {
        let scheduleId = String(Date.now()) + getRandomNum();

        const schedule = {
            id: scheduleId,                  
            calendarId: scheduleData.calendarId,  
            title: scheduleData.title,         
            body: scheduleData.body,            
            start: scheduleData.start,         
            end: scheduleData.end,              
            isAllDay: scheduleData.isAllDay,    
            category: scheduleData.isAllDay ? 'allday' : 'time',  
            dueDateClass: '',                 
            attendees: scheduleData.attendees,  
            recurrenceRule: scheduleData.recurrenceRule,       
            isVisible: scheduleData.isVisible,  
            isReadOnly: scheduleData.isReadOnly,
            color: calendars.color,          
            bgColor: calendars.bgColor,      
            dragBgColor: calendars.bgColor, 
            borderColor: calendars.borderColor,                
            customStyle: scheduleData.customStyle,              
            state: scheduleData.state           
        };
        calendar.createSchedules([schedule]);
    }

calendar.on({
        clickMore: function (e) {
            console.log('clickMore', e);
        },
        clickSchedule: function (e) {
            console.log('clickSchedule', e);
        },
        clickDayname: function (date) {
            console.log('clickDayname', date);
        },
        beforeCreateSchedule: function (e) {
            console.log('beforeCreateSchedule', e);
            saveNewSchedule(e);
            //e.guide.clearGuideElement();
        },
        beforeUpdateSchedule: function (e) {
            const {schedule, changes} = e;
            console.log('beforeUpdateSchedule', e);

            /*TODO:
            if (schedule.isReadOnly === false) {
                calendar.updateSchedule(schedule.id, schedule.calendarId, changes);}
            */
        },
        beforeDeleteSchedule: function (e) {
            console.log('beforeDeleteSchedule', e);
            calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);
        },
        afterRenderSchedule: function (e) {
            const schedule = e.schedule;
            let element = calendar.getElement(schedule.id, schedule.calendarId);
            console.log('afterRenderSchedule', element);
        }
    });
```

## Current Behavior
Creation popup not showing "read only" & "attendees" options and show only "private" padlock.

## Expected Behavior
I would to custumize the creation popup, but I can't find the way to do this.
I've to show "Read only","Attendees" field s and remove "Private" padlock.
How can I proceed?
I read about this:
https://github.com/nhn/tui.calendar/blob/master/docs/getting-started.md#customize-popups
So far everything ok! ...But how can I "pass" the my template to use it? And where\how should I write it??

Thanks!!!

**Comment by adhrinae** [comment]
@saraxp98 Unfortunately, the default creation popup is not so much customizable.

Those templates are for button labels, datetime formats, etc. Here's an example page.

https://nhn.github.io/tui.calendar/latest/tutorial-example16-template-for-popup

So You need to implement your own creation popup and decide when you show that popup.
Mostly leveraging the `beforeCreateSchedule` would work. Get the start & end dates from the event, then open your popup passing data. That's the meaning of the doc you mentioned.

**Comment by saraxp98** [comment]
@adhrinae I read about issue #231.
So, for customizing the creation popup I've to fork nhn repo and change only these files? :

https://github.com/nhnent/tui.calendar/blob/master/src/js/view/popup/scheduleCreationPopup.js
https://github.com/nhnent/tui.calendar/blob/master/src/js/view/template/popup/scheduleCreationPopup.hbs
https://github.com/nhnent/tui.calendar/blob/master/src/js/view/popup/scheduleDetailPopup.js
https://github.com/nhnent/tui.calendar/blob/master/src/js/view/template/popup/scheduleDetailPopup.hbs

I have to install webpack and karma for run command "npm run test" & "npm run serve" and also for view my local changes to my repo?

**Comment by adhrinae** [comment]
@saraxp98
Yes. Perhaps you're not familiar with the Node.js ecosystem. `npm install` is the starting point for developing the project. This will install all dependencies into the project folder including Karma, Webpack.

You may need to add your own properties to these lines of code for adding read-only, attendees.

https://github.com/nhn/tui.calendar/blob/ebca413403c4caaba19670b57e0224945351f752/src/js/view/popup/scheduleCreationPopup.js#L274-L283

`npm run serve` command will fire up the dev server. You can open the browser and play around with your local changes through `localhost:8080`. Check the `example` folder.

You might not need to execute `npm run test`, but If you want to test your own dialog, you can write test and run it with that command.

**Comment by saraxp98** [comment]
@adhrinae Sorry but I've a problem...
I followed your instructions and I removed "location" (line 277):
![image](https://user-images.githubusercontent.com/37674460/132311574-15048cea-721e-4f72-a99c-4112b624ce44.png)

I executed `npm run bundle` and pushed changes to my Git repo: https://github.com/sarabEriced/tui.calendar.git .
But when I download my repo with Bower in my project (`bower install https://github.com/sarabEriced/tui.calendar.git`) seems to download the NHN's repo.
I checked my online repo and changes were pushed (sarabEriced/tui.calendar/dist/tui.calendar.js)

What I'm doing wrong?

**Comment by saraxp98** [comment]
> @adhrinae Sorry but I've a problem...
> I followed your instructions and I removed "location" (line 277):
> ![image](https://user-images.githubusercontent.com/37674460/132311574-15048cea-721e-4f72-a99c-4112b624ce44.png)
> 
> I executed `npm run bundle` and pushed changes to my Git repo: https://github.com/sarabEriced/tui.calendar.git .
> But when I download my repo with Bower in my project (`bower install https://github.com/sarabEriced/tui.calendar.git`) seems to download the NHN's repo.
> I checked my online repo and changes were pushed (sarabEriced/tui.calendar/dist/tui.calendar.js)
> 
> What I'm doing wrong?


I resolved this problem creating a new version for my fork with command `bower tag "1.xx.x"` & `git push --tag` . In my project I installed my repo in this way: `bower install https://github.com/sarabEriced/tui.calendar.git#1.xx.x`

**Comment by saraxp98** [comment]
![image](https://user-images.githubusercontent.com/37674460/132345084-182f65b2-9e8f-4918-87e8-57c98d0faec4.png)
I downloaded my fork (I removed all references to "location" in scheduleCreationPopup.js) but it seems not working... The problem now, as you see ^^^, is that "Location" field continues appearingin my project.

there are somethng else to change in my fork in addition to scheduleCreationPopup.js?

**Comment by adhrinae** [comment]
@saraxp98 
First of all, you don't need to publish a package to use your forked version of the library. Just bundle it and move bundles in the `dist` folder to somewhere your project folder. then import it.

```js
// for example, in your code
import Calendar from './external/tui-calendar';
```

And I thought you caught the context in [the previous comment](https://github.com/nhn/tui.calendar/issues/884#issuecomment-909259720) about which files should be modified. As you mentioned, You need to modify only the form data of `scheduleCreationPopup.js`, but also template files ending with the `.hbs` extension.

**Comment by saraxp98** [comment]
@adhrinae ok, thank you for your reply.
I hope this is the last question...

@dongsik-yoo or @adhrinae:
Normally (by installing NHN tui.calendar `bower install tui-calendar`) how does it "import" the .hbs files and where are they placed?

Thank you!

**Comment by saraxp98** [comment]
> @adhrinae ok, thank you for your reply.
> I hope this is the last question...
> 
> @dongsik-yoo or @adhrinae:
> Normally (by installing NHN tui.calendar `bower install tui-calendar`) how does it "import" the .hbs files and where are they placed?
> Correct me if i'm wrong...to use my .hbs files i've to change all directoys only in the scheduleCreationPopup.js file..?
> 
> Thank you!


I found the problem. With `npm run bundle` minified files (that we use in production) were not updated because I had not install win-node-env (`npm install -g win-node-env`). After installing it and after running `npm run bundle` another time, all works!

**Comment by adhrinae** [comment]
@saraxp98
I'm glad to hear that :) Hope you can enjoy making your application with the calendar.
