### ISSUE TITLE
Navigation between Calendar views

### ISSUE THREAD

**Issue by GloriaTwebaze** [nhn/tui.calendar#888]
How can I customize this calendar from month view to year view? I want to be able to navigate through all the months of the year to view different events, am finding it hard to find where you implemented the buttons you used at the top of the calendar. Am using react typescript
Thank you.

**Comment by adhrinae** [comment]
@GloriaTwebaze 

There are useful methods you can manipulate the calendar view.

- https://nhn.github.io/tui.calendar/latest/Calendar#prev
- https://nhn.github.io/tui.calendar/latest/Calendar#next
- https://nhn.github.io/tui.calendar/latest/Calendar#today
- https://nhn.github.io/tui.calendar/latest/Calendar#changeView

The example code is just binding those methods to buttons. so you need to create event handlers invoking the certain method and bind them into your `button` component.

```jsx
const MyCalendar = () => {
  // ...
  const calendarRef = useRef(); // this will store the `Calendar` instance.
  // ...

  const handleClickPrev = () => {
    calendarRef.current.prev();
  }
  // and other handlers
  
  return (
    <div>
      <button onClick={handleClickPrev}>←</button>
      {/* */}
    </div>
  )
}
```

**Comment by GloriaTwebaze** [comment]
hey

Thank you so much for your response
However, am wondering if you are free with zoom calls or google meet
i would kindly ask you to look at my code and calendar.
am trying to implement it into a web app but everything doesnt look and
work like expected compared to yours.

The pops got distorted, am finding it difficult to customise them.
Do you have tsx implementation of it?

patiently waiting for your response

Thanks and regards
Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze 
Would this work for you? This is a very simple example to implement navigation for the calendar.

https://codesandbox.io/s/implement-tui-calendar-nav-b3kr4

Or If you're dealing with unexpected rerenders while managing states of your app, try [the React wrapper](https://github.com/nhn/toast-ui.react-calendar) of the calendar.

**Comment by GloriaTwebaze** [comment]
Thank you for your reply

am using this very example however , it cant seem to get where i can
customise the popups. especially the creation popup
could you please advise

Thanks

Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze 
You can refer the issue #884.
Customizing popups is quite limited at this moment. So you need to implement your own popup and connect to the `beforeCreateSchedule` event or fork the repo and customize the source directly.

**Comment by GloriaTwebaze** [comment]
Thanks a million Ahn,
And sorry for incovenienting.
One last question,
could you please help me with link to the repo so i try out with the source
code?

Thank you
Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze 
I meant that you can fork [this calendar source code](https://github.com/nhn/tui.calendar) and research it on your own.

That might be hard for you, but I'm not able to help you with the detail.

**Comment by GloriaTwebaze** [comment]
Hello there

Hope this email finds you well

Could you please advise on how I can have my date mounted like how you did
yours below
[image: Screenshot (609).png]

I have the buttons functioning but displaying date, month, year one has
clicked is not working

Thanks and regards
Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze I cannot see your screenshot.
And since I don't understand your description and intention, Please give me some sample code or sandbox like I uploaded.

**Comment by GloriaTwebaze** [comment]
Hello,

Thanks for your response
i have attached two screenshots, one is yours highlighting what i want to
achieve and mine showing the progress.
My intention is to display  the year, month and day when one navigates
through the calendar
with below functions i was able to navigate through different months but
one cant know which month exactly they have clicked on.

function onClickTodayBtn() {
        cal.current.calendarInst.today()
        cal.current.calendarInst.changeView("day", true)
    }

    const moveToPrev = () => {
        cal.current.calendarInst.prev()
    }
    const moveToNext = () => {
        cal.current.calendarInst.next()
    }

**Comment by GloriaTwebaze** [comment]
Thank you @Dohyung Ahn!
I have been trying out this but it's giving me trouble. Could there be a
typescript implementation of it?

Kindly advise.

Thanks
Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze 

https://codesandbox.io/s/quizzical-babycat-kglbx?file=/src/App.tsx

Is this enough for you?

BTW, In this use case, you don't need to use [the react wrapper](https://github.com/nhn/toast-ui.react-calendar).

And Please leave details when you ask questions as far as you can.

**Comment by GloriaTwebaze** [comment]
Hey Dohyung

Thank you so much this was very helpful.
However I have one more last one.
How to apply different colors for different created events. I want my
events to differ from each other by having different colors
How do i go about that in typescript still?

Thanks and regards
Gloria

**Comment by adhrinae** [comment]
@GloriaTwebaze Every schedule has `color` and `bgColor` properties. You can set colors with them.

https://nhn.github.io/tui.calendar/latest/Schedule

I'm not willing to teach you TypeScript because it seems to be irrelevant to the library's type definition file. If you find the bug of the type definition file so you can't write the program, override it and create a bug issue.
