### ISSUE TITLE
Can we have horizontal day view of calendar please?

### ISSUE THREAD

**Issue by sunnykoundal** [nhn/tui.calendar#889]
## Version
Write the version that you are currently using.

## Development Environment
Write the browser type, OS and so on.

## Current Behavior
Write a description of the current operation. You can add sample code, 'CodePen' or 'jsfiddle' links.

```js
// Write example code
```

## Expected Behavior
Write a description of the future action.

**Comment by adhrinae** [comment]
@sunnykoundal 
Unfortunately, we don't consider implementing this feature.
