### ISSUE TITLE
Materialize messing with styling of the tui-calendar-popup

### ISSUE THREAD

**Issue by FelixBrgn** [nhn/tui.calendar#890]
## Describe the bug
I have an angular project and added the tui-calendar and the materialize styling is overwriting some of the styling. How can I deactivate the styling or make the tui-styling "!important"

## Screenshots
![image](https://user-images.githubusercontent.com/57171559/132479273-b75c0729-a503-4935-bcfb-3ef71db594f0.png)

**Comment by adhrinae** [comment]
@FelixBrgn 

First of all, Did you import other stylesheets for the popup? You need to import dependant stylesheets if you want to use the default popup.

https://github.com/nhn/tui.calendar#using-module-format-in-node-environment

And the style of the popup is defined [here](https://github.com/nhn/tui.calendar/blob/e125cb2b2e83a189620429e5d1a673f637690a87/src/css/popup.styl). You might need to check other stylesheets.

https://github.com/nhn/tui.date-picker/blob/master/src/css/calendar.css
https://github.com/nhn/tui.time-picker/blob/master/src/css/timepicker.css

**Comment by FelixBrgn** [comment]
Imported in my component.ts file like: 
@import "tui-calendar/dist/tui-calendar.css";

@import "tui-date-picker/dist/tui-date-picker.css";
@import "tui-time-picker/dist/tui-time-picker.css";

Also, the tui-calendar-styling is added as can be seen in the screenshot. The problem is that also materialize styling gets laid over it.

**Comment by adhrinae** [comment]
@FelixBrgn 
Since I don't know about Angular and Materialized CSS framework, You need to figure out what kind of styles are overridden by Materialized. I can't help with that. and this is not a but of the calendar.

Because it works well without any external CSS framework.

Please check CSS rules in stylesheets as I mentioned above.
