### ISSUE TITLE
unable to create schedule in day view

### ISSUE THREAD

**Issue by nandodefaria** [nhn/tui.calendar#891]
## Describe the bug
Hi! Nothing works when in daily view screen (no selectable action, time select, drag option).  The other views, everything works fine. Who's missing?
Using the latest tui calendar.

**Comment by adhrinae** [comment]
@nandodefaria
It seems ok on my side.
Could you share a sandbox(i.e. codesandbox, stackblitz) reproducing the bug so that I can check the issue?

**Comment by nandodefaria** [comment]
Hi!Thanks for the ultra fast feedback....I fixed...rss It was a div wirh position:relative the was messing with the daily format.

**Comment by adhrinae** [comment]
@nandodefaria 
Good to hear that :) Happy coding!
