### ISSUE TITLE
Sorry for my ignorance, but where does create schedule stay?

### ISSUE THREAD

**Issue by nandodefaria** [nhn/tui.calendar#893]
Hi! Where do i put calendar.createSchedules? Inside <script> tag in html or inside app.js?

Thanks

**Comment by adhrinae** [comment]
@nandodefaria 
It doesn't matter. Just be sure you put the script in the right order.
As long as putting your scripts after importing `tui.calendar`.
This article might be helpful.

https://newbedev.com/load-and-execute-order-of-scripts
