### ISSUE TITLE
Please help me next() 2 weeks or 3 weeks, or next month in WeekView?

### ISSUE THREAD

**Issue by lieuavlq** [nhn/tui.calendar#895]
## Summary
I want to click button and schedule show next 2 weeks, or next month in 
defaultView: 'week',
taskView: false,
scheduleView: ['allday'],

## Screenshots
https://gyazo.com/ff6fa395546f2241c93612cbdffebae0

**Comment by adhrinae** [comment]
@lieuavlq 
You need to implement your own navigation buttons.
the `Calendar` instance has several methods to help you with.

Duplicated to #888
