### ISSUE TITLE
How to click a schedule behind a guide Element?

### ISSUE THREAD

**Issue by hyunibbal** [nhn/tui.calendar#896]
Hi, Thank you for awesome calendar.
I have two questions.

1. If schedule element and guide element overlap, I can't click schedule element.
![image](https://user-images.githubusercontent.com/34429030/132798129-c7d19083-5570-4f47-a364-03503126f2f9.png)

2. In this situation, I can't click any element. Any event never fire. 
![image](https://user-images.githubusercontent.com/34429030/132799707-1a7fea44-476c-4c47-a0b4-5c262867ddd2.png)

## Version
@toast-ui/react-calendar@1.0.5 (includes tui-calendar@1.12.5)

**Comment by adhrinae** [comment]
@hyunibbal 
As long as the guide exists, the click event cannot find related elements except the guide element.

http://github.com/nhn/tui.calendar/blob/ebdbe37cd98be821dd22a7c0eefcd241349fd65a/src/js/handler/month/click.js#L53-L87

You need to remove the guide before executing other actions.
