### ISSUE TITLE
Display event/schedule body data already in week view

### ISSUE THREAD

**Issue by Possommi** [nhn/tui.calendar#898]
I was curious whether it is possible to display more data of an event e.g. the data in body already in the week view. Thus the question is how can one customize the way events/schedules are displayed in the week view.

## Version
1.14.1

**Comment by adhrinae** [comment]
@Possommi Currently, There are no customizable options to display the body of the timed event in the week view.

It only works for all-day events, but there's not enough space to show the body.
https://nhn.github.io/tui.calendar/latest/tutorial-example15-template-for-timegrid

**Comment by Possommi** [comment]
Thank you for your answer.
