### ISSUE TITLE
IE browser version 11 schedule-block left: 0%, top: 0px, width: 0%

### ISSUE THREAD

**Issue by lieuavlq** [nhn/tui.calendar#899]
## Describe the bug
Please check bug on IE version 11 and IOS, schedule-block show error? plz?

## Screenshots
https://gyazo.com/24ea849264f3ca1e11b5ebda5658680c

**Comment by adhrinae** [comment]
@lieuavlq 
I don't understand the exact situation.
Please give me the precise context like steps to reproduce bugs, example codes, etc.

BTW, Did you set the fixed container size for the calendar? That might be helpful.

**Comment by lieuavlq** [comment]
> @lieuavlq
> I don't understand the exact situation.
> Please give me the precise context like steps to reproduce bugs, example codes, etc.
> 
> BTW, Did you set the fixed container size for the calendar? That might be helpful.

Ah i fixed, so i input 2021-09-09 00:30:00 lead to bug on IE and IOS, thanks for reply!

**Comment by adhrinae** [comment]
@lieuavlq 
Hmm.. ok. but If you have time, please describe the bug and the solution in detail so that others will get help from this issue.

**Comment by lieuavlq** [comment]
This is my code:
`var calendar = new tui.Calendar('#calendar', {
    defaultView: 'week',
    taskView: false,
    scheduleView: ['allday'],
    week: {
      daynames: ['（日）','（月）','（火）','（水）','（木）','（金）','（土）'],
      startDayOfWeek: 1
    },
    template: {
      allday: function(schedule) {
        return '<a href="/event/list.html"><span class="tui-full-calendar-weekday-schedule-title">' + schedule.title + '</span><span class="tui-full-calendar-weekday-schedule-body">' + schedule.body + '</span></a>';
      },
      weekDayname: function(dayname) {
        var spl = (dayname.renderDate).split('-');
        return '<span class="calendar-week-dayname-date">' + parseInt(spl[1]) + '/' + dayname.date + '</span><br><span class="calendar-week-dayname-name">' + dayname.dayName + '</span>';
      }
    }
  });

  calendar.createSchedules([
    {
      id: '1',
      calendarId: '1',
      title: 'ID1 My title',
      body: 'My body content',
      category: 'allday',
      start: '2021-09-13T22:30:00+09:00',
      end: '2021-09-16T15:30:00+09:00'
    },
    {
      id: '2',
      calendarId: '1',
      title: 'ID2 My title',
      body: 'My body content',
      category: 'allday',
      start: '2021-09-13T17:30:00+09:00',
      end: '2021-09-20T17:31:00+09:00'
    }
  ]);`

This is screenshot for result: https://gyazo.com/bdd7dbd06b6780b38130dcb963b7d2e0

So when i change code
`calendar.createSchedules([
    {
      id: '1',
      calendarId: '1',
      title: 'ID1 My title',
      body: 'My body content',
      category: 'allday',
      start: '2021-09-13 22:30:00',
      end: '2021-09-16 15:30:00'
    },
    {
      id: '2',
      calendarId: '1',
      title: 'ID2 My title',
      body: 'My body content',
      category: 'allday',
      start: '2021-09-13 17:30:00',
      end: '2021-09-20 17:31:00'
    }
  ]);`

And bug happen: https://gyazo.com/5d6edf7b9d3b8347e4f7189da1f9d8cb

This bug show on IE and Safari (IOS)

**Comment by adhrinae** [comment]
@lieuavlq I see. When you create schedules, `start` and `end` values will be passed the argument of the `Date` constructor. The result might vary by browser and timezone.

http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
