### ISSUE TITLE
Is it possible to prevent multiple event times on the same day from crossing over?

### ISSUE THREAD

**Issue by Alextbush-gg** [nhn/tui.calendar#901]
Hello,

I am building a schedule calendar that allows users to submit their own events into the calendar. 

If an event for a given day already exists, the time period it occupies needs to be blocked out for any additional events created on the same day. 

Is it possible to remove the time periods that have already been booked for any additional events on the same day?

**Comment by adhrinae** [comment]
@Alextbush-gg 
You can use the `beforeCreateSchedule` event to get the time period from the user.

https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule

After getting datetime information, you will be able to check whether it is available for a certain period.
