### ISSUE TITLE
Not able to create new schedules

### ISSUE THREAD

**Issue by nandodefaria** [nhn/tui.calendar#903]
Hi! I'm sorry but i cannot create new schedules. I've tried to insert the create new schedule in my page cshtml where the calendar is but i get the "is not a function' error. I tested inside <script> tags, inside div tags but nothing. Am i missing something?
I'm using the latest calendar, npm and my solution is .net mvc.
I'm a new of programmer...rs
Thanks.

**Comment by adhrinae** [comment]
@nandodefaria 
I cannot help you as long as you don't provide enough context for the question.
I don't know how your project is structured, how did you write your HTML file, where did you put the script, etc.

As I mentioned in #893, I think You need to understand how to use Javascript on your webpage first.

**Comment by nandodefaria** [comment]
This is my cshtml:

@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{ ViewData["Title"] = "Inicio"; }

<div class="container fundo_branco ">
    <div class="cabecalho_1">
        <p>@ViewData["Title"]</p>
    </div>
    <div class="row justify-content-lg-center">
        <div class="col-12"> 
            @if (SignInManager.IsSignedIn(User))
            {
                <div id="calendar" class="justify-content-lg-center " style="background-color:#fff;margin-left:-2px;width:350px!important;margin-bottom:50px;"></div>
            }
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="/js/tui-code-snippet.min.js"></script>
<script src="/js/tui-time-picker.min.js"></script>
<script src="/js/tui-date-picker.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chance/1.0.13/chance.min.js"></script>    
<script src="/Calendario/dist/tui-calendar.min.js"></script>
<script src="/Calendario/js/data/calendars.js"></script>
<script src="/Calendario/js/data/schedules.js"></script>
<script src="/Calendario/js/app.js"></script>        
 
It does load the calendar, create new schedules in month, week, day from the popup (it points to app.js ok). 
You are right about the js. If you could point me to a direction, i would learn from threre...rs

Thanks.

**Comment by adhrinae** [comment]
@nandodefaria 
Following [this tutorial](https://developer.mozilla.org/en-US/docs/Learn) will be helpful.
And try to put your own script at the last of your `script` tags. Still don't get a context about the problem though.

**Comment by nandodefaria** [comment]
Thanks! The problem is that i want to manually create a new schedule from the index (not the popup) like posted in the example: calendar.createSchedules([
    {
        id: '1',
        calendarId: '1',
        title: 'my schedule',
        category: 'time',
        dueDateClass: '',
        start: '2018-01-18T22:30:00+09:00',
        end: '2018-01-19T02:30:00+09:00'
    }
])
so after create is successfully, i can bring and save in db. How do i write the instruction above and where? This is suppose to point to the function in the app.js, right? Thanks for your patience!!

**Comment by adhrinae** [comment]
Let's tear down your intention.

> want to manually create a new schedule from the index (not the popup) like posted in the example
- What example? in our documentation site?
- the index? your `index.html` page?
- and do you want to create a button making an arbitrary schedule? or something else?

> bring and save in db
- Maybe you want to save the schedule in the browser and save it to the server. That's why you're project is based on ASP.Net, which I don't know about it.
- That would be more complicated if you don't have the knowledge about how to request to the server 
from the client(browser) in Javascript.
  - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
- you may write your instruction inside the `beforeCreateSchedule` event. Like its name, you can communicate with the server and call the `createSchedule` method after the server responds with the 'OK' status.
  - https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule

---

Please read [this instruction](https://stackoverflow.com/help/how-to-ask) before you ask someone about something. Writing an apropriate question is the most basic and the most important skill as a programmer.

When you ask about the code, use [code block](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

Learning programming is a very long journey. but there are tons of resources you can get help if you can utilize them.

**Comment by nandodefaria** [comment]
Better explanation:
I'm using .net mvc. The solution is a implementation of an odontologic clinic. The professional, clientes and the clinic have calendars (wich will be rendered in there own pages). In this first attempt, i'm trying to create a schedule:
Inside the Index.cshtml with the calendar. If i can create from there, i can load the data from a model.schedule array and do a for loop to populate the data from the db. This won't have a bottom, because it must be loaded with the calendar.

"you may write your instruction inside the beforeCreateSchedule event. Like its name, you can communicate with the server and call the createSchedule method after the server responds with the 'OK' status."

So, all the code functions i need are in the app.js? Functions to save, update, delete, etc.?

I'll try this! by this i mean studie...rs 
Would have an example of how to fetch from and to functions? 
Thanks!! You are 100+ on speed and kindness!! 






    On Tuesday, September 14, 2021, 02:37:38 AM GMT-3, Dohyung Ahn ***@***.***> wrote:  
 
 


Let's tear down your intention.


want to manually create a new schedule from the index (not the popup) like posted in the example

   
   - What example? in our documentation site?
   - the index? your index.html page?
   - and do you want to create a button making an arbitrary schedule? or something else?


bring and save in db

   
   - Maybe you want to save the schedule in the browser and save it to the server. That's why you're project is based on ASP.Net, which I don't know about it.
   - That would be more complicated if you don't have the knowledge about how to request to the server   
from the client(browser) in Javascript.      
      - https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

   - you may write your instruction inside the beforeCreateSchedule event. Like its name, you can communicate with the server and call the createSchedule method after the server responds with the 'OK' status.      
      - https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule


Please read this instruction before you ask someone about something. Writing an apropriate question is the most basic and the most important skill as a programmer.

When you ask about the code, use code block.

Learning programming is a very long journey. but there are tons of resources you can get help if you can utilize them.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
