### ISSUE TITLE
Compatibility with Lit-Element or Polymer?

### ISSUE THREAD

**Issue by hfazai** [nhn/tui.calendar#904]
Thanks for providing such wonderful javascript library!

I'm wondering if I can use tui celendar within Lit-Element or Polymer?

**Comment by adhrinae** [comment]
@hfazai I'm afraid not. This library doesn't consider compatibility with the web component yet.

I nearly succeed to mount the `Calendar` instance to the shadow dom, however, I couldn't find the way to bring the default stylesheet.

**Comment by hfazai** [comment]
@adhrinae Thanks for the answer. Do you recommand any open source library working with web components?

**Comment by hfazai** [comment]
> @hfazai How about the [fullcalendar.io](https://github.com/fullcalendar/fullcalendar)?
> I didn't try it, although there was a resolved shadow DOM issue about it.

Ok I will give it a try. Thanks.

My question has been answered, so I'm going to close this issue. :+1:
