### ISSUE TITLE
How to keep row height in proportion across all breakpoints

### ISSUE THREAD

**Issue by bkline** [nhn/tui.calendar#906]
## Summary
Can you please tell me which setting to use to tell the calendar to keep the "week" row heights in proportion with the cell widths of the "month" view so that the appearance is not so unappealingly stretched out on smaller devices?

## Screenshots
![image](https://user-images.githubusercontent.com/1634628/135750866-c3118479-3edf-4245-9d4e-6176b5955fb2.png)

## Version
1.14.1, installed with `npm`.

**Comment by bkline** [comment]
Yeah, I tried lowering the container height, but below a certain value the calendar ignores what I specify when it calculates the row height.

**Comment by adhrinae** [comment]
@bkline Please refer to [this issue](https://github.com/nhn/tui.calendar/issues/842).

**Comment by bkline** [comment]
Thanks, that's helpful. Might be useful to add that information to the documentation.
