### ISSUE TITLE
modal links target missing

### ISSUE THREAD

**Issue by ikerib** [nhn/tui.calendar#907]
version 1.1.1
Ubuntu. Chrome/Firefox

We are using this library but we have an issue. In our database we store de event details sometimes with a link witch has a target="_blank" but when it is rendered in the popup the target is deleted. Is ther any way to keep that? We need this links to be opened in a new tab/window

this is how we store schedule body for example:
`<div><a href="https://www.google.es" target="_blank">testing modal is opened in a new tab></div>`

but when it is rendered the popup code is like this:
```
<span class="tui-full-calendar-content">
    <pre>
        <a href="https://www.google.es">testing modal is opened in a new tab</a>
    </pre>
</span>
```

thanks in advance

**Comment by adhrinae** [comment]
Transferring the issue from the vue-calendar repo since it's related to the core.
