### ISSUE TITLE
Redirect events do not work

### ISSUE THREAD

**Issue by kolia-zamnius** [nhn/tui.calendar#911]
## Describe the bug
Redirect events do not work when clicking on a link anywhere in the document.

## Expected behavior
Option to disable this setting. Or remove this behavior altogether.

**Comment by adhrinae** [comment]
@kolia-zamnius 
I'm afraid I can't understand your request.

- Did you mean that you cannot click any links in your document?
- How exactly does it have any relationship with the calendar?
- Can you show any example code to reproduce the problem? Any sandboxes like JSFiddle, Codesandbox, Glitch would be fine.
