### ISSUE TITLE
how to Disabled Schedule dragging without isReadOnly(Schedule, Calendar): true ?

### ISSUE THREAD

**Issue by mspark2Dev** [nhn/tui.calendar#921]
## Summary
how to Disabled Schedule dragging without isReadOnly(Schedule, Calendar): true ?

I can't turn it off, but can editing

**Comment by adhrinae** [comment]
@mspark2Dev As I mentioned in #869, There's no option to prevent dragging only.

**Comment by mspark2Dev** [comment]
@adhrinae 
This problem was solved by using drag editing.
Thank you for comment :)

**Comment by adhrinae** [comment]
@mspark2Dev 
That's good to know 👍 But I still don't understand your question and the solution.

Could you paste a code that solved your problem?
