### ISSUE TITLE
how can I decrease the width of the first column (hour) so that it takes less space on mobile weekly view, meaning there's more room for the actual events

### ISSUE THREAD

**Issue by ilija-jovev** [nhn/tui.calendar#923]
![image](https://user-images.githubusercontent.com/84774063/140022520-5b06a5fd-18ff-4cab-8490-c3383b74b008.png)

I would like to decrease the width of the left-most column (showing the hour of the day) in mobile weekly view, so that there's more space for the events to be displayed better. Is there any way to do this?

**Comment by adhrinae** [comment]
@ilija-jovev 
There's a `theme` option to adjust some component styles.

https://nhn.github.io/tui.calendar/latest/themeConfig

You'll need to set properties below:  
- `week.daygridLeft.width`
- `week.timegridLeft.width`

It's a little bit hard to recognize to point out the right property for each user's demands. Hope this example helps you.

```js
const cal = new Calendar(document.getElementById('calendar'), {
  defaultView: 'week',
  taskView: false,
  theme: {
    'week.daygridLeft.width': '48px',
    'week.timegridLeft.width': '48px',
  },
});
```
