### ISSUE TITLE
RecurrenceRule Format?

### ISSUE THREAD

**Issue by WillTA5** [nhn/tui.calendar#924]
I'm trying to implement the TUI Calendar and want to make use of recurring schedules while importing events from my outlook calendar.

The TUI documentation is no help at all other than letting us know that the recurrenceRule must be a string. 
 
I know this question was asked before (https://github.com/nhn/tui.calendar/issues/371) but I couldn't see any useful response. I attempted to implement the way that is shown in the link to  Dooray!'s RFC5545 rule (https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html) but no matter what I tried I couldn't get it to work.

After a lot of research I gave up and started to create a function that will manually loop through all occurrences within the recurrence range however its proving to be a tedious process and would I was wondering if anyone could shed some light on a way to get the recurrence rule that is built into TUI to work.

Thanks in advanced - A distressed and mildly annoyed developer.

**Comment by adhrinae** [comment]
@WillTA5 
In the calendar's schedule model, `recurrenceRule` is just a property to save any kind of recurrence rule for developers trying to implement recurring events on their own.

So You'll need to make a rule to parse the recurrence rule and convert it into recurring events.

I understand the documentation isn't helpful for you. Someday we will improve it but... :(

If you're looking for another calendar that supports recurring events programmatically, [fullcalendar](https://fullcalendar.io/docs/recurring-events) might be useful.

**Comment by WillTA5** [comment]
Thank you for your response! I will progress with my function to loop through the recurrences and create individual events. Thank you for clearing it up :)
