### ISSUE TITLE
More than 7 days in week view?

### ISSUE THREAD

**Issue by blacksmoke26** [nhn/tui.calendar#940]
Is there a possibility to display/add more than 7 days in week view? 

= WEEK VIEW =
[1|2|3|4|5|6|7]

Showing all days of the month (29..31) in week view along with the horizontal scrollbar. Or is there a way to customize this part?

 Any chance?

**Comment by adhrinae** [comment]
@blacksmoke26 

I'm afraid it's not. The current week view is fixed for 7 days at the code level.
Similar to #892

**Comment by blacksmoke26** [comment]
Ah, It's OJ @adhrinae 

What about in-future possibilities? Any chance or Fixed 7 days till the end of the world?

**Comment by adhrinae** [comment]
@blacksmoke26 
We'll work on it. But I'm sorry I can't guarantee the release date.

**Comment by Fusseldieb** [comment]
Would be useful to have only 5 days shown
