### ISSUE TITLE
Schedules does not render in Calendar (Apple Ipad 15.1.1 )

### ISSUE THREAD

**Issue by tafzeelmohammad** [nhn/tui.calendar#946]
Version
1.14.0

Development Environment
Apple iPad 15.1

Current Behavior
I used createSchedules(), and created multiple schedules, but it does not render on (Apple iPads & on iPhone),
On other devices like Laptops (MacBook/Windows) and on android phones all the schedules are rendered and visible properly on calendar.

![ipad mini 6th gen portrait2](https://user-images.githubusercontent.com/29578313/144219694-0051469c-b2a3-45ff-99b3-a10e884f6e30.png)

![CAR__ Shop Dashb](https://user-images.githubusercontent.com/29578313/144218426-ad98d998-a699-4844-806d-06fcaa721ee8.png)

Schedule Create function
--------------------------
let schedule = {
      id: evtDetails.id,
      calendarId: evtDetails.calendarId,
      title: evtDetails.title,
      category: 'time',
      dueDateClass: '',
      start: evtDetails.startTime,
      end: evtDetails.endTime,
      raw: evtDetails.eventData || {},
      color: '#ffffff',
      bgColor: bgcolor,
      borderColor: brcolor,
    };
    this.serviceCalender.createSchedules([schedule]);

**Comment by adhrinae** [comment]
@tafzeelmohammad 
Did you try this on Safari Desktop?
I wonder what browsers gave you the right result.

**Comment by adhrinae** [comment]
Closing the issue because there's no reponse.
