### ISSUE TITLE
Hide field/s in the Schedule create/edit popup

### ISSUE THREAD

**Issue by klimentpetkov** [nhn/tui.calendar#953]
## Version
@version 1.15.0 | Thu Oct 21 2021

## Development Environment
Browser: Chrome
OS: Linux

## Current Behavior
Currently there is not a way for hide location, activity (busy, free) and show easily something custom inside and then process it with a callback

## Expected Behavior
At least to be able to to hide any (one or more) field inside Schedule popup without to have to write a new one.

**Comment by adhrinae** [comment]
@klimentpetkov 
Yes, I'm aware of that.
[This discussion](https://github.com/nhn/tui.calendar/discussions/941) explains the context well.

**Comment by reynaldmorel** [comment]
Hello,

I found a solution by modifying the 'tui-calendar.css' file.

Modify as follows: 
.tui-full-calendar-popup-section-item.tui-full-calendar-section-location {
  /*display: block;*/
  display: none;
}
