### ISSUE TITLE
Timezone affects actual times passed from DB

### ISSUE THREAD

**Issue by klimentpetkov** [nhn/tui.calendar#954]
## Summary
Well in the DB I have times recoded as datetime fields, and when the data are fetched I prepare them as a schedules for the calendar. But when shown in the calendar they are with offset e.g: if the time passed is 05:30 the time offset of +2 hours is applied and in calendar the time is shown as 07:30. So, is there a way with some of the options to tell the calendar not to pay attention to timezones?

## Version
1.15

**Comment by adhrinae** [comment]
@klimentpetkov 
Basically, Javascript's `Date` object follows the local(the browser's) timezone.
Even though there are several limitations, we provide the `timezone` option when you create the instance. Please refer to [this doc](https://nhn.github.io/tui.calendar/latest/Timezone).
