### ISSUE TITLE
Infinite-scroll rendering on Day View

### ISSUE THREAD

**Issue by projjm** [nhn/tui.calendar#956]
## Summary
I'm primarily using the Day View for a project I'm working on, one issue users are having is that it's difficult to schedule events that span between two days, for example 23:00 - 02:00. 

My question is how difficult would it be to implement an infinite-scroll feature that renders the next day after the current day view automatically?

I appreciate any advice or suggestions,
Thanks.

**Comment by projjm** [comment]
Alternatively, I'm looking for a way to show 48 hours in the day view. 
I thought the hourStart and hourEnd options would help achieve this, but it seems to have no effect when greater than 24.

**Comment by adhrinae** [comment]
@projjm 
Sorry to say this, but It's too hard to implement your requests. and I think you need to use the week view for your use case.

**Comment by projjm** [comment]
Ah okay, I will try and use the week view instead. Thank you.
