### ISSUE TITLE
Is there a method that listens for schedule changes so I don't have to do a page refresh?

### ISSUE THREAD

**Issue by wktdev** [nhn/tui.calendar#962]
I am using SVELTE with this Calendar. I am storing date data in IndexedDB.
My app is structured as follows (very basic).

When the page mounts I do a call to indexedDB to find any calendar events and I populate `calendar.createSchedules`
SVELTE makes this easy as it have a built in method named onMount:

**On calendar load:**

```
nMount(async function () {
    calendar = new TuiCalendar("#calendar", {
      defaultView: "month",
      taskView: true,
      scheduleView: ["time"],
      useCreationPopup: true,
      useDetailPopup: true,
    });

    await getAllCalendarEvents().then((calendarEventList) => {        // From indexedDB
 
      calendar.createSchedules([...calendarEventList]);
    });
})
```

**Data Submission**
When a user submits a calendar event, I capture the data using the **beforeCreateSchedule** method.

Like this:

```
  beforeCreateSchedule: function (e) {
        console.log("beforeCreateSchedule", e);
        let x = e.start;
        let y = e.end;
        async function makeEvent(){
          createCalendarEvent(
          new Date(x),
          new Date(y),
          e.title,
          e.location,
          e.isPrivate,
          e.isAllDay,
          "time",
          e.calendarId,
          "placeholder" 
        )
  
            makeEvent()
 
      }
```

This works perfect for getting data to indexedDB. The problem I am having is that I don't see a way to trigger an updated call for the newly submitted calendar data without doing a page refresh using location.reload. 

Like this:
```

      beforeCreateSchedule: function (e) {
        console.log("beforeCreateSchedule", e);
        let x = e.start;
        let y = e.end;
        async function makeEvent(){
          createCalendarEvent(
          new Date(x),
          new Date(y),
          e.title,
          e.location,
          e.isPrivate,
          e.isAllDay,
          "time",
          e.calendarId,
          "placeholder" 
        ).then(()=>{ 
         
                location.reload();            // Here
          })

        } 
  
            makeEvent()
    
      },


```
I am curious if there are any built in methods that can help me update the calendar without having to force a page  refresh.

Thank you!

**Comment by adhrinae** [comment]
@wktdev 
Hi, Can you check the `category` property of the new event data?

https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules

The calendar doesn't render the event properly when the `category` property is not defined.
I tested on an arbitrary svelte sandbox with the `category` property and it worked.

**Comment by wktdev** [comment]
> @wktdev Hi, Can you check the `category` property of the new event data?
> 
> https://nhn.github.io/tui.calendar/latest/Calendar#createSchedules
> 
> The calendar doesn't render the event properly when the `category` property is not defined. I tested on an arbitrary svelte sandbox with the `category` property and it worked.

I don't know if that answers my question. I am referencing the category property and my code is working.
My problem is it is only working when I do a round trip and send data to the "database" that in this case is IndexedDB.

To be more clear, when I delete an event I can do it in parallel where the item is removed from the calendar and the database using this code:

```


   beforeDeleteSchedule: function (e) {
        console.log("beforeDeleteSchedule", e.schedule.id);
        
        //____________________________________REMOVE FROM CALENDAR & UPDATES IMMEDIATLY
        calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);
        

        //___________________________________REMOVE FROM DB
         async function removeEvent(){
          await deleteCalendarEvent(e.schedule.id)
         }

         removeEvent()   // ____ NO PAGE REFRESH !

      },


```


I just want to know what methods I am t use to add and update events so I don't need a round trip. In the example above I am using  `calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);`


To add events is there an addSchedule and to update is there an updateSchedule ? I just want to know what methods I should be using if I am to update the data without a round trip.

Thank you

**Comment by adhrinae** [comment]
@wktdev 
I misunderstood your question, and I'm still figuring out the question. but I think the points are:

- `deleteSchedule` updates the calendar properly.
- but `createSchedules` and `updateSchedule` methods don't re-render(update the view) the calendar even though the data is updated.
  - So you had to do a force refresh the page.
- According to the situation, you want to know the way to add & update events then the calendar re-renders without the round trip.

I hope I get the point.

Usually `createSchedules` and `updateSchedule` re-render after they finish the job unless you pass the additional argument as `true`. (Check the `silent` parameter in the doc) But I believe you didn't do that.

As a possible solution, You can try to call the [`render` method](https://nhn.github.io/tui.calendar/latest/Calendar#render) after modifying the calendar.

But would you share the sandbox or repo reproducing the problem so that I can check it?

**Comment by wktdev** [comment]
**@adhrinae** 

Thanks, you just answered my question and all is working. Thank you!

**Comment by adhrinae** [comment]
@wktdev 
Glad it could help you.
I'm still wondering why this is happening because I don't know much of svelte.
