### ISSUE TITLE
how to hide milestone and task category.

### ISSUE THREAD

**Issue by cx4** [nhn/tui.calendar#968]
[example](https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic)
I don't want to show milestone and task categories, but I don't have anything related to it from the document.

**Comment by adhrinae** [comment]
@cx4
I feel sorry that you couldn't find the option.
There's the `taskView` option to adjust categories of what you want to show.

https://nhn.github.io/tui.calendar/latest/Options

Just set `false` to the option. Then you won't see them.
