### ISSUE TITLE
How to hide the location input box in the pop-up window where the schedule is created

### ISSUE THREAD

**Issue by cx4** [nhn/tui.calendar#970]
i want hide the `location input box` which in the create schedule popup window

**Comment by adhrinae** [comment]
@cx4 

You can't.

Please Refer to #941.

**Comment by reynaldmorel** [comment]
Hello,

I found a solution by modifying the 'tui-calendar.css' file.

Modify as follows: 
.tui-full-calendar-popup-section-item.tui-full-calendar-section-location {
  /*display: block;*/
  display: none;
}
