### ISSUE TITLE
Canlendar too big and option today, next, prev not working.

### ISSUE THREAD

**Issue by WhiTExB3AR** [nhn/tui.calendar#971]
Hello, I have some problem with canlendar when run in flask python. The button next and previous month is not work. And I can not control the size of calendar, I am uisng the boostrap 4 for my web. Can anyone help me to fix this? 
Thank you so much.

## Summary
A clear and concise description of what the question is.

## Screenshots
![image](https://user-images.githubusercontent.com/62128227/147726336-76e5834a-68d1-406b-93a0-44314c911ad9.png)
![image](https://user-images.githubusercontent.com/62128227/147726384-7bf3f129-b898-4f92-a712-84be859b5644.png)
![image](https://user-images.githubusercontent.com/62128227/147726417-068db24e-c408-40fd-b355-d33a05d57b86.png)
The content of scripts.html file is below. I put the CDN in both css and js.
![image](https://user-images.githubusercontent.com/62128227/147726393-66d1210d-a482-41d2-884b-d44b2f12f37b.png)
![image](https://user-images.githubusercontent.com/62128227/147726536-0fcbb4d1-19e3-4b2d-b4ee-d2966fb63313.png)

## Version
1.5.2

**Comment by adhrinae** [comment]
@WhiTExB3AR 

About the size, The calendar follows their container's size. It would be `#calendar` in your code. Try setting the size of it.

I don't see any code calling the `prev` or `next` method in your code.
You should add event listeners to your buttons which call `prev` or `next` method when it is clicked.

For more info, check the documentation.

https://nhn.github.io/tui.calendar/latest/Calendar#prev
https://nhn.github.io/tui.calendar/latest/Calendar#next

You may need basic Javascript knowledge about the [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) API.

**Comment by WhiTExB3AR** [comment]
> @WhiTExB3AR
> 
> About the size, The calendar follows their container's size. It would be `#calendar` in your code. Try setting the size of it.
> 
> I don't see any code calling the `prev` or `next` method in your code. You should add event listeners to your buttons which call `prev` or `next` method when it is clicked.
> 
> For more info, check the documentation.
> 
> https://nhn.github.io/tui.calendar/latest/Calendar#prev https://nhn.github.io/tui.calendar/latest/Calendar#next
> 
> You may need basic Javascript knowledge about the [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) API.

Hi, I just need to add the addEventListener or more code about get the time of current datetime? Like the image below, after I added, the calendar still freeze when I press next or prev button.
![image](https://user-images.githubusercontent.com/62128227/147740466-1ac8f154-3953-45d6-bcbc-51ddd817288a.png)

**Comment by adhrinae** [comment]
@WhiTExB3AR 

That's because there's no such thing like `val` in your `moveToNextOrPrevRange` function.
Put the `console.log(val)` in that function. A totally different thing will show up.

[The event listener takes `Event` object as an argument.](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#the_event_listener_callback) and since you've already set `data-action` attribute to your buttons, you can read it from the event object.

```js
function moveToNextOrPrevRange(event) {
  const target = event.target;
  const action = target.dataset.action;

  if (action === 'move-prev') {
    cal.prev();
  } else {
    cal.next();
  }
}
```

And again, It requires Javascript knowledge, not the calendar library itself. Please take a moment and find some useful resources like [this](https://javascript.info/).
