### ISSUE TITLE
Using it as a standalone app

### ISSUE THREAD

**Issue by ugintl** [nhn/tui.calendar#991]
Can I use it as a standalone app?

What database is it using and how to configure it?

**Comment by adhrinae** [comment]
@ugintl 
You can use it as a standalone app. With [Electron](https://www.electronjs.org/), maybe?
But That's an implementation detail we don't care about.

It's just a JavaScript application, so it manages events(or schedules) as JavaScript objects. When the window refreshes, all the data will be gone.

So you might need to apply any persistent layer to your application and sync with the calendar. Such as IndexedDB, or other backend servers connected with any database.

You can sync your events between the calendar and the database in [`beforeCreateSchedule`](https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeCreateSchedule) events or [`beforeUpdateSchedule`](https://nhn.github.io/tui.calendar/latest/Calendar#event-beforeUpdateSchedule) events.
