### ISSUE TITLE
Is there a way to choose a date and move?

### ISSUE THREAD

**Issue by sohyun0** [nhn/tui.calendar#999]
Is there a way to move the date by creating another calendar other than the previous button and the next button in the calendar? For example, if a date is selected using a datepicker, go to that date (but only in the day view)

**Comment by sohyun0** [comment]
We solved the problem using the datepicker of toast ui and the setDate of the calendar.
If there's a better way, please share it.  😆

**Comment by adhrinae** [comment]
@sohyun0
That's the right thing to do :)
Closing the issue since it's resolved.
